### ISSUE TITLE
Error: P1000 When trying to upgrade

### ISSUE THREAD

**Issue by AuthorShin** [ghostfolio/ghostfolio#1011]
Hello
When I try to upgrade the container I got the following error:
`
root@user:/home/docker/ghostfolio# docker-compose --env-file .env -f docker-compose.yml up -d
Creating network "ghostfolio-development_default" with the default driver
Creating volume "ghostfolio-development_postgres" with default driver
Creating ghostfolio-development_postgres_1   ... done
Creating ghostfolio-development_redis_1      ... done
Creating ghostfolio-development_ghostfolio_1 ... done
`

`
root@user:/home/docker/ghostfolio# docker-compose --env-file ./.env -f docker-compose.yml exec ghostfolio yarn database:migrate
yarn run v1.22.19
$ prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "ghostfolio-db", schema "public" at "postgres:5432"
`
`Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `user` are not valid.`
`
Please make sure to provide valid database credentials for the database server at `postgres`.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by dtslvr** [comment]
Have you changed your `.env` file? It looks like the credentials for postgres are no longer valid.
