### ISSUE TITLE
Docker container no platform

### ISSUE THREAD

**Issue by SH4LT1S** [ghostfolio/ghostfolio#1033]
Hello, I am running a [Docker container](https://hub.docker.com/r/ghostfolio/ghostfolio/) on [unraid ](https://unraid.net/) and I cant choose a platform.
![g4g45g4reggre](https://user-images.githubusercontent.com/56916200/174801573-ecb07a00-db67-48e4-848f-ac67ae4493f5.png)

Also how can I track crypto? Or is it not possible?

**Comment by dtslvr** [comment]
Hello @SH4LT1S

Please make _Unraid_ related requests directly in the [support thread](https://forums.unraid.net/topic/123829-support-community-applications-ghostfolio).

> Also how can I track crypto? Or is it not possible?

Yes indeed, tracking cryptocurrencies is possible via _Portfolio_ > _Activities_.
