### ISSUE TITLE
Unable to access Portfolio pages - Cannot read property 'investment' of undefined

### ISSUE THREAD

**Issue by ramesh-lingappan** [ghostfolio/ghostfolio#1057]
Hi, 

Thank you for the nice product, am running ghostfolio in docker, after importing around 2814 transactions, now am unable to access any tab under Portfolio section. 

Getting 500 Internal Server Error for endpoint "http://home-server:3333/api/v1/portfolio/details"

On the server logs, i see this error, 

```
 ERROR [ExceptionsHandler] Cannot read property 'investment' of undefined
TypeError: Cannot read property 'investment' of undefined
    at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:394340)
    at Generator.next (<anonymous>)
    at /ghostfolio/apps/api/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/ghostfolio/apps/api/node_modules/tslib/tslib.js:113:16)
    at PortfolioService.getCashPositions (/ghostfolio/apps/api/main.js:1:393106)
    at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:378651)
    at Generator.next (<anonymous>)
    at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
 ```
 
 
 Overview page, Activites are working fine though. Lemme know if you need any more information. 
 
 Any help is appreciated!

**Comment by barisdemirdelen** [comment]
I have the same problem, I thought this would be a common issue since I didn't do anything special but it seems no one else has it?

**Comment by dtslvr** [comment]
Hi @barisdemirdelen

Can you narrow down the error to a single activity? It would help if you could provide an export (as simple as possible) so I can analyze the issue locally. You can mask `quantity` (set to 1).

**Comment by barisdemirdelen** [comment]
I have delved a bit deeper on why the problem exists.

https://github.com/ghostfolio/ghostfolio/blob/693ff9d3ead4e0b18f655211c4039bb3ef3bf2de/apps/api/src/app/portfolio/portfolio.service.ts#L1164-L1166

Here, 
`cashPositions `only contains 'EUR' but `userCurrency `is set to 'USD', thus returning `undefined`. We then try to call `.investment` of `undefined`.

Hope this helps.
