### ISSUE TITLE
Allocation data empty

### ISSUE THREAD

**Issue by c-erb** [ghostfolio/ghostfolio#1079]
The allocation for sectors and countries is empty for my chosen etfs. Is there a possibility or are there any plans for different data sources than yahoo? For example SEAC.DE doesn't show me any allocation data.

**Comment by dtslvr** [comment]
Hi @c-erb

Data for countries and sectors is coming from additional data providers than _Yahoo_. Please check these [instructions](https://github.com/ghostfolio/ghostfolio/issues/715#issuecomment-1046267439) to setup the data enhancer for `SEAC.DE`.

**Comment by c-erb** [comment]
Hi @dtslvr,

Are there other webpages as well where you can get data from? Trackinsight that is mentioned in the post doesn't know about this ETF.

Thanks.

**Comment by dtslvr** [comment]
Hello @c-erb

Unfortunately, I'm not aware of other services providing this data.

I thought you're looking for this one, at least the name is very similar: [UBS ETF – MSCI World Socially Responsible UCITS ETF](https://www.trackinsight.com/en/fund/WSRCHA)

**Comment by dtslvr** [comment]
This issue was closed because it has been inactive for 25 days.

**Comment by c-erb** [comment]
@dtslvr sorry about not replying back. It is sadly not the same, as the percentages are different (at least a bit) and it is using $ instead of €.

Guess nothing can be done at the moment. Thank you for looking into it though.
