### ISSUE TITLE
Manual dark mode

### ISSUE THREAD

**Issue by alfredonodo** [ghostfolio/ghostfolio#1103]
Hi,
I saw that dark mode is already available, but it is based on browser/OS preferences. If the browser uses the anti-fingerprint technique, you cannot use the dark mode. So a simple switch to force the mode would be appropriate.
Thank you

**Comment by dtslvr** [comment]
Add _Appearance_ to _Account Settings_: `AUTO`, `DARK`, `LIGHT`
(very similar to _Base Currency_)

**Comment by yksolanki9** [comment]
@dtslvr I'll like to take this up. Please assign it to me
