### ISSUE TITLE
Consider current month in FIRE calculation

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1129]
The savings amount (red box) is not adjusted based on the months of the current year that have already passed. Even if 10 months of the year have passed, the amount is `12 * 1200 = 14400`. It should be propagated to all other calculations.

<img width="1144" alt="savings-rate-in-fire-calculator" src="https://user-images.githubusercontent.com/4159106/195188337-3fe86221-9a3e-49e1-9ecd-f0f3cd64e22e.png">

[Source Code](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/fire-calculator/fire-calculator.service.ts#L11)

**Comment by yksolanki9** [comment]
@dtslvr Can you please assign this to me?
