### ISSUE TITLE
Add support for other architectures for the docker image

### ISSUE THREAD

**Issue by Areedtz** [ghostfolio/ghostfolio#1130]
The docker image is currently only built for the amd64 architecture (x64).

Adding support for more architectures like arm64, would make it possible to host ghostfolio on more devices, such as Raspberry Pis.

It seems like it's possible to do this using docker's ``buildx`` command as can be seen in [this](https://www.docker.com/blog/multi-arch-build-what-about-travis/) blogpost.

**Comment by dtslvr** [comment]
Hi @Areedtz

Thanks for creating this ticket. The topic has already been raised multiple times: [Docker multiplatform image](https://github.com/ghostfolio/ghostfolio/discussions/1030) (#1030)

Are you interested in creating the setup with `buildx`? Either with [_Travis_](https://github.com/ghostfolio/ghostfolio/blob/main/.travis.yml) as the `linux/amd64` image is currently built or with _GitHub Actions_ as it seems to be easier according to the blog post.

I'm looking forward to your feedback.

**Comment by Areedtz** [comment]
Hi @dtslvr 

Sorry, I only searched in issues and didn't find the topic there.

I just tested ``buildx`` locally, as well as tried to build the dockerfile on my Raspberry Pi directly, but it seems like there might be an issue when using arm64 and docker, as I get an error during ``yarn install`` when loading the prisma schema:

```
#0 754.1 $ prisma generate && ngcc --properties es2020 browser module main
#0 761.4 Prisma schema loaded from prisma/schema.prisma
#0 763.2 Error: Get Config: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
#0 763.2 Details: Unable to require(`/ghostfolio/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
#0 763.2  Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /ghostfolio/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
#0 763.2
#0 763.2 Prisma CLI Version : 4.1.1
```

I don't get this error when running ``yarn install`` outside of docker on my Raspberry Pi.

Seems like it might be an [issue](https://github.com/prisma/prisma/issues/14043#issuecomment-1181982000) with the node alpine image.

I'll try to convert the image to a ``-slim`` variant and see if it fixes it. Would it be okay to use that in the future if it fixes the arm64 issues and the image size doesn't change much?

**Comment by Areedtz** [comment]
Hi @dtslvr 

I've added a draft pull request #1134 with a suggestion for a solution, but it also introduces some points to discuss, such as using the ``slim`` variant instead of the ``alpine`` variant of node.
