### ISSUE TITLE
No such file or directory /ghostfolio/apps/client/index.html

### ISSUE THREAD

**Issue by danny91** [ghostfolio/ghostfolio#1146]
Hi,

Hoping you can help i've setup using the steps on the main page and also seperately using the community applications for Unraid but get the same issue for both.

`[Nest] 1  - 08/13/2022, 4:03:41 PM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, stat '/ghostfolio/apps/client/index.html'
Error: ENOENT: no such file or directory, stat '/ghostfolio/apps/client/index.html'`

Rest of log: https://pastebin.com/raw/hPEJihms

Formatting went dodgy on here.

The webpage gives me this messsage;
![Screenshot 2022-08-13 160544](https://user-images.githubusercontent.com/16515882/184499865-f0a5ad8a-7f4e-40ba-a9a6-2545ac7941f0.png)

This is a fresh install on both machines that are having the issue.

**Comment by dtslvr** [comment]
Hi @danny91

There is currently an issue with the `latest` version of the docker image. Can you try as a workaround to open the url followed with `/en`? (e.g. `http://localhost:3333/en`)

**Comment by danny91** [comment]
Hi @dtslvr 

Thanks that seems to work.

**Comment by dtslvr** [comment]
Fixed in [Ghostfolio 1.179.5](https://github.com/ghostfolio/ghostfolio/releases/tag/1.179.5).

**Comment by brettinternet** [comment]
I encountered the same issue in `v1.203.0`. Could there be a regression?

**Comment by dtslvr** [comment]
Thanks for the update @brettinternet.
