### ISSUE TITLE
Cannot read properties of undefined (reading `items`)

### ISSUE THREAD

**Issue by MisterDeee** [ghostfolio/ghostfolio#1228]
Using version 1.187.0 in Docker on unRAID.

Opened up Holdings, as previous bug was stopping me from doing so. I see the one line entry for my holdings. Click on it, a new dialog opens, but does not populate. I get an "Oops!" error message and find this in the logs:

[Nest] 845  - 09/04/2022, 12:03:39 PM   DEBUG Fetched 1 quotes from YAHOO in 1.153 seconds
[Nest] 845  - 09/04/2022, 12:03:39 PM   DEBUG ------------------------------------------------
[Nest] 845  - 09/04/2022, 12:03:39 PM   DEBUG Fetched 1 quotes in 1.155 seconds
[Nest] 845  - 09/04/2022, 12:03:39 PM   DEBUG ================================================
[Nest] 845  - 09/04/2022, 12:03:44 PM    WARN [PortfolioCalculator] Missing initial value for symbol AC.TO at 2021-02-15
[Nest] 845  - 09/04/2022, 12:03:44 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'items')
TypeError: Cannot read properties of undefined (reading 'items')
    at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:372230)
    at Generator.next (<anonymous>)
    at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:115:62)

**Comment by Gorpokki** [comment]
Experiencing this as well on Docker Unraid with 1.188

**Comment by MisterDeee** [comment]
Still happening in 1.189

**Comment by polarspark** [comment]
I am having this error with WARN [PortfolioCalculator] Missing initial value for symbol

**Comment by hunsbct** [comment]
I'm experiencing the same issue in 1.242.0/Unraid/Docker.

**Comment by Trentflix** [comment]
Also have this issue in 1.250 using Unraid/Docker

**Comment by boraxhacker** [comment]
Same running 2.8.0, logs show

First error happens
`
Fetching crumb and cookies from https://finance.yahoo.com/quote/AAPL...
Success. Cookie expires on Thu Oct 03 2024 16:59:59 GMT-0400 (Eastern Daylight Time)
New crumb: REDACTED
[Nest] 122  - 10/04/2023, 11:00:41 AM     LOG [DataGatheringService] Asset profile data gathering has been completed for REDACTED (YAHOO).
... ^ repeated lines
[Nest] 122  - 10/04/2023, 11:00:56 AM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
`

Then later

`
[Nest] 122  - 10/04/2023, 11:02:53 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'items')
TypeError: Cannot read properties of undefined (reading 'items')
    at PortfolioService.getPosition (/ghostfolio/apps/api/main.js:1:323878)
    at async PortfolioController.getPosition (/ghostfolio/apps/api/main.js:1:344706)
`
