### ISSUE TITLE
Wrong portfolio value with Shell Stock

### ISSUE THREAD

**Issue by cbirkenbeul** [ghostfolio/ghostfolio#1229]
Hi,
as discussed on twitter I open a issue.
I've bought Shell stocks which are traded in GBp, but because of that the total portfolio value is complete off. There is no possibilities to put the correct values in the activities. 
As requested I export the activity
```
{
  "meta": {
    "date": "2022-09-05T18:15:31.913Z",
    "version": "v1.187.0"
  },
  "activities": [
    {
      "accountId": "00377f07-7222-4889-a209-bfcd30a9bcc2",
      "comment": null,
      "fee": 0,
      "quantity": 18.882,
      "type": "BUY",
      "unitPrice": 24.17,
      "currency": "GBp",
      "dataSource": "YAHOO",
      "date": "2022-08-04T22:00:00.000Z",
      "symbol": "SHEL.L"
    }
  ]
}
```
I also attached a screenshot that shows the growth of nearly 10k %!
<img width="1133" alt="Bildschirmfoto 2022-09-05 um 20 20 19" src="https://user-images.githubusercontent.com/1380162/188499918-92b4e8dd-d930-4d06-988d-8adb670f5772.png">

**Comment by dtslvr** [comment]
Hi @cbirkenbeul

I have analyzed the exported activity. Your `unitPrice` in `GBp` is probably `2417` and not `24.17`.

Before:
<img width="769" alt="shell-before" src="https://user-images.githubusercontent.com/4159106/189417269-b4396f2a-09e2-4a62-9402-0278c98c6ec1.png">

After:
<img width="769" alt="shell-after" src="https://user-images.githubusercontent.com/4159106/189417234-051832c8-6920-4ae4-bf3d-2d5ccdcc59ac.png">
