### ISSUE TITLE
GBp to GBP Exchange Rate Error

### ISSUE THREAD

**Issue by Jordfoz16** [ghostfolio/ghostfolio#1254]
The issue that has been encountered is that the exchange rate from GBp (Pence) to GBP (Pound) isn't showing correctly. For example in the below screenshot the exchange rate is showing as 1 GBP = 1 GBp whereas the rate should be 1 GBP = 100 GBp. This issue causes the investment total to be incorrect as the value of the investments are off.
<img width="1151" alt="Screenshot 2022-09-14 at 11 20 21" src="https://user-images.githubusercontent.com/17856379/190150647-9c9c2e1a-16ea-4ca1-9148-a8fb640f6f20.png">

Checking the logs of the service I can see there are exchange errors being thrown. This is after a restart of the service.
<img width="1216" alt="Screenshot 2022-09-14 at 11 26 16" src="https://user-images.githubusercontent.com/17856379/190150657-6d2ace9a-18ba-421a-81e3-2759f807ad39.png">

**Comment by dtslvr** [comment]
@Jordfoz16 can you please check again with Ghostfolio [1.193.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.193.0)?

**Comment by Jordfoz16** [comment]
Holding value is still showing as the incorrect value
<img width="808" alt="Screenshot 2022-09-15 at 11 55 07" src="https://user-images.githubusercontent.com/17856379/190386429-0e21fa89-05b0-47f3-b53d-fd2ad40b1627.png">

It still showing 1 GBP = 1 GBp. Do i need to do anything to reset the value?
<img width="1189" alt="Screenshot 2022-09-15 at 11 55 19" src="https://user-images.githubusercontent.com/17856379/190386475-8b2ce46a-5505-4bd3-93bf-e01fb9df1835.png">

**Comment by dtslvr** [comment]
I have tested it again, here are the steps that worked for me:

1. Start from scratch (wipe the database, remove volumes, etc.)
2. Create a new Ghostfolio instance and set `BASE_CURRENCY=GBP`
3. Start the server
4. Create a new user
5. Add an activity using `GBp` (e.g. `SHEL.L`)
6. Restart the server

Then you should see the correct exchange rate like this:

<img width="1102" alt="admin-panel-GBp" src="https://user-images.githubusercontent.com/4159106/192087183-281d77e0-11c1-4f15-9b10-1e3ef275c0f4.png">
