### ISSUE TITLE
apps/client/index.html missing (404 not found)

### ISSUE THREAD

**Issue by niceborn** [ghostfolio/ghostfolio#1259]
Hello,

I installed new release 1.193.0 docker and get 

{"statusCode":404,"message":"ENOENT: no such file or directory, stat '/ghostfolio/apps/client/index.html'"}

on start. I checked and the file index.html is missing in this directory.

BR
Michael

**Comment by Diondk** [comment]
Hi,

I have the same error as you since upgrading to the latest release.

Kr,
Dion

**Comment by bliekp** [comment]
+1

**Comment by dtslvr** [comment]
Does it happen when you open `http://0.0.0.0:3333` in your browser? Does it work if you open `http://0.0.0.0:3333/en`?

**Comment by lammetak** [comment]
Got the same error after recreate of the container with latest image

**Comment by dtslvr** [comment]
Can you try to set `NODE_ENV: production` as in [docker-compose.yml](https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.yml)?

**Comment by niceborn** [comment]
With setting NODE_ENV: production the normal startpage is shown.

**Comment by LeonStoldt** [comment]
ℹ️  I've added the NODE_ENV=production variable to the Unraid Application. It should be available in a few hours from now.
Post in Unraid Support Thread will follow.
