### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by TaakoMagnusen** [ghostfolio/ghostfolio#1262]
Just discovered this tool and am excited to self host and try it but there is basically no documentation. I tried the online version by creating an account to trial importing but i literally can't find the format that the CSV should be in to import my transactions (which i currently have fully recorded in a google spreadsheet.

Would you please add documentation so users can understand how to use the tool instead of guessing? I had to search around the code just to find an example: https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv

A good tool is nothing without good documentation, please consider prioritizing this.

**Comment by TaakoMagnusen** [comment]
related:

**Comment by dtslvr** [comment]
Thanks for your feedback. Would you like to join us in improving the documentation [here](https://github.com/ghostfolio/ghostfolio/issues/769)?
