### ISSUE TITLE
Payload too large

### ISSUE THREAD

**Issue by TaakoMagnusen** [ghostfolio/ghostfolio#1265]
I was unable to import a csv file to the activities page. There was a popup that said "Import Activities Error" with no further information.

I opened the console and tried to repeat and saw the console error "payload too large", i've attached the log
[ghostfol.io-1663347324731.log](https://github.com/ghostfolio/ghostfolio/files/9585871/ghostfol.io-1663347324731.log)

The csv file was a mere 48kB, so i dont quite understand why it's failing.

**Comment by TaakoMagnusen** [comment]
After deleting a ton of rows and dropping the csv size to 25kB now i get an import error that at least says something, it says "20 activities at most"

What is the purpose of an import function if you have to do it 20 at a time? I have 750+ transactions i have to import....

**Comment by dtslvr** [comment]
Hi @TaakoMagnusen

It seems that _Ghostfolio Basic_ for new investors who are just getting started with trading is not a good fit for you having 750+ transactions. Please consider one of the other [options](https://ghostfol.io/en/pricing).
