### ISSUE TITLE
Add AUD as Compatible Currency

### ISSUE THREAD

**Issue by Joshndroid** [ghostfolio/ghostfolio#1309]
Hello,
Looking to be an AUD user here and dont see it listed as a currency.
i can see some ASX listed ETF's so figured I would give it a shot, however unable to set the currency as AUD.
Cheers

**Comment by dtslvr** [comment]
Hello @Joshndroid

Where would expect to select `AUD`? Are you using a managed or self-hosting Ghostfolio instance?

**Comment by Joshndroid** [comment]
Hello.
I had a look at the live instance on your site to which I found the ETF. In there I wasn't able to set AUD.

I then spun up a self hosted instance and parsed AUD.

I saw it within 'default account' in the account section as AUD but everywhere else listed it as USD as well as default homepage.

Are you looking to add the ASX to the markets page as well?

**Comment by Joshndroid** [comment]
Disregard.
I am curious if my desktop Firefox settings were primary issue with it as a self hosted instance as I tried again looking through the sections on my mobile device and AUD is there.

I will close this

**Comment by dtslvr** [comment]
> I tried again looking through the sections on my mobile device and AUD is there.

Great, thanks for the feedback.
