### ISSUE TITLE
Crypto not showing when adding new activity in self-hosted instance

### ISSUE THREAD

**Issue by chortya** [ghostfolio/ghostfolio#1316]
I am tryining to add BTCEUR or BTCUSD asset but my self-hosted instance is not pulling any crypto related symbols from Yahoo. I have tried the same with the public instance of ghostfolio and it works. My base currency is set to EUR. Stock works fine.

**Comment by dtslvr** [comment]
Hi @chortya

If you want to track _Bitcoin_ (`BTC`) in `USD`, you cannot set `BASE_CURRENCY=EUR`. But you will be able to set the user account's currency to `EUR` regardless of the environment variable.

**Comment by chortya** [comment]
I think you misunderstood the issue. None of the crypto-fiat combinations can be added as they are not showing if you start to input BTC or ETH. Only a stock named BTC is shown in the list.

**Comment by arnoudius** [comment]
I have the same issue. Crypto currencies don't seem to show up, regardless of the base currency I'm using (tried both USD and EUR).

**Comment by arnoudius** [comment]
Ah, I just noticed that if you search for BTC followed by - the base currency you configured (i.e. `BTC-USD` or `BTC-EUR`), it does work.

**Comment by brandonhinds** [comment]
Can I clarify this means if I have the base currency set to AUD I can't track bitcoin at all (as according to the doco I cannot change the base currency once it has been created)?

**Comment by dtslvr** [comment]
> Can I clarify this means if I have the base currency set to AUD I can't track bitcoin at all (as according to the doco I cannot change the base currency once it has been created)?

I haven't tested it, but I would expect that it works, because _Yahoo Finance_ supports the pair [BTC-AUD](https://finance.yahoo.com/quote/BTC-AUD).

**Comment by brandonhinds** [comment]
Ah good one - I had to specifically enter "BTC-AUD", with the dash. Entering "BTCAUD" or "BTC-" didn't bring up anything.

Thanks for your help @dtslvr.
