### ISSUE TITLE
[Request] Can we get the mobile app published to Github Releases or via F-Droid?

### ISSUE THREAD

**Issue by Joshndroid** [ghostfolio/ghostfolio#1317]
Hello,
i was wondering if you could have the app release within github releases or consider publishing to f-droid for those of us who are not using google services to be able to easily download and track the app for updates with something like obtanium or fdroid.

**Comment by dtslvr** [comment]
Hi @Joshndroid

The _Android_ app from the store is just a wrapper of the web app. If you add the web app to your homescreen (e.g. via _Add to homescreen_ in _Google Chrome_) you will get an icon and always use the latest version.
