### ISSUE TITLE
[BUG] Cannot find name '$localize' when running Storybook

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1323]
**Describe the bug**
_Storybook_ is not starting anymore.

**To Reproduce**
1. Run `yarn start:storybook`
2. Get various errors in files of `libs/ui/src` like: `Cannot find name '$localize'.`

**Expected behavior**
_Storybook_ starts without errors and can be accessed via http://localhost:4400/

**Screenshots**

**Logs**
```
Error: libs/ui/src/lib/activities-table/activities-table.component.ts:134:7 - error TS2304: Cannot find name '$localize'.
$localize`Do you really want to delete this activity?`
at addError (/dev/ghostfolio/source/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:29)
```
**Environment**
 - Ghostfolio Version `1.201.0`

**Comment by LoganArnett** [comment]
I would like to take this one

**Comment by LoganArnett** [comment]
I have found a workaround but I am not sure if this is a fix. The usual setup and `preview.js` configurations that should work and are already in place do not work and recommendations from the Storybook team have not worked either. However removing the import from the `preview.js` and simply importing it into one of the stories(not all) will make it available. I will create a PR around this but I do not see another way from the Storybook docs, community, or just in general.
