### ISSUE TITLE
Change view mode selector to slide toggle

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1341]
Change the user experience of the view mode setting from a selector (A) to a slide toggle (B) in the user account settings.

<img width="1023" alt="select-to-toggle" src="https://user-images.githubusercontent.com/4159106/194714838-fa969f07-b124-4525-8698-bdc3d44260dc.png">

**Comment by Chaitanya-087** [comment]
i would like to work on this

**Comment by dtslvr** [comment]
Hey @Chaitanya-087, are you making progress?
