### ISSUE TITLE
Support pagination in activities component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1354]
Support client-side [pagination](https://material.angular.io/components/table/overview#pagination) in the `ActivitiesTableComponent`.

Add `@Input() pageSize = Number.MAX_SAFE_INTEGER;` to make the page size configurable. By default it should not display the paginator.

Hint: set `pageSize="1"` in `apps/client/src/app/pages/portfolio/transactions/transactions-page.html` to play around.

**Comment by yksolanki9** [comment]
@dtslvr Can you please assign it to me
