### ISSUE TITLE
[BUG] Fix placeholder color of disabled mat-select

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1363]
![mat-select-disabled-placeholder](https://user-images.githubusercontent.com/4159106/196026556-21f1a28b-79ad-46c6-9f4f-635f7581735d.png)

**Comment by dtslvr** [comment]
A ticket for you @yksolanki9?

**Comment by yksolanki9** [comment]
Oops, I'll fix it. Please assign it to me
