### ISSUE TITLE
[BUG] ERROR [ExceptionsHandler] [big.js] Invalid number

### ISSUE THREAD

**Issue by oaasen** [ghostfolio/ghostfolio#1371]
**Bug Description**

Error after upgrade from version 1.202.0 to 1.203.0 or higher.

When selecting Accounts, Holdings, Allocations or Fire results in error "Oops! Something went wrong. Please try again later."

When downgrading to version 1.202.0 everthing is working ok again.

**Logs**

[Nest] 314  - 10/16/2022, 7:48:50 PM   ERROR [ExceptionsHandler] [big.js] Invalid number
 Error: [big.js] Invalid number
     at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
     at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
     at PortfolioCalculator.getAnnualizedPerformancePercent (/ghostfolio/apps/api/main.js:1:338746)
     at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:396827)
     at Generator.next (<anonymous>)
     at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:115:62)

**Environment**

- Ghostfolio Version 1.203.0 and higher

**Additional context**

Percentage calculation also seems to be wrong in the upgraded version (1.203.0 and higher) where YTD percentage is listed as -1.360,89%, while in version 1.202.0 YTD percentage is listed as +4,94% (assumed correct).

**Comment by thepill** [comment]
Can confirm this error(s)

**Comment by dtslvr** [comment]
Thank you for your report @oaasen.

Is it possible to narrow down the error to a single position and provide an export of the affected activities?

Which version does the error in `/ghostfolio/apps/api/main.js:1:338746` refer to?

**Comment by oaasen** [comment]
Not sure how to narrow down the error to any specific position. Any way of enabling extended debug information?

Which version does the error in /ghostfolio/apps/api/main.js:1:338746 refer to?
-> Version 1.203.0

Similar error for version 1.205.2:
    at PortfolioCalculator.getAnnualizedPerformancePercent (/ghostfolio/apps/api/main.js:1:338917)
    at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:395569)

**Comment by dtslvr** [comment]
This is most likely invalid: https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio-calculator.ts#L156

Any chance to get an export of your activities to further analyze it? It should work with obfuscated data (e.g. set all quantities to `1` in the `json` file).

**Comment by dtslvr** [comment]
@oaasen we have created a fix. Can you please check Ghostfolio [1.206.2](https://github.com/ghostfolio/ghostfolio/releases/tag/1.206.2) and provide feedback? Thank you.

**Comment by oaasen** [comment]
I can confirm that this issue is resolved.

**Comment by dtslvr** [comment]
> I can confirm that this issue is resolved.

Great, thank you for the feedback!
