### ISSUE TITLE
Create endpoint for dividends

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1402]
Create an endpoint which returns all activities of type `DIVIDEND` aggregated per month: `api/v1/portfolio/dividends?groupBy=month&range=5y`

Integrate it as a chart at the end of the _Analysis_ page.

<img width="1083" alt="dividend-timeline" src="https://user-images.githubusercontent.com/4159106/198523721-1e9587d1-fe1f-408e-86b5-8daa1a7d9237.png">

The concept is very similar to `api/v1/portfolio/investments?groupBy=month&range=5y` ([implementation](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.controller.ts#L183)) used for the _Investment Timeline_.

**Comment by jpereiramp** [comment]
As discussed through Slack, I'll gladly pick up this work :)

This would be my first contribution, so I'm still familiarizing myself with the code. I was able to get a successful version of this endpoint up & running by copying the existing logic for the `Investment Timeline` graph. 

Now, I'm reviewing that code which obviously has a lot of duplicate logic, and am trying to re-use as much as possible the existing logic. Still need to look into testing.

**Activities** Page, displaying all dividends earned:
![image](https://user-images.githubusercontent.com/12866147/198710762-f0ea6492-e5aa-46db-be19-9b33c10e31c0.png)

**Analysis** Page, displaying the graph with only dividends earnings:
![image](https://user-images.githubusercontent.com/12866147/198710699-bec0101f-4a49-4db5-a168-4d4d61b20093.png)

I'll have a PR open soon so we can review the new code.

**Comment by jpereiramp** [comment]
First draft of [PR-1403](https://github.com/ghostfolio/ghostfolio/pull/1403) is up for preliminary reviews :)

**Comment by dtslvr** [comment]
Closed via #1498.
