### ISSUE TITLE
[BUG] matSort is not working in dialogs

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1418]
**Bug Description**

`matSort` of the `ActivitiesTableComponent` is not working in dialogs (e.g. `PositionDetailDialog`).

**To Reproduce**

1. Go to _Portfolio_ → _Holdings_ and open a holding (with multiple activities)
2. Click on _Date_ in the _Activities_ table to sort the items
3. The order does not change

**Expected behavior**

The items are sorted properly.

**Screenshots**

<img width="1282" alt="position-detail-dialog-mat-sort" src="https://user-images.githubusercontent.com/4159106/200005341-4d72941d-febd-4154-ab3d-bbd5fe19ce84.png">

**Environment**

- Ghostfolio Version 1.208.0

**Additional context**

Sorting works as expected if it is not in a dialog.

**Comment by yksolanki9** [comment]
@dtslvr Please assign it to me
