### ISSUE TITLE
Support sorting of values with sign in PositionsTableComponent

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1419]
Currently, it is not possible to sort the `PositionsTableComponent` by _Performance_ (see _Portfolio_ → _Holdings_).

**Expected behavior**

Adapt `ValueComponent` in that way, that it is sortable (with `[colorizeSign]="true"`).

**Screenshots**

<img width="1282" alt="holdings" src="https://user-images.githubusercontent.com/4159106/200024449-4a26c2e6-e287-4bf7-b9ad-c665ed31819e.png">

**Comment by yksolanki9** [comment]
@dtslvr Please assign it to me
