### ISSUE TITLE
Local Currency ZAR - ZAc

### ISSUE THREAD

**Issue by Aimtjie** [ghostfolio/ghostfolio#1430]
Good day team

Please advise how i can change the below to reflect correctly
![image](https://user-images.githubusercontent.com/8002405/200267832-fb709502-d1a4-44e7-99e1-b0901c14fb30.png)
1ZAR = 100ZAc(ents)

**Comment by dtslvr** [comment]
Hi @Aimtjie

Thanks for creating this issue. `ZAR` <> `ZAc` is currently not handled in the code. It has to be added in the following places (cf. `GBp ` and `ILA`):

* https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-provider/yahoo-finance/yahoo-finance.service.ts#L203
* https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-provider/yahoo-finance/yahoo-finance.service.ts#L266

Would you like to create a pull request?
