### ISSUE TITLE
[BUG] - Unable to import GBp transactions

### ISSUE THREAD

**Issue by Sl3ipnir-Sec** [ghostfolio/ghostfolio#1451]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our [Slack channel](https://ghostfolio.slack.com) or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**
Ghostfolio errors when attempting to import any GBp transaction.

**To Reproduce**

1. Attempt to post a GBp transaction either through the import CSV/JSON functionality, or with the following payload body for the API: {'activities': [{'dataSource': 'YAHOO', 'date': '2020-01-11T18:22:44', 'currency': 'GBp', 'fee': 0, 'quantity': 52.46215127, 'symbol': 'INRG', 'unitPrice': 1394.5, 'type': 'BUY'}]}
2. Response: {"error":"Bad Request","message":["activities.0.currency (\"GBp\") does not match with \"undefined\""]}

**Expected behavior**
Successful activity import.

**Environment**

- Ghostfolio Version 1.212.0
- Browser N/A
- OS N/A

**Additional context**
This version of Ghostfolio has been deployed via unRaid.

**Comment by Sl3ipnir-Sec** [comment]
Never mind - user error. The stock on Yahoo is listed as INRG.L.

**Comment by musantro** [comment]
I got this error too but solved using correct `symbol`. Maybe the error is not descriptive, as the currency is fine but the problem is the symbol.
