### ISSUE TITLE
Need more digits/decimals for cryptocurrencies

### ISSUE THREAD

**Issue by luk6173** [ghostfolio/ghostfolio#1453]
Hi,

I see it is possible to add only 2 decimal places to the buy (cryptocurrency). Is there any option to enable 8 decimal places? ...or is this a "premium" feature?

I mean, if I buy 0,00148673 BTC, how I can track this in Ghostfolio?

Thank you,
Lukas

**Comment by dtslvr** [comment]
Hi @luk6173

You can enter more than just 2 decimal places for _Quantity_ and _Unit Price_. Internally it calculates with this precision, but in some views it only renders less decimal places.

This is not a Ghostfolio Premium feature, you probably need to track `0.00148673` (dot notation) instead of `0,00148673`.

**Comment by luk6173** [comment]
Hi @dtslvr 

thank you for your answer. I entered `0.00148673` instead of `0,00148673` but after saving the value is stored/displayed as `0,00148673`

Possible to update the views to show more decimal places ? Would be very useful for me.

**Comment by dtslvr** [comment]
It calculates the value as `quantity * unit price` -> `0.00148673 * 10000.56 = 14.87`. What would you expect?

The quantity displayed as `0,00` is a trade off because you can also have cryptocurrencies with a low value at the same time (like _Dogecoin_).

**Comment by luk6173** [comment]
> It calculates the value as `quantity * unit price` -> `0.00148673 * 10000.56 = 14.87`. What would you expect?

the values is fine for me.

> The quantity displayed as `0,00` is a trade off because you can also have cryptocurrencies with a low value at the same time (like _Dogecoin_).

would it still be possible to add an option to display more than 2 decimal places?

**Comment by dtslvr** [comment]
> would it still be possible to add an option (in settings) to display more than 2 decimal places?

No, we would like to keep Ghostfolio as simple as possible. In the position details you should see more decimal places, but it was broken. I have just provided a bugfix.
