### ISSUE TITLE
Missing Admin Control in the Menu [BUG]

### ISSUE THREAD

**Issue by hvddrift** [ghostfolio/ghostfolio#1467]
I just did a fresh install to see if I missed anything but I don't have access to the "Admin Control" menu. 

Local docker install on Unraid.

![image](https://user-images.githubusercontent.com/972926/202881223-636e7b51-8b8c-41fa-b3ce-83c4c1ffccda.png)

**Comment by dtslvr** [comment]
Hi @hvddrift

Only the first user you create gets the `ADMIN` role. You could connect directly to the database and change the `ROLE` in the `User` table.

**Comment by hvddrift** [comment]
I'll try, but it was a new install and I am the only user. I am sure I have done something wrong in my setup.
