### ISSUE TITLE
Give option to list ISIN, WKN or Name instead of only Symbol

### ISSUE THREAD

**Issue by MichlF** [ghostfolio/ghostfolio#1513]
Most financial websites list stock/etf name along with either ISIN or WKN. Symbol is by comparison less often used. 

I see the advantage in that it needs less space than the other identifications, however I doubt the majority is using Symbol only or always over any of the other identifications. So, why not give users the option to display whichever they prefer?

**Comment by dtslvr** [comment]
Hi @MichlF

Thanks for your feedback. Currently there is no information available for `ISIN` or `WKN` in Ghostfolio. But I see your point to improve the tables. Which ones do you refer to in particular? And do you use the application on desktop or mobile?

I have already created an improvement for the holdings page: #1514
What do you think?

**Comment by MichlF** [comment]
I am using the self-hosted version. So from my understanding I can't use the official (android) app (btw, maybe another feature request: will we ever be able to connect directly to a self-hosted server using the android app?). 
In other words, I am using only the desktop/website environment.

I should have clarified that I am referring to the table when managing your portfolio activities. 
I just gave ghostfolio a try and it was a pain to do the initial input of my activities, seeing that I never used stock Symbols before. There was a lot of unnecessary clicking and double checking to know which previous entries I could clone to speed up the entry process. Also, since symbols are sometimes completely different depending on which market (and thus in which currency) they are traded, one is required to go on a long search to find the stock symbol. That's just to name a few headaches of only using Symbols in this table.

**Comment by dtslvr** [comment]
> I should have clarified that I am referring to the table when managing your portfolio activities.

Okay, I see. I have just created a PR which adds the name to the activities table (#1516).

> btw, maybe another feature request: will we ever be able to connect directly to a self-hosted server using the android app?

I don't think it is needed. The android app is just a wrapper of the web app for marketing purposes. You will have the same experience when you open the (self-hosted) app on your smartphone and "install" the progressive web app on your home screen.
