### ISSUE TITLE
Where do I set the URL to deploy on my server?

### ISSUE THREAD

**Issue by philipkukoba** [ghostfolio/ghostfolio#1543]
I have a domain, let's say it's `mydomain.org`. I want to deploy ghostfolio with docker-compose on `ghostfolio.mydomain.org`.

Where do I set the URL to `ghostfolio.mydomain.org`? 

The only Docker environment variable I found was `HOST` but that seems to expect an IP address.

**Comment by philipkukoba** [comment]
Edit: what's needed is a reverse proxy of some kind like [Caddy](https://caddyserver.com/)
It would be handy if this was also included in the sample docker-compose file

**Comment by second2falcon** [comment]
@philipkukoba I tried with Nginx Proxy Manager, but wasn't able to get it proxied. I always get a `Web server is returning an unknown error` error (Error 520). Any idea why?
