### ISSUE TITLE
[BUG] failed migration when upgrading from 1.220.0 to 1.221.0

### ISSUE THREAD

**Issue by stephenogg** [ghostfolio/ghostfolio#1557]
**Bug Description**
Self-hosting ghostfolio on UNRAID from community apps. It's been stable (and brilliant - thanks!)  since first installed more than 6 months ago. Also installed redis and Postgres from community apps as containers. Enabled the Fear and greed index using the instructions in [#833](https://github.com/ghostfolio/ghostfolio/discussions/833). I did this in September, when the dataSource was still RAKUTEN. I ran into a problem upgrading from version 1.220.0 to 1.221.0. After upgrade, the ghostfolio docker container fails to start with this error:
```
The 20221225084546_removed_rakuten_from_data_source migration started at 2022-12-27 05:34:41.389372 UTC failed

error Command failed with exit code 1.

error Command failed with exit code 1.
```
and the Postgres logs:

```
2022-12-27 08:34:41.458 +03 [11887] ERROR:  invalid input value for enum "DataSource_new": "RAKUTEN"
2022-12-27 08:34:41.458 +03 [11887] STATEMENT:  -- AlterEnum
BEGIN;
	CREATE TYPE "DataSource_new" AS ENUM ('ALPHA_VANTAGE', 'EOD_HISTORICAL_DATA', 'GHOSTFOLIO', 'GOOGLE_SHEETS', 'MANUAL', 'RAPID_API', 'YAHOO');
	ALTER TABLE "MarketData" ALTER COLUMN "dataSource" TYPE "DataSource_new" USING ("dataSource"::text::"DataSource_new");
	ALTER TABLE "SymbolProfile" ALTER COLUMN "dataSource" TYPE "DataSource_new" USING ("dataSource"::text::"DataSource_new");
	ALTER TYPE "DataSource" RENAME TO "DataSource_old";
	ALTER TYPE "DataSource_new" RENAME TO "DataSource";
	DROP TYPE "DataSource_old";
	COMMIT;

2022-12-27 08:34:41.459 +03 [11887] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-12-27 08:34:41.459 +03 [11887] STATEMENT:  UPDATE "_prisma_migrations" SET "logs" = $1 WHERE "id" = $2
```

**To Reproduce**

I'm not sure exactly. I **think** this might be due to the fact that I enabled the fear & greed index when the dataSource was still referred to as RAKUTEN rather than RAPID_API - before version 1.204.0. Therefore I have both "RAPID_API" values and "RAKUTEN" values in my MarketData table in the "dataSource" column (see below, RAKUTEN before October 15th and RAPID_API after October 15th). If I connect to the database using psql, I can run the first statement in the transaction and create the data type "DataSource_new", but when I try to run the first "ALTER TABLE" statement, it fails with the `invalid input value for enum "DataSource_new": "RAKUTEN"` error. My SQL fu isn't strong enough to further diagnose/solve the issue. Nor do I have any experience with prisma and failed migrations.

Here are some of the values in the MarketData table from October - that must be around the time that the dataSource name was changed.
```
ghost-db=# select date,symbol,"marketPrice", "dataSource" from "MarketData" where symbol LIKE '_GF_FEAR_AND_GREED_INDEX' ORDER BY date;
        date         |          symbol          | marketPrice | dataSource 
---------------------+--------------------------+-------------+------------
 2022-10-12 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          18 | RAKUTEN
 2022-10-13 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          18 | RAKUTEN
 2022-10-14 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          24 | RAKUTEN
 2022-10-15 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          24 | RAKUTEN
 2022-10-16 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          24 | RAPID_API
 2022-10-17 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          21 | RAPID_API
 2022-10-18 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          28 | RAPID_API
 2022-10-19 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          34 | RAPID_API
 2022-10-20 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          34 | RAPID_API
 2022-10-21 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          40 | RAPID_API
 2022-10-22 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          40 | RAPID_API
 2022-10-23 00:00:00 | _GF_FEAR_AND_GREED_INDEX |          40 | RAPID_API
```
I'm tempted to replace all the RAKUTEN values with RAPID_API and try again manually to complete the migration and then mark the migrations as complete, but if I'm on the right track, then others may also have this issue. Also, I may be way off base.

**Environment**

- Ghostfolio Version 1.221.0
- Browser: Safari
- OS : UNRAID

**Comment by dtslvr** [comment]
Hi @stephenogg

Yes, you're on the right track. As of Ghostfolio `1.204.1`, the data source `RAKUTEN` has been renamed to `RAPID_API`. Please change all your entries in `MarketData` from `RAKUTEN` to `RAPID_API` (see [here](https://github.com/ghostfolio/ghostfolio/discussions/833#discussioncomment-3886060)).

`RAKUTEN` has been finally removed in Ghostfolio [1.221.0](https://github.com/ghostfolio/ghostfolio/blob/main/CHANGELOG.md#12210---2022-12-26).

Then you should be able to upgrade again. I think the migration has not been marked yet, so it should run again (and remove `RAKUTEN` as a value of the `dataSource` enum). I am not familiar with Unraid, unfortunately.

**Comment by kruemelro** [comment]
Hi
its not a Unraid related problem. I've got the same error on my docker deployment. The container dies and restarts after some seconds.

`ghostfolio-app-1    | $ prisma migrate deploy
ghostfolio-app-1    | Prisma schema loaded from prisma/schema.prisma
ghostfolio-app-1    | Datasource "db": PostgreSQL database "ghostfolio", schema "public" at "db:5432"
ghostfolio-app-1    |
ghostfolio-app-1    | 54 migrations found in prisma/migrations
ghostfolio-app-1    |
ghostfolio-app-1    | Error: P3009
ghostfolio-app-1    |
ghostfolio-app-1    | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
ghostfolio-app-1    | The `20221225084546_removed_rakuten_from_data_source` migration started at 2022-12-26 17:16:33.501297 UTC failed
ghostfolio-app-1    |
ghostfolio-app-1    |
ghostfolio-app-1    | error Command failed with exit code 1.
ghostfolio-app-1    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ghostfolio-app-1    | error Command failed with exit code 1.
ghostfolio-app-1    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ghostfolio-app-1 exited with code 1`

**Comment by stephenogg** [comment]
Thanks @dtslvr -
I used psql to update all the RAKUTEN values in the dataSource column of the MarketData table to RAPID_API, manually completed the rest of the sql statements in the migration transaction, and then marked the update as completed in the _prisma_migrations table and voilà, my issue was solved.

**Comment by dtslvr** [comment]
Great, thank you very much for your feedback @stephenogg.

The same steps should also work for you @kruemelro.
