### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Chouaib99** [ghostfolio/ghostfolio#1569]
Hello everybody,

I have just discovered Ghosfolio and I thank you for the quality of this project.

I just installed GhostFolio on my NAS via Docker.

After clicking on start and creating the account, I see in the “Admin Control” tab:

- The existence of two accounts
- The account i created does not have all the features of Admin

Could you please help me?

<img width="1482" alt="Capture d’écran 2023-01-02 à 15 43 14" src="https://user-images.githubusercontent.com/121811575/210246429-41133fac-ad06-48aa-8d1a-68946c832cd6.png">

**Comment by dtslvr** [comment]
Thank you for your feedback @Chouaib99.

User 1 is the demo account. You can remove it if you want.

Which features are you missing in the _Admin Control_ panel?

**Comment by Chouaib99** [comment]
Thank you.

Thank you for the info. it's not blocking but how do you delete the Demo account?

It seems to me that to import a batch of transactions you have to go through the Admin Control tab. Is this the case?
I saw on some videos options like Gather Profile Data and Gather All Data

**Comment by dtslvr** [comment]
Ah, I see. The concept of the administration has changed during the last months. It is a bit more automated now (re data gathering).  You should see a tab navigation in the bottom to manage the users, though.

To manage your transactions (_Activities_), please open the _Portfolio_ section.
