### ISSUE TITLE
[BUG] Grouping by month / year is broken for YTD

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1574]
**Bug Description**

Grouping investments / dividends by month / year has missing data if the date range is `YTD`.

**To Reproduce**

1. Add any `BUY` activity in 2023
2. Go to _Portfolio_ > _Analysis_
3. Select date range `YTD`
4. No data is presented in _Dividend_ / _Investment Timeline_ (the grouping by month / year does not matter)

**Expected behavior**

A bar is displayed in the chart.

**Environment**

- Ghostfolio Version 1.224.0

**Comment by yksolanki9** [comment]
@dtslvr I'd like to take this up. Please assign it to me

**Comment by dtslvr** [comment]
> @dtslvr I'd like to take this up. Please assign it to me

Thank you! 🙂
