### ISSUE TITLE
[BUG] "Yearly" label is not translated

### ISSUE THREAD

**Issue by MaVdbussche** [ghostfolio/ghostfolio#1587]
**Bug Description**

On the Portfolio/Analysis page, the two graphs at the bottom allow to show data monthly or yearly. The latter button is not translated, not is it translatable; we can see when switching to another language that the label remains in English, but the string is also absent in `messages.xlf`

**To Reproduce**

1. Change the language to something else than English
2. Go to Portfolio/Analysis
3. Look at the 2 graphs at the bottom

**Expected behavior**

The label should be displayed in the language selected by the user, like the rest of the interface.

**Environment**

Production (self-hosted docker image)

- Ghostfolio Version: 1.225.0
- Browser: Firefox
- OS: Linux

**Additional context**

`yarn build:dev` gives warnings about the issue when building the dev environment

**Comment by MaVdbussche** [comment]
The label "Import Dividends" in Portfolio/Activities/_overflow menu_ has the same issue.

**Comment by dtslvr** [comment]
The missing locales (`state="new"`) for `Import Dividends` and `Yearly` are now available in the `messages.*.xlf` files.
