### ISSUE TITLE
[BUG] Add activity modal is broken

### ISSUE THREAD

**Issue by paulobarrosnunes** [ghostfolio/ghostfolio#1604]
Whenever I try to add a buy or sell or dividend the box is blank with no possibility to select or write.
![11](https://user-images.githubusercontent.com/4313300/212487425-e5422393-484d-4302-9d17-c24b573797eb.png)

**Comment by dtslvr** [comment]
I will take a look, thanks for the report @paulobarrosnunes.

**Comment by dtslvr** [comment]
New Ghostfolio release ([1.227.1](https://github.com/ghostfolio/ghostfolio/releases/tag/1.227.1)) is in progress.

**Comment by dtslvr** [comment]
> New Ghostfolio release ([1.227.1](https://github.com/ghostfolio/ghostfolio/releases/tag/1.227.1)) is in progress.

✅ Available now on Docker Hub and deployed on [Ghostfol.io](https://Ghostfol.io)

**Comment by paulobarrosnunes** [comment]
tks for your help !
