### ISSUE TITLE
Extend import / export functionality by accounts

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1614]
At the moment, the import / export functionality is limited. Only activities are considered.

1. The exported `JSON` file from `ActivitiesPageComponent` should also include accounts (`this.user.accounts`) and…
2. the user can import `activities` and `accounts` (to a fresh user). The challenge are the `id`’s if they are already occupied, new account `id`’s should be assigned.

**Comment by yksolanki9** [comment]
@dtslvr I'd like to take this up, please assign it to me
