### ISSUE TITLE
[BUG] Dockerfile doesn't expose PORT env var

### ISSUE THREAD

**Issue by BeauAgst** [ghostfolio/ghostfolio#1659]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our [Slack channel](https://ghostfolio.slack.com) or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

The Dockerfile [exposes port 3333](https://github.com/ghostfolio/ghostfolio/blob/main/Dockerfile#L60) by default. There is an option to change the port that the service runs on by setting the `PORT` env var. The dockerfile doesn't expose this port if you change it

**To Reproduce**

1. Set a custom PORT value in your `.env` file, and run `docker-compose --env-file ./.env -f docker/docker-compose.yml up -d`
2. Attempt to access the service from that port

**Expected behavior**

Correct port is exposed, and is accessible

**Environment**

- Ghostfolio Version 1.231.0

**Comment by dtslvr** [comment]
What about `EXPOSE ${PORT}` instead of `EXPOSE 3333` in `Dockerfile`?

**Comment by BeauAgst** [comment]
Hey @dtslvr, sorry about this I was going to put an MR in myself. That's fine, but we don't have that control when using the official docker image. It will always expose 3333. We could do:

`EXPOSE ${PORT:-3333}`

To let it default back

**Comment by dtslvr** [comment]
> `EXPOSE ${PORT:-3333}`

ChatGPT says it should be `EXPOSE ${PORT:=3333}`. What is correct now? 😃

**Comment by BeauAgst** [comment]
`:-` "falls back" whereas `:=` reassigns the value. I don't think reassignment would be required here! I'll throw up a PR and you can modify it if you wish 🙏🏼
