### ISSUE TITLE
problem index.html

### ISSUE THREAD

**Issue by fablin** [ghostfolio/ghostfolio#1680]
Hi

When I run :
 yarn start:server

I got this error:
[Nest] 91050  - 02/10/2023, 5:47:43 AM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, stat '/Users/fabrice/workspace/ghostfolio-main/dist/apps/client/index.html'
Error: ENOENT: no such file or directory, stat '/Users/fabrice/workspace/ghostfolio-main/dist/apps/client/index.html'

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/29496388/217947912-bee8f9fe-b0dd-4fe9-bd7e-455a097e4a91.png">

**Comment by dtslvr** [comment]
Hi @fablin

You probably need to run `yarn build:dev` first as mentioned [here](https://github.com/ghostfolio/ghostfolio#setup).

**Comment by fablin** [comment]
> Hi @fablin
> 
> You probably need to run `yarn build:dev` first as mentioned [here](https://github.com/ghostfolio/ghostfolio#setup).

I ran `yarn build:dev` first

**Comment by fablin** [comment]
<img width="1298" alt="Screenshot 2023-02-10 at 22 59 22" src="https://user-images.githubusercontent.com/29496388/218123801-9aef8ac1-236a-4461-8c75-18fea6a8312c.png">

**Comment by dtslvr** [comment]
That looks fine. Are you opening http://localhost:4200/en in your browser?

**Comment by fablin** [comment]
> That looks fine. Are you opening http://localhost:4200/en in your browser?
That's working. 
Thanks for your help.

**Comment by dtslvr** [comment]
> That's working.
> Thanks for your help.

Great. Thank you for your feedback. I have added this instruction to the developer guide: https://github.com/ghostfolio/ghostfolio/pull/1683
