### ISSUE TITLE
No exchange rate has been found

### ISSUE THREAD

**Issue by labuzer** [ghostfolio/ghostfolio#1774]
Hello,

I've just installed Ghostfolio on my Debian 11 server using docker. Everything seems to run okay, however I noticed that currency conversion does not work. I've checked my logs and keep seeing the error message:
"ERROR [ExchangeRateDataService] No exchange rate has been found for DKKEUR"
"ERROR [ExchangeRateDataService] No exchange rate has been found for USDEUR"
"ERROR [ExchangeRateDataService] No exchange rate has been found for CADEUR"

Am I missing something in my setup?

**Comment by dtslvr** [comment]
Hi @labuzer 

I suspect it has to do by setting `BASE_CURRENCY=EUR`. With the latest additions like choosing a (custom) currency at the activity level, the concept `BASE_CURRENCY` will disappear sooner or later. I strongly advise you not to override it.

**Comment by labuzer** [comment]
Hi @dtslvr 

I am not using the BASE_CURRENCY function. I have my setup using the following compose

`version: "3.9"
services:
  ghostfolio-redis:
    image: redis
    container_name: Ghostfolio-REDIS
    hostname: ghostfolio-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - /portainer/Files/AppData/Config/ghostfolio/redis:/data
    restart: always

  ghostfolio-db:
    image: postgres
    container_name: Ghostfolio-DB
    hostname: ghostfolio-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ghostfoliodb", "-U", "ghostfoliouser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /portainer/Files/AppData/Config/ghostfolio/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ghostfoliodb
      - POSTGRES_USER=ghostfoliouser
      - POSTGRES_PASSWORD=ghostfoliopass
    restart: always

  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: Ghostfolio
    hostname: ghostfolio
    security_opt:
      - no-new-privileges:true
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN_SALT=gmkh8ze42wrx53ysdl9i6ab1fjcqvot7
      - JWT_SECRET_KEY=3dx6ih72rmqklesofuv09npg48zaw1jt
      - REDIS_HOST=ghostfolio-redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://ghostfoliouser:ghostfoliopass@ghostfolio-db:5432/ghostfoliodb?sslmode=disable
    ports:
      - 3333:3333
    restart: always
    depends_on:
      ghostfolio-db:
        condition: service_started
      ghostfolio-redis:
        condition: service_healthy`

**Comment by dtslvr** [comment]
What does the log show, right after the server start? Are there already errors before you open the web app in the browser?

**Comment by labuzer** [comment]
Not as far as i'm aware. This is the complete log
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [InstanceLoader] ImportModule dependencies initialized +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] AppController {/api} (version: 1): +12ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] AdminController {/api/admin} (version: 1): +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/gather, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/gather/max, POST} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/gather/profile-data, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/gather/profile-data/:dataSource/:symbol, POST} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/gather/:dataSource/:symbol, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/gather/:dataSource/:symbol/:dateString, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/market-data, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/market-data/:dataSource/:symbol, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/market-data/:dataSource/:symbol/:dateString, PUT} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/profile-data/:dataSource/:symbol, DELETE} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/profile-data/:dataSource/:symbol, PATCH} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/settings/:key, PUT} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] QueueController {/api/admin/queue} (version: 1): +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/queue/job, DELETE} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/queue/job, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/admin/queue/job/:id, DELETE} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] SubscriptionController {/api/subscription} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/subscription/redeem-coupon, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/subscription/stripe/callback, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/subscription/stripe/checkout-session, POST} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] AccessController {/api/access} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/access, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/access, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/access/:id, DELETE} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] AccountController {/api/account} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/account/:id, DELETE} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/account, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/account/:id, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/account, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/account/:id, PUT} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] PortfolioController {/api/portfolio} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/details, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/dividends, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/investments, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/performance, GET} (version: 2) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/positions, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/public/:accessId, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/position/:dataSource/:symbol, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/portfolio/report, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] OrderController {/api/order} (version: 1): +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/order/:id, DELETE} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/order, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/order, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/order/:id, PUT} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] CacheController {/api/cache} (version: 1): +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/cache/flush, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] UserController {/api/user} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/user/:id, DELETE} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/user, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/user, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/user/setting, PUT} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] AuthDeviceController {/api/auth-device} (version: 1): +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth-device/:id, DELETE} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] AuthController {/api/auth} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/anonymous/:accessToken, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/google, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/google/callback, GET} (version: Neutral) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/internet-identity/:principalId, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/webauthn/generate-registration-options, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/webauthn/verify-attestation, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/webauthn/generate-assertion-options, POST} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/auth/webauthn/verify-assertion, POST} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] BenchmarkController {/api/benchmark} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/benchmark, GET} (version: 1) route +2ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/benchmark/:dataSource/:symbol/:startDateString, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] SymbolController {/api/symbol} (version: 1): +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/symbol/lookup, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/symbol/:dataSource/:symbol, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/symbol/:dataSource/:symbol/:dateString, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] ExchangeRateController {/api/exchange-rate} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/exchange-rate/:symbol/:dateString, GET} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] ExportController {/api/export} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/export, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] ImportController {/api/import} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/import, POST} (version: 1) route +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/import/dividends/:dataSource/:symbol, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] InfoController {/api/info} (version: 1): +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/info, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RoutesResolver] LogoController {/api/logo} (version: 1): +1ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/logo/:dataSource/:symbol, GET} (version: 1) route +0ms
[Nest] 282  - 03/08/2023, 8:56:14 PM     LOG [RouterExplorer] Mapped {/api/logo, GET} (version: 1) route +0ms
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG [NestApplication] Nest application successfully started +251ms
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG    ________               __  ____      ___
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG   / ____/ /_  ____  _____/ /_/ __/___  / (_)___
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG  / / __/ __ \/ __ \/ ___/ __/ /_/ __ \/ / / __ \
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG / /_/ / / / / /_/ (__  ) /_/ __/ /_/ / / / /_/ /
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG \____/_/ /_/\____/____/\__/_/  \____/_/_/\____/ v1.243.0
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG 
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG Listening at http://0.0.0.0:3333
[Nest] 282  - 03/08/2023, 8:56:15 PM     LOG

**Comment by dtslvr** [comment]
It does not seem to have any errors.

Do you see any exchange rates here: http://localhost:3333/en/admin/overview?
Do you have any currency pairs here: http://localhost:3333/en/admin/market-data?

**Comment by labuzer** [comment]
I did not have any currencies in the /overview. I have added those I needed and now it seems to work, thanks! I don't know if this is normally needed, because I don't seem to be able to find this in the documentation.

**Comment by dtslvr** [comment]
The currencies should be automatically derived from your assets. I don't know why that's not the case in your setup 🤔

**Comment by LordVaderXIII** [comment]
Im having the same issue, Im using AUD, in http://localhost:3333/en/admin/market-data I have the currency there but it seems to be malformed. 

![image](https://user-images.githubusercontent.com/12748373/225511062-afdab51c-b688-4733-afda-2782cc2b4c57.png)

**Comment by Ralfons-06** [comment]
I just experienced this issue and could fix it by adding 'GBp' as currency and syncing all historical market data again
