### ISSUE TITLE
[BUG] Data provider hiccups with Today view

### ISSUE THREAD

**Issue by oshvarts** [ghostfolio/ghostfolio#1780]
**Bug Description**

During market hours, the Overview/Today view always displays $0, 0% change and a tooltip saying our data provider partner is experiencing hiccups.  That consistently goes away after 3:00 PM US Eastern time.  It's the same symptoms as #1416, however, the time zone (TZ) variable is never set in the container or in the DB (I triple checked) so it is not that easy to fix.   The log file always reports "Missing initial value for symbol `symbol` at date `initial purchase date`".

**To Reproduce**

1. Load some transactions
1. Restart the app
1. Open today view during US market hours before 3:00 PM
1. See the little (i) icon with Data Provider Errors message

**Expected behavior**

It should display current portfolio value and today's value and % change.

**Screenshots**

![image](https://user-images.githubusercontent.com/25232143/224426232-1a4fd4f9-1436-4b55-a684-ee4f387c7a96.png)

**Logs**

```
DEFAULT 2023-03-10T19:51:59.764983Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol 0P00000DNO at 2021-12-31[39m
DEFAULT 2023-03-10T19:51:59.765154Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol ABNB at 2022-01-24[39m
DEFAULT 2023-03-10T19:51:59.765424Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol ATVI at 2022-05-04[39m
DEFAULT 2023-03-10T19:51:59.765623Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol BTCUSD at 2022-05-23[39m
DEFAULT 2023-03-10T19:51:59.765837Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol F at 2023-02-08[39m
DEFAULT 2023-03-10T19:51:59.766034Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol GLPI at 2019-10-23[39m
DEFAULT 2023-03-10T19:51:59.766426Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol GOOG at 2021-01-28[39m
DEFAULT 2023-03-10T19:51:59.766502Z [33m[Nest] 226 - [39m03/10/2023, 7:51:59 PM [33m WARN[39m [38;5;3m[PortfolioCalculator] [39m[33mMissing initial value for symbol IVV at 2022-05-04[39m
```

Note that the log message is wrong: the value does exist in the postgres database for the initial purchase dates.

**Environment**

Self-hosted.

- Ghostfolio Version 1.243.0
- Chrome 110.0 for Windows
- Docker container in Google Cloud Run

**Additional context**

I traced the error message through the code and looked into the database.   The root cause is that data for yesterday's market close is not written to the postgres db until after 3:00 the following day.  Specific example:

Running the application today, 2023-03-10.  The database has contains a data row in MarketData table for *day before yesterday* only (2023-03-08), not 2023-03-09.  Therefore, the application is unable to calculate the value change from yesterday to today (it's able to get current quotes from yahoo).  Yesterday's data is populated only after 3 pm on 2023-03-10, at which time the app starts to behave as expected and is showing the proper prices.

![image](https://user-images.githubusercontent.com/25232143/224427415-8e445f28-a924-4553-b583-a316bafc4899.png)

I believe the fix to above (write yesterday's closing price as soon as it's available) will also fix #1416.

**Comment by oshvarts** [comment]
I see the following in the database log:

```
2023-03-10 20:00:29.330 UTC [1929267] postgres@ghostfoliodb1 LOG:  execute s34: INSERT INTO "public"."MarketData" ("createdAt","dataSource","date","id","symbol","marketPrice") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "public"."MarketData"."id"
2023-03-10 20:00:29.330 UTC [1929267] postgres@ghostfoliodb1 DETAIL:  parameters: $1 = '2023-03-10 20:00:28.931', $2 = 'YAHOO', $3 = '2023-03-09 00:00:00', $4 = '223ae039-ee5d-4499-b28e-f5abcd0e5573', $5 = 'USDEUR', $6 = '0.94791'
2023-03-10 20:00:29.432 UTC [1929267] postgres@ghostfoliodb1 LOG:  execute s37: SELECT "public"."MarketData"."id", "public"."MarketData"."createdAt", "public"."MarketData"."dataSource", "public"."MarketData"."date", "public"."MarketData"."symbol", "public"."MarketData"."marketPrice" FROM "public"."MarketData" WHERE "public"."MarketData"."id" = $1 LIMIT $2 OFFSET $3
2023-03-10 20:00:29.432 UTC [1929267] postgres@ghostfoliodb1 DETAIL:  parameters: $1 = '223ae039-ee5d-4499-b28e-f5abcd0e5573', $2 = '1', $3 = '0'
2023-03-10 20:00:29.730 UTC [1929267] postgres@ghostfoliodb1 LOG:  statement: COMMIT
```

Please note the insert happens at 2023-03-10 20:00:29.730 UTC (3 PM Eastern time) adding the data for 2023-03-09 (yesterday's date).  It's also precisely on the dot at 3 o'clock, so there must be a scheduled job doing it -- I'd be happy to fix it but I am not familiar enough with the code to find it.

**Comment by dtslvr** [comment]
Hi @oshvarts

Thanks a lot for your detailed roundup. "Missing initial value for symbol `symbol` at `date`" seems to be wrong, probably only the data from the day before is missing 🤔 Can you confirm?

This is a rough sketch of the data gathering concept:

1. A cron job is triggered [every 4 hours](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/cron.service.ts#L22) to fetch missing historical data of the [last 7 days](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-gathering.service.ts#L284)
2. For each asset (`symbol`) a [job is added](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-gathering.service.ts#L210) (with retries) to the queue (based on [bull](https://github.com/OptimalBits/bull))
3. The data gathering processor finally [completes the jobs](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-gathering.processor.ts#L49) from the queue.

Do you have ideas to improve this process and make it independent of your time zone?

**Comment by oshvarts** [comment]
Thank you @dtslvr -- that explains the code path now.  I think the big issue is what happens if the job does not run, or if it runs on a mismatched timezone -- the `(CronExpression.EVERY_4_HOURS)` sets it to run not really every 4 hours, but at 0, 4, 8, 16, and 20:00 hours each day, which may not correspond to market close times in the timezone it's run. 

Can I recommend  that if `dataGatheringItems` from https://github.com/ghostfolio/ghostfolio/blob/5db2faa17d1514d19ea026da9228ec6d40bda78d/apps/api/src/app/portfolio/current-rate.service.ts#L42 contains 2 dates but the return from `getValues` only contains 1 date, then something like https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-gathering.service.ts#L284 is called synchronously to populate the DB, then `getValues` is retried?  Since that call is synchronous, yesterday's data should always be loaded successfully from the data source.  Do you feel that would solve the issue?

**Comment by dtslvr** [comment]
Unfortunately, I can't follow your thoughts 😞 

The current mechanism should be as follows:
* data gathering process (populating DB) is separated from portfolio calculation (`getValues()`)
* cron job is triggered (only) every 4 hours (and not every hour, which would solve one issue?) because with a lot of data, the process will take longer than an hour and it happened to overload the database (somehow it created more and more jobs)

How should we proceed, maybe we can chat in [Slack](https://ghostfolio.slack.com)?

**Comment by oshvarts** [comment]
Hi!  I really don't know how best to fix this issue. 

I think it's most visible to services that do not run all the time -- for example, I run mine on google cloud run which shuts down containers unless they have requests.  Hence, the scheduled jobs do not run and I consistently get this error.  

Maybe, upon getting this situation (yesterday and today was requested, but only today's data set is present), the code could queue the sync job in the background right away, but make sure that only one is queued (check the queue before adding)?  then, the next reload would update the numbers.  

What do you think?

**Comment by dtslvr** [comment]
> For example, I run mine on google cloud run which shuts down containers unless they have requests. Hence, the scheduled jobs do not run and I consistently get this error.

Thanks for the information. Unfortunately, I don't have any experience if the application runs only once in a while. Ghostfolio is specifically designed for use in continuous operation.

> Cron job is triggered (only) every 4 hours (and not every hour, which would solve one issue?) because with a lot of data, the process will take longer than an hour and it happened to overload the database (somehow it created more and more jobs)

This part has been extensively improved in the last few days (cf. [Changelog](https://github.com/ghostfolio/ghostfolio/blob/main/CHANGELOG.md)). The data gathering job now runs hourly, which means the delay should be no more than 60 minutes until the data is ready. It would be interesting to know if the [latest version](https://github.com/ghostfolio/ghostfolio/releases) also improves the experience for you.

**Comment by oshvarts** [comment]
I finally found a solution that works for me, and tested it over a period of time.  I think it's minimally invasive, though as the refresh is in the background -- it's still not ideal (a refresh after a minute or two is required).  Please see my PR!
