### ISSUE TITLE
[BUG] Error during CSV import - hard to debug

### ISSUE THREAD

**Issue by Marx2** [ghostfolio/ghostfolio#1806]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our [Slack channel](https://ghostfolio.slack.com) or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**
I have history generate form my Google Sheet which has almost 400 positions
I have aligned all the data, like strange date format, dots for numbers, Yahoo tickers
During import I'm getting now an error:

activities.53.currency ("PLN") does not match with "EUR"

but it's really hard to know, which row is causing this error.
For sure it isn't 53 row in a file, because this row and a few around imports ok, when standalone.
I suspect, that problem is because I have a few brokerage accounts, and buy some stocks not in original EUR, but in PLN (brockerage operates fully in PLN, even for foreign stocks).

**To Reproduce**
I can't share my history, and now I can't easily find out, which rows is causing troubles

**Expected behavior**
It would be nice to have better error handling, so give more details, which line in CSV has caused this problem.

**Logs**

[Nest] 245  - 03/25/2023, 4:02:54 PM   ERROR Error: activities.53.currency ("PLN") does not match with "EUR"
[Nest] 245  - 03/25/2023, 4:02:54 PM   ERROR class ImportController{constructor(e,t,o){this.configurationService=e,this.importService=t,this.request=o}import(o,i){var r;return(0,e.__awaiter)(this,void 0,void 0,(function*(){if(!fo(this.request.user.permissions,so)||!fo(this.request.user.permissions,co))throw new t.HttpException((0,Vt.getReasonPhrase)(Vt.StatusCodes.FORBIDDEN),Vt.StatusCodes.FORBIDDEN);let e=this.configurationService.get("MAX_ACTIVITIES_TO_IMPORT");this.configurationService.get("ENABLE_FEATURE_SUBSCRIPTION")&&"Premium"===this.request.user.subscription.type&&(e=Number.MAX_SAFE_INTEGER);const n=this.request.user.Settings.settings.baseCurrency;try{return{activities:yield this.importService.import({isDryRun:i,maxActivitiesToImport:e,userCurrency:n,accountsDto:null!==(r=o.accounts)&&void 0!==r?r:[],activitiesDto:o.activities,userId:this.request.user.id})}}catch(a){throw t.Logger.error(a,Ja),new t.HttpException({error:(0,Vt.getReasonPhrase)(Vt.StatusCodes.BAD_REQUEST),message:[a.message]},Vt.StatusCodes.BAD_REQUEST)}}))}gatherDividends(t,o){return(0,e.__awaiter)(this,void 0,void 0,(function*(){const e=this.request.user.Settings.settings.baseCurrency;return{activities:yield this.importService.getDividends({dataSource:t,symbol:o,userCurrency:e})}}))}}

**Environment**

- Ghostfolio Version: latest docker image (v1.247.0)
- Browser: Firefox
- OS: Mac OS

**Additional context**

**Comment by dtslvr** [comment]
Hello @Marx2

Have you expanded the validation error? You should see the affected row there:

<img width="788" alt="validation-error-png" src="https://user-images.githubusercontent.com/4159106/227737263-c990642d-69ed-41b7-9d63-a53dea6b551b.png">

**Comment by Marx2** [comment]
It's not possible
<img width="818" alt="image" src="https://user-images.githubusercontent.com/822886/227739926-2d52baff-e05a-4147-b058-8762ed18251a.png">

**Comment by dtslvr** [comment]
Okay, thanks for checking.

Can you verify line `55` of your `csv` file? I assume there is a mismatch between the currency of this record (`PLN`) and the associated currency of the _Yahoo_ ticker (`USD`).

In that case, the validation fails intentionally. You would have to change the ticker to `USD` and convert the unit price manually. There is currently no automated import for that scenario.

**Comment by Marx2** [comment]
You're right, I need to add 2 to error displayed, to find correct row number.
Now another strange problem:
activities.54.currency ("GBP") does not match with "GBp"
I have currencies uppercase, why you've decided to do it "GBp"?

**Comment by Marx2** [comment]
Almost there, looks like I've fixed all transactions format, but now I'm getting:
Http failure response for https://ghostfolio.<mydomain>/api/v1/import?dryRun=true: 0 Unknown Error
Nothing in logs

**Comment by dtslvr** [comment]
Thanks for letting me know about the progress.

> Wouldn't it be better during import to ignore case?

`GBP` and `GBp` is not the same: `GBp` stands for "pence" and is used to represent smaller denominations of the British Pound. One pound is made up of 100 pence, so 1 `GBP` is equal to 100 `GBp`.

> Almost there, looks like I've fixed all transactions format, but now I'm getting:
Http failure response for https://ghostfolio.mydomain/api/v1/import?dryRun=true: 0 Unknown Error
Nothing in logs

Without further details, it's difficult to provide a solution. Have you tried narrowing down the issue to specific transactions? It might help to split them into smaller chunks and see if the error persists. This could help to isolate the problematic data and potentially identify the root cause of the issue.

**Comment by Marx2** [comment]
Funny thing is import went ok, I mean I see imported data in database and on form
But the problem now is nothing more works. All other forms are empty.
I suspect it's because account is not assigned (seems to be mandatory when I try to edit).
Can I set an account during import? the best would be per row
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/822886/227766300-015b1d66-39ab-4667-8a83-375bc6513325.png">

**Comment by dtslvr** [comment]
> Can we make all fields to be possible to import via CSV?

Yes, you can add the column `accountId` to your `csv` file with the id of one of your accounts (e.g. _Default Account_).

**Comment by Marx2** [comment]
i've succesfully finished import

**Comment by dtslvr** [comment]
> i've succesfully finished import

Great! 😎
