### ISSUE TITLE
JSON "Import Activities" from ghostfol.io "Activities Export" not working in self-hosted ghostfolio

### ISSUE THREAD

**Issue by webster8347** [ghostfolio/ghostfolio#1817]
**Bug Description**

JSON "Import Activities" from ghostfol.io "Activities Export" not working after "Validating data..." finished, and then clicking "Import". The list of activities is displayed but the fields "Quantity", "Unit Price", "Fee" and "Value" stay empty (pulsing grey fields) and when you click "Import" there is a notification "Oops! Something went wrong. Try again later..."

**To Reproduce**

1. Create New User
2. Go to portfolio/activities
3. Import "ghostfolio-export-202303282025 - cleaned.json"
4. Wait for list... then click "Import"

**Expected behavior**

Activities get imported

**Screenshots**

![image](https://user-images.githubusercontent.com/75222054/228374748-33ea896e-ac34-4c2c-8382-e31f93f724b7.png)

![image](https://user-images.githubusercontent.com/75222054/228375434-d227c953-5bb9-464f-a89d-456d544f9c7d.png)

**Logs**

--> Where can I find the logs?

**Environment**

ghostfolio/ghostfolio:latest Docker image on Synology NAS

- Ghostfolio Version: 1.248.0 - 2023-03-25
- Browser: Brave v1.49.132 (Brave Shield turned off)
- OS: Synology DSM

[ghostfolio-export-202303282025 - cleaned.zip](https://github.com/ghostfolio/ghostfolio/files/11094476/ghostfolio-export-202303282025.-.cleaned.zip)

**Comment by dtslvr** [comment]
Thanks for reporting this issue @webster8347. I have analyzed the import with your example file. The exception is caused by missing platforms in your local environment. I'm working on an improvement.

**Comment by dtslvr** [comment]
Regarding missing values in some columns, I haven't find the reason for it yet. I first thought it's because there are negative values for fees in the import file, but that didn't change anything.

**Comment by dtslvr** [comment]
> Regarding missing values in some columns, I haven't find the reason for it yet.

Fixed. There was an issue in the pagination when there were more than 50 items.
