### ISSUE TITLE
No historical exchange rate for any date

### ISSUE THREAD

**Issue by NickSChristiansen** [ghostfolio/ghostfolio#1825]
I run a selfhosted setup and I get this error on every currency, on every date in the past:
![ghostfolio](https://user-images.githubusercontent.com/44038652/229894386-be6ed654-9c0f-4df3-be2e-0c9c34763264.png)

ghostfolio docker logs:

	[Nest] 364  - 04/04/2023, 6:59:51 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for DKKUSD at 2022-07-14
	[Nest] 364  - 04/04/2023, 6:59:53 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2022-07-14
	[Nest] 364  - 04/04/2023, 6:59:56 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2022-10-14
	[Nest] 364  - 04/04/2023, 6:59:59 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for DKKUSD at 2022-10-14
	[Nest] 364  - 04/04/2023, 7:00:01 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2022-10-14
	[Nest] 364  - 04/04/2023, 7:02:11 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2022-10-14
	[Nest] 364  - 04/04/2023, 7:02:13 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for DKKUSD at 2022-10-14
	[Nest] 364  - 04/04/2023, 7:02:15 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2022-10-14
	[Nest] 364  - 04/04/2023, 7:02:23 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2023-03-02
	[Nest] 364  - 04/04/2023, 7:02:52 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2023-04-03

**Comment by dtslvr** [comment]
Hi @NickSChristiansen

Can you check in your _Admin Control_ panel if the historical data is available? If not, you can _Gather Historical Data_ there.

<img width="1792" alt="missing-historical-data-for-currency" src="https://user-images.githubusercontent.com/4159106/230013343-2a1de03f-2e99-4475-93b8-3e81ee7a1c9c.png">

**Comment by NickSChristiansen** [comment]
There is no historical data present. Clicking the "Gather Historical Data"-button does not fetch historical data.

The logs are quite puzzling: When clicking the button, a log entry is created telling me historical data was fetched. But when trying to utilize said data, an error is thrown.

	[Nest] 408  - 04/06/2023, 11:12:18 PM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been completed for USDEUR (YAHOO).
	[Nest] 408  - 04/06/2023, 11:12:40 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURUSD at 2023-04-07

**Comment by dtslvr** [comment]
@NickSChristiansen

1. Please update to the latest version: https://github.com/ghostfolio/ghostfolio/releases/tag/1.251.0
1. Click _Gather Historical Data_ from the menu and wait a few seconds
1. Click _Refresh_ from the same menu
1. Now you should see many green squares for each historical value

**Comment by dtslvr** [comment]
> Yep, I see it now! 👏

Great! Thanks for the feedback 🙂
