### ISSUE TITLE
Allow mobile app to connect to self-hosted backend

### ISSUE THREAD

**Issue by DanZirnhelt** [ghostfolio/ghostfolio#1835]
Mobile app is pretty awesome and easier to use over the web app mainly because i can use finger print to lgin over using an entire token. It would be great if I could connect the mobile app to my self hosted back end for easy use!

**Comment by dtslvr** [comment]
Hi @DanZirnhelt

Have you already tried to add the app to your homescreen (e.g. via _Add to homescreen_ in _Google Chrome_)? It is the exact same experience as the Android app from the store including the _Sign in with fingerprint_ feature.

**Comment by dtslvr** [comment]
Hi @DanZirnhelt

Have you already tried to add the app to your homescreen (e.g. via _Add to homescreen_ in _Google Chrome_)? It is the exact same experience as the Android app from the store including the _Sign in with fingerprint_ feature.

**Comment by MetaBliss** [comment]
This is interesting @dtslvr , for iPhones is there a way to sign in with Face ID? My iPhone does not have fingerprint, only Face ID and does not work.

**Comment by dtslvr** [comment]
Hi @MetaBliss

> For iPhones is there a way to sign in with Face ID? My iPhone does not have fingerprint, only Face ID and does not work.

From a technological point of view, it should work exactly the same with Face ID. Could you describe the problem as detailed as possible in a new ticket? Thank you.
