### ISSUE TITLE
Optionally update cash balance of account

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1867]
Let the user decide if the cash balance of the account should be updated for `BUY`, `DIVIDEND` and `SELL` activities.

<img width="1156" alt="update-cash-balance" src="https://user-images.githubusercontent.com/4159106/232476567-39c54382-fcb0-4517-8bca-980b0cce21f8.png">

### Implementation details

- Add a checkbox to [CreateOrUpdateActivityDialog](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/activities/create-or-update-activity-dialog/create-or-update-activity-dialog.component.ts)
  - Only show it in creation mode (not in update) and if the type is `BUY`, `DIVIDEND` or `SELL`
- Extend the endpoint `POST /api/order/` with a optional flag `updateAccountBalance` (see [CreateOrderDto](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/create-order.dto.ts))
- Update the `balance` of the account in [createOrder()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/order.service.ts#L67) (notice the currency)

**Comment by Resurrectum** [comment]
Per default the cash balance never seems to be updated, no matter which action I enter. Is that normal?

**Comment by dtslvr** [comment]
> Is that normal?

Yes, this is a new feature idea.
