### ISSUE TITLE
Display invalid activity in import of a csv file

### ISSUE THREAD

**Issue by thendrich** [ghostfolio/ghostfolio#1877]
Currently, errors will yield messages like "activity(12) is a duplicate" which you have to backtrack to the csv for you were importing. You then have to count lines and see which item was causing problems. Probably, with the data available at that stage, the error could at least mention the details of the transaction that won't Import (date, symbol etc).

**Comment by dtslvr** [comment]
When you import a `json` file, the problematic activity is displayed.

<img width="794" alt="import-json-error" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/543c0216-c5e1-4e1b-82ed-2eead7f240eb">

It would be a useful addition for the import of `csv` files as well.

**Comment by dl90** [comment]
I can take a look.

**Comment by dtslvr** [comment]
> I can take a look.

Great! Here are are some test files you can use / extend for development: https://github.com/ghostfolio/ghostfolio/tree/main/test/import
