### ISSUE TITLE
[BUG] Changing account type from SECURITIES to CASH makes ghostfolio crash

### ISSUE THREAD

**Issue by Resurrectum** [ghostfolio/ghostfolio#1900]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our [Slack channel](https://ghostfolio.slack.com) or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

**Comment by dtslvr** [comment]
This issue is now considered obsolete as the concept of account type has been deprecated.
