### ISSUE TITLE
[BUG] ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by oaasen** [ghostfolio/ghostfolio#1907]
**Bug Description**

Error after upgrade from version 1.261.0 to 1.262.0 

Selecting "Accounts" results in error "Oops! Something went wrong. Please try again later."

When downgrading to version 1.261.0 everthing is working ok again.

**Logs**

[Nest] 251  - 04/30/2023, 7:40:44 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'some')
TypeError: Cannot read properties of undefined (reading 'some')
    at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:310331)
    at Generator.next (<anonymous>)
    at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:115:62)

**Environment**

- Ghostfolio Version 1.262.0

**Comment by dtslvr** [comment]
Should be fixed in Ghostfolio [1.263.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.263.0). Thank you very much for reporting @oaasen!
