### ISSUE TITLE
Improve check for duplicates in import

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1932]
If a user exports activities from a broker and imports the complete file multiple files, Ghostfolio should take care that the portfolio does not contain duplicate entries of the same activities.

To reproduce, successfully import any [test file](https://github.com/ghostfolio/ghostfolio/tree/main/test/import). Then import the same file again and the user should see this:

<img width="1188" alt="duplicate-activities-import-png" src="https://user-images.githubusercontent.com/4159106/236608180-e0ed5ae0-f053-45af-a3e9-de618d726758.png">

**Comment by visrut7** [comment]
You can assign it to me I will work on this.
