### ISSUE TITLE
[BUG] Cannot add new securities from Yahoo Finance

### ISSUE THREAD

**Issue by muppie** [ghostfolio/ghostfolio#1948]
**Bug Description**

Unable to add stock/mutual fund after updating to latest version (1.267.0 or 1.266). Log says "[Nest] 257  - 05/07/2023, 6:10:24 PM   ERROR [YahooFinanceService] Error: Invalid Cookie"

**To Reproduce**

1. Add security, e.g. EQT.ST or Swedbank Robur Access Edge Gl
2.
3.

**Expected behavior**

Being able to add the stock/mutual fund

**Screenshots**

**Logs**

"[Nest] 257  - 05/07/2023, 6:10:24 PM   ERROR [YahooFinanceService] Error: Invalid Cookie"

**Environment**

- Ghostfolio Version 1.266 & 1.267
- Chrome 112.0.5615.137  and Safari version 16.4 (18615.1.26.110.1)
- MacOS 13.3.1 (a) 

**Additional context**

**Comment by dtslvr** [comment]
Related to https://github.com/ghostfolio/ghostfolio/issues/1873#issuecomment-1537121155

**Comment by dtslvr** [comment]
Should be fixed with Ghostfolio [1.268.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.268.0).
