### ISSUE TITLE
Add support for fees linked to an account

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1950]
Support activities of type `FEE` in Ghostfolio and aggregate them with the existing fees in the net worth calculation.

### Add activity of type FEE

<img width="797" alt="fee" src="https://user-images.githubusercontent.com/4159106/236901031-6e13cb76-2be7-4a43-a474-629098132ec6.png">

### Add fees to the fees of the portfolio summary

<img width="719" alt="portfolio-summary-fees" src="https://user-images.githubusercontent.com/4159106/236901839-1ea8ceb9-a567-4942-8c11-e9c0c4ba1823.png">

**Comment by JPFrancoia** [comment]
I'm willing to sponsor $50 for this feature and this one: https://github.com/ghostfolio/ghostfolio/discussions/2224. These two features can probably be implemented at the same time, since it's just 2 new types of activities. For whoever implements the features.

**Comment by dtslvr** [comment]
Hello @JPFrancoia

I have started with the implementation of the fees. It will be similar but still quite different from the interest part. It becomes a bit too big when you combine the two tasks.

**Comment by JPFrancoia** [comment]
No worries, happy to split the work and up the bounty. Just PMed you
