### ISSUE TITLE
Add "Set as Benchmark" to market data list

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1968]
Add a "Set as Benchmark" action to the market data list in the admin control panel.

<img width="1792" alt="set-as-benchmark" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/83596222-df01-4173-8e82-eb150d315e8c">

* Create endpoint to `POST` a benchmark (get property `BENCHMARKS`: e.g. `[{"symbolProfileId":"1580148b-7b97-4bf3-bc94-5fd5cf417935"},{"symbolProfileId":"033a586f-da0e-4319-a191-5167fa687fca"}]` and add the new one) with proper permission
* Add action to menu of table row

**Comment by aGhosh02** [comment]
Hi @dtslvr ,
I have understood the following from the requirement.

API - Create a new endpoint in benchmark.controller to add new benchmark
- POST /api/v1/benchmark
- payload - {datasource: "YAHOO", symbol: "value"}

This will fetch and add symbol data to SymbolProfile and add symbolProfileId to Property.BENCHMARKS array

UI
- "Add Benchmark" button to be added to Admin Control page
- Modal with Symbol search input to select symbol

Let me know if there is anything I have missing or any changes you want in this.

PS - Working on my Fork, will raise a PR once completed

**Comment by dtslvr** [comment]
Thanks for your description.The UI should be simplified. There should not be a "Add Benchmark" button which opens a modal (not needed in in this first version). The add action should be added to the table row (menu).

**Comment by aGhosh02** [comment]
Raised PR - https://github.com/ghostfolio/ghostfolio/pull/1973

"Set as Benchmark" button in Market Data
![2023-05-17 11_55_09-Market Data – Ghostfolio – Open Source Wealth Management Software](https://github.com/ghostfolio/ghostfolio/assets/16503180/f57869de-4913-4ddd-9dbc-b763a6c97319)

Benchmarks view in Admin Overview
![2023-05-17 11_55_36-Admin Control – Ghostfolio – Open Source Wealth Management Software](https://github.com/ghostfolio/ghostfolio/assets/16503180/b71a8468-1cf1-4bd4-b0c1-e721d8015a2b)

Benchmark chart on Portfolio
![2023-05-17 11_56_01-Analysis – Ghostfolio – Open Source Wealth Management Software](https://github.com/ghostfolio/ghostfolio/assets/16503180/fd1532ac-903c-42a6-8f2b-813d5ce12bee)
