### ISSUE TITLE
[BUG] Cannot select non-USD currency as account currency

### ISSUE THREAD

**Issue by DamianBarabonkovQC** [ghostfolio/ghostfolio#1969]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our [Slack channel](https://ghostfolio.slack.com) or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

I am trying to create an account denominated in EUR. When I click on the '+' to create an account, the currency dropdown only shows "USD" and no other currency. This prevents me from correctly accounting my EUR assets such as `VUSA.DE`. The system lists the amount I have as USD in the accounts tab and in the overview homepage.

**To Reproduce**

1. Click '+' to add an account
2. Click on the currency drop down and see only USD

**Expected behavior**

The currency drop down would have many more currencies. When I select EUR, the accounts and overview homepage would then understand that this is a EUR asset and automatically apply a conversion rate to show me the USD total.

**Screenshots**

<img width="799" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/65635505/04447fb5-a09b-4b50-9851-4fa0f02bd739">

**Logs**

**Environment**

- Ghostfolio Version v1.269.0
- Firefox 112.0.2
- MacOS Monterey 12.6

**Additional context**

**Comment by dtslvr** [comment]
Hi @DamianBarabonkovQC

The list of available currencies is composed as follows:
* Created activities
* Manually entered currencies in the Admin Control panel

Does it work when you add `EUR` in the Admin Control panel?

**Comment by DamianBarabonkovQC** [comment]
Yes, it worked. Maybe a suggestion would be to make this more obvious, or simply have more currencies by default?
