### ISSUE TITLE
Introduce stepper to import activities dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1970]
Add [MatStepper](https://material.angular.io/components/stepper/overview) to [ImportActivitiesDialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/portfolio/activities/import-activities-dialog).

<img width="793" alt="import-activities-stepper" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/58a29750-9988-458a-91bc-16e5609a6f07">

* First step: Select file
* Second step: Display either the table to select the activities to import or the validation errors
* Do not allow to go directly to the second step

**Comment by visrut7** [comment]
You can assign this to me.
