### ISSUE TITLE
Support file drop in import activities dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1971]
Support file drop in `ImportActivitiesDialog` with plain _TypeScript_ (no external library).

### Before

<img width="794" alt="import-activities-dialog-before" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/ec507d21-f582-4458-a42f-afa62d7443cf">

### After

<img width="794" alt="import-activities-dialog-after" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/bc897433-966e-475f-b11f-b4932ffe970c">

### Resources

* https://stackoverflow.com/a/38968948

**Comment by FraneCaleta** [comment]
Hi!

I'll take a look at this issue. @dtslvr could you please assign it on me?
