### ISSUE TITLE
[BUG] GBP total wrong when unit price is in pence

### ISSUE THREAD

**Issue by margatemarcel** [ghostfolio/ghostfolio#2008]
**Bug Description**

For example, using this ticker 0P00013P6I.L -  the market price is in pence but the software assumes that is pounds. As a result, the portfolio value for that holding is wrong by two digits (i.e. 1000 x 243.08p should show as £2,430.80 but actually shows as £243,080).

**To Reproduce**

Add 0P00013P6I.L to your holdings and the amount/total can be clearly seen.

**Expected behavior**

Total should be current total/100.

**Screenshots**

<img width="766" alt="Holdings_–_Ghostfolio_–_Open_Source_Wealth_Management_Software" src="https://github.com/ghostfolio/ghostfolio/assets/37417851/e1bd35b7-5099-4a0a-bd94-03006d9b77b9">

**Logs**

n/a

**Environment**

Self-hosted (Umbrel 0.5.3 on Ubuntu 22)
Ghostfolio v1.269.0
Safari 16.4 on macOS 13.3.1(a)

**Comment by dtslvr** [comment]
Hi @margatemarcel

Thank you for your bug report. We kindly request that you stick to our [bug report template](https://github.com/ghostfolio/ghostfolio/issues/new?template=bug_report.md&title=%5BBUG%5D) when submitting issues. The template helps us gather all the necessary information to address the problem effectively (e.g. providing the version, cloud or self-hosted, export of the activity).

Please revise your bug report and follow the provided template. Thank you.

**Comment by margatemarcel** [comment]
Apologies - post updated.

**Comment by dtslvr** [comment]
I have tried to reproduce your transaction:

```
{
  "meta": {
    "date": "2023-05-27T08:35:24.072Z",
    "version": "dev"
  },
  "activities": [
    {
      "comment": null,
      "fee": 0,
      "id": "d1fc2420-dccb-4be0-bed5-e542d5bd81f3",
      "quantity": 1,
      "type": "BUY",
      "unitPrice": 243.08,
      "currency": "GBp",
      "dataSource": "YAHOO",
      "date": "2023-05-27T08:31:39.305Z",
      "symbol": "0P00013P6I.L"
    }
  ]
}
```

<img width="782" alt="0P00013P6I" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/d7adfea7-f735-4bf6-bebe-39eb3097d4f5">

That looks as expected.

Can you please verify the exchange rates in your Admin Control panel?

<img width="702" alt="exchange-rates" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/e1dfd21d-f146-4d47-8728-8074f2378085">

**Comment by margatemarcel** [comment]
Thanks - that was embarrassingly simple. I was unaware I had to add GBp as a currency in addition to GBP!
