### ISSUE TITLE
[BUG] Oops! Could not get the historical exchange rate from 28/05/2023

### ISSUE THREAD

**Issue by rdybro** [ghostfolio/ghostfolio#2023]
**Bug Description**

I am a new user to Ghostfolio (cloud version), and I am trying to build my portfolio.
When I click "Add activity" and want to add a Bitcoin transaction I did long time ago through Coinbase in Euro, I am not allowed.
When I select another currency than USD for "Unit price" and/or "Fee" it gives me an error: "Oops! Could not get the historical exchange rate from 28/05/2023".
As the error message suggest, it doesn't even work if I select yesterday.

**To Reproduce**

1. Click "Add activity"
2. Select ticker - I've tried BTCUSD and MSFT, both in USD.
3. Change date to some time in the past, even as late as yesterday.
4. Change currency for Unit price and/or Fee to something else than USD (I've tried EUR, DKK, SEK, NOK)
5. Gives me an error message: "Oops! Could not get the historical exchange rate from 28/05/2023"

**Expected behavior**

I would expect it to pull exchange rate for the selected currency on the selected date, and then calculate price paid in ticker currency.

It seems to be working if I select today as the date.

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/10737581/e5544022-9eca-4e0a-b762-2d50614273ac)

**Environment**

- [X] Cloud
- [ ] Self-hosted

- Ghostfolio Version 1.274.0

- Google Chrome 113.0.5672.127 on Windows 11 21H2
- Google Chrome 113.0.5672.163 on Android 13

**Additional context**

I can understand that others weren't able to reproduce this, so it might be me doing something wrong, but I can't figure out what I should be doing instead then.

**Comment by dtslvr** [comment]
Many thanks for the detailed bug report @rdybro. I have found a bad database query which aborted the exchange rate calculation.

**Comment by rdybro** [comment]
My pleasure @dtslvr - happy that it was useful. Looking forward to the fix being release 👍

**Comment by dtslvr** [comment]
> Looking forward to the fix being release 👍

Ghostfolio [1.275.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.275.0)
