### ISSUE TITLE
[BUG] activities.0.currency is not valid

### ISSUE THREAD

**Issue by lee-costa** [ghostfolio/ghostfolio#2045]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our [Slack channel](https://ghostfolio.slack.com) or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

When trying to import transactions using .CSV file the error is displayed.

**To Reproduce**

1. Import .CSV
2. Error shows
3.

**Expected behavior**

No error.

**Screenshots**
![Screen Shot 2023-06-04 at 7 55 58 AM](https://github.com/ghostfolio/ghostfolio/assets/22748735/e1dc8205-e31d-404b-896e-076095894804)

**Logs**

**Environment**

- [x] Self-hosted

- Ghostfolio Version 1.276.0
- Browser Firefox
- OS Ubuntu 20.04

**Additional context**

.CSV file
[history.csv](https://github.com/ghostfolio/ghostfolio/files/11645514/history.csv)

**Comment by dtslvr** [comment]
Hi @lee-costa

Thank you for creating this ticket including an example `csv` file.

You need to manually clean the file to overcome this (first) issue by removing the following lines:

```

Plan name:,ALLIANCE HEALTH, INC
Date Range,01/01/2000 - 06/03/2023,,,,


```

The file content needs to start with the header row:

```
Date,Investment,Transaction Type,Amount,Shares/Unit
```

Please also make sure to adapt the content to the [supported format](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv).

**Comment by lee-costa** [comment]
I cleaned up the lines as advised but the error remains. Do you believe it to be an issue with the content? If so, what needs to be changed based on .csv that was linked?

**Comment by pedrommvv** [comment]
The [sample .csv](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv) does not work.
It's possible to provide a working one? Thank you

**Comment by dtslvr** [comment]
> The [sample .csv](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv) does not work.

I have quickly checked `ok.csv` and has worked as expected. Which version are you using @pedrommvv?

**Comment by pedrommvv** [comment]
Using raspbian OS 64 bit
the docker-compose yml versions below.
```
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
```

```
  postgres:
    image: postgres:12
```

```
  redis:
    image: 'redis:alpine'
```

**Comment by lee-costa** [comment]
And since this was revived, I still can't get my file to work. Cleaned it up so it starts with the correct header row but still nothing.

**Comment by pedrommvv** [comment]
Working now after one week, not sure if it's related to latest commits. Forget about it :)

**Comment by frindle** [comment]
So stumbled on this and trying the ok.csv produces the following:

`{
  "<!DOCTYPE html>": "<html"
}`
