### ISSUE TITLE
Support import for historical market data

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2046]
As an administrator I would like to import historical market data for an asset.

Create a new endpoint out of the existing `PUT api/v1/admin/market-data/:dataSource/:symbol/:dateString` and deprecate it.

**URL**
`POST api/v1/admin/market-data/:dataSource/:symbol` (support multiple dates)

**Body**
```
{
  "marketData": [
    { "date": "2023-06-01T00:00:00.000Z", "marketPrice": 1.61 },
    { "date": "2023-06-02T00:00:00.000Z", "marketPrice": 1.63 },
    { "date": "2023-06-03T00:00:00.000Z", "marketPrice": 1.63 },
  ]
}
```

Extend the [asset profile dialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog) with a textarea to import historical market data in the form of:

```
20230601;1.61
20230602;1.63
20230603;1.63
```

<img width="1187" alt="asset-profile-dialog" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/73823a1f-71ac-4c56-9bf7-ddb51758724b">

**Comment by KK4ito** [comment]
I'm on it 👍
