### ISSUE TITLE
Support comment / note in activities import (CSV)

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2048]
Support comment / note in activities import with a `*.csv` file.

_Originally posted by @dtslvr in https://github.com/ghostfolio/ghostfolio/discussions/2032#discussioncomment-6089550_

**Comment by Zaxim** [comment]
This would be very useful for me, as I have a bunch of historical transactions in my spreadsheet that contain extra unstructured data in a COMMENT column

**Comment by Fullstack-Arshad** [comment]
Hi @dtslvr , I am working on it, can I get it assigned please.

**Comment by Fullstack-Arshad** [comment]
do you want the comment/note column in specific position with specific column name
![image](https://github.com/ghostfolio/ghostfolio/assets/61023134/6d9ef393-696c-4d9e-b4d0-a0a59cb4ef28)

**Comment by dtslvr** [comment]
> Hi @dtslvr , I am working on it, can I get it assigned please.

Sure! 👍🏻 

> do you want the comment/note column in specific position with specific column name

`ActivitiesTableComponent` already supports notes. See here:

<img width="1294" alt="activity-with-note" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/c2edc148-46a5-45f1-9df9-810bde4b85bc">

Can you add a note to ok.json for testing please?

**Comment by Fullstack-Arshad** [comment]
sure
