### ISSUE TITLE
[BUG] activities.0.date is not valid

### ISSUE THREAD

**Issue by musantro** [ghostfolio/ghostfolio#2050]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our [Slack channel](https://ghostfolio.slack.com) or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

When I upload a csv for activities, `activities.0.date is not valid`.

**To Reproduce**

1. [Upload this csv](https://github.com/ghostfolio/ghostfolio/files/11677259/64807b4fd3a7ae0002000025.csv)

**Expected behavior**

Process the csv as defined here https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/13135993/066da2b1-c518-4436-9609-e75b74a28b34)

**Logs**

No logs

**Environment**

Docker compose, main branch

- [ ] Cloud
- [x] Self-hosted

- Ghostfolio Version v1.276.0.
- Browser Chrome
- OS Windows

**Additional context**

**Comment by dtslvr** [comment]
Thank you for the bug report @musantro, I have fixed the issue.
