### ISSUE TITLE
[BUG] Unable to save Liability

### ISSUE THREAD

**Issue by DidierLmn** [ghostfolio/ghostfolio#2107]
**Bug Description**

When creating a Liability in the Activities section, you are unable to click "save" (the button remains greyed out) even when all data is filled.
I inspected the DOM and it seems like the "Name, Symbol, ISIN" field is still required, but hidden. When I show that field and fill it out, I am able to save the Liability.

**To Reproduce**

1. Go to https://ghostfol.io/en/portfolio/activities?createDialog=true
2. Choose Type Liability
3. Fill out remaining info
4. Try to save -> does not work

**Expected behavior**

Be able to save.

**Screenshots**
<div>
<img width="60%" alt="Screenshot from 2023-06-28 14-01-32" src="https://github.com/ghostfolio/ghostfolio/assets/15478968/7abd7270-21a4-4422-9a94-447ad36dcf05">

<img width="60%%" alt="Screenshot from 2023-06-28 14-04-51" src="https://github.com/ghostfolio/ghostfolio/assets/15478968/e10ff8cf-df73-48bb-a970-a4b02c98675d">
</div>

**Environment**

- Cloud
- Ghostfolio Version v1.269.0
- Browser Firefox

**Comment by euphdk** [comment]
Same for "Item". 

Chrome, v1.285.0 and local install.

**Comment by dtslvr** [comment]
Fixed in Ghostfolio [2.286.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.286.0) by @aGhosh02.
