### ISSUE TITLE
[BUG] Android app not scaling correctly on tablets in horizontal mode

### ISSUE THREAD

**Issue by ms32035** [ghostfolio/ghostfolio#2132]
**Bug Description**

Android app not scaling correctly on tablets in horizontal mode.

Looks like a common issue with apps designed for phones.

**Screenshots**

![markup_Screenshot_20230707-234311.png](https://github.com/ghostfolio/ghostfolio/assets/5060473/6f4e4ccd-3cda-4acd-b454-b7cc444abbb5)

**Environment**

- Self-hosted
- Ghostfolio Version  - latest
- OS - Android

**Comment by dtslvr** [comment]
What do you exactly mean with _Self-hosted Android app_?

**Comment by ms32035** [comment]
I installed the app from the browser at my local instance, not from Play Store

**Comment by dtslvr** [comment]
I don't think we are shrinking the width (cf. desktop). Maybe this is a "feature" on Android?

**Comment by ms32035** [comment]
I don't think either. Looks more like a feature or a default behaviour that should be changed/unset, but sadly I have zero expertise in the area.
