### ISSUE TITLE
[BUG] & in description is shown as &amp;

### ISSUE THREAD

**Issue by ups7** [ghostfolio/ghostfolio#2134]
**Bug Description**

When adding an activity for anything which has an **&** in the name, Ghostfolio displays it as **&amp;**. This is true for both adding the activity manually and import. This is also then visible in all screens.

**To Reproduce**

1. Add ISIN GB00B0CNH163 which contains & in the name.
2. The name shows &amp; rather than & (see screenshot).
3. Add the activity to the portfolio.
4. Check other screens, it appears as &amp; everywhere.

**Expected behavior**

Show & instead of &amp; when adding an activity.
Hopefully the fix will also work on already added activities.

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/135383477/c5801737-fb0e-4667-b05d-cb511dd04bee)

**Logs**

**Environment**

- Self-hosted
- Ghostfolio Version 1.286.0
- Browser: Firefox
- OS: Ubuntu Linux

**Additional context**

**Comment by dtslvr** [comment]
> Hopefully the fix will also work on already added activities.

You will need to _Gather Profile Data_ in the _Admin Control_ panel to beautify already added activities once the improvement has been released.
