### ISSUE TITLE
[BUG] activities.0.currency ("USD") does not match with "undefined"

### ISSUE THREAD

**Issue by powerwade** [ghostfolio/ghostfolio#2148]
**Bug Description**
During importing the sample `ok.json` I got this error `activities.0.currency ("USD") does not match with "undefined"`

**To Reproduce**
1. Download https://raw.githubusercontent.com/ghostfolio/ghostfolio/main/test/import/ok.json
2. Click on `Import Activities` at http://`<server>`:3333/en/portfolio/activities 
3. Select downloaded sample `ok.json` file

**Expected behavior**
All activities in the json file should be imported.

**Screenshots**
![image](https://github.com/ghostfolio/ghostfolio/assets/7243197/cacedff7-6844-4820-b114-1019dbb37441)

**Logs**
```[Nest] 155  - 07/13/2023, 8:57:20 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 155  - 07/13/2023, 8:57:20 PM   ERROR Error: activities.0.currency ("USD") does not match with "undefined"
[Nest] 155  - 07/13/2023, 8:57:20 PM   ERROR class ImportController{constructor(e,t,o){this.configurationService=e,this.importService=t,this.request=o}import(o,r){var i;return(0,e.__awaiter)(this,void 0,void 0,(function*(){if(!yo(this.request.user.permissions,To.createAccount)||!yo(this.request.user.permissions,To.createOrder))throw new t.HttpException((0,no.getReasonPhrase)(no.StatusCodes.FORBIDDEN),no.StatusCodes.FORBIDDEN);let e=this.configurationService.get("MAX_ACTIVITIES_TO_IMPORT");this.configurationService.get("ENABLE_FEATURE_SUBSCRIPTION")&&"Premium"===this.request.user.subscription.type&&(e=Number.MAX_SAFE_INTEGER);const a=this.request.user.Settings.settings.baseCurrency;try{return{activities:yield this.importService.import({isDryRun:r,maxActivitiesToImport:e,userCurrency:a,accountsDto:null!==(i=o.accounts)&&void 0!==i?i:[],activitiesDto:o.activities,userId:this.request.user.id})}}catch(n){throw t.Logger.error(n,ps),new t.HttpException({error:(0,no.getReasonPhrase)(no.StatusCodes.BAD_REQUEST),message:[n.message]},no.StatusCodes.BAD_REQUEST)}}))}gatherDividends(t,o){return(0,e.__awaiter)(this,void 0,void 0,(function*(){const e=this.request.user.Settings.settings.baseCurrency;return{activities:yield this.importService.getDividends({dataSource:t,symbol:o,userCurrency:e})}}))}}
```

**Environment**

- Self-hosted
- Ghostfolio Version 1.288 (and a few releases behind )
- Firefox 
- Arch Linux

**Additional context**
I tried to import other csv/json files as well - even through the API. I got the same error: USD doesn't match with 'undefined'. I tried to change the default currency to something else, then change it back to USD.

**Comment by dtslvr** [comment]
> **Logs**
> 
> ```
> [Nest] 155  - 07/13/2023, 8:57:20 PM   ERROR Error: activities.0.currency ("USD") does not match with "undefined"
> [Nest] 155  - 07/13/2023, 8:57:20 PM   ERROR class ImportController{constructor(e,t,o){this.configurationService=e,this.importService=t,this.request=o}import(o,r){var i;return(0,e.__awaiter)(this,void 0,void 0,(function*(){if(!yo(this.request.user.permissions,To.createAccount)||!yo(this.request.user.permissions,To.createOrder))throw new t.HttpException((0,no.getReasonPhrase)(no.StatusCodes.FORBIDDEN),no.StatusCodes.FORBIDDEN);let e=this.configurationService.get("MAX_ACTIVITIES_TO_IMPORT");this.configurationService.get("ENABLE_FEATURE_SUBSCRIPTION")&&"Premium"===this.request.user.subscription.type&&(e=Number.MAX_SAFE_INTEGER);const a=this.request.user.Settings.settings.baseCurrency;try{return{activities:yield this.importService.import({isDryRun:r,maxActivitiesToImport:e,userCurrency:a,accountsDto:null!==(i=o.accounts)&&void 0!==i?i:[],activitiesDto:o.activities,userId:this.request.user.id})}}catch(n){throw t.Logger.error(n,ps),new t.HttpException({error:(0,no.getReasonPhrase)(no.StatusCodes.BAD_REQUEST),message:[n.message]},no.StatusCodes.BAD_REQUEST)}}))}gatherDividends(t,o){return(0,e.__awaiter)(this,void 0,void 0,(function*(){const e=this.request.user.Settings.settings.baseCurrency;return{activities:yield this.importService.getDividends({dataSource:t,symbol:o,userCurrency:e})}}))}}
> ```

@powerwade Do you also see `ERROR [YahooFinanceService] Error: Invalid Crumb` as the first error message?

**Comment by powerwade** [comment]
Actually I see  `Invalid Cookie` error before this particular case, but I found `Invalid Crumb` errors in the logs as well.

```
[Nest] 155  - 07/13/2023, 8:55:22 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 155  - 07/13/2023, 8:55:22 PM   ERROR Error: activities.0.currency ("USD") does not match with "undefined"
[Nest] 155  - 07/13/2023, 8:55:22 PM   ERROR class ImportController{constructor(e,t,o){this.configurationService=e,this.importService=t,this.request=o}import(o,r){var i;return(0,e.__awaiter)(this,void 0,v
oid 0,(function*(){if(!yo(this.request.user.permissions,To.createAccount)||!yo(this.request.user.permissions,To.createOrder))throw new t.HttpException((0,no.getReasonPhrase)(no.StatusCodes.FORBIDDEN),no.S
tatusCodes.FORBIDDEN);let e=this.configurationService.get("MAX_ACTIVITIES_TO_IMPORT");this.configurationService.get("ENABLE_FEATURE_SUBSCRIPTION")&&"Premium"===this.request.user.subscription.type&&(e=Numb
er.MAX_SAFE_INTEGER);const a=this.request.user.Settings.settings.baseCurrency;try{return{activities:yield this.importService.import({isDryRun:r,maxActivitiesToImport:e,userCurrency:a,accountsDto:null!==(i
=o.accounts)&&void 0!==i?i:[],activitiesDto:o.activities,userId:this.request.user.id})}}catch(n){throw t.Logger.error(n,ps),new t.HttpException({error:(0,no.getReasonPhrase)(no.StatusCodes.BAD_REQUEST),me
ssage:[n.message]},no.StatusCodes.BAD_REQUEST)}}))}gatherDividends(t,o){return(0,e.__awaiter)(this,void 0,void 0,(function*(){const e=this.request.user.Settings.settings.baseCurrency;return{activities:yie
ld this.importService.getDividends({dataSource:t,symbol:o,userCurrency:e})}}))}}
```

**Comment by dtslvr** [comment]
I have just released Ghostfolio [1.289.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.289.0). Can you check it again please?

**Comment by powerwade** [comment]
I confirm with this latest release I was able to import the demo ok.csv/json also my own stuff. Good job on this, many thanks!!

**Comment by dtslvr** [comment]
Excellent, thank you for the feedback @powerwade.

Many thanks go out to @gadicc for the incredibly fast patch 🚀

**Comment by romalane** [comment]
Hello, could you please tell us how to upgrade to this release for the Umbrel app? I'm on 1.287 and I don't see how to upgrade. Thanks!

**Comment by dtslvr** [comment]
Hi @romalane

> could you please tell us how to upgrade to this release for the Umbrel app?

Releases in the _Umbrel App Store_ are managed [here](https://github.com/getumbrel/umbrel-apps/tree/master/ghostfolio).

**Comment by romalane** [comment]
Hello! I sent a pull request to upgrade Ghostfolio to latest version. @dtslvr is this Merge Request ok or is there anything missing? I tested it locally and with my umbrel and it seemed to work fine! https://github.com/getumbrel/umbrel-apps/pull/805

**Comment by dtslvr** [comment]
> @dtslvr is this Merge Request ok or is there anything missing?

Unfortunately, I am not familiar with Umbrel. However, your changes look similar to the last update (https://github.com/getumbrel/umbrel-apps/pull/662).

**Comment by romalane** [comment]
They are similar in the sense that it's an update of Ghostfolio version. But my merge request updates to 2.10.0 which contains the fix to this issue.
