### ISSUE TITLE
[BUG] 404 on /api/v1/auth/anonymous

### ISSUE THREAD

**Issue by kruemelro** [ghostfolio/ghostfolio#2173]
**Bug Description**

i tryed to access the api endpoint (http://ghostfolio:3333/api/v1/auth/anonymous) but get a 404. 

**Expected behavior**

Connection to Api endpoint , no 404. :-)

**Logs**
`{"statusCode":404,"message":"ENOENT: no such file or directory, stat '/ghostfolio/apps/client/index.html'"}`

**Environment**

- Self-hosted with docker-compose
- Ghostfolio Version 1.290.0
- Google Chrome
- Windows 11 and Ubuntu 22.04

**Additional context**

Env Variables in my compose file:
```
- "DATABASE_URL=postgresql://user:pass@db:5432/ghostfolio?sslmode=prefer"
- "NODE_ENV=production"
- "REDIS_HOST=redis"
- "REDIS_PORT=6379"
- "COMPOSE_PROJECT_NAME=ghostfolio-development"
- "JWT_SECRET_KEY=mysecretkey"
- "ACCESS_TOKEN_SALT=mysecrettoken"
- "ALPHA_VANTAGE_API_KEY=APIKEY"
- "ENABLE_FEATURE_FEAR_AND_GREED_INDEX=true"
- "ENABLE_FEATURE_STATISTICS=true"
- "RAPID_API_API_KEY=RapidApiKey"
- "PORT=3333"
- "HOST=0.0.0.0"
```

**Comment by dtslvr** [comment]
Hello @kruemelro

Are you trying to make a `GET` or `POST` request to `http://ghostfolio:3333/api/v1/auth/anonymous`?

**Comment by kruemelro** [comment]
Thanks for the hint. I checked and realisied i did a get instead of a post. Sorry for confusing
