### ISSUE TITLE
Option to include dividends in performance chart

### ISSUE THREAD

**Issue by samman375** [ghostfolio/ghostfolio#2177]
It would be great if there were an option to include dividends (and maybe fees) in the overall performance chart. This is a better indicator of overall value generated, and is a very useful feature I'd found in other tools.

**Comment by dtslvr** [comment]
Hi @samman375

Thanks for creating this issue. In my opinion, dividend performance should go beyond the overall performance chart. There is already a discussion going on about how the performance could be split in capital, dividend and currency gains: https://github.com/ghostfolio/ghostfolio/discussions/1166

Please join the discussion there if you would like to contribute.
