### ISSUE TITLE
Support custom currency in activities import

### ISSUE THREAD

**Issue by Hugo-Persson** [ghostfolio/ghostfolio#2187]
**Description**

Support a custom currency (different to the official currency the asset is listed) in the activities import. The import should convert the currency with the exchange rate on that day or return an error ("Could not get the historical exchange rate from 23.05.2023 for SEK").

**To Reproduce**

Try to import activites with this item
```json
{
  "meta": { "date": "2023-02-05T00:00:00.000Z", "version": "dev" },
  "activities": [
    {
      "date": "2023-05-19",
      "comment": null,
      "fee": 0,
      "currency": "SEK",
      "symbol": "US0378331005",
      "quantity": 36,
      "unitPrice": 0.24,
      "accountId": "87270fc1-f433-4c3e-b746-451c84b59bf4",
      "dataSource": "YAHOO",
      "type": "DIVIDEND"
    }
  ]
}
```

Now I get the following error:
```
activities.0.currency ("SEK") does not match with "undefined"
```

**Expected behavior**

Activities should be imported with the corresponding exchange rates of the day.

**Screenshots**

<img width="806" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/47189713/6d180fae-ad1a-416c-997b-2f5b69ac23c5">

**Logs**

**Environment**

Cloud or Self-hosted: Self hosted
Ghostfolio Version X.Y.Z: Ghostfolio v1.292.0.
Browser: Arc
OS: Mac

**Additional context**

**Comment by dtslvr** [comment]
Hi @Hugo-Persson

`US0378331005` resolves to [AAPL](https://finance.yahoo.com/quote/AAPL) which is listed in `USD`. That's why you get the currency mismatch (`SEK` vs. `USD`).

**Comment by Hugo-Persson** [comment]
> Hi @Hugo-Persson
> 
> `US0378331005` resolves to [AAPL](https://finance.yahoo.com/quote/AAPL) which is listed in `USD`. That's why you get the currency mismatch (`SEK` vs. `USD`).

Ok so what is the correct way to do this? My bank export my Buy price as SEK. Is there some way to convert this automatically? Or maybe take whatever the price was for AAPL that day.

**Comment by dtslvr** [comment]
Ghostfolio currently does not execute an automated currency conversion during the import. You would need to convert your unit price (0.24 `SEK`) to `USD` manually with the rate of that specific date in your `csv` file.

**Comment by Hugo-Persson** [comment]
> Ghostfolio currently does not execute an automated currency conversion during the import. You would need to convert your unit price (0.24 `SEK`) to `USD` manually with the rate of that specific date in your `csv` file.

Ok, do Ghostfolio have an API for this? Otherwise that could maybe be a cool feature?

**Comment by dtslvr** [comment]
You could add the logic inside the import functionality. The `ExchangeRateDataService` provides the data (if available).

**Comment by Hugo-Persson** [comment]
> You could add the logic inside the import functionality. The `ExchangeRateDataService` provides the data (if available).

Ok going to look into that. Should I create an issue of this and assign myself?

**Comment by dtslvr** [comment]
> Ok going to look into that. Should I create an issue of this and assign myself?

Cool! We can use this issue, I have just updated the description.
