### ISSUE TITLE
[BUG] Cannot gather full historical data for a benchmark that is also an existing holding

### ISSUE THREAD

**Issue by shiruken** [ghostfolio/ghostfolio#2219]
**Bug Description**

The full historical data for a Benchmark cannot be gathered if that asset is also an existing holding. The "Gather Historical Data" action will be limited to the first date that asset was held rather than the first date in the entire portfolio.

**To Reproduce**

1. Start with new account
2. Add an asset to your holdings (e.g. 100 VTI purchased on 01/01/2020)
3. Add another asset to your holdings (e.g. 100 VTSAX purchased on 01/01/2023)
4. Use the admin interface to define that second asset as a Benchmark (VTSAX > Set as Benchmark)
5. Use the admin interface to gather historical data on that second asset (VTSAX > Gather Historical Data)
6. Reload the page and view the second asset's market data (VTSAX), the earliest data will be limited to the first transaction date (01/01/2023) rather than the earliest date in the portfolio (01/01/2020)
    * Portfolio performance analysis using the VTSAX benchmark will only begin at 01/01/2023

**Expected behavior**

Assets defined as benchmarks should always gather historical data beginning at the earliest date in the entire portfolio, not just the earliest transaction date for that specific asset.

**Environment**

- Self-Hosted (Unraid Docker)
- Ghostfolio Version v1.298.0
- Google Chrome (115.0.5790.170)
- macOS Ventura (13.4.1)

**Comment by shiruken** [comment]
Seems to be working now! Thanks!

**Comment by dtslvr** [comment]
> Seems to be working now! Thanks!

Great to hear @shiruken.

If you believe in what we do and would like to help us continue our mission, please consider [supporting us](https://www.buymeacoffee.com/ghostfolio).
