### ISSUE TITLE
[BUG] YARN  error Command "start:prod" not found

### ISSUE THREAD

**Issue by ThierryBegin** [ghostfolio/ghostfolio#2244]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**
Yarn error in latest docker images

**To Reproduce**

1.deploy developpement docker container

**Expected behavior**

no crashing
**Screenshots**

**Logs**
yarn run v1.22.19
error Command "start:prod" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

**Environment**

- Cloud or Self-hosted
- Ghostfolio Version X.Y.Z
- Browser
- OS

**Additional context**

**Comment by ThierryBegin** [comment]
Whenever I start the Docker container. It was working before the last
update.

Le jeu. 17 août 2023, 16 h 37, Thomas Kaul ***@***.***> a
écrit :

**Comment by dtslvr** [comment]
Unfortunately, I'm encountering difficulty in reproducing the issue based on the provided instructions.

It is probably related with these [changes](https://github.com/ghostfolio/ghostfolio/pull/2156). Can you please compare the `Dockerfile` with your local version? Should the problem persist, kindly consider submitting a pull request. Thanks.
