### ISSUE TITLE
[BUG] Adding activities at the wrong value

### ISSUE THREAD

**Issue by pippo73** [ghostfolio/ghostfolio#2270]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

When adding an activity, the unit price is set to the actual day not at the value of the date

**To Reproduce**

1. Insert an ISIN
2. set a date different from today
3. update the unit price pressing on the round arrow

**Expected behavior**

the unit price should be at the date indicated, not at the current price

**Screenshots**
![2023-08-26 22_08_41-Activities – Ghostfolio – Open Source Wealth Management Software – Mozilla Firef](https://github.com/ghostfolio/ghostfolio/assets/757121/dd0dc618-c304-4cb0-9b9e-05ab36a79c67)

the value is not the one it was at 26/08/2021

**Logs**

**Environment**

- Self-hosted
- Ghostfolio v1.303.0. (docker)

**Comment by tmp-hallenser** [comment]
I'm have exactly the same issue. Any insights how to resolve the issue? I'm also docker self-hosted and I'm on version 2.52

**Comment by tmp-hallenser** [comment]
Same issue can be observed in the demo instance, hence it's not an hosting issue. The interface takes the unit price of today and not of the selected date

**Comment by tmp-hallenser** [comment]
I was more hoping the button fetches the market price of the selected day (instead of it being only shown if the selected day is today). 
But appreciate the fix
