### ISSUE TITLE
Support adding manual asset profile

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2283]
As an administrator I would like to add an asset profile with `MANUAL` as data source from _Admin Control_ > _Market Data_.

![265200524-dc6d9405-b259-4525-bda4-42f6097b231f](https://github.com/ghostfolio/ghostfolio/assets/4159106/1c126630-b5a0-4510-8934-9129eed8fcc6)

- [ ] Extend the [CreateAssetProfileDialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/admin-market-data/create-asset-profile-dialog) with a radio button to toggle between `<gf-symbol-autocomplete>` (existing) and a simple `<input>`
- [ ] Extend the endpoint `POST api/v1/admin/profile-data/:dataSource/:symbol` to create a manual asset profile (e.g. `POST api/v1/admin/profile-data/MANUAL/MY_CUSTOM_SYMBOL`)

**Comment by M27afk** [comment]
Hey @dtslvr ! I'd like to give this a try!
Could you assign me this?

**Comment by dtslvr** [comment]
> What should be the Inputs @dtslvr?

Do you mean the form input when you create manually? Just one input field `symbol` is needed.

**Comment by M27afk** [comment]
What about the default values for currency, datasource and others?

**Comment by dtslvr** [comment]
> What about the default values for currency, datasource and others?

- For `currency` you can use `baseCurrency` from user settings
- `dataSource` is `MANUAL`
- `symbol` is the input from the form
