### ISSUE TITLE
Support dd.MM.yyyy date format in activities import

### ISSUE THREAD

**Issue by gogo199432** [ghostfolio/ghostfolio#2287]
**Description**

Unable to import activity with date format: 01.09.2023 (dd.MM.yyyy)
I get "activities.0.date is not valid" message when trying to import via CSV

**Environment**

- Self-hosted
- Ghostfolio Version latest
- Firefox
- K8S

**Comment by dtslvr** [comment]
Thanks for reporting @gogo199432.

Are you interested in extending the `parseDate()` function [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/services/import-activities.service.ts#L226)?

**Comment by FraneCaleta** [comment]
@dtslvr Feel free to asign me on this one. I'm already taking a look at it.

**Comment by dtslvr** [comment]
@FraneCaleta can you extend [ok.csv](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv) with that date format that it can be tested easily?

**Comment by FraneCaleta** [comment]
> @FraneCaleta can you extend [ok.csv](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv) with that date format that it can be tested easily?

Maybe, let me finish the basics first, it got more complicated than I expected :)
