### ISSUE TITLE
[BUG] activities.0.currency ("EUR") does not match with "undefined" and no exchange rate is available from "EUR" to "undefined"

### ISSUE THREAD

**Issue by brhahlen** [ghostfolio/ghostfolio#2303]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

Trying to import transactions that I did. Created a new CSV and it gives the error:
` Error: activities.0.currency ("EUR") does not match with "undefined" and no exchange rate is available from "EUR" to "undefined" `

**To Reproduce**

1. Use attached CSV
2. Try to import

**Expected behavior**

It would import without errors.

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/1798663/07b77367-9f6f-47c1-9ede-c085ba6d86c3)

**Logs**

```
ERROR [class ImportController{constructor(e,t,a){this.configurationService=e,this.importService=t,this.request=a}async import(t,a){if(!Za(this.request.user.permissions,Ia)||!Za(this.request.user.permissions,Pa))throw new e.HttpException((0,pt.getReasonPhrase)(pt.StatusCodes.FORBIDDEN),pt.StatusCodes.FORBIDDEN);let r=this.configurationService.get("MAX_ACTIVITIES_TO_IMPORT");this.configurationService.get("ENABLE_FEATURE_SUBSCRIPTION")&&"Premium"===this.request.user.subscription.type&&(r=Number.MAX_SAFE_INTEGER);const o=this.request.user.Settings.settings.baseCurrency;try{return{activities:await this.importService.import({isDryRun:a,maxActivitiesToImport:r,userCurrency:o,accountsDto:t.accounts??[],activitiesDto:t.activities,userId:this.request.user.id})}}catch(n){throw e.Logger.error(n,Js),new e.HttpException({error:(0,pt.getReasonPhrase)(pt.StatusCodes.BAD_REQUEST),message:[n.message]},pt.StatusCodes.BAD_REQUEST)}}async gatherDividends(e,t){const a=this.request.user.Settings.settings.baseCurrency;return{activities:await this.importService.getDividends({dataSource:e,symbol:t,userCurrency:a})}}}] Error: activities.0.currency ("EUR") does not match with "undefined" and no exchange rate is available from "EUR" to "undefined"
```

**Environment**

- Self-hosted - Docker
- Ghostfolio Version 1.305.0
- Firefox 117.0
- CSV Created on Windows

**Additional context**

File used:
[transacts_test.csv](https://github.com/ghostfolio/ghostfolio/files/12549637/transacts_test.csv)

**Comment by dtslvr** [comment]
Replace `LU0871827548` with `0P0000XYY8.F` (see https://finance.yahoo.com/quote/0P0000XYY8.F).

**Comment by brhahlen** [comment]
That worked, thank you very much for the quick reply!

**Comment by brhahlen** [comment]
...and the great tool!
Just starting to explore it, but it looks great!
@dtslvr
