### ISSUE TITLE
[BUG] Summary page doesn't show content in Dutch language

### ISSUE THREAD

**Issue by jstrvr** [ghostfolio/ghostfolio#2313]
**Bug Description**

Summary page doesn't show content in Dutch language

**To Reproduce**

1. Open ghostfolio (self-hosted/hosted doesn't matter)
2. Set language to Dutch
3. Go to summary page

**Expected behavior**

See a summary with contents.

**Screenshots**

Self-hosted
<img width="1440" alt="Screenshot 2023-09-09 at 15 15 38" src="https://github.com/ghostfolio/ghostfolio/assets/14895505/e9e5fa5c-5c03-4727-8a9b-c10b819bf73b">

Hosted
<img width="1440" alt="Screenshot 2023-09-09 at 15 15 11" src="https://github.com/ghostfolio/ghostfolio/assets/14895505/8986d683-d978-4d18-aa4f-a1e2a1625b60">

**Logs**

**Environment**

- Cloud and Self-hosted
- Ghostfolio Version 2.0.0
- Browser chrome
- OS Mac OS Ventura 13.5.1

**Additional context**

Other languages do seem to work

**Comment by dtslvr** [comment]
Thank you for the bug report, @jstrvr!

This problem seems to have been around for 9 months 😮  I have found the issue and fixed it.
