### ISSUE TITLE
Extend performance endpoint with net worth per day

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2328]
The existing endpoint `api/v2/portfolio/performance` provides a a response in the following format:

```
{
  chart: [
    {
      date: "2020-01-01",
      netPerformance: 0,
      netPerformanceInPercentage: 0,
      totalInvestment: 3627.05,
      value: 3627.05
    },
    ...
  ],
  errors: [],
  firstOrderDate: "2020-01-01T00:00:00.000Z",
  hasErrors: false,
  performance: { ... },
}
```

Extend the chart item by `totalAccountBalance` (cash balance of all accounts) and `netWorth` (`value` + `totalAccountBalance`) fields to render a net worth chart out of it.

**Comment by Siddharth9890** [comment]
I can work on this @dtslvr please

**Comment by M27afk** [comment]
I'd like to work on this! @dtslvr

**Comment by M27afk** [comment]
Is this the right format? @dtslvr 
_Note: Value has been replaced by ValueInPercentage in recent update._

```
 "chart": [
        {
            "date": "2023-10-28",
            "netPerformanceInPercentage": -4.545454545454546,
            "netWorth": 20034,
            "totalAccountBalance": 19968,
            "totalInvestment": 0.4474700184727259,
            "valueInPercentage": 0.06828183728696693
        },
        {
            "date": "2023-10-29",
            "netPerformanceInPercentage": 549.3340041506618,
            "netWorth": 20934.582075444498,
            "totalAccountBalance": 19968,
            "totalInvestment": 1,
            "valueInPercentage": 1
        }
    ],
```

**Comment by dtslvr** [comment]
> Is this the right format?

Yes, the added attributes are fine like this. However, `value` should still be there (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/interfaces/historical-data-item.interface.ts)). Why do you think it has been replaced?

**Comment by M27afk** [comment]
`value` is being used to derive `valueInPercentage` in the latest version.

 However, I'm still using the `value` for `netWorth`.
