### ISSUE TITLE
Implement support for transfer of securities between accounts

### ISSUE THREAD

**Issue by elnigno** [ghostfolio/ghostfolio#2334]
In the past I had to transfer a number of stocks I had in an account in the US to an account in another country.
Unfortunately it's not possible to model this transaction correctly in Ghostfolio, or if it is I can't find out how.

For the moment I have modeled this transfer as a sell for 0 in the source account and a buy for 0 in the destination account, but that alters statistics like Average Unit Price. A sell would also be considered a taxable event, but that's incorrect since it didn't happen.

**Comment by dtslvr** [comment]
Please use the discussion [here](https://github.com/ghostfolio/ghostfolio/discussions/1899) and the upvote feature before raising an issue. Thank you.
