### ISSUE TITLE
[BUG] Unable to add any Activities involving instruments other than cryptocurrencies

### ISSUE THREAD

**Issue by dantrauner** [ghostfolio/ghostfolio#2344]
**Bug Description**

Fresh docker-compose setup results in an inability to add instruments other than cryptocurrencies.

**To Reproduce**

1. Set up `.env`
2. Run `docker-compose --env-file ./.env -f docker/docker-compose.yml up -d`
3. Create account
4. Try to add a Buy Activity; search for `Apple` or `AAPL`
5. Observe the only options are cryptocurrency

**Expected behavior**

Searching for `Apple` or `AAPL` should show Apple Inc. equity and possibly other instruments beyond just cryptocurrencies.

**Screenshots**

![Screenshot 2023-09-16 at 12 36 13 PM](https://github.com/ghostfolio/ghostfolio/assets/1462423/ed554b36-89fa-4153-9b23-e2bd53f692b7)

**Logs**

N/A

**Environment**

- Self-hosted
- Ghostfolio Version 2.1.0 (`latest` tag as of today)
- Chrome
- macOS

**Additional context**

I saw `ALPHA_VANTAGE_API_KEY` was not set in .env.example, so tried both with a valid API key and no API key. I also looked at the general settings to confirm that USD is set as the default currency in case that matters.

Apologies if I missed something else basic!

**Comment by dtslvr** [comment]
Hi @dantrauner

Can you please provide the server log when you search for `Apple` or `AAPL`?

**Comment by dantrauner** [comment]
Good call – it was just overly aggressive network filtering on my end:

```
[Nest] 171  - 09/16/2023, 5:18:18 PM   ERROR [YahooFinanceService] FetchError: request to https://query2.finance.yahoo.com/v1/finance/search?lang=en-US&region=US&quotesCount=6&newsCount=4&enableFuzzyQuery=false&quotesQueryId=tss_match_phrase_query&multiQuoteQueryId=multi_quote_single_token_query&newsQueryId=news_cie_vespa&enableCb=true&enableNavLinks=true&enableEnhancedTrivialQuery=true&q=aapl failed, reason: connect ECONNREFUSED 0.0.0.0:443
```

Fixed now, sorry for the false alarm!
