### ISSUE TITLE
Create carousel component for testimonials

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2370]
Create a new carousel component in `libs/ui/src/lib` for the landing page based on the following source code: [carousel](https://github.com/angular/material.angular.io/tree/7aae145b440c6afb5385dcc8129691ffa36a13c5/src/app/shared/carousel)

**Before**
<img width="1157" alt="testimonials-before" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/440904c7-50c5-4b4d-9cc7-ea155ccf8057">

**After**
<img width="1085" alt="testimonials-after" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/10e928e9-acaf-4ecc-9111-562c7e8bb74c">
(the content with the ghost icon and the name / flag should stay the same as before)

**Comment by subhajit20** [comment]
@dtslvr hey, want to help.
Can you assign it to me?

**Comment by dtslvr** [comment]
> Can you assign it to me?

Sure @subhajit20 😃

**Comment by M27afk** [comment]
@dtslvr I'd like to help!
Can you assign it to me?

**Comment by dtslvr** [comment]
Hi @M27afk

@subhajit20 reached out first and I want to give him his time to implement that. Do you want to take over another ticket in the meantime?

**Comment by dtslvr** [comment]
> sorry for the delay, pr is almost ready just give some time

No problem, just take the time to do it right @subhajit20! 🙂

**Comment by M27afk** [comment]
Okayy @dtslvr !!

**Comment by akhil-pragallapati** [comment]
@dtslvr I would like to help on similar issues, could you please assign me any other issue?

**Comment by dtslvr** [comment]
> @dtslvr I would like to help on similar issues, could you please assign me any other issue?

Maybe this one #2440, @akhil-pragallapati?
