### ISSUE TITLE
Migrate jobs table of Admin Control to mat-table

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2371]
Change the [jobs table](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/admin-jobs) of the _Admin Control_ to an [Angular Material Table](https://material.angular.io/components/table).

Reference: [Market Data table](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/admin-market-data)

**Comment by M27afk** [comment]
Hey @dtslvr !
I'd like to work on this!
Could you please describe how to populate the jobs table for testing purpose?

**Comment by dtslvr** [comment]
> Could you please describe how to populate the jobs table for testing purpose?

You can add some asset profiles at _Admin Control_ > _Market Data_. Then open the kebab menu on the top right of the table and click _Gather All Data_, it will create jobs. But they will be added to the jobs queue and executed shortly after. Maybe you can disconnect the Internet before running _Gather All Data_ to make them fail (and therefore stay in the table).

**Comment by M27afk** [comment]
@dtslvr 
Could you please assign this to others?

**Comment by Basimohd** [comment]
Could you please assign this to me?

**Comment by Basimohd** [comment]
Hey, @dtslvr, I'm looking for guidance on whether it's recommended to implement sorting and pagination features within the mat-table?

**Comment by dtslvr** [comment]
> I'm looking for guidance on whether it's recommended to implement sorting and pagination features within the mat-table?

This issue is only the migration to `mat-table`, sorting and pagination is out of scope for now.
