### ISSUE TITLE
Prepare activities endpoint for pagination

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2374]
Add support for pagination (`skip`, `take`) to the [endpoint](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/order.controller.ts#L84): `GET api/v1/order`

Reference: `GET api/v1/admin/market-data` (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.controller.ts#L252))

**Comment by shyam1s15** [comment]
Hiii I am working on it thank you, raising a PR soon
