### ISSUE TITLE
[BUG] Importing Sell Activities with Negative Quantity will increase the number of Shares Purchased

### ISSUE THREAD

**Issue by rafacla** [ghostfolio/ghostfolio#2375]
**Bug Description**

When importing a CSV file with Activities, if you define the Activity as Sell, but keep the Quantity negative, it'll sum as a Purchase (it'll add instead of subtract)

**To Reproduce**

1. Import a CSV file with a Sell activity and a Negative quantity
2. Check your holds and you'll see that now you have this quantity as purchased instead of sell

**Expected behavior**

When importing or creating an Activity of the Sell type, no matter if the Quantity is negative in the input, it should be considered as a Sell of that Quantity not a Purchase

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/3695510/968734c3-f490-4523-9e85-4f3f7edb5735)
![image](https://github.com/ghostfolio/ghostfolio/assets/3695510/1955a23e-5216-40c3-aa07-06f9d69e9a84)

**Environment**

- Self-hosted
- Ghostfolio Version 2.4.0
- Chrome
- Linux

**Additional Context**
Probably, the easiest solution would be to implement a validation when importing the CSV file, but maybe it should also treat this in the calculation?

I can help on the solution of this issue, but probably we should discuss this first?

**Comment by dtslvr** [comment]
Hi @rafacla

The `csv` import should be tolerant and transform `quantity`, `unitPrice` and `value` to an absolute value ([ImportActivitiesService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/services/import-activities.service.ts)).

However, the API should be strict and only tolerate `values >= 0` for `quantity`, `unitPrice` and `value` ([CreateOrderDto](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/create-order.dto.ts) and [UpdateOrderDto](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/update-order.dto.ts))

What do you think of this approach?

**Comment by rafacla** [comment]
> Hi @rafacla
> 
> The `csv` import should be tolerant and transform `quantity`, `unitPrice` and `value` to an absolute value ([ImportActivitiesService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/services/import-activities.service.ts)).
> 
> However, the API should be strict and only tolerate `values >= 0` for `quantity`, `unitPrice` and `value` ([CreateOrderDto](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/create-order.dto.ts) and [UpdateOrderDto](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/update-order.dto.ts))
> 
> What do you think of this approach?

Hi @dtslvr 

I think it's a good idea, I can work on that if you will

**Comment by dtslvr** [comment]
Go for it @rafacla! 😎

**Comment by rafacla** [comment]
Hi @dtslvr 
Sorry for the time out, I'm with a small baby in home, so things are a bit complicated nowadays hehe

I made minors changes at the code like you suggested, just a doubt to we discuss, for instance, the way we are checking for positive numbers, in case you earned assets with unitPrice zero, the API won't let the importer continue.

Does it makes sense? I mean, there's any scenario where we should import an asset with Zero unitPrice? So far I know, even bonus stocks has a price on it, but what do you think about?

I've created a draft PR https://github.com/ghostfolio/ghostfolio/pull/2496
