### ISSUE TITLE
Change UX to set an asset profile as a benchmark

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2381]
Change the benchmark setting in the [asset profile dialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog) from the action menu to a checkbox.

<img width="1239" alt="benchmark-ux" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/a5dabbc4-f04d-405a-b288-ff91b84f9b9f">

**Comment by shyam1s15** [comment]
please assign this issue to me, starting on it thankyou :)

**Comment by M27afk** [comment]
Hey @dtslvr ! I'd like to work on this!
Could I get assigned?
