### ISSUE TITLE
Switch activities table to lazy loading (pagination)

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2384]
As a follow up task of #2374, the reusable [ActivitiesTableComponent](https://github.com/ghostfolio/ghostfolio/tree/main/libs/ui/src/lib/activities-table) should be combined with lazy loaded pages.

Create a concept for the [ActivitiesPageComponent](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/activities/activities-page.component.ts#L105).

**Comment by dtslvr** [comment]
What about adding `@Input() dataSource: MatTableDataSource<Activity>;` to the `ActivitiesTableComponent`? (and still support the current concept (`Input() activities: Activity[];`)?

**Comment by shyam1s15** [comment]
Hii, would you like to describe more, actually didnt understood the problem

**Comment by dtslvr** [comment]
At the moment, all the activities are loaded, but this does not work well if you have 100+ activities. Therefore we would like to introduce pagination for the activities table and only fetch the activities actually needed.

As the `ActivitiesTableComponent` is used in different parts of the app, we should focus on the`ActivitiesPageComponent` (`localhost:4200/en/portfolio/activities`) first. Instead of passing activities (`Input() activities: Activity[];`), a dataSource (`@Input() dataSource: MatTableDataSource<Activity>;`) should be passed as an input to the `ActivitiesTableComponent`.

**Comment by Basimohd** [comment]
@dtslvr I would like to work in this issue. I'm not much familiar in datasource workings. Although I am giving a try to do it. I've a doubt that should I pass the activities to the component for other uses of activities in the component or should I use datasource.data instead of activities in activities-table.component

**Comment by dtslvr** [comment]
I suggest to have both `@Input()` at the same time and check (e.g. in `ngOnChanges()`) which of them is available for the logic.
