### ISSUE TITLE
[BUG] FIRE calculator freezes when 0 is entered as projected total amount

### ISSUE THREAD

**Issue by ondrejkopka** [ghostfolio/ghostfolio#2387]
**Bug Description**
I accidentaly put 0 into Projected Total Amount and Ghostfolio freezes

I used Ghostfolio on my phone, wanted to change projected total amount and because page is instantly recalculating it, i somehow managed to put 0 here, browser tab gets stuck instantly and it's not possible to change this value as whole page is unresponsible.

**To Reproduce**

1. open https://$instance/en/portfolio/fire
2. put 0 into Projected Total amount
3. watch it freeze browser tab
4. when you wait long enough, Projected Total amount value changes to 1 but tab is stil freezed

**Expected behavior**

I would expect values to recalculate

**Screenshots**

<img width="292" alt="obrazek" src="https://github.com/ghostfolio/ghostfolio/assets/2601375/c77920e0-94a7-4019-b5e0-9abbacf2b4e5">

**Logs**
logs are not saying anything

**Environment**

- Self-hosted
- Ghostfolio Version 2.5.0
- Firefox 117.0.1
- macOS 13.5.2 (22G91)

**Comment by dtslvr** [comment]
I was unable to reproduce the issue described here.
