### ISSUE TITLE
Extend Turkish translation

### ISSUE THREAD

**Issue by sadmimye** [ghostfolio/ghostfolio#2397]
Turkish translation is on the way

**Comment by dtslvr** [comment]
@sadmimye what is the current status here?

**Comment by sadmimye** [comment]
Dear Thomas,

I am currently having some family issues these days. I will send a new PR
as soon as possible. Apologies for not being able to keep up the initial
pace.

Regards

*****************************************
Sadık Murat YÜKSEL
İlim kesbiyle paye-i rif’at / Bir hayal-i muhal imiş ancak.
Aşk imiş her ne var alemde / İlim bir kiylü kal imiş ancak.
*****************************************


Thomas Kaul ***@***.***>, 27 Eki 2023 Cum, 20:32 tarihinde
şunu yazdı:

**Comment by dtslvr** [comment]
Hi @sadmimye

No need to apologize at all, I completely understand.
Whenever you are ready to send the new PR, we will be here to review and merge it. In the meantime, take care of your family!
