### ISSUE TITLE
Problem Running the Frontend

### ISSUE THREAD

**Issue by AmirNaghibi** [ghostfolio/ghostfolio#241]
I followed the setup instructions in README. 

For the server, I ran `yarn start:server` and for client, I ran `yarn start:client` 

However, I get the following error and `http://localhost:4200/` is blank (nothing is showing up)

![Screen Shot 2021-07-31 at 7 53 04 PM](https://user-images.githubusercontent.com/20001191/127757560-d1f2c8d1-902c-4d74-a3ee-4596527b9997.png)

Any idea how to solve this? 

really cool project btw 🙏🏼 😃

**Comment by dtslvr** [comment]
Hello @AmirNaghibi

Thanks for creating a ticket. It looks like the server is not running.

What happens in the log when you run `yarn start:server`? You should finally see:

`[Nest] 46139   - 01/08/2021, 09:43:20   Listening at http://localhost:3333 +1ms`

To double check that the server is running, you can call the endpoint `GET http://localhost:3333/api/info` and you should get a response (`200 OK`).

**Comment by AmirNaghibi** [comment]
It works 🎉 I'm not sure what I did wrong the first round 😄 

I've noticed that data gathering happens automatically and I don't need to click on the `Gather All Data` button. Is that expected? How long does data gathering take? (so far it has been 20min)


When I log out and click on `Live Demo` I get an error in the server:

![Screen Shot 2021-08-03 at 8 33 51 AM](https://user-images.githubusercontent.com/20001191/128043796-cc640812-6075-443b-8f7e-67f4f53d6d20.png)


maybe it is still downloading data?

**Comment by dtslvr** [comment]
Great, at least the first part 😃 

`Gather All Data` will not run automatically, but the 7d data gathering.

You only need to run `Gather All Data` (max) once, but it will take some time. 45min seems to be very long 🤔 

You could run `yarn database:gui` to check the records of the `MarketData` table.

I have created an issue for your error: #249

**Comment by dtslvr** [comment]
#249 has been fixed via #253.

**Comment by AmirNaghibi** [comment]
Awesome! I'll run the app again tomorrow!

**Comment by dtslvr** [comment]
> Awesome! I'll run the app again tomorrow!

Is it working for you now, @AmirNaghibi?

**Comment by AmirNaghibi** [comment]
Apologies, I forgot to get back to you.

I remember that I ran the application again and it worked. 

Will close this issue. Thanks for your help, Thomas :)

**Comment by dtslvr** [comment]
> I remember that I ran the application again and it worked.

Thank you for the update. Please let me know if you have any questions.
