### ISSUE TITLE
[BUG] Invalid account form is submitted by pressing enter

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2418]
**Bug Description**

When I press the enter key in the state of the `CreateOrUpdateAccountDialog` as shown below, an http request is sent to the backend and the dialog is closed.

**Expected behavior**

Should not send an http request to the backend and keep the dialog open if the form is invalid.

**Screenshots**

<img width="791" alt="add-account-press-enter" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/d574e99e-ea9d-4c43-8181-11d80dde5748">

**Logs**

```
POST http://localhost:4200/api/v1/account 400 (Bad Request)
```

**Comment by RANJEETJ06** [comment]
is it resolved or what ?
#2418

**Comment by dtslvr** [comment]
Hi @RANJEETJ06

> is it resolved or what ? #2418

No, this is a follow-up task of #2418.

**Comment by akshaywadatkar** [comment]
I just want to know if the dialog will close after press enter or not ? #2418

**Comment by dtslvr** [comment]
> I just want to know if the dialog will close after press enter or not ? #2418

Yes, the dialog currently closes after pressing enter (regardless if the form is valid or not), but it should only close if the form is valid. I have refined the description above.

**Comment by dtslvr** [comment]
> Is anyone currently working on this ?

Not yet, as far as I know.

**Comment by anirudhsudhir** [comment]
I'd like to work on this issue. Could you assign it to me?
