### ISSUE TITLE
Change platform control from select to autocomplete in account dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2419]
As platforms are growing, a simple select is not enough anymore: Change the platform form control from [Select](https://material.angular.io/components/select/overview) to [Autocomplete](https://material.angular.io/components/autocomplete/overview) in the [account dialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/accounts/create-or-update-account-dialog). Make sure that only a platform from the list is a valid value.

<img width="795" alt="account-form" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/7ed5aaa2-1b6f-4eef-abfb-958a985e39de">

**Comment by KK4ito** [comment]
Hi @dtslvr , I can work on this if its still unassigned
