### ISSUE TITLE
Use current version from AdminData (endpoint) in Admin Control panel

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2424]
Change the current version of Ghostfolio in the [Overview](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/admin-overview) of the Admin Control panel.

<img width="1225" alt="version-in-admin-control-panel" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/447e056b-0aef-4997-965d-cac03ca0c45e">

The version should be fetched from `AdminData` instead of `environment.version` (deprecated for security reasons).

The template should be changed to a `gf-value` component (for the loading indicator):

```
<gf-value [value]="version" />
```

**Comment by Franqsanz** [comment]
Hello @dtslvr , that would be the only change?

**Comment by dtslvr** [comment]
> Hello @dtslvr , that would be the only change?

Yes, this is a relatively small change. Good as a first issue 🙂

**Comment by Franqsanz** [comment]
Where to import AdminData from?

**Comment by dtslvr** [comment]
> Where to import `AdminData` from?

You can get the version from [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-overview/admin-overview.component.ts#L207).
