### ISSUE TITLE
Create form in dialog for cash transfer between accounts

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2432]
As a preparation to transfer a cash balance from one account to another, we need a GUI very similar to [CreateOrUpdateAccountDialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/accounts/create-or-update-account-dialog):

<img width="1170" alt="transfer-cash-balance" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/439e7ad4-541f-4d50-a590-b6542aa73a4c">

- [ ] Add button _Transfer Cash Balance_ to [AccountsPageComponent](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/accounts)
- [ ] Add `transfer-balance-dialog` similar to [create-or-update-account-dialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/accounts/create-or-update-account-dialog) according to the mockup
- [ ] Populate _From_ and _To_ selectors with available accounts
- [ ] Log a message on form submit like "Transfer cash balance of 100 from account ce1a94d4-08cf-46c1-8c4b-8356682f495e to account 84a00b32-d4e7-4e20-a257-b04114ac43da"

**Comment by Dhoni77** [comment]
Hey @dtslvr  I would like to take up this issue can you please assign it to me.
Thanks.

**Comment by dtslvr** [comment]
I have created a follow-up task including the API implementation: #2446
