### ISSUE TITLE
Create GET api/v1/account/:id/balances endpoint

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2435]
Create a new API endpoint in the [AccountController](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/account/account.controller.ts):

`GET api/v1/account/:id/balances` which should return the following object:

```
{
  "balances": [
    {
      "date": "2023-10-04T00:00:00.000Z",
      "id": "e7da015d-457e-46d2-9000-46baec119031",
      "value": 7178.4
    },
    ...
  ]
}
```

To get the data from the database, create a new function `getAccountBalances(accountId: string)` in [AccountBalanceService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/account-balance/account-balance.service.ts).

Hint: you can easily populate the `AccountBalances` table by updating the _Account Balance_ of an account multiple times.

**Comment by pkolc** [comment]
Hi can you please assign me this issue?

**Comment by thesanjeevsharma** [comment]
Is this in progress currently? If not, can I try this?

**Comment by pkolc** [comment]
Yes, I am working on it.

**Comment by tibormichel1** [comment]
Hello @dtslvr dont you have something simular to this issue ? (needed for university task)

**Comment by thesanjeevsharma** [comment]
Is this still in progress? @dtslvr can I work on this?

**Comment by pkolc** [comment]
#2484

**Comment by pkolc** [comment]
#2484

**Comment by dtslvr** [comment]
Follow-up task: #2491
