### ISSUE TITLE
API import missing transactions

### ISSUE THREAD

**Issue by tzwaeaen** [ghostfolio/ghostfolio#2438]
**Bug Description**

I try to write an importer using the import API for one trading platform that I am using. My first issue was that I don't have all transaction after running the script. After some analyzes I found that I have some trades on the same day, with same quantity and same market price. Only some minutes later than the first trade.

**To Reproduce**

1. having a list of trades, some trades having the same date (different time), same quantity, same market price
2. convert list to json
3. call import API

**Expected behavior**

Having the same number of transaction in ghostfolio as in the list.
Having the API reporting a duplicate transaction error. Instead the activities object in the response is empty for those imports.

**Screenshots**
-

**Logs**
-

**Environment**

- Self-hosted
- Ghostfolio Version 2.8.0

**Additional context**

In `ghostfolio/apps/api/src/app/import/import.service.ts` I found `isSameDay(activity.date, date) &&`. Is there some way to change the coding in my instance  that it is using the timestamp with time or to include the comment in the duplicate detection? I put the transaction id from my trading platform into the comment.

Thanks for your help :-)

**Comment by tzwaeaen** [comment]
Ok, I did a dirty fix to import my missing transactions. I used the dockerfile to create a temporary image and during creation I changed the coding in the above mentioned file to `activity.date == date` via `sed`. During the start of the temp container I copy the compiled `/ghostfolio/apps/api/main.js` to a mounted volume and place it inside my main ghostfolio container. :-|

**Comment by ms32035** [comment]
Experiencing the same issue. @dtslvr you recon this https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/import/import.service.ts#L491 should be `isSameSecond` ?
