### ISSUE TITLE
Create membership card component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2440]
Create a new membership card component (`gf-membership-card`) in `libs/ui/src/lib` inspired by the following [CodePen](https://codepen.io/JavaScriptJunkie/pen/YzzNGeR).

<img width="1235" alt="membership-card" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/78308223-8366-4894-9e81-7be754b7c75d">

- [ ] Create component
- [ ] Support an input parameter `@Input() public expiresAt: Date;` and render it in the component (_Expires_)
- [ ] Integrate the component in the [AboutOverviewPageComponent](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/about/overview)

**Comment by infiniteltd** [comment]
I would love to work on this issue.

**Comment by akhil-pragallapati** [comment]
yes @dtslvr , issues like this, please let me know if any in future

**Comment by dtslvr** [comment]
Any progress to share on this @infiniteltd?

**Comment by dtslvr** [comment]
As @infiniteltd does not respond anymore, I am unblocking this ticket.

Who would like to take it over?

**Comment by Basimohd** [comment]
I would like to take it up?

**Comment by Basimohd** [comment]
@dtslvr what about card holder should i just write as it is?

**Comment by dtslvr** [comment]
> what about card holder should i just write as it is?

You could add `@Input() public name: string;` to make it customizable.

> and where should i integrate in AboutOverviewPageComponent

You can integrate it below everything else in the bottom.
