### ISSUE TITLE
[BUG] Endpoint api/v1/portfolio/positions is requested twice when loading Holdings in Overview

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2442]
**Bug Description**

The API endpoint `GET api/v1/portfolio/positions` is requested twice when loading the holdings tab from the overview.

**To Reproduce**

1. Login to Ghostfolio
2. Select _Holdings_
3. Check _Network_ in your browser's web developer tools

**Expected behavior**

`GET api/v1/portfolio/positions` is only requested once.

**Environment**

- Cloud and Self-hosted
- Ghostfolio Version 2.8.0

**Comment by Yasir761** [comment]
I want to give it a try, Please do assign me

**Comment by Yasir761** [comment]
Hey, @dtslvr I give it a try, but I didn't able to solve it, My bad.

**Comment by Basimohd** [comment]
@dtslvr Could you please assign this to me?

**Comment by Fullstack-Arshad** [comment]
@dtslvr  just one hour back I saw Yasir761 removed this task assignment, So I simply started working on it. Now when I have fixed it, It's assigned to Basimohd. My bad, I should have asked first to assign it to me 😕
But the solution is simple only

https://github.com/ghostfolio/ghostfolio/assets/61023134/197be73d-41b4-4d8b-ab69-24dea1ebb21f

**Comment by Basimohd** [comment]
@dtlsr, if the commit by @Fullstack-Arshad is correct, kindly assign him the issue; otherwise, I will check it out by setting up.

**Comment by Fullstack-Arshad** [comment]
Hi @Basimohd, I am so sorry I committed and pushed that code just as a backup so that I can start working on other bug, I did not mean to take this task from you. But thanks for allowing me I have added a PR @dtslvr
