### ISSUE TITLE
Add date column in gf-benchmark component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2463]
Add a new column (_Last All Time High_) displaying the `date` value to the [BenchmarkComponent](https://github.com/ghostfolio/ghostfolio/tree/main/libs/ui/src/lib/benchmark).

<img width="1393" alt="markets-with-date" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/f21f7803-dfb3-4a51-86e4-28cdb7e7d4d1">

The column should not be visible on small devices (compare with implementation of [ActivitiesTableComponent](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/activities-table/activities-table.component.html#L197)).

**Comment by Dhoni77** [comment]
Hi @dtslvr  I can take this up
