### ISSUE TITLE
[Style] Progressbar style 

### ISSUE THREAD

**Issue by manuelbento19** [ghostfolio/ghostfolio#2471]
I would like to work on styling the scrollbar.
![Captura de ecrã 2023-10-11 151503_](https://github.com/ghostfolio/ghostfolio/assets/65732773/29c80e64-c8a5-4178-b2a9-00f6f7d0cdef)

**Comment by dtslvr** [comment]
Hi @manuelbento19

This seems to be a bug in _Microsoft Edge_: [Scrollbars are white even in dark mode](https://www.reddit.com/r/MicrosoftEdge/comments/xrf1wb/scrollbars_are_white_even_in_dark_mode)

There are no plans to fix this within Ghostfolio.
