### ISSUE TITLE
[BUG] Import error when importing CSV with fee type

### ISSUE THREAD

**Issue by rotojp** [ghostfolio/ghostfolio#2472]
**Bug Description**

When trying to import a CSV on the a "Import activities" option, I get the following error:

> activities.1.type is not valid
>
>  {
>   "accountId": "`account`",
>   "Date": "`xx-xx-xxxx`",
>   "symbol": "Management fee",
>   "currency": "EUR",
>   "unitPrice": 0,
>   "quantity": 0,
>   "type": "FEE",
>   "fee": `x.x`,
>   "comment": null
> }

Self-hosted (2.9.0 - 2023-10-08)

**Comment by dtslvr** [comment]
Thank you for the report @rotojp.
