### ISSUE TITLE
Add chart to account detail dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2475]
Integrate the [InvestmentChartComponent](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/investment-chart) into the [AccountDetailDialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/account-detail-dialog).

<img width="1279" alt="account-details-with-chart" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/89fb6336-6f0f-4b6f-b756-f26b665ace0f">

Fetch `historicalDataItems` (use `value` of `chart`) via [fetchPortfolioPerformance()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/services/data.service.ts#L386) (filter by `accountId`, `range: 'max'`)  and leave `benchmarkDataItems` empty.

**Comment by Basimohd** [comment]
Could you please assign this to me?

**Comment by Basimohd** [comment]
@dtslvr Should I label the y-axis with years, as shown in the picture, or is the current representation sufficient?

![image](https://github.com/ghostfolio/ghostfolio/assets/107759928/ae31a6a9-d0b2-4ae6-b93b-013c06279c9b)

**Comment by dtslvr** [comment]
> Should I label the x-axis with years, as shown in the picture, or is this representation sufficient?

Yes, keep the x-axis with years from [InvestmentChartComponent](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/investment-chart).

**Comment by Basimohd** [comment]
Thank you for the clarification. In that case, I'll keep the x-axis with years from the InvestmentChartComponent. Regarding the values, I'll proceed with summing the `value`. Does that sound correct?

Regarding the y-axis, do you have any specific label recommendations, or is the current representation satisfactory?

**Comment by dtslvr** [comment]
> I'll proceed with summing the `value`.

You don't need to sum anything. Pass all `date` and `value` you get from `fetchPortfolioPerformance()` (on `chart` attribute).

> Regarding the y-axis, do you have any specific label recommendations, or is the current representation satisfactory?

Don't change [InvestmentChartComponent](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/investment-chart), just reuse the component as is please.

**Comment by Basimohd** [comment]
![image](https://github.com/ghostfolio/ghostfolio/assets/107759928/cfb2070c-5012-4f72-bdfc-2da89e1030c2)

@dtslvr Apologies for any inconvenience, but I'd like to confirm if the implementation in the image above is correct. Would it be appropriate for me to submit a pull request?

**Comment by dtslvr** [comment]
It looks like a chart 😄 Please create your pull request @Basimohd and I will give you feedback based on the code. Okay?

**Comment by Basimohd** [comment]
Yeah! Sure😊
