### ISSUE TITLE
Change checkboxes to slide toggle in account settings

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2482]
Change all [Checkbox](https://material.angular.io/components/checkbox) to [Slide toggle](https://material.angular.io/components/slide-toggle) components in the [Account Settings](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/user-account-settings). Set `hideIcon` to `true` and keep the `color` (`primary`).

<img width="1158" alt="account-settings" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/53d5fb39-2579-45a6-bc22-2c834002d4dc">

**Comment by RaviTejaVattem** [comment]
Hi @dtslvr,

I want to try this.

I think I need to change the `mat-checkbox`es in `user-account-settings.html` to `mat-slide-toggle`. Please let me know if this is correct so that I can create a PR.

**Comment by dtslvr** [comment]
@rohitverma007 you should wait until the ticket is cleared for you.

@RaviTejaVattem do you want to resume @rohitverma007's changes? There is still a problem with the style (unchecked slide toggles are not in primary color, checked slide toggles are barely visible):

<img width="1152" alt="account-settings-rohit" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/5fe420a3-19f6-4aa4-9bfe-c531d0bbed17">

**Comment by RaviTejaVattem** [comment]
Hi @dtslvr,

I will be creating a new PR for this.

**Comment by rohitverma007** [comment]
Hey @dtslvr,
My apologies, I didn't realize the PR was already assigned and jumped the gun a bit and prematurely created a PR, I will close mine and let @RaviTejaVattem continue.

**Comment by dtslvr** [comment]
No problem @rohitverma007 and thanks to @RaviTejaVattem for the implementation.
