### ISSUE TITLE
Add a loader/progress bar when switching menu in navbar

### ISSUE THREAD

**Issue by dev-palwar** [ghostfolio/ghostfolio#2485]
When we click on a menu in the navbar, there is a delay of at least half a second which does not feel good at all. It would look good if there were a progress bar at the top (below the navbar) like this when a new page finishes loading.

![Screenshot 2023-10-14 at 13-55-09 Progress](https://github.com/ghostfolio/ghostfolio/assets/102988552/de82d068-2070-4dc5-b381-f6d93523db30)

**Comment by dtslvr** [comment]
Hi @dev-palwar

The static files of the page should load immediately and for the content components we are using [skeleton loaders](https://www.nngroup.com/articles/skeleton-screens) whenever possible. Thus, I think there is no reason to add an additional progress bar at the moment.
