### ISSUE TITLE
[BUG] BTC-EUR/ETH-EUR data is not being pulled from yahoo

### ISSUE THREAD

**Issue by oofsoundeffect** [ghostfolio/ghostfolio#2486]
**Bug Description**

For about 30 days now I'm getting an error on the Overview saying 
Data Provider Errors for
BTCEUR (YAHOO)
ETHEUR (YAHOO)

I've checked the logs and I get some errors like the ones below. I actually clicked the links, like this one:
https://query2.finance.yahoo.com/v7/finance/download/BTCEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600 . And indeed they don't load. 

But then when I modify the URL a little bit and instead put [...]download/**BTC-EUR**?interval=[...] I can download the data just fine. 

Not sure if this fix has to be applied by you guys or somewhere in a library upstream, but I'd really appreciate if this issue were fixed, given that it's just a silly dash :)

**Logs**

[Nest] 158  - 10/14/2023, 12:04:21 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
https://query2.finance.yahoo.com/v7/finance/download/BTCEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 1:00:01 PM   ERROR [DataProviderService] Error: Could not get historical market data for BTCEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
https://query2.finance.yahoo.com/v7/finance/download/ETHEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 1:00:04 PM   ERROR [DataProviderService] Error: Could not get historical market data for ETHEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
https://query2.finance.yahoo.com/v7/finance/download/BTCEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 2:00:00 PM   ERROR [DataProviderService] Error: Could not get historical market data for BTCEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
https://query2.finance.yahoo.com/v7/finance/download/ETHEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 2:00:04 PM   ERROR [DataProviderService] Error: Could not get historical market data for ETHEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
[Nest] 158  - 10/14/2023, 2:03:54 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 158  - 10/14/2023, 2:05:07 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 158  - 10/14/2023, 2:05:09 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 158  - 10/14/2023, 2:05:33 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 158  - 10/14/2023, 2:06:10 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
https://query2.finance.yahoo.com/v7/finance/download/BTCEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 2:10:10 PM   ERROR [DataProviderService] Error: Could not get historical market data for BTCEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
https://query2.finance.yahoo.com/v7/finance/download/ETHEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 2:10:14 PM   ERROR [DataProviderService] Error: Could not get historical market data for ETHEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
[Nest] 158  - 10/14/2023, 2:16:50 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 158  - 10/14/2023, 2:17:05 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 158  - 10/14/2023, 2:17:10 PM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 158  - 10/14/2023, 2:18:18 PM   ERROR [CoinGeckoService] RequestError: The operation was aborted
[Nest] 158  - 10/14/2023, 2:18:18 PM   ERROR [CoinGeckoService] RequestError: The operation was aborted
[Nest] 158  - 10/14/2023, 2:18:18 PM   ERROR [CoinGeckoService] RequestError: The operation was aborted
[Nest] 158  - 10/14/2023, 2:18:18 PM   ERROR [CoinGeckoService] RequestError: The operation was aborted
[Nest] 158  - 10/14/2023, 2:18:18 PM   ERROR [CoinGeckoService] RequestError: The operation was aborted
[Nest] 158  - 10/14/2023, 2:32:02 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDBTCEUR
https://query2.finance.yahoo.com/v7/finance/download/BTCEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 2:34:14 PM   ERROR [DataProviderService] Error: Could not get historical market data for BTCEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
https://query2.finance.yahoo.com/v7/finance/download/ETHEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696636800&period2=1697241600
[Nest] 158  - 10/14/2023, 2:34:18 PM   ERROR [DataProviderService] Error: Could not get historical market data for ETHEUR (YAHOO) from 2023-10-07 to 2023-10-14: [HTTPError] Not Found
https://query2.finance.yahoo.com/v7/finance/download/ETHEUR?interval=1d&events=history&includeAdjustedClose=true&period1=1696032000&period2=1696118400
[Nest] 158  - 10/14/2023, 2:37:51 PM   ERROR [DataProviderService] Error: Could not get historical market data for ETHEUR (YAHOO) from 2023-09-30 to 2023-10-01: [HTTPError] Not Found

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/128265265/1a4d444c-ab45-4ff7-9dd8-8d7df70b88cf)
![image](https://github.com/ghostfolio/ghostfolio/assets/128265265/0cb74477-feba-4c54-ac24-ee6d2fc5380d)
**Environment**

- Self-hosted
- Ghostfolio Version 2.10.0
- Waterfox G6.0.4 / browser agnostic
- Windows 10 / OS agnostic

**Comment by dtslvr** [comment]
Hi @oofsoundeffect

I suspect that this is related with the update to Ghostfolio 2.0 and you are still using the environment variable `BASE_CURRENCY`. This has been deprecated since version [1.264.0](https://github.com/ghostfolio/ghostfolio/blob/e1022846b9969aeee01232cdfe32acfe6cb007ce/CHANGELOG.md?plain=1#L735) and was finally removed in version [2.0.0](https://github.com/ghostfolio/ghostfolio/blob/e1022846b9969aeee01232cdfe32acfe6cb007ce/CHANGELOG.md?plain=1#L189).

I would recommend that you create a new activity for `BTC` (`COINGECKO` will be used automatically as a data source and not `YAHOO`) and then migrate your activities to this new ticker.

**Comment by MRobi1** [comment]
> I would recommend that you create a new activity for BTC (COINGECKO will be used automatically as a data source and not YAHOO) and then migrate your activities to this new ticker.

Is there a simple way of doing this or do we have to recreate every crypto transaction and make sure we select the proper currency while doing so? Having the same issue with BTCCAD. Sounds like a nightmare to me.
