### ISSUE TITLE
MANUAL data source, unable to set market price for today's date

### ISSUE THREAD

**Issue by karter16** [ghostfolio/ghostfolio#2512]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

There appears to be a bug with the new MANUAL data source feature in that once you have created a new MANUAL data source, and recorded an activity against it, you can go to Admin Control > Market Data > [the manually created datasource] and you get the popup which shows the history graph. You can click on each day to add the historical market price. However today's date shows in blue and appears to be locked to the value 123.45. I cannot find any way to change this. It appears that "today's date" is also the default date to use for past days that have no value specified. This means that it's almost impossible to use as it always appears as though the current value is 123.45

**To Reproduce**

1. Add a MANUAL data source
2. Create one or more historical activities using the manually created data source
3. Observe that today's value for the data source is always 123.45

**Expected behavior**

You should be able to set the value for today to its real value.

**Screenshots**
<img width="903" alt="Screenshot 2023-10-19 at 8 07 11 PM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/e0109ccf-503a-468d-b204-af33381996e6">

**Logs**

**Environment**

- Self-hosted
- Ghostfolio Version 2.12.0
- Browser Safari
- OS MacOS

**Additional context**

**Comment by karter16** [comment]
Thank you very much for addressing this so quickly - have upgraded and tested this out and it's working nicely now! thank you!

**Comment by dtslvr** [comment]
> have upgraded and tested this out and it's working nicely now!

Great, thanks for the feedback! If you believe in what we do and would like to help us continue our mission, please consider [supporting us](https://www.buymeacoffee.com/ghostfolio).

**Comment by karter16** [comment]
Great, thanks for the feedback! If you believe in what we do and would like to help us continue our mission, please consider [supporting us](https://www.buymeacoffee.com/ghostfolio).

Done :-)

**Comment by dtslvr** [comment]
> Done :-)

Thank you very much! 🙂
