### ISSUE TITLE
Receive the message "Oops! Could not get the historical exchange rate from [dd/mm/yyyy]" when adding an activity in a target currency

### ISSUE THREAD

**Issue by karter16** [ghostfolio/ghostfolio#2518]
**Bug Description**

When attempting to add an activity to record a historical bitcoin purchase in NZD, I am encountering the message "Oops! Could not get the historical exchange rate from..." when setting the unit price in NZD. It does not appear to matter what date I set the activity for, the message is the same.

**To Reproduce**

1. Create a new activity and set, for example, bitcoin as the name
2. Specify an activity date that is in the past
3. Enter a quantity
4. Change unit price currency to NZD (in my example)
5. Observer the error message "Oops! Could not get the historical exchange rate from [dd/mm/yyyy]"
6. Observe that even when entering a unit price you are unable to save the activity record

**Expected behavior**

When selecting a unit price exchange rate the exchange rate on that day should be retrieved and you should be able to enter a unit price in your target currency, and then go on to be able to save the activity record.

**Screenshots**

<img width="808" alt="Screenshot 2023-10-21 at 8 33 47 AM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/e700471e-2615-4163-ae55-2faf3cd8ee82">

**Logs**

**Environment**
- Self-hosted
- Ghostfolio Version 2.13.0
- Safari 17.0 (19616.1.27.211.1)
- MacOS Sonoma 14.0

**Additional context**

**Comment by dtslvr** [comment]
Hi @karter16

You probably need to load the market data first:

1. Go to _Admin Control_ > _Market Data_
2. In _Filter by..._ select the _Currencies_ preset
3. Click on `USDNZD`
4. Select _Gather Historical Data_ from the action menu

**Comment by karter16** [comment]
My apologies - this was absolutely the issue. Didn't realise I needed to gather the historical data :-) all good now!
