### ISSUE TITLE
Improve historical market data import

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2521]
<img width="1294" alt="market-data-import" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/8ec8458a-a44a-445d-ab18-5c456b4cb728">

With this ticket, the historical market data import should be improved with the following:

- [ ] Create a dedicated form group for the historical market data import
- [ ] Consider the [default value](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts#L55) as "invalid" (disable the _Import_ button)
- [X] Change [parseISO()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts#L160) to [parseDate()](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/helper.ts#L295)
- [ ] Wrap `csvToJson` and `parseDate()` in one `try / catch` block and show a [snackbar](https://material.angular.io/components/snack-bar) on error
- [ ] Remove the current [placeholder](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.html#L64)

**Comment by dtslvr** [comment]
> i woulod love to work on this issue

Hi @priyanshu9899

Any progress on this issue to share?

**Comment by Dhoni77** [comment]
Hi @dtslvr I would like to take this up

**Comment by Dhoni77** [comment]
Hi @dtslvr here should I create a new formgroup or add a group to the existing form ?
**Create a dedicated form group for the historical market data import**

**Comment by dtslvr** [comment]
> should I create a new formgroup or add a group to the existing form ?

These forms are quite different and will be submitted independently. The nesting is only caused by the structure of the dialog, because the submit button is located in the action. That's why I'm tending towards independent form groups, but I'm not really familiar with sub forms either. What are your thoughts?

**Comment by Dhoni77** [comment]
> > should I create a new formgroup or add a group to the existing form ?
> 
> These forms are quite different and will be submitted independently. The nesting is only caused by the structure of the dialog, because the submit button is located in the action. That's why I'm tending towards a new form group, but I'm not really familiar with sub forms either. What are your thoughts?

I'll try using a sub form group and try to handle submits for import and normal submit.
