### ISSUE TITLE
Extend the asset profile dialog form

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2524]
Extend the [AssetProfileDialog](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/asset-profile-dialog/asset-profile-dialog.component.ts) form by `name` (required), `assetClass` and `assetSubClass` where `dataSource` is `MANUAL` (same as `scraperConfiguration`).

Here you can find examples for the [asset class selector](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/activities/create-or-update-activity-dialog/create-or-update-activity-dialog.html#L285) and [asset sub class selector](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/activities/create-or-update-activity-dialog/create-or-update-activity-dialog.html#L301).

<img width="796" alt="extend-asset-profile-dialog-form" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/465aaf5e-8894-4d89-9b0b-b45183c89a32">

**Comment by Dhoni77** [comment]
Hi @dtslvr  I would like to work on this
