### ISSUE TITLE
Extend holding by dividend yield

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2533]
Extend [PortfolioPositionDetail](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/interfaces/portfolio-position-detail.interface.ts) by `dividendYieldInPercent` so that `GET api/v1/position/:dataSource/:symbol` returns the dividend yield expressed as a percentage.

For development / testing, you can use [ok-dividend.json](https://github.com/ghostfolio/ghostfolio/files/13062626/ok-dividend.json) with real world data for `MSFT` (add to `./test/import/`).

**Comment by Fullstack-Arshad** [comment]
Hi @dtslvr can you give any reference of it, within the project, so that I can see it and try implementing

**Comment by dtslvr** [comment]
> can you give any reference of it, within the project, so that I can see it and try implementing

I would extend [PortfolioPositionDetail](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/interfaces/portfolio-position-detail.interface.ts) by `dividendYieldInPercent` and start the server. The compiler will complain, that `dividendYieldInPercent` has not been implemented yet. There is your starting point...

Ps. I have fixed the broken link.

**Comment by dtslvr** [comment]
> I will try to work on it

Hi @Fullstack-Arshad

Any progress on this issue to share?

**Comment by Fullstack-Arshad** [comment]
Hi @dtslvr, sorry I was quite busy this week, didn't get time to work on it. I have one doubt, how we will get the value of dividendYieldInPercent, any specific formula or variables to be used?

**Comment by dtslvr** [comment]
No problem. There are various resources on the Internet about dividend yield, e.g. [Investopedia](https://www.investopedia.com/terms/d/dividendyield.asp) or _ChatGPT_ 😉

**Comment by Fullstack-Arshad** [comment]
Hi @dtslvr, I am so sorry I am taking so much time to do this, I am still busy and not getting much time. I will try make some progress within a week. However if you can't give me anymore extension I can unassign this task.
