### ISSUE TITLE
[BUG] Portfolio page crashes after deleting benchmark from Market Data

### ISSUE THREAD

**Issue by helgehatt** [ghostfolio/ghostfolio#2538]
**Bug Description**

The Portfolio page no longer works after deleting an Asset Profile that was selected as a benchmark. See below:

![Screenshot](https://github.com/ghostfolio/ghostfolio/assets/12933913/0271679f-fa49-47a8-8360-19a29629f93a)

Here is the logs:

```
[Nest] 142  - 10/23/2023, 10:05:31 PM   ERROR [ExceptionsHandler] No data provider has been found.
Error: No data provider has been found.
    at DataProviderService.getDataProvider (/ghostfolio/apps/api/main.js:1:192151)
    at DataProviderService.getQuotes (/ghostfolio/apps/api/main.js:1:190168)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SymbolService.get (/ghostfolio/apps/api/main.js:1:204224)
    at async Promise.all (index 0)
    at async BenchmarkService.getMarketDataBySymbol (/ghostfolio/apps/api/main.js:1:206875)
```

**To Reproduce**

I have not tested this, since my app is currently in a non-working state, but I imagine this is what happened:

1. Add an Asset Profile and toggle "Benchmark"
2. On the Portfolio page, select the asset in the "Compare with..." drop-down.
3. Delete the Asset Profile

**Environment**

- Self-hosted
- Version 2.12.0
- Firefox
- Linux Mint

**Comment by karter16** [comment]
Have just tested this and your supposition appears to be true. If the asset profile is selected as the "Compare with" at the time that it is deleted from the Market Data then the error occurs. You can restore the portfolio page by simply making another selection from the "Compare with" dropdown. If the asset profile is not the currently selected item in "Compare with" then no error occurs.

**Comment by Basimohd** [comment]
@dtslvr could you please assign this to me?

**Comment by Basimohd** [comment]
@dtslvr, how can I retrieve the admin account? I've forgotten the token ID. I am running Postgres in Docker.

**Comment by dtslvr** [comment]
> how can I retrieve the admin account?

You could create a new user, then connect to the database table _User_ and assign the `role` = `ADMIN`.
