### ISSUE TITLE
Improve Transfer Cash Balance

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2550]
There are some tasks planned to further improve the [TransferBalanceDialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/accounts/transfer-balance) (open via `http://localhost:4200/en/accounts`).

- [x] Frontend: Remove height (`80vh`)
- [x] Frontend: Remove default value (`0`) of `balance`
- [x] Frontend: Treat form as invalid if `accountFrom` is equal to `accountTo`
- [x] Backend: Throw a `400 Bad Request` error if `accountFrom` is equal to `accountTo` in `api/v1/account/transfer-balance`
- [x] Backend: Throw a `400 Bad Request` error if the current balance of `accountFrom` is lower than the `balance` from the payload

**Comment by iajaymk** [comment]
@dtslvr Can you please assign this to me?
