### ISSUE TITLE
Extend benchmark endpoint by trend50d and trend200d

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2567]
Extend the response of `GET api/v1/benchmark` by `trend50d` and `trend200d`. Calculate the trend using a 50-day / 200-day moving average.

[Benchmark](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/interfaces/benchmark.interface.ts) (interface)
```
  export interface Benchmark {
    marketCondition: 'BEAR_MARKET' | 'BULL_MARKET' | 'NEUTRAL_MARKET';
    name: EnhancedSymbolProfile['name'];
    performances: {
      allTimeHigh: {
        date: Date;
        performancePercent: number;
+       trend50d: BenchmarkTrend; // Add
+       trend200d: BenchmarkTrend; // Add
      };
    };
  }
```
```
// @ghostfolio/common/types/benchmark-trend-type.type
export type BenchmarkTrend = 'DOWN' | 'NEUTRAL' | 'UP';
```

### Steps to setup

1. Create an activity for symbol `VOO`
2. Open http://localhost:4200/en/admin/market-data?dataSource=YAHOO&symbol=VOO&assetProfileDialog=true
3. Set asset profile (`VOO`) as _Benchmark_ (checkbox)
4. Click _Gather Historical Data_ from the kebab menu
5. Open http://localhost:4200/en/markets
6. `GET http://localhost:4200/api/v1/benchmark` is loaded (this is the request to be extended by `trend50d` and `trend200d`)

**Comment by Dhoni77** [comment]
Hi @dtslvr I would like to take this up

**Comment by Dhoni77** [comment]
Hi @dtslvr the trend50 and tren200d should be calculated based on which data ?
Is it based on historical market data ?

**Comment by dtslvr** [comment]
> Is it based on historical market data ?

Yes, exactly.
