### ISSUE TITLE
[BUG] Fee on Account level not working anymore

### ISSUE THREAD

**Issue by toble** [ghostfolio/ghostfolio#2584]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

I cannot add any fee on account level anymore. It worked 1 month ago where I had the experimental feature enabled. But the feature has been moved to general availability since.
The server reports Bad request with Message "quantity must be a positive number", "unitPrice must be a positive number" and the activity is not added.

**To Reproduce**

1. Go to Activities
2. Add Activity
3. Choose Type Fee
4. Fill out "Name" and "Fee" e.g. with value 10 USD
5. Press save

**Expected behavior**

After step 5 I expect to see the fee activity added to the activities.

**Environment**
- Cloud and local development setup.
- Ghostfolio Version latest main
- Browser Firefox

**Comment by dtslvr** [comment]
Thank you for the bug report @toble. I have prepared a fix.

**Comment by toble** [comment]
Thank you for this prompt fix!
