### ISSUE TITLE
Add docker image major version tag

### ISSUE THREAD

**Issue by ianschmitz** [ghostfolio/ghostfolio#2585]
Hi there 👋

I'm hoping you'll consider tagging your image with a major version tag alongside the full version tag during release.

This is useful for those of us that use tools like watchtower or similar to keep our containers up to date on a schedule, but don't want to risk pulling in a new major version that may break the deployment.

So for example you'd tag a release with:

'latest', '2.30.0', '2'

**Comment by dtslvr** [comment]
Hi @ianschmitz

Thanks for your suggestion. Would you be interested in contributing your idea as a pull request to the repository?
