### ISSUE TITLE
[BUG] Multiple errors when importing the `ok.csv` file. 

### ISSUE THREAD

**Issue by sameleff** [ghostfolio/ghostfolio#2610]
**Bug Description**

I downloaded the [ok.csv](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv) file in order to test how the GUI csv importer worked. When I imported this file into Ghostfolio, the following errors occured:
1. activities.0.quantity must be a positive number
2. activities.0.unitPrice must be a positive number
3. activities.4.quantity must be a positive number
4. activities.4.unitPrice must be a positive number
5. activities.0.date is not valid
6. activities.3.symbol ("US5949181045") is not valid for the specified data source ("YAHOO")

Also, activities.5.date did not specifically throw an error, but it was imported as '06/06/2050' which seems like an unlikely test case.

**To Reproduce**

A. Download [ok.csv](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv) and save it as a csv file.
B. Under Portfolio > Activities, click "Import Activities..." and drag the ok.csv file from Step 1 into Ghostfolio.
C. Errors 1-4 occur.
D. Fix errors 1-4 in the csv file, re-save it, and repeat Step B.
E. Error 5 occurs.
F. Fix Error 5 in the csv file, re-save it, and repeat Step B.
G. Error 6 occurs.
H. Fix Error 6 in the csv file, re-save it, and repeat Step B. No further errors occur and the contents are now able to be imported. However - the date from activities.5.date is imported as '06/06/2050' which seems incorrect. 

**Expected behavior**

All activities contained within ok.csv should be able to be imported successfully.

**Screenshots**

**Logs**

N/A

**Environment**

- Self-hosted
- Ghostfolio Version 2.17.0
- Browser: Brave 1.58.129
- OS: Ghostfolio, redis, and postgres are all ran via Docker in UnRAID

**Additional context**

N/A

**Comment by dtslvr** [comment]
Hi @sameleff

This issue has been fixed via #2588. Please upgrade to Ghostfolio [2.18.0](https://github.com/ghostfolio/ghostfolio/releases/tag/2.18.0).
