### ISSUE TITLE
[BUG] Zen mode shows base currency instead of %

### ISSUE THREAD

**Issue by slagiewka** [ghostfolio/ghostfolio#2625]
**Bug Description**
When using zen mode, the % value shows the base currency.

**To Reproduce**
1. Run v2.20.0
2. Enable zen mode
3. Go to the overview

**Expected behavior**
Value should be shown with the % sign.

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/11974489/1e28816a-6cd2-44c4-9d35-449d6217e1b8)

**Logs**

**Environment**

- Self-hosted
- Ghostfolio v2.20.0
- Firefox 119.0

**Additional context**
Seems like the change in #2622 might have caused it.

**Comment by dtslvr** [comment]
Thank you for the bug report, @slagiewka.

**Comment by slagiewka** [comment]
Fixed for me. Thanks!
