### ISSUE TITLE
grossPerformance, grossPerformancePercentage, netPerformance, netPerformancePercentage returns as null for MANUAL sources where the period being evaluated starts after the date of the first activity

### ISSUE THREAD

**Issue by karter16** [ghostfolio/ghostfolio#2639]
**Bug Description**

I'm not sure whether this qualifies as a bug as I can't identify the exact steps to reproduce this.

I have several Manual sources created for which I have populated daily price data and have activities against. Some of these work just fine, however a couple appear to be causing issues and I can't work out why.

**To Reproduce**

1. Create a manual source
2. Create activities against the manual source
3. populate daily price data
4. observe that SOMETIMES Ghostfolio reports Data Provider Errors

<img width="830" alt="Screenshot 2023-11-12 at 10 51 58 AM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/4232b5b3-f666-43f2-b2b8-0b4d3da97c07">

<img width="1723" alt="Screenshot 2023-11-12 at 10 43 29 AM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/cf257380-9ad9-40af-8732-21c8b78d0df0">

It is worth noting also that in the Portfolio - Analysis page the holdings show now performance data in the performance section:
<img width="1228" alt="Screenshot 2023-11-12 at 10 48 50 AM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/6b664bb7-8f28-4127-90f0-51a96c4d09bb">

And also appear to be excluded from the Portfolio Evolution graph (I'm deducing this from the fact that the value against the portfolio evolution graph is low by the total holding value of the two manual sources that are erroring):

<img width="1258" alt="Screenshot 2023-11-12 at 10 49 45 AM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/853a863b-0574-4482-95c5-ffcfc09a1957">

The other thing to note is that if I extend the Analysis time period to start earlier than the date of the first holding for these troublesome sources, then performance stats are correctly calculated and the holdings are included on the portfolio evolution graph:
<img width="1456" alt="Screenshot 2023-11-12 at 11 03 09 AM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/2cfba475-a6bb-4c6c-a7df-c220a926ce2f">

Any advice on what I can do to narrow down what is happening would be greatly appreciated

**Expected behavior**

One can create a manual source, load activities against it and populate daily price data without error.

**Environment**

- Self-hosted
- Ghostfolio Version 2.22.0
- Safari Version 17.0 (19616.1.27.211.1)
- MacOS Sonoma 14.0

**Additional context**

**Comment by karter16** [comment]
Adding another piece of context here...

When the range selector is set to "Today" (and presuming historical data has been entered for today) the manual sources are represented on the Analysis page without issue. 
<img width="359" alt="Screenshot 2023-11-23 at 8 03 35 AM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/9b311eaa-ddac-48ef-99e7-1a6eec951f3a">

**Comment by karter16** [comment]
Further info on this: It appears, looking at the positions data that the issue could be related to grossPerformance, grossPerformancePercentage, netPerformance and netPerformancePercentage being returned as null.

`{
    "hasErrors": true,
    "positions": [
        {
            "averagePrice": 2.547,
            "currency": "NZD",
            "dataSource": "MANUAL",
            "fee": "0",
            "firstBuyDate": "2021-06-10",
            "grossPerformance": null,
            "grossPerformancePercentage": null,
            "investment": 11421.99603,
            "marketPrice": 2.547,
            "netPerformance": null,
            "netPerformancePercentage": null,
            "quantity": 4484.49,
            "symbol": "ANZ Kiwisaver Growth",
            "tags": [],
            "transactionCount": 1,
            "assetClass": "EQUITY",
            "assetSubClass": "MUTUALFUND",
            "marketState": "delayed",
            "name": "ANZ Kiwisaver Growth"
        },
        {
            "averagePrice": 45299.497461077655,
            "currency": "USD",
            "dataSource": "COINGECKO",
            "fee": "0",
            "firstBuyDate": "2021-08-21",
            "grossPerformance": 2787.651755605807,
            "grossPerformancePercentage": 0.6236595101890506,
            "investment": 5323.027073947786,
            "marketPrice": 61761.8988,
            "netPerformance": 2787.651755605807,
            "netPerformancePercentage": 0.6236595101890506,
            "quantity": 0.11750742,
            "symbol": "bitcoin",
            "tags": [],
            "transactionCount": 6,
            "assetClass": "CASH",
            "assetSubClass": "CRYPTOCURRENCY",
            "marketState": "open",
            "name": "Bitcoin"
        },
        {
            "averagePrice": 1.0444263498236892,
            "currency": "NZD",
            "dataSource": "MANUAL",
            "fee": "0",
            "firstBuyDate": "2022-12-27",
            "grossPerformance": null,
            "grossPerformancePercentage": null,
            "investment": 48495.00271602,
            "marketPrice": 1.1736,
            "netPerformance": null,
            "netPerformancePercentage": null,
            "quantity": 46432.19,
            "symbol": "Foundation Series Total World Fund",
            "tags": [],
            "transactionCount": 24,
            "assetClass": "EQUITY",
            "assetSubClass": "ETF",
            "marketState": "delayed",
            "name": "Foundation Series TWF"
        },
        {
            "averagePrice": 1.414359791053007,
            "currency": "NZD",
            "dataSource": "MANUAL",
            "fee": "0",
            "firstBuyDate": "2023-04-30",
            "grossPerformance": 241.00254417,
            "grossPerformancePercentage": 0.019542558493136013,
            "investment": 12332.18998703,
            "marketPrice": 1.442,
            "netPerformance": 241.00254417,
            "netPerformancePercentage": 0.019542558493136013,
            "quantity": 8719.2736,
            "symbol": "Milford Kiwisaver Aggressive Fund",
            "tags": [],
            "transactionCount": 27,
            "assetClass": "EQUITY",
            "assetSubClass": "MUTUALFUND",
            "marketState": "delayed",
            "name": "Milford KS Agressive Fund"
        },
        {
            "averagePrice": 7.550513144705588,
            "currency": "USD",
            "dataSource": "YAHOO",
            "fee": "59.7744",
            "firstBuyDate": "2022-05-22",
            "grossPerformance": 741.165473485254,
            "grossPerformancePercentage": 0.05519382419776542,
            "investment": 15125.546631588057,
            "marketPrice": 7.073304,
            "netPerformance": 736.184273485254,
            "netPerformancePercentage": 0.05482287939943169,
            "quantity": 2003.24750672,
            "symbol": "RKLB",
            "tags": [],
            "transactionCount": 12,
            "assetClass": "EQUITY",
            "assetSubClass": "STOCK",
            "marketState": "closed",
            "name": "Rocket Lab USA, Inc."
        },
        {
            "averagePrice": 0,
            "currency": "NZD",
            "dataSource": "YAHOO",
            "fee": "0",
            "firstBuyDate": "2020-04-29",
            "grossPerformance": 403.74885755,
            "grossPerformancePercentage": 0.024381479081847922,
            "investment": 0,
            "marketPrice": 3.22,
            "netPerformance": 403.74885755,
            "netPerformancePercentage": 0.024381479081847922,
            "quantity": -0.0046,
            "symbol": "TWF.NZ",
            "tags": [],
            "transactionCount": 32,
            "assetClass": "EQUITY",
            "assetSubClass": "STOCK",
            "marketState": "closed",
            "name": "Smartshares Total World"
        },
        {
            "averagePrice": 1.4151988634119796,
            "currency": "NZD",
            "dataSource": "MANUAL",
            "fee": "0",
            "firstBuyDate": "2020-06-25",
            "grossPerformance": null,
            "grossPerformancePercentage": null,
            "investment": 26416.973591276,
            "marketPrice": 1.5839,
            "netPerformance": null,
            "netPerformancePercentage": null,
            "quantity": 18666.61589,
            "symbol": "VAN8287AU",
            "tags": [],
            "transactionCount": 40,
            "assetClass": "EQUITY",
            "assetSubClass": "MUTUALFUND",
            "marketState": "delayed",
            "name": "Vanguard Intl. Shares Select Exclusions (NZD Hedged)"
        }
    ]
}`

**Comment by karter16** [comment]
Have updated the title of this ticket based on the above ^

**Comment by karter16** [comment]
Okay further investigation on this has shown it to be related to having market data for specific days in question. For one of the holdings I was missing having loaded data around key dates (end/start of year, etc.). For another I believe I somehow ended up with multiple market data records for a single day (don't know how, couldn't reproduce it). Therefore this is not a bug and is just a case of making sure you get the daily data just so.

@dtslvr out of all this investigation I've done I've uncovered a separate bug, and have a feature suggestion. For the bug I'll raise a separate issue, for the feature suggestion how would you like me to raise it for consideration? do I just raise an issue and you then mark it as a feature request? or do I start with a discussion?

**Comment by dtslvr** [comment]
Hi @karter16

Glad you figured it out!

For the bug, please create a [Bug report](https://github.com/ghostfolio/ghostfolio/issues/new/choose). For the feature suggestion, please start with a new discussion [here](https://github.com/ghostfolio/ghostfolio/discussions/new/choose) (_Ideas_).

Thanks!
