### ISSUE TITLE
Support for Zerodha Brokerage

### ISSUE THREAD

**Issue by g-kartik** [ghostfolio/ghostfolio#2648]
I use Zerodha for managing stocks. Kindly enable support this brokerage service.

**Comment by dtslvr** [comment]
> I use Zerodha for managing stocks. Kindly enable support this brokerage service.

Thank you for your input. We focus on bug reports here. For other topics, please use [GitHub Discussions](https://github.com/ghostfolio/ghostfolio/discussions).
Appreciate your cooperation!
