### ISSUE TITLE
[BUG] Invalid `prisma.marketData.findMany()` invocation

### ISSUE THREAD

**Issue by aveekbhat** [ghostfolio/ghostfolio#2653]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

Accounts section does not work see screenshot below
Seems to be a prisma library issue
Invalid `prisma.marketData.findMany()` invocation:
Assertion violation on the database: `too many bind variables in prepared statement, expected maximum of 32767, received 37180`
[https://github.com/prisma/prisma/issues/21648](https://github.com/prisma/prisma/issues/21648)

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/1280869/f92ed36b-a209-49c9-8121-324c68f58456)

**Logs**

[_ghostfolio-ghostfolio-1_logs.txt](https://github.com/ghostfolio/ghostfolio/files/13362712/_ghostfolio-ghostfolio-1_logs.txt)

**Environment**

- Self-hosted
- Ghostfolio Version 2.22.0 - 2023-11-11
- Browser Chrome/Firefox
- OS Windows/Archlinux

**Additional context**

**Comment by dtslvr** [comment]
Maybe be related with this change [here](https://github.com/ghostfolio/ghostfolio/pull/2631/files#diff-b0e47fe793de4f6983154c932c0220b42fb84202a9b71c37f1983b8d78233106R77) of #2631? 🤔

**Comment by dtslvr** [comment]
@aveekbhat @Pindol83
I am not able to reproduce this error locally. Can you give a rough estimate of how many assets / activities you have in Ghostfolio?

**Comment by aveekbhat** [comment]
sorry for the late reply .. i have 534

> @aveekbhat @Pindol83 I am not able to reproduce this error locally. Can you give a rough estimate of how many assets / activities you have in Ghostfolio?
i have 534 activities .. 

I downgraded to version 2.20.0 (i was running that before) and everything is normal .. i will wait for the next release

**Comment by dtslvr** [comment]
Thank you for the reply, @aveekbhat.
There is a new release available addressing this: https://github.com/ghostfolio/ghostfolio/releases/tag/2.24.0
Does it fix the issue?

**Comment by aveekbhat** [comment]
> Thank you for the reply, @aveekbhat. There is a new release available addressing this: https://github.com/ghostfolio/ghostfolio/releases/tag/2.24.0 Does it fix the issue?

Just upgraded it to this release and everything looks great !! 💯

**Comment by dtslvr** [comment]
> Just upgraded it to this release and everything looks great !! 💯

That's great. Thanks for the feedback 😎

**Comment by shiruken** [comment]
I was also seeing this error but upon updating to 2.24.0 I'm now seeing flat lines (0%) on all performance charts and $0.00 values for all my holdings. No error messages are being generated in the logs.

**Comment by dtslvr** [comment]
> I was also seeing this error but upon updating to 2.24.0 I'm now seeing flat lines (0%) on all performance charts and $0.00 values for all my holdings. No error messages are being generated in the logs.

Do you see anything if you create a new user account and import the activities of [ok.json](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.json)?

**Comment by shiruken** [comment]
> Do you see anything if you create a new user account and import the activities of [ok.json](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.json)?

Nope, everything is still zeros with errors in the log

![image](https://github.com/ghostfolio/ghostfolio/assets/867617/11b61c99-9058-4420-b6b8-36031f96f845)

![image](https://github.com/ghostfolio/ghostfolio/assets/867617/da2c8882-85bd-4af9-af42-543677121acd)

**Comment by dtslvr** [comment]
> ![image](https://user-images.githubusercontent.com/867617/283919364-da2c8882-85bd-4af9-af42-543677121acd.png)

`Cannot read properties of undefined (reading 'items')` seems to be a different issue: #1228

**Comment by shiruken** [comment]
> `Cannot read properties of undefined (reading 'items')` seems to be a different issue: #1228

Ah, that's it. I recently disabled the `TZ=""` variable in my configuration because I couldn't remember what it was for. Added it back and everything is working again now.

**Comment by dtslvr** [comment]
> Ah, that's it. I recently disabled the `TZ=""` variable in my configuration because I couldn't remember what it was for. Added it back and everything is working again now.

Interesting. Could you please document your insights in this ticket #2669, too?
