### ISSUE TITLE
[Question] How to deal with corporate actions (stock split & reverse split)

### ISSUE THREAD

**Issue by Elli-Rid** [ghostfolio/ghostfolio#2722]
Currently it doesn't look like ghostfolio can handle split/reverse-split situations well. For example TMF recently had a reverse split and now it show that my holdings are x10. 

Any proper way to handle or perhaps just go back in time and re-adjust my trades according with the new price?

Thanks!

**Comment by dtslvr** [comment]
Hi @Elli-Rid

While we primarily address bug reports in this space, we've got an ongoing discussion about stock splits happening over here: https://github.com/ghostfolio/ghostfolio/discussions/1072

Feel free to join in!
