### ISSUE TITLE
[BUG] Unclear import process for interest activies

### ISSUE THREAD

**Issue by winklevos** [ghostfolio/ghostfolio#2723]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

csv examples in repo do not work for interest activities.

After looking at the api requests, these columns in a csv worked so i could import interest

- Date
- unitPrice
- Symbol
- Currency
- type = `INTEREST`
- fee = 0
- quantity
- accountid
- dataSource = `MANUAL`

**To Reproduce**

1. Follow the csv structure outlined in the repo to attempt to upload 
2. see issue on missing fields or incorrect symbol for YAHOO

**Expected behavior**

**Screenshots**

**Logs**

**Environment**

- Cloud or Self-hosted
- Ghostfolio Version X.Y.Z
- Browser
- OS

**Additional context**

**Comment by dtslvr** [comment]
> csv examples in repo do not work for interest activities.

Which csv file of the repository are you referring to?

**Comment by dtslvr** [comment]
Okay, got it. This is primarily to address bug reports. Please consider starting a [discussion](https://github.com/ghostfolio/ghostfolio/discussions) or creating a pull request. Thank you.
