### ISSUE TITLE
[BUG] TODAY value shows different value to YTD, 1Y, 5Y, and Max

### ISSUE THREAD

**Issue by winklevos** [ghostfolio/ghostfolio#2725]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

Basically the title. The Day in my instance shows a different value. I can't understand why this would be beside a bug?

I am also investigating performance values being incorrect as well. It's possible my instance DB is broken? :/

**To Reproduce**

1. ?? unsure
2.
3.

**Expected behavior**

**Screenshots**

**Logs**

**Environment**

- Self-hosted
- Ghostfolio Version 2.28.0
- Browser firefox
- OS windows

**Additional context**

**Comment by dtslvr** [comment]
Hi @winklevos

Could you please follow our bug report template including detailed steps to reproduce the problem and the expected behavior. Thanks for your assistance.

**Comment by dtslvr** [comment]
> just click on TODAY or YTD do they show different values?

I've just tested in the _Live Demo_ of https://ghostfol.io and there are the same values.
