### ISSUE TITLE
[BUG] Unable to add/update quantity and unitprice for new activity type VALUABLE

### ISSUE THREAD

**Issue by rambo-srk** [ghostfolio/ghostfolio#2763]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**
Unable to enter the **quantity** while adding a **Valuable** type activity in the account/portfolio. Also, I don't see any option if I try to edit the same but I can see the default quantity set to 1 for the type **Valuable**

**To Reproduce**
1. Click add new activity under **Portfolio -> Activities**
2. Change the Type dropdown to **Valuable**
3. Enter any value in the Value field and update the mandate fields then click save
4. You can see the quantity set to 1 as default after creating and there is no quantity field and unit price field to update

**Expected behavior**
The type Valuable is used to create any private equity asset class and they also have similar buy, sell, unit price, date and total value etc. and I would expect the same steps and fields as available in the normal equity to be enabled for all equity, options and other stocks/exchange type activities.

**Screenshots**
### While adding
![image](https://github.com/ghostfolio/ghostfolio/assets/67826695/0b868b57-567a-4e4e-b00a-4cc4f46e1c29)

### After saving
![image](https://github.com/ghostfolio/ghostfolio/assets/67826695/5baef012-5108-43ce-8108-b3eef6d3dbe2)

### Trying to update
![image](https://github.com/ghostfolio/ghostfolio/assets/67826695/a59ca068-45fe-4821-b506-ef8ee776d5af)

**Logs**

**Environment**
- Chrome (Desktop and iOS app)

**Additional context**

**Comment by dtslvr** [comment]
Hi @rambo-srk

Thank you for your report. After review, we confirm that the observed behavior for valuables is intentional.

If you are looking to create activities for custom assets, please create them first at _Admin Control_ > _Market Data_ > _Add Asset Profile_ (manually).
