### ISSUE TITLE
[BUG] Multi currency calculation is not working properly in account page

### ISSUE THREAD

**Issue by rambo-srk** [ghostfolio/ghostfolio#2764]
**Bug Description**

Multi currency is not working properly. I have created a two accounts for different currencies INR & EUR and I have set INR as the base currency. After creating an activity with test amount _1,111,111 EUR_ under the EUR account, the value in the account page shows different value _12,282.18 EUR_ from what I have entered. I assume even though I have created the value in EUR still in the account preview it considers the cost as INR which is my base currency, 

Also, by selecting the account and while seeing the account dashboard, it shows the correct value _1,111,111_ but with wrong currency code _INR_ which should be _EUR_

**To Reproduce**
1. Create two accounts one for INR and another for EUR
2. Set base currency as INR
3. Create a new activity in EUR account with test value
4. Goto account page and check if the value shown in the account page is same as your initial value
5. Open the account dashboard by clicking the account name and check the value and currency code (INR/EUR) at all the places (i.e. the top, bottom and in th emiddle below charts)

**Expected behavior**
The value and the currency code should be the same as initial value which entered while creating the activity.

**Screenshots**
### Account dashboard
![image](https://github.com/ghostfolio/ghostfolio/assets/67826695/c2552c3b-ac04-49e6-acca-4122570d4fdc)

### Account preview page
![image](https://github.com/ghostfolio/ghostfolio/assets/67826695/0ff632a5-5df0-41b5-ac92-268ba6ff9355)

**Logs**

**Environment**

- Chrome (Windows desktop and iOS)

**Additional context**

**Comment by dtslvr** [comment]
Hi @rambo-srk

Thank you for your report. Could you kindly provide a minimal export of your activities for easier reproduction?
