### ISSUE TITLE
[BUG] Default account currency is non USD, yet Total account currency force sticks to USD

### ISSUE THREAD

**Issue by ashutoshsaboo** [ghostfolio/ghostfolio#2766]
**Bug Description**

Default account currency is non USD, yet Total account currency some force sticks to USD.

**To Reproduce**

1. Add an account on Ghostfolio - only single account and assign it some non USD currency
2. Yet the totals currency force sticks to USD with no way to change it
3. As a result the default overview screen where overall portfolio value is shown also shows USD only. It should show the currency relevant to what I want to see as a user - which should be configurable in totals currency. 

**Expected behavior**

Ideally provide for a way to change total currency too, like for the individual accounts. 

**Screenshots**

<img width="1384" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/9900945/32683fc2-5ade-48df-ad66-28ab3a6886e4">

<img width="1396" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/9900945/93371f5b-3b77-44d3-b7c9-fb270ab36728">

**Environment**

Cloud only - https://ghostfol.io/en/accounts

**Comment by dtslvr** [comment]
Hi @ashutoshsaboo

Please go to _My Ghostfolio_ and change your _Base Currency_ to your preferred currency.

**Comment by ashutoshsaboo** [comment]
Ohh perfect, works like a charm. Maybe let's add this option in the accounts screen as well, so it's more easily visible (I guess would be better UX)? We can keep the option in the profile section as well for base currency. @dtslvr thoughts?

**Comment by dtslvr** [comment]
Great!

I think once the concept account vs. user account is clear, this question becomes irrelevant. Should the confusion appear more frequently, we will be happy to consider a potential adaption.

**Comment by ashutoshsaboo** [comment]
Hey @dtslvr so I just for my self-hosted setup for ghostfolio working, for some reason it only shows me USD as a selectable option in there, even in the accounts section. Is there something special that I have to do for a self hosted setup to add currencies other than USD?

**Comment by dtslvr** [comment]
> Is there something special that I have to do for a self hosted setup to add currencies other than USD?

You can add currencies manually in the _Admin Control_ panel. When you add your first asset in another currency, you can also select this one for your user account.

**Comment by ashutoshsaboo** [comment]
Hi @dtslvr thanks for the help. So i think i figured from the logs the currency issue is happening due to redis issues on my ghostfolio setup, like when I try to do fetch historical data for the currency pair it isn't able to connect to Redis. I mentioned some more logs and related details here - https://github.com/ghostfolio/ghostfolio/discussions/2770 . 

Would it be possible for you to kindly please help with the above discussion? @dtslvr
