### ISSUE TITLE
[BUG] PWA - Bottom menu is partially shown

### ISSUE THREAD

**Issue by Xosten** [ghostfolio/ghostfolio#2785]
**Bug Description**
The bottom menu bar in the Progressive Web App, is partially shown. Scrolling to the bottom of the page, reveals the entire bar. 

**To Reproduce**

1. Add the PWA on your iPhone
2. Login

**Expected behavior**

The menu bar should be « sticky » to the bottom of the viewport for easy access. 

**Screenshots**
![IMG_1785](https://github.com/ghostfolio/ghostfolio/assets/11696836/751be97a-b768-4b9f-8100-f343373fd84f)

**Logs**

N/A

**Environment**

- 2.32.0
- Self-hosted
- Experimental Features disabled
- Browser: PWA (Safari?)
- iOS 17.2.1

**Comment by dtslvr** [comment]
How does it look in version 2.34.0, @Xosten?

**Comment by Xosten** [comment]
> How does it look in version 2.34.0, @Xosten?

Hi @dtslvr, thanks for the quick fix. The icons seem to not load anymore, which make navigation a bit harder haha 😅.
<img width="414" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/11696836/9b4c3a28-4261-431a-a1bd-c72dc7172b02">

Same in the lap/desktop version, as you can see bellow:
<img width="223" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/11696836/b7f1ffd2-37fa-473a-9586-ccfe2d2f6fb8">

**Comment by dtslvr** [comment]
> After a few hours, icons are back, I suspect maybe a caching issue... I can confirm that the initial bug is fixed on my end. Thanks a lot!

Yes, that was probably a caching issue of the browser.

Many thanks for the feedback, @Xosten. Great to here it's fine now.
