### ISSUE TITLE
[BUG] Incorrect loss calculation when there are multiple selling transactions

### ISSUE THREAD

**Issue by souxun2015** [ghostfolio/ghostfolio#2791]
**Bug Description**
I find one problem in calculating the losses(changes). When I sell my stock with several times, the loss is not calculated correctly. Moreover, it is related to the stock market. When I buy APPLE, the tracking status is correct, however, when I buy BYD, the tracking status is wrong. 

**To Reproduce**
I provide this activity file as an example. 
[ghostfolio-export-202401082211.json](https://github.com/ghostfolio/ghostfolio/files/13869793/ghostfolio-export-202401082211.json)

For each stock, I buy it two times and sell it two times, ghostfolio should be able to calculate the changes in the corresponding stock investment.

**Expected behavior**
When I sell the ETF in the first time, the loss is 435 which is correct. I guess the formulation is like this:
$$change=(aup - marketprice) * quantity_{remain} + (aup - sellprice)*quantity_{selling} + fee$$

aup: average unit price.

But after I sell the ETF in the second time, the loss becomes to 385, which should be 510. And 510 is calculated by this formulation:
$$change=(aup - marketprice) * quantity_{remain} + (aup - sellprice_{first})*quantity_{selling_{first}} + (aup - sellprice_{second})*quantity_{selling_{second}} + fee$$
Here, the market price at 0.871.

The json file of these activities is here. [ghostfolio-export-202312281720.json](https://github.com/ghostfolio/ghostfolio/files/13790640/ghostfolio-export-202312281720.json)

**Environment**
- Ghostfolio Version 2.32.0
- Self-hosted
- Experimental Features disabled
- Browser
- Docker

**Comment by souxun2015** [comment]
Is there anyone who can help? or met the similar problem?

**Comment by dtslvr** [comment]
Hi @souxun2015

Here is a possible starting point: Create a unit test similar to [apps/api/src/app/portfolio/portfolio-calculator-novn-buy-and-sell-partially.spec.ts](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio-calculator-novn-buy-and-sell-partially.spec.ts) with your scenario. To keep it as simple as possible, use a stock in `USD` (e.g. `AAPL`), buy only once and sell twice without any fees.

You can run a single test via [yarn test:single](https://github.com/ghostfolio/ghostfolio/blob/main/package.json#L48) and enable additional logging [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio-calculator.ts#L50). I hope that helps.

**Comment by souxun2015** [comment]
Hi, @dtslvr , thanks for your answer. And the portfolio is a great tool, and I would like to use it as my main tracking platform. However, the calculations are confusing me, as they show different values compared to my stockbroker.

I tried to set up the development but met [this problem]{https://github.com/ghostfolio/ghostfolio/issues/2801}. To be honest, I don't know frontend programming... I would continue after this problem is resolved.
