### ISSUE TITLE
[BUG] Fix state of CurrencySelectorComponent

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2795]
**Bug Description**

After changing the `@Input` parameters, the `CurrencySelectorComponent` does not display the correct state.

**To Reproduce**

1. Open _Admin Control_ > _Market Data_
2. Open an asset profile where data source is `MANUAL`
3. Change the _Currency_ and _Save_
4. The component does not display the current currency and all options are gone

**Expected behavior**

The component displays the current currency and all options are still available.

**Environment**

- Ghostfolio Version 2.32.0

**Comment by dtslvr** [comment]
Do you perhaps have any ideas for a solution, @Dhoni77?

**Comment by SirZemar** [comment]
What do you think @dtslvr? I would like take on this issue 😁

**Comment by dtslvr** [comment]
> What do you think @dtslvr?

`currency` is persisted as a string ([ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)). The _Angular Material_ component seems to be using `label` and `value` (`USD` for both). Can you convert it properly after loading and before submitting to fix the issue?
