### ISSUE TITLE
[BUG] Importing activity in GBP, priced in GBp on YF results in error

### ISSUE THREAD

**Issue by zgeor** [ghostfolio/ghostfolio#2812]
**Bug Description**
Attempting to import an activity from json file fails with the following message. 

`activities.0.currency ("GBP") does not match with "GBp" and no exchange rate is available from "GBP" to "GBp"` 

This activity can be created manually in GBP via the UI, which seems to take advantage of the built-in conversion between GBP/GBp and vice versa. However it does not work via json import. 

**To Reproduce**

1. Navigate to **Activities** on a clean setup
2. Click  **Import Activities**
3. Drop the following json
``` 
{
  "meta": {
    "date": "2024-01-01T18:59:32.374Z",
    "version": "v2.33.0"
  },
  "accounts": [
    {
      "balance": 0,
      "comment": null,
      "currency": "GBP",
      "id": "871a33f4-c556-4f15-aedc-98ebe621055f",
      "isExcluded": false,
      "name": "Default Account",
      "platformId": null
    }
  ],
  "activities": [
    {
      "accountId": "871a33f4-c556-4f15-aedc-98ebe621055f",
      "comment": null,
      "fee": 0,
      "quantity": 1,
      "type": "BUY",
      "unitPrice": 2.24,
      "currency": "GBP",
      "dataSource": "YAHOO",
      "date": "2024-01-01T18:58:57.250Z",
      "symbol": "AML.L"
    }
  ]
}
```

**Expected behavior**
The activity has been successfully imported, and the appropriate GBP or GBp currency is used. 

**Logs**

`Error: activities.0.currency ("GBP") does not match with "GBp" and no exchange rate is available from "GBP" to "GBp"`

**Environment**

- Ghostfolio Version 2,33,0
- Self-hosted
- Experimental Features disabled
- Browser Firefox 123.0a1

**Comment by dtslvr** [comment]
Hi @zgeor

The error thrown is intended behavior as `AML.L` is listed in `GBp` and not `GBP` on [Yahoo Finance](https://finance.yahoo.com/quote/AML.L). Please change the currrency in your `json` file.

**Comment by kymckay** [comment]
Just hit this same use case. While intended, I think better interoperability of these two "currencies" would be a big convenience feature (since they are really two flavours of the same currency).

My use case is creating imports via script from my ISA provider - which lists all transactions in GBP where Yahoo lists some in GBP and some in GBp.
