### ISSUE TITLE
[BUG] Wrong Percentual Gross Performance since new year

### ISSUE THREAD

**Issue by MichelFR** [ghostfolio/ghostfolio#2823]
**Bug Description**

Since the 01.01.2024 at 00:00:00 the calculated percentual gross performance is wrongly calculated.

**Expected behavior**

Calculate the right value which should be "2.01%"

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/7061122/66e2fb51-9f54-47c3-a69d-9c3a1b70130c)

**Logs**

**Environment**

- Ghostfolio Version 2.34.0
- Self-hosted
- Experimental Features enabled or disabled - enabled
- Chrome
- Windows

**Comment by dtslvr** [comment]
Hi @MichelFR

This is related to a change of the performance calculation to [Time-Weighted Rate of Return](https://www.investopedia.com/terms/t/time-weightedror.asp) (TWR) introduced in [Ghostfolio 2.33.0](https://github.com/ghostfolio/ghostfolio/releases/tag/2.33.0).
I have created a pull request (https://github.com/ghostfolio/ghostfolio/pull/2824) that indicates this in the portfolio summary view.
