### ISSUE TITLE
Feature/Add Coingecko api key support

### ISSUE THREAD

**Issue by TanguyHerbron** [ghostfolio/ghostfolio#2826]
When synchronizing large transaction history with coingecko, the error `Unexpected format` is returned to the user.

Coingecko offers API keys (demo or pro) for their API, which would help bypassing this issue.

This would require two new environment variables :
- `COINGECKO_DEMO_API_KEY`
- `COINGECKO_PRO_API_KEY`

**Comment by dtslvr** [comment]
Related: Crowdfunding campaign [CoinGecko API Key](https://www.buymeacoffee.com/ghostfolio/w/34190)

**Comment by dtslvr** [comment]
> This would require two new environment variables

@TanguyHerbron why not just `COINGECKO_API_KEY`?

**Comment by TanguyHerbron** [comment]
> @TanguyHerbron why not just `COINGECKO_API_KEY`?

From Coingecko's documentation, they use different parameters for the `demo` and `pro` version of their authentication, so I thought it would make sense to give the opportunity to the user to change either.

After review, the `pro` version uses `x_cg_pro_api_key` instead of `x_cg_demo_api_key` for `demo` but they also change the subdomain from `api.coingecko.com` to `pro-api.coingecko.com` so I might actually use your recommendation and limit this feature to the `demo` option if it is ok for you.
