### ISSUE TITLE
[BUG] Can't save any activity (newly installed)

### ISSUE THREAD

**Issue by OultimoCoder** [ghostfolio/ghostfolio#2855]
![image](https://github.com/ghostfolio/ghostfolio/assets/14974045/4567d137-1780-45c3-bbbb-3ce4c222b8f4)

No matter what I select or do I can never click save. Latest version, newly installed. Am I missing some required prerequisite?

**Comment by ArcherBullseye** [comment]
What did you do to fix this?  I am running into the same issue.  I went to Markets and it also was not showing up, so I thought it was a data retrieval issue, but CoinGecko shows I am hitting the API.
