### ISSUE TITLE
API /order 400 error on TSK symbols

### ISSUE THREAD

**Issue by sadortun** [ghostfolio/ghostfolio#286]
Hi,

Trying to add BB.TO return a 400 error from the API

```
// https://ghostfol.io/api/order
{"accountId":"asdf","dataSource":"YAHOO","date":"2021-08-13T12:40:33.184Z","fee":0,"quantity":11,"symbol":"BB.TO","type":"BUY","unitPrice":22}
```

![image](https://user-images.githubusercontent.com/794449/129358623-dc4f0f6b-b3cd-4f5a-ae50-015b0971718b.png)

**Comment by dtslvr** [comment]
Hey @sadortun

Thank you very much for reporting this bug. At the moment, [Ghostfol.io](https://ghostfol.io) only supports the following currencies: `CHF`, `EUR`, `GBP` and `USD`.

We are planning to rework the management of exchange rates. Until this task has been finished, the search will no longer suggest unsupported symbols to avoid errors in the user interface.

**Comment by sadortun** [comment]
Nice !
