### ISSUE TITLE
[BUG] in the activity section, the symbol list filter is in AND

### ISSUE THREAD

**Issue by marco-ragusa** [ghostfolio/ghostfolio#2873]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

When I try to enter more than one symbol in the list of activities in the portfolio, I do not see anything listed, I imagine that in the search the symbols are put in AND and not OR to perform the search.

**To Reproduce**

1. Go to portfolio/activities
2. Insert more than one symbol in search bar

**Expected behavior**

I expect that if I enter more than one symbol, the searched symbols will appear in the list.

**Screenshots**

![immagine](https://github.com/ghostfolio/ghostfolio/assets/7346348/476c04d2-c291-4c05-8249-840d1afd3a4c)
![immagine](https://github.com/ghostfolio/ghostfolio/assets/7346348/466705b3-0c13-463b-ad0b-57291220f012)
![immagine](https://github.com/ghostfolio/ghostfolio/assets/7346348/944bec58-b1d2-480a-872b-52459ef7fab9)

**Environment**

- Ghostfolio Version 2.39.0
- Self-hosted (docker compose)
- Experimental Features disabled
- Browser Firefox
- OS macOS Monterey 12.6

**Comment by dtslvr** [comment]
Hi @marco-ragusa

Thank you for reporting this issue. It is indeed not an ideal solution.

We are currently reworking the filter functionality. As the previous component can be considered deprecated, I am closing this ticket.

You can see the work in progress by activating experimental features in _My Ghostfolio_.
