### ISSUE TITLE
[BUG] zombie processes after ghostfolio starts

### ISSUE THREAD

**Issue by nantostars** [ghostfolio/ghostfolio#2879]
**Bug Description**

I'm using ghostfolio 2.38.0 with docker compose using the template available in the repository (docker/docker-compose.yml).
Once started, the ghostfolio container leaves two zombie/defunct processes, even if the application is working correctly, there is something not managed correctly on how these processes exit.

I tried to understand which are the processes that fail, running ps command many times after the container start and this are the command that I've seen:

- ![image](https://github.com/ghostfolio/ghostfolio/assets/46993725/eee42417-3899-447a-8d54-1c442c981c55)

- ![image](https://github.com/ghostfolio/ghostfolio/assets/46993725/abbaf74c-48a9-4002-a5c7-1dbc5ec335a9)

- ![image](https://github.com/ghostfolio/ghostfolio/assets/46993725/9b14dcf9-18fc-48f7-9787-7809c590fc56)

**To Reproduce**

1. restart the ghostfolio container
2. check the presence of zombie processes on the docker host with command: ps aux | grep Zs 

**Expected behavior**

No zombie processes

**Screenshots**

This is the situation after processes become zombies:
![image](https://github.com/ghostfolio/ghostfolio/assets/46993725/8ec5a9b9-1c2f-4110-a5fb-a8b093234829)

**Logs**

**Environment**

- Ghostfolio Version 2.38.0
- Self-hosted
- Experimental Features disabled
- Browser Firefox
- OS Ubuntu 22.04 LTS running Docker version 24.0.7 managed with Portainer

**Comment by Sonlis** [comment]
I'll have a look in the following days if that's fine by you @dtslvr

**Comment by Sonlis** [comment]
It seems to be an issue with prisma: https://github.com/prisma/prisma/issues/17024
I am checking on their side if something can be done 👍

**Comment by Sonlis** [comment]
Thanks to this article: https://maximorlov.com/process-signals-inside-docker-containers/ I understood why this is happening.
The CMD entrypoint starts the process as init process with PID 1. This process is responsible for handling signals. Yarn is not a process manager, so running `CMD [ "yarn", "start:production" ]` disables any signal handling in the container.

I am trying to think of the better way to handle it. An easy solution would be to use [tiny](https://github.com/krallin/tini), which introduces signal handling for very few modifications, by just adding `init: true` to the docker-compose file.
```yaml
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    init: true
```
```sh
# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 18:41 ?        00:00:00 /sbin/docker-init -- docker-entrypoint.sh yarn start:production
root         8     1  1 18:41 ?        00:00:00 node /opt/yarn-v1.22.19/bin/yarn.js start:production
root        30     8  0 18:41 ?        00:00:00 /bin/sh -c yarn database:migrate && yarn database:seed && node main
root       144    30 24 18:41 ?        00:00:06 /usr/local/bin/node main 
```
Very few modification, however it does not fix the signal handling from the host and keep the processes in the table.
I think a better solution would be to modify the main function instead, to make it execute the prisma functions to not spawn more processes than required.
