### ISSUE TITLE
[BUG] ExchangeRateDataService cannot find exchange rate data

### ISSUE THREAD

**Issue by sorrento-lab** [ghostfolio/ghostfolio#2880]
**Bug Description**

After updating to 2.39.0 (and also in 2.40.0) I get the following rolling errors for exchange rate data. My portfolio values also appear to be incorrect. When accessing the portfolio view, the ghostfolio instance hangs.

`[31m[Nest] 170 - [39m01/16/2024, 12:52:29 AM [31m ERROR[39m [38;5;3m[ExchangeRateDataService] [39m[31mNo exchange rate has been found for USDEUR at 2016-04-08[39m`

**To Reproduce**

Not sure how to reproduce this - appeared to be working correctly in previous versions to 2.39.0...

**Expected behavior**

Exchange rate data pulled correctly with no log errors.

**Logs**
[https://pastebin.com/HC7P0N0J](https://pastebin.com/HC7P0N0J)

**Environment**

UnRAID docker

- Ghostfolio Version 2.40.0
- Self-hosted
- Experimental Features disabled
- Browser Firefox
- OS MacOS

**Comment by dtslvr** [comment]
Hi @sorrento-lab

Can you please verify that you have all historical exchange rate data?

Go to _Admin Control_ → _Market Data_ and select the preset _Currencies_ (see _Filter by..._). There you should find `USDEUR`. If there are (red) gaps, try to gather all historical data.
