### ISSUE TITLE
[BUG] Incorrect performance calculation

### ISSUE THREAD

**Issue by VibeNL** [ghostfolio/ghostfolio#2890]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

There seems a problem with the performance calculation, see screenshot

**To Reproduce**

1. Import the provided transactions
2. View the holding
3.

**Expected behavior**

A somewhat realistic performance number, -142% seems a bit off

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/30174292/55594f11-5c83-4b16-94ab-e28e64df9f6a)

**Logs**

No errors or warning found

**Environment**

- Ghostfolio Version: v2.41.0
- Self-hosted (also tested on Hosted, same issue)
- Experimental Features disabled
- Browser Crhome
- OS Android and Windows 11

**Additional context**

[bug.json](https://github.com/ghostfolio/ghostfolio/files/13965513/bug.json)

@dtslvr , I unfortunately couldn't get a development environment up and running on short notice.

**Comment by VibeNL** [comment]
If I run an instance with only the given transactions, an error does appear in the log. Not sure if it is related:

Error: [big.js] Invalid number
    at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
    at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
    at PortfolioCalculator.getAnnualizedPerformancePercent (/ghostfolio/apps/api/main.js:1:315322)
    at PortfolioService.getSummary (/ghostfolio/apps/api/main.js:1:359847)
    at async PortfolioService.getDetails (/ghostfolio/apps/api/main.js:1:343050)
    at async Promise.all (index 1)
    at async PortfolioService.getAccounts (/ghostfolio/apps/api/main.js:1:336303)
    at async PortfolioService.getAccountsWithAggregations (/ghostfolio/apps/api/main.js:1:336996)
[Nest] 125  - 01/17/2024, 4:03:30 PM   ERROR [ExceptionsHandler] [big.js] Invalid number

**Comment by dtslvr** [comment]
Hi @VibeNL

Can you please try again with Ghostfolio [2.42.0](https://github.com/ghostfolio/ghostfolio/releases/tag/2.42.0)?

**Comment by VibeNL** [comment]
Looks a lot better, thanks 👍🏻
![Screenshot_20240121-122148](https://github.com/ghostfolio/ghostfolio/assets/30174292/12b1ad3d-d200-47a9-b1e8-684e894f4990)

**Comment by dtslvr** [comment]
Thank you for the feedback, @VibeNL.

Fixed via https://github.com/ghostfolio/ghostfolio/pull/2896.
