### ISSUE TITLE
Support filters in export endpoint

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2901]
Add support for filters (`filterByAccounts`, `filterByAssetClasses`, `filterByTags`) in `GET /api/v1/export` [endpoint](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/export/export.controller.ts#L19). The same functionality already exists for `getDetails()` (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.controller.ts#L82)).

**Comment by Fullstack-Arshad** [comment]
Hi @dtslvr, I have worked on this issue, shall I raise PR?

**Comment by dtslvr** [comment]
> shall I raise PR?

Sure 😎

**Comment by Fullstack-Arshad** [comment]
PR Added, let me know if any there is any issue 😀
