### ISSUE TITLE
Replace toggle with select in assistant component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2903]
Replace `gf-toggle` with `mat-select` in `AssistantComponent` and replace the date range options:

```
public dateRangeOptions = [
  { label: $localize`Today`, value: '1d' },
  { label: $localize`Week to date` + ' (' + $localize`WTD` + ')', value: 'wtd' },
  { label: $localize`Month to date` + ' (' + $localize`MTD` + ')', value: 'mtd' },
  { label: $localize`Year to date` + ' (' + $localize`YTD` + ')', value: 'ytd' },
  { label: $localize`1Y`, value: '1y' },
  { label: $localize`5Y`, value: '5y' },
  { label: $localize`Max`, value: 'max' }
];
```

**Comment by meuter** [comment]
I am by no means an Angular expert, but I tried my best to implement the change in #2905. There is one part that I cannot quite make work: when opening the panel, I would have liked the selection box to pick the entry that matches `user?.settings?.dateRange` like it was done for the `gf-toggle`. But I have not quite figured out how. @dtslvr Do you have any advice?
