### ISSUE TITLE
[BUG] Unable to import manual activities

### ISSUE THREAD

**Issue by marco-ragusa** [ghostfolio/ghostfolio#2909]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

When I try to import manual activity ghostfolio return this error

activities.0.symbol ("ALL-IN-AZN") is not valid for the specified data source ("MANUAL")
"02e0de17-36b5-4908-98ec-4239d9e8464f,,0,2.203,BUY,22.700,EUR,MANUAL,2024-01-16,ALL-IN-AZN"

**To Reproduce**

1. Create a manual datasource
2. Go to portfolio/activities
3. Import a manual activity like

accountId,comment,fee,quantity,type,unitPrice,currency,dataSource,date,symbol
02e0de17-36b5-4908-98ec-4239d9e8464f,,0,2.203,BUY,22.700,EUR,MANUAL,2024-01-16,ALL-IN-AZN

**Expected behavior**

The activity should be imported

**Screenshots**

![immagine](https://github.com/ghostfolio/ghostfolio/assets/7346348/3ff4ae72-bc3a-4208-8e54-86fcf8da0be9)

**Logs**

[Nest] 124  - 01/22/2024, 5:47:04 PM   ERROR [class ImportController{constructor(e,t,a){this.configurationService=e,this.importService=t,this.request=a}async import(t,a){if(!Za(this.request.user.permissions,Aa))throw new e.HttpException((0,It.getReasonPhrase)(It.StatusCodes.FORBIDDEN),It.StatusCodes.FORBIDDEN);let r=this.configurationService.get("MAX_ACTIVITIES_TO_IMPORT");this.configurationService.get("ENABLE_FEATURE_SUBSCRIPTION")&&"Premium"===this.request.user.subscription.type&&(r=Number.MAX_SAFE_INTEGER);const o=this.request.user.Settings.settings.baseCurrency;try{return{activities:await this.importService.import({isDryRun:a,maxActivitiesToImport:r,userCurrency:o,accountsDto:t.accounts??[],activitiesDto:t.activities,userId:this.request.user.id})}}catch(n){throw e.Logger.error(n,kc),new e.HttpException({error:(0,It.getReasonPhrase)(It.StatusCodes.BAD_REQUEST),message:[n.message]},It.StatusCodes.BAD_REQUEST)}}async gatherDividends(e,t){const a=this.request.user.Settings.settings.baseCurrency;return{activities:await this.importService.getDividends({dataSource:e,symbol:t,userCurrency:a})}}}] Error: activities.0.symbol ("ALL-IN-AZN") is not valid for the specified data source ("MANUAL")

**Environment**

- Ghostfolio Version 2.42.0
- Self-hosted
- Experimental Features disabled
- Firefox
- macOS

**Comment by dtslvr** [comment]
Hi @marco-ragusa

Please upgrade first to the latest version (>= `2.45.0`).

Can you check if

- `dataSource`: `MANUAL`
- `symbol`: `ALL-IN-AZN`

exists in the _Market Data_ view of your _Admin Control_ panel. This is required if `type` is `BUY`, `DIVIDEND` or `SELL`.

**Comment by marco-ragusa** [comment]
Now it works with the version you suggested

**Comment by montaleone** [comment]
I have the same issue, but I am using a premium account of the cloud version. Whereas in the self-hosted version I had access to add a manual data-source, I do not see where to do this in the premium version? There is no admin section. 
For this reason I am unable to import in my data from the self hosted solution.
