### ISSUE TITLE
[BUG] Healthcheck fails due to curl missing in container

### ISSUE THREAD

**Issue by mocdaniel** [ghostfolio/ghostfolio#2912]
**Bug Description**

The healthcheck introduced in `v2.43.0` depends on `curl` which is missing in the official container images. Thus, healthchecks are constantly failing and the container will never be considered `healthy` by Docker.

This is due to `curl` being installed in the `builder` step of the image's multi-stage build in [5fc84a0](https://github.com/ghostfolio/ghostfolio/commit/5fc84a06cc67f8b6f06291343b11d93f36ddd95c) instead of being installed in the final stage of the build. I will submit a PR with a fix.

**To Reproduce**

1. `docker compose -f docker/docker-compose.yml up -d `
2. `watch docker ps`
3. See the ghostfolio container never reaching `healthy` state
4. `docker exec <ghostfolio_container> curl`
5. See the execution of `curl` fail because it's not installed.

**Comment by dtslvr** [comment]
cc @ThomDietrich

**Comment by ThomDietrich** [comment]
What a silly mistake 🙈 Thanks @mocdaniel

**Comment by dtslvr** [comment]
> What a silly mistake 🙈

My initial link to the code has been misleading. All's well that ends well 🙂
