### ISSUE TITLE
Analysis not showing all percentages [BUG]

### ISSUE THREAD

**Issue by christopherdenny** [ghostfolio/ghostfolio#2919]
The Analysis page shows the appropriate stocks, but it does not always show the percentages for the top stocks. This happens in Chrome and Edge on the desktop and Chrome on Android. 

![Screenshot_20240124_220448_Chrome](https://github.com/ghostfolio/ghostfolio/assets/43104561/23d1edc1-3ee5-492d-ad08-ff6aa99ca3fa)

**Comment by dtslvr** [comment]
Hi @christopherdenny

Could you please follow our bug report template including detailed steps to reproduce the problem and open a new issue. Thanks for your assistance.
