### ISSUE TITLE
[BUG] Actions Import from T212

### ISSUE THREAD

**Issue by BloodyXmas** [ghostfolio/ghostfolio#2924]
[from_2020-05-01_to_2021-04-30_MTcwNDgxMjIwMjE0OQ - reduced.csv](https://github.com/ghostfolio/ghostfolio/files/14065580/from_2020-05-01_to_2021-04-30_MTcwNDgxMjIwMjE0OQ.-.reduced.csv)
**Bug Description**

When I try to import a CSV file from Trading 212. The following error message appears: activities.0.currency is not valid

I uploaded the file. Only reduced to a few rows.

The problem is with the 

**To Reproduce**

1. Upload CSV file from trading 212 in Activities

**Expected behavior**

The Activities should upload correctly from the CSV file.

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/157811498/8ab0dbcf-fe07-4d06-8024-d8fc3b32422c)

**Logs**

{
  "Action": "Deposit",
  "Time": "2020-05-03 22:00:43",
  "ISIN": null,
  "Ticker": null,
  "Name": null,
  "No. of shares": null,
  "Price / share": null,
  "Currency (Price / share)": null,
  "Exchange rate": null,
  "Result": null,
  "Currency (Result)": null,
  "Total": 2000,
  "Currency (Total)": "GBP",
  "Withholding tax": null,
  "Currency (Withholding tax)": null,
  "Stamp duty": null,
  "Currency (Stamp duty)": null,
  "Stamp duty reserve tax": null,
  "Currency (Stamp duty reserve tax)": null,
  "Notes": "Transaction ID: 1825885432324321",
  "ID": "6568e4f2-a1cf-4d27-8821-e7838f91ddfb"
}

**Environment**

- Ghostfolio Version: online
- Browser: Chrome
- OS: Win10

**Comment by dtslvr** [comment]
Hi @BloodyXmas

Unfortunately, direct import from _Trading 212_ is not supported at the moment. However, you can manually transform your `csv` file to match Ghostfolio's format (check out the examples [here](https://github.com/ghostfolio/ghostfolio/tree/main/test/import)) or try this [community project](https://github.com/dickwolff/Export-To-Ghostfolio) by @dickwolff.
