### ISSUE TITLE
[BUG] non valid price jump - possible data / conversion issue

### ISSUE THREAD

**Issue by theflyer08** [ghostfolio/ghostfolio#2964]
There is a non valid price jump in the chart (IWDA.L).

**Expected behavior**
No price jump. 

![Ghostfolio](https://github.com/ghostfolio/ghostfolio/assets/130169389/bb93f476-d00a-4905-8b07-2613064797b9)

- Ghostfolio Version 2.47.0 - 2024-02-02
- Self-hosted
- Experimental Features disabled
- Chrome
- Debian / Docker

**Comment by dtslvr** [comment]
Hi @theflyer08

This looks like a glitch of the data provider. Can you try to reimport historical data via _Gather Historical Data_?

**Comment by theflyer08** [comment]
Thank you a lot. The reimport of the historical data in the admin console worked. 

Data looks great again :-)

**Comment by theflyer08** [comment]
Issue is fixed by reimporting the data.
