### ISSUE TITLE
[BUG] Editing price in market data doesn't work for certain dates

### ISSUE THREAD

**Issue by gccollect** [ghostfolio/ghostfolio#2965]
**Bug Description**
The Yahoo market data for [Vanguard FTSE Dev Wld ex-UK Eq Idx £ Acc](https://uk.finance.yahoo.com/quote/0P0000KSP6.L/history?period1=1630454400&period2=1631232000&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true) on 6 September 2021 is clearly wrong (price not multiplied by 100 for GBp) so I tried changing it in the market data screen. However, after I click save and check the price again it is still showing the incorrect price and there are no logs on the DB side indicating any change was made. Note that I was able to modify other prices at the front of the timeseries.

**To Reproduce**

1. Add 0P0000KSP6.L to the market data
2. Modify the price for 06/09/21 from 526.016113 to 52601.6113
3. Observe that the price hasn't changed and there are no logs on the DB side

**Expected behavior**

Changing a market data point should update it in the DB

**Environment**

- Ghostfolio Version 52601.6113
- Self-hosted
- Experimental Features disabled
- Browser Chrome
- OS Windows 11

**Comment by dtslvr** [comment]
Hi @gccollect 

Can you check if https://github.com/ghostfolio/ghostfolio/pull/2994 has fixed this bug?

**Comment by dtslvr** [comment]
> What would be the best way to do that?

Verify that you are running the [latest version](https://github.com/ghostfolio/ghostfolio/releases) in the _Admin Control_ panel and carry out the steps to reproduce.

**Comment by gccollect** [comment]
The issue doesn't appear to be fixed in 2.56.0

**Comment by dtslvr** [comment]
Should be fixed now, can you check again @gccollect?

**Comment by gccollect** [comment]
> Should be fixed now, can you check again @gccollect?

Yes, it works now. Thanks
