### ISSUE TITLE
[BUG] Incorrect Data in Overview & Summary - Ignoring Currency

### ISSUE THREAD

**Issue by AlexCPU** [ghostfolio/ghostfolio#2974]
**Bug Description**

The performance graph on Overview-> Overview page is applying no adjustments for currency. Same problem in the summary table for total assets value

Looks like a duplicate of #2941 which I reported, but I think it's just appeared in the latest release

**To Reproduce**

1. Set base currency to GBP
2. Set currency of account to GBP
3. Add one unit of INRG.L and SLXX.L on 1st Jan 2024 using the price of the day
4. Check performance graph on overview (total value on this page is incorrect - shows ~£750, when should be ~£130)
5. Check summary (total value of assets is wrong - should match total of investment)

**Expected behavior**

Currency conversions apply correctly

**Screenshots**
Assets added to reproduce:
![image](https://github.com/ghostfolio/ghostfolio/assets/4178651/33cbc520-d63a-4408-8be1-1f7b95936d45)

Overview with incorrect value:
![image](https://github.com/ghostfolio/ghostfolio/assets/4178651/f7c8b277-8bfd-4a3d-bd06-2763137cac86)

Summary:
![image](https://github.com/ghostfolio/ghostfolio/assets/4178651/bff7ddc6-3364-4ce2-878f-551ec68f92b3)

**Logs**

N/A

**Environment**

- Ghostfolio Version 2.48.1
- Self-hosted
- Experimental Features enabled or disabled: tested both
- Browser: chrome
- OS: Win 11

**Additional context**

**Comment by AlexCPU** [comment]
The issue seems to affect more than just these areas.  However I rolled back to 2.47.0 and the problem went away, then rolling back forwards to 2.48.1 it didn't reappear, and I can no longer reproduce the issue, so maybe we close this?

**Comment by dtslvr** [comment]
> I can no longer reproduce the issue, so maybe we close this?

Yes, let's close this issue. If you encounter it again, please open a new issue with detailed steps to reproduce.
