### ISSUE TITLE
Nodejs version issue

### ISSUE THREAD

**Issue by vmajor** [ghostfolio/ghostfolio#298]
I am trying to install on WSL2 Ubuntu and I get this error after trying yarn install

```
yarn install v1.22.11
[1/5] Validating package.json...
error ghostfolio@1.39.0: The engine "node" is incompatible with this module. Expected version "14.x". Got "16.6.2"
error Found incompatible module.
```

This is odd as the requirement is 14.x and above. 16.6.2 clearly satisfies this requirement.

**Comment by dtslvr** [comment]
Hey @vmajor

Thank you very much for reporting this version mismatch. I have just fixed it, can you please confirm?

**Comment by vmajor** [comment]
Sorry, I used: `yarn config set ignore-engines true` to get around this and move on. I am now trying to work with ghostfolio. I will make a post about another error that I encountered once I got it to run, in a separate thread.

**Comment by dtslvr** [comment]
> Sorry, I used: `yarn config set ignore-engines true` to get around this and move on. I am now trying to work with ghostfolio. I will make a post about another error that I encountered once I got it to run, in a separate thread.

Okay, I will close this issue for now. Do not hesitate to create another one.
