### ISSUE TITLE
[BUG] Incorrect holding performance calculation

### ISSUE THREAD

**Issue by Pima-Dev** [ghostfolio/ghostfolio#2997]
**Bug Description**

When there is more than one activity on a holding, displayed performance for this holding is incorrect.

**To Reproduce**

1. Visit https://ghostfol.io/en/home/holdings
2. Click on Vanguard FTSE All-World UCITS ETF
3. Calculate the earnings: 17819.85 * 21.73 / 100 = 3872.25, which is significantly different from the actual earnings of 2432.81 (the correct value).

**Expected behavior**

The expected performance should be calculated as follows: 20344.53 / 17819.85 = 1.1416, resulting in a performance of 14.16%.

**Screenshots**

<img width="789" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/28201009/f7b9a926-859c-48b8-af8a-dec266974785">

<img width="791" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/28201009/ef78deec-ea09-41dc-9da1-267848a1c492">

**Environment**

- Ghostfolio Version 2.50.0
- Cloud and Self-hosted
- Experimental Features disabled
- Browser : Chrome or Safari
- OS : macOS or iPhone

**Comment by dtslvr** [comment]
Hi @Pima-Dev

Ghostfolio uses [Time-Weighted Rate of Return](https://www.investopedia.com/terms/t/time-weightedror.asp) (TWR). As this is not considered a bug, I am closing this ticket.
