### ISSUE TITLE
[BUG] Total invested is incorrect

### ISSUE THREAD

**Issue by VanQz** [ghostfolio/ghostfolio#3004]
**Bug Description**

![image](https://github.com/ghostfolio/ghostfolio/assets/29053316/251766c6-27d5-4137-992e-cb77f14e6bff)

i think the image uploaded is self explanatory. The total sum added and the equity does not match. Not sure how it happened but also not sure how to fix it.

**To Reproduce**

Not sure when this happened. Recently checked and this was an issue

**Expected behavior**

It should should 6k+ USD.

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/29053316/23a83135-6a81-4f3d-be6f-62f80e074991)

**Environment**

- Ghostfolio Version v2.51.0
- Self-hosted
- Experimental Features disabled
- Browser - Chrome
- OS - Windows 11

**Comment by dtslvr** [comment]
Hi @VanQz

Please note: _Holdings_ are displayed in the value of your user account's base currency while _Equity_ is displayed in your account's currency. 

If you still think it is a bug, please open a new issue with detailed steps to reproduce. Thank you.

**Comment by VanQz** [comment]
Yes the currency is in USD and it should show $6000+ USD but its showing only $5520. Not sure how to reproduce this but im pretty sure previously before i have updated the total sum was accurate. @dtslvr

**Comment by VanQz** [comment]
@dtslvr SGD. after conversion the amount is wrong too. previously it was correct

**Comment by dtslvr** [comment]
4242.00 / 57 * 100 = 7442.10 SGD
7442.10 SGD = 5522.87 USD

Quite close to 5520.39 USD of the screenshot. Let me know what is wrong.

**Comment by VanQz** [comment]
> 4242.00 / 57 * 100 = 7442.10 SGD 7442.10 SGD = 5522.87 USD
> 
> Quite close to 5520.39 USD of the screenshot. Let me know what is wrong.

![image](https://github.com/ghostfolio/ghostfolio/assets/29053316/110ecf1a-e216-45db-a618-62594854a7e8)
that amount shown above is in USD and its the same as the amount shown in the first screenshot tho
