### ISSUE TITLE
Extend market data with preset by activitiesCount and date

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3006]
Add missing attributes `activitiesCount` and `date` (_First Activitiy_) to market data endpoint for `presetId` = `CURRENCIES` (`api/v1/admin/market-data?presetId=CURRENCIES`).

### Steps to reproduce

1. Go to _Admin Control_
2. Click on _Market Data_
3. Select preset _Currencies_ in _Filter by..._

<img width="1122" alt="market-data-with-currencies-preset" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/f8a17041-3e0a-4708-9afa-f6c34e8236d5">

### Todo

- [ ] Set `activitiesCount` and `date` as required in `AdminMarketDataItem` interface (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/interfaces/admin-market-data.interface.ts#L8))
- [ ] Add `activitiesCount` and `date` to `getMarketDataForCurrencies()` (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.service.ts#L376))

**Comment by bikash-789** [comment]
@dtslvr Can I work on this?

**Comment by SirZemar** [comment]
Hey @dtslvr. If nobody is working on this and still open, I can have a go.

**Comment by SirZemar** [comment]
@dtslvr As you suggested in  https://github.com/ghostfolio/ghostfolio/pull/3022#issuecomment-1954941236, I would like to import this data, but couldn't figure out how. Any guidance you can give on this? 

Also, can you clarify what activities are we looking for to display in each currency pair?

**Comment by SirZemar** [comment]
Sounds good. However, I couldn't import the data yet 😅. It is the last step so I can test it. Can you help with this?
![FireShot Capture 001 - Activities – Ghostfolio - localhost](https://github.com/ghostfolio/ghostfolio/assets/87383586/16af95ee-7ac1-49e3-a0e7-13b3909dae0a)

**Comment by dtslvr** [comment]
> However, I couldn't import the data yet 😅

Do you see this in your log when you start the server?

```
Fetching crumb and cookies from https://finance.yahoo.com/quote/AAPL...
...
fetch https://query1.finance.yahoo.com/v1/test/getcrumb
New crumb: t***N.t***G
```

If not, you probably need to reinstall the dependencies via `yarn install`, especially check for `"yahoo-finance2": "2.11.3"` (see https://github.com/ghostfolio/ghostfolio/pull/3441).
