### ISSUE TITLE
Add Robinhood to list of platforms

### ISSUE THREAD

**Issue by michaelwschultz** [ghostfolio/ghostfolio#3044]
Not sure why this isn't already part of the list. But with Robinhood's 5% interest rate, a lot of people have savings there.

**Comment by dtslvr** [comment]
Hi @michaelwschultz

I have just added _Robinhood_ to [ghostfol.io](https://ghostfol.io).

**Comment by michaelwschultz** [comment]
Ah, thanks. That was quick! lol I'm not sure I really understand the purpose of "Platform". I guess it's just for helping categorize things.

**Comment by dtslvr** [comment]
> I guess it's just for helping categorize things.

Exactly. It can be useful if you have several accounts on one platform (e.g. saving and trading account). You can check the platform risk in _Allocations_.

**Comment by michaelwschultz** [comment]
Any reason I shouldn't just be able to enter a custom Platform name in? Nice tool btw and thanks for the responses.

**Comment by dtslvr** [comment]
> Any reason I shouldn't just be able to enter a custom Platform name in?

As an administrator (self-hosted version) you can manage the platforms by yourself. However, there is no feature to manage them per user.

**Comment by joscha** [comment]
@dtslvr I have a few platforms I'd like to add as well, what is the metric to add one? Can I open a ticket here and name the platform, the reasoning for adding it and a logo? Can I also send it via email, so I don't expose personal data (i.e. which platforms I use personally).

**Comment by dtslvr** [comment]
@joscha please drop us an email with your desired platforms to hi[at]ghostfol.io.
