### ISSUE TITLE
[BUG] Mixed exchange rates in the Accounts page

### ISSUE THREAD

**Issue by tuupola** [ghostfolio/ghostfolio#3049]
**Bug Description**

When adding a valuable in some other currency than USD the accounts page gets confused and shows the value assuming the valuable price was entered is USD.

**To Reproduce**

1. Create new user
2. Add a THB account with name Thailand
3. Add a new valuable to the Thailand account with value of 1000THB
4. Go to Accounts page. The value of Thailand account is 35900THB (which equals 1000USD)

**Expected behavior**

The value of Thailand account should be 1000THB.

**Screenshots**

![Screenshot from 2024-02-25 19-31-50](https://github.com/ghostfolio/ghostfolio/assets/21913/357109a4-c740-4909-81c0-1ef50b54c1e8)
![Screenshot from 2024-02-25 19-32-31](https://github.com/ghostfolio/ghostfolio/assets/21913/8d4848b8-d6c3-469e-9964-8886160cdbb6)
![Screenshot from 2024-02-25 19-32-56](https://github.com/ghostfolio/ghostfolio/assets/21913/b8647c5a-dbe9-45c7-946b-ccd9a0d8afa1)
![Screenshot from 2024-02-25 19-51-27](https://github.com/ghostfolio/ghostfolio/assets/21913/2d75f6e5-df10-4f28-8277-4fdd7c3665c6)

**Environment**

- Ghostfolio Version 2.56.0
- Kubernetes Self-hosted
- Experimental Features disabled
- Brave 1.61
- Fedora 39

**Additional context**

**Comment by dtslvr** [comment]
Hey @tuupola

The fix has been released with Ghostfolio [2.59.0](https://github.com/ghostfolio/ghostfolio/releases/tag/2.59.0). Can you please provide feedback?

**Comment by dtslvr** [comment]
> Seems to be fixed. I did exactly the same steps as above and the accounts page now shows correct numbers. Thanks!

Great, thanks for the feedback!

**Comment by ms32035** [comment]
@dtslvr there seems to still be some issues as the figures I see in my app are crazy on 2.59. Please notice the following output for a single position from the `positions` api for GBp where GBp/GBP = 100
```
{'currency': 'GBp',
 'dataSource': 'YAHOO',
 'firstBuyDate': '2018-01-12',
 'symbol': '0P00000YII.L',
 'transactionCount': 1,
 'assetClass': 'EQUITY',
 'assetSubClass': 'MUTUALFUND',
 'averagePrice': 556,
 'grossPerformance': 78136.72968504,
 'grossPerformancePercentage': 0.3908273165467626,
 'grossPerformancePercentageWithCurrencyEffect': 138.08273165467622,
 'grossPerformanceWithCurrencyEffect': 276063.94488504,
 'investment': 199926.48,
 'investmentWithCurrencyEffect': 1999.2648000000004,
 'marketState': 'delayed',
 'name': 'Janus Henderson Eurp Mid & Lrg Cap I Acc',
 'netPerformance': 78136.72968504,
 'netPerformancePercentage': 0.3908273165467626,
 'netPerformancePercentageWithCurrencyEffect': 138.08273165467622,
 'netPerformanceWithCurrencyEffect': 276063.94488504,
 'quantity': 359.58,
 'timeWeightedInvestment': 199926.48,
 'timeWeightedInvestmentWithCurrencyEffect': 1999.2648000000004}
```
Specifically, these 2
```
 'grossPerformancePercentage': 0.3908273165467626,
 'grossPerformancePercentageWithCurrencyEffect': 138.08273165467622,
```
After currency conversions some of my positions skyrocketed
Incorrect data is displayed in:
Overview -> Overview
Overview -> Holdings
Overview -> Summary
Portfolio -> Analysis
Portfolio -> Holdings
Accounts

Values in Portfolio-Activities are correct
