### ISSUE TITLE
[BUG] Currency does not match despite correct currency

### ISSUE THREAD

**Issue by Raptor05** [ghostfolio/ghostfolio#3055]
**Bug Description**

I'm trying to import my historical share activities to Ghostfolio. For this I've collected all transactions in an excel file. After changing my computer language for the separator and using an online converter to replace the delimeter from ; to , I was able to upload the CSV file to Ghostfolio. 
But then the following error occurs:
**_activities.5.currency ("EUR") does not match with "CHF" and no exchange rate is available from "EUR" to "CHF"_** 

The relevant line is:
"01.08.2017,LU0290355717,YAHOO,EUR,228.4722222,0.216,buy,0,Einlieferung,1234"

The transaction happened with EUR currency and [Yahoo](https://finance.yahoo.com/quote/XGLE.DE) is listing that share with EUR, too.

When I'm removing all other entries from the file, it works with that line, thats really strange...

**To Reproduce**

I've uploaded the CSV file.
1. Go to activities
2. Choose Import activities
3. Choose the file
4. Error in step 2

**Expected behavior**
Accept the line.

**Environment**

- Ghostfolio Version v2.55.0
- Self-hosted with docker on Synology NAS
- Experimental Features disabled
- Browser Edge
- OS is Win 11

[test.csv](https://github.com/ghostfolio/ghostfolio/files/14402793/test.csv)

**Comment by dtslvr** [comment]
Hi @Raptor05

`LU0274208692` should be in `CHF` instead of `EUR`.

It looks like the row in the error message is wrong, maybe because the entries in the CSV file are not sorted.

**Comment by Raptor05** [comment]
> LU0274208692

Thanks for your answer.

2 Questions:

1. What means sorted? Do they need to be sorted by date?
2. Okay, on YAHOO the ETF is listed with CHF, on other platforms in EUR. But I bought them in EUR. How should I handle that? If I just change the currency, the price is wrong.
