### ISSUE TITLE
[BUG]Market Data has a ghost record that influence performance

### ISSUE THREAD

**Issue by EricVanCaenenberghe** [ghostfolio/ghostfolio#3063]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

For one equity type fund I have a ghost record (rate no date) that persist as last value of the equity

**To Reproduce**

no clue

1.
2.
3.

**Expected behavior**

- there should not be any phantom / ghost data residing in the system.

**Screenshots**

![Schermafdruk van 2024-02-28 19-24-55](https://github.com/ghostfolio/ghostfolio/assets/29582047/71dab4c0-da6d-4975-8c3c-593f6adde38c)
graph of the fund notice the deep dive on the right side.
![Schermafdruk van 2024-02-28 19-25-25](https://github.com/ghostfolio/ghostfolio/assets/29582047/966d0daa-66d5-4520-9a5c-473f33a3399a)
the blue blop is the day of today on which no new rate is fixed yet but ...
![Schermafdruk van 2024-02-28 19-25-46](https://github.com/ghostfolio/ghostfolio/assets/29582047/59f412cd-1fed-42f5-a24a-18eebca7c70a)
but nevertheless the market price is 105.01.
During the night a market price is set for today but the next day is prepopulated by 105.1
At a certain point (a year ago) 105.1 was the actual market price.

**Logs**

**Environment**

- Ghostfolio Version 2.58.x
- Self-hosted
- Experimental Features disabled
- Browser: firefox & chrome
- OS: linux mint 21.3

**Additional context**

This problem was persistent since a year. Over the weekend however 2.56.x the problem was gone but with installing 2.57.x and then today 2.58, the problem reoccurred.

**Comment by dtslvr** [comment]
Hi @EricVanCaenenberghe

It seems to be a problem of the data provider: https://finance.yahoo.com/quote/0P0001PB9N.F

<img width="346" alt="0P0001PB9N-quote" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/27d2d925-c042-46b2-9d61-5e4090fe7d19">
