### ISSUE TITLE
Visual Studio Code terminal hangs when building

### ISSUE THREAD

**Issue by sahb1239** [ghostfolio/ghostfolio#3064]
When running either yarn watch:server or yarn start:client in the Visual Studio Code terminal the command hangs on the copy-assets command. 

![image](https://github.com/ghostfolio/ghostfolio/assets/5653344/0a626b23-d0c0-48d4-b225-16a34d1b49d6)

It seems like the reason to this is due to a bug on NX nrwl/nx#21779 which are causing the Visual Studio terminal to freeze when building the API or Client due to this change here #3052. The change is however still required on the pipeline in order to run successfully. 

For now a temporary locally fix is removing the rm command and running everything else in parallel.

**Comment by dtslvr** [comment]
@sahb1239 can you try to run it with the environment variable `NX_NATIVE_COMMAND_RUNNER=false`? (https://github.com/ghostfolio/ghostfolio/pull/3120)
