### ISSUE TITLE
Some ETF do not fetch sectors / countries data

### ISSUE THREAD

**Issue by rejuce** [ghostfolio/ghostfolio#3071]
**Bug Description**

adding some etf in Market Data, trying to fetch historical data and profile data, but profile data is not fetched even though it exists in yahoo.
For most it works fine though.

**To Reproduce**

1. use IE00B48X4842 or IE000OJ5TQP4
2. add them under market data
3. fetch all data, historical data and profile data

![grafik](https://github.com/ghostfolio/ghostfolio/assets/28755821/f722a509-7361-407f-a9f9-b965a8047b92)

**Expected behavior**

like in any other etf, to show the countires and sectors
if it really can not be fetched, then there should be the option to add those manually

**Environment**

portainer / dockerhost

- Ghostfolio Version 2.57.0
- Self-hosted
- Experimental Features  disabled

**Comment by dtslvr** [comment]
Hi @rejuce

I'm not aware that country weightings are available on _Yahoo Finance_. Can you show me please?

Data for countries and sectors is currently coming from additional data providers. Please check these [instructions](https://github.com/ghostfolio/ghostfolio/issues/715#issuecomment-1046267439) to setup the data enhancer for your asset.

**Comment by rejuce** [comment]
Thank you for the pointer, that workaround does the trick

True yahoo seems to provide only the sector data

The asset list should show other sources then yahoo though then
