### ISSUE TITLE
[BUG] Performance graph on homepage is wrong

### ISSUE THREAD

**Issue by jamiehannaford** [ghostfolio/ghostfolio#3072]
**Bug Description**

The portfolio performance graph on the home page shows an incorrect profit spike. This spike shows a profit jump of 629% for 6 days, and then returns to normal. See below:

![Screenshot 2024-03-01 at 10 38 18](https://github.com/ghostfolio/ghostfolio/assets/1867202/39f58ba1-1897-4c7f-857c-788a696e89c2)

However this does not correlate to any transfers in the Activity tab:

![Screenshot 2024-03-01 at 10 38 33](https://github.com/ghostfolio/ghostfolio/assets/1867202/8fd55df7-082f-4ce1-ab2a-b79b073a4d1b)

**To Reproduce**

1. Go to home page 
2. View incorrect graph
3. Try to find erroneous transfers/activities that may have led to this error, but not find any

**Expected behavior**

I expect the graph to reflect listed activities. I'm not sure how the graph is generated or what data populates it. I tried clearing the cache but had no affect. 

**Environment**

- Ghostfolio Version docker.io/ghostfolio/ghostfolio@sha256:b0f4da6562306321921763fb2e21d2167538df71dd568f72a2ff46b9e342ff18
- Self-hosted

**Comment by jamiehannaford** [comment]
@dtslvr How is the graph on the home page populated - do we cache it anywhere? Wondering if it's possible to manually remove this blip.

**Comment by dtslvr** [comment]
Hi @jamiehannaford

It's almost impossible to figure out what the problem could be with this information. Can you narrow down the spike to a single holding?

> do we cache it anywhere?

No, the chart is currently not cached.

**Comment by jamiehannaford** [comment]
I went through all my holdings and found some weird price spikes. I deleted and re-added them and seems to be fixed. Thanks for the tip!
