### ISSUE TITLE
[BUG] Missing exchange rates caused extremely slow loading times

### ISSUE THREAD

**Issue by TheekshanaA** [ghostfolio/ghostfolio#3082]
**Bug Description**

Loading of portfolio related pages are extremely slow if there is a currency conversion with missing exchange rates. Setting base currency to USD does resolve the issue.

**To Reproduce**

1. Add an activity in  a different currency to base currency in 2018
2. View any portfolio related pages

**Expected behavior**

Should load normal speed and ignore currency conversion errors

**Screenshots**
![image](https://github.com/ghostfolio/ghostfolio/assets/10327965/63abd725-a695-4d04-9b91-ca65ba075d96)

**Logs**

`
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-04-01
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-31
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-30
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-29
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-28
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-27
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-26
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-25
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-24
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-23
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-22
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-21
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-20
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-19
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-18
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-17
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-16
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-15
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-14
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-13
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-12
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-11
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-10
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-09
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-08
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-07
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-06
[Nest] 142  - 03/02/2024, 8:35:44 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-05
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-04
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-03
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-02
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-03-01
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-28
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-27
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-26
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-25
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-24
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-23
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-22
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-21
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-20
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-19
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-18
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-17
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-16
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-15
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-14
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-13
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-12
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-11
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-10
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-09
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-08
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-07
[Nest] 142  - 03/02/2024, 8:35:45 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDAUD at 2018-02-06
`
**Environment**

- Ghostfolio Version v2.59.0
-  Self-hosted
- Experimental Features disabled
- Browser: Chrome
- OS: Windows 11

**Comment by swissbuechi** [comment]
I've also experienced this issue.

Fixed it by triggering a manual "historical data import" on the affected currency.

**Comment by TheekshanaA** [comment]
> I've also experienced this issue.
> 
> Fixed it by triggering a manual "historical data import" on the affected currency.

Oh right, how did you about doing so? Sorry it's actually my first time using Ghostfolio

**Comment by dtslvr** [comment]
> Oh right, how did you about doing so?

You can find the instructions in the [FAQ for self-hosting](https://ghostfol.io/en/faq/self-hosting).
