### ISSUE TITLE
[BUG] Import (dividend) not working in 2.60.0

### ISSUE THREAD

**Issue by Babasile** [ghostfolio/ghostfolio#3090]
**Bug Description**

When I tried to import a Dividend with the button
<img width="161" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/18406066/71ff04d9-2436-4223-9011-66884dccf382"> 
I have a success message but the dividend is not visible in the list and it does'nt exist in the DB. (It works when I do it manually). 
I reverted to 2.59.0 and it works as expected.

**To Reproduce**

1. Click on Import Dividend in /portfolio/activities.
2. Select the stock and dividend to import.
3. Click on Import -> success message but the dividend is not visible or present in DB.

**Expected behavior**

Import the dividend.

**Screenshots**

1.

<img width="202" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/18406066/5f51a981-6018-44dd-a59a-acaf9c9e3c90">

2.
<img width="363" alt="image" src="https://github.com/ghostfolio/ghostfolio/assets/18406066/d97924e6-698d-4c6c-b180-1b1b2944b06d">
(No dividend even after F5)

**Logs**

I do not have errors in logs.

**Environment**

- Ghostfolio Version 2.60.0
- Self-hosted
- Experimental Features disabled
- Browser Chrome
- OS Windows

**Additional context**

**Comment by SimoGh** [comment]
Hi,

Actually it seems that no import work in 2.60.0.
Tested both in csv and json, selfhosted and in ghostfol.io.

Downgraded to 2.59.0 and the import worked fine.
