### ISSUE TITLE
[BUG] Invalid Number Exception

### ISSUE THREAD

**Issue by TiloHeidasch** [ghostfolio/ghostfolio#3098]
## **Bug Description**

When opening the Accounts Tab i get greeted with " Oops! Something went wrong. Please try again later. "
The logs show a big.js Invalid Number Exception
```[Nest] 170  - 03/04/2024, 11:33:00 PM   ERROR [ExceptionsHandler] [big.js] Invalid number
Error: [big.js] Invalid number
    at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
    at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
    at P.plus.P.add (/ghostfolio/apps/api/node_modules/big.js/big.js:653:9)
    at PortfolioService.getAccountsWithAggregations (/ghostfolio/apps/api/main.js:1:375868)
```

## **To Reproduce**

I have no further details than:
```[Nest] 170  - 03/04/2024, 11:33:00 PM   ERROR [ExceptionsHandler] [big.js] Invalid number
Error: [big.js] Invalid number
    at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
    at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
    at P.plus.P.add (/ghostfolio/apps/api/node_modules/big.js/big.js:653:9)
    at PortfolioService.getAccountsWithAggregations (/ghostfolio/apps/api/main.js:1:375868)
```
Is there a way to enable debug logging?

## **Expected behavior**
Well, showing the accounts :) 

## **Screenshots**
![Screenshot 2024-03-04 at 23 36 32](https://github.com/ghostfolio/ghostfolio/assets/56626655/5fa0378b-f83a-4c41-bc60-34bcd745853d)
![Screenshot 2024-03-04 at 23 36 49](https://github.com/ghostfolio/ghostfolio/assets/56626655/d6804f99-6db4-46e9-bbf4-f467f68c3bd2)

## **Logs**
```[Nest] 170  - 03/04/2024, 11:33:00 PM   ERROR [ExceptionsHandler] [big.js] Invalid number
Error: [big.js] Invalid number
    at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
    at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
    at P.plus.P.add (/ghostfolio/apps/api/node_modules/big.js/big.js:653:9)
    at PortfolioService.getAccountsWithAggregations (/ghostfolio/apps/api/main.js:1:375868)
```

## **Environment**

- Host: Docker on Unraid, Tag: latest
- Ghostfolio Version: 2.60.0 - 2024-03-02
- EDIT: Issue Persists with 2.61.0 - 2024-03-04
- EDIT: Issue does not exist in 2.59.0 - 2024-02-29
- Self-hosted
- Experimental Features disabled
- Browser: Firefox 123.0 (64bit)
- OS: MacOS

**Comment by TiloHeidasch** [comment]
A quick diff between https://github.com/ghostfolio/ghostfolio/compare/2.59.0...2.60.0 reveals 
this change with a Big, so this might be a hint?
![Screenshot 2024-03-05 at 09 01 44](https://github.com/ghostfolio/ghostfolio/assets/56626655/0357c344-d75e-4b58-952c-f74ee397786f)

**Comment by karter16** [comment]
Dropping in here to say that I am also experiencing this with 2.61.0 (selfhosted)

**Comment by dtslvr** [comment]
Can you provide a minimal export file to reproduce this issue? Eventually including a dividend activity (see hint by @TiloHeidasch).

**Comment by TiloHeidasch** [comment]
@dtslvr Thanks for jumping on this. Without any debug logging I have no Idea what to do to create a minimal export file. What should I look for? Otherwise I would just go about it in a trial and error way (which I'd prefer not to do). Also: what hint do you mean?

**Comment by TiloHeidasch** [comment]
Nevermind - I found the issue. The Problem is with Liabilities. The Value of an Account becomes less than 0 when it only has liabilities to it. Therefor the minimum reproducable is:
```
{
  "meta": {
    "date": "2024-03-06T11:52:40.648Z",
    "version": "v2.60.0"
  },
  "accounts": [
    {
      "balance": 0,
      "comment": null,
      "currency": "USD",
      "id": "029c0934-7e9d-44a2-8f2c-015faa2b0725",
      "isExcluded": false,
      "name": "My Account",
      "platformId": null
    }
  ],
  "activities": [
    {
      "accountId": "029c0934-7e9d-44a2-8f2c-015faa2b0725",
      "comment": null,
      "fee": 0,
      "quantity": 1,
      "type": "LIABILITY",
      "unitPrice": 1,
      "currency": "USD",
      "dataSource": "MANUAL",
      "date": "2024-03-06T11:52:11.190Z",
      "symbol": "A Liability"
    }
  ]
}
```

**Comment by dtslvr** [comment]
> ghostfolio-export-202403061252.json

Thank you very much for providing this valuable data to reproduce the issue, @TiloHeidasch!

**Comment by TiloHeidasch** [comment]
Thanks for the quick help! Nevertheless, an option for debug logging would be helpful :)
