### ISSUE TITLE
[BUG] Error: Could not get historical market data 

### ISSUE THREAD

**Issue by cheesestickstomatojuice** [ghostfolio/ghostfolio#3106]
**Bug Description**

I get the error whenever I launch ghostfolio or when I try to gather historical data via the admin control panel, it also doesn't gather the historical data.

`ERROR [DataProviderService] Error: Could not get historical market data for IE00BK5BQT80.SG (YAHOO) from 2023-11-30 to 2024-03-05: [HTTPError] Not Found`

**To Reproduce**

1. Add the stock ISIN: IE00BK5BQT80.SG 
2. Relaunch ghostfolio or gather historical data via the admin control panel
3. Check the logs for the error.

**Expected behavior**

I wanted it to gather historical data so it can show me the stock market data from the previous dates.

**Logs**

`[Nest] 142  - ERROR [DataProviderService] Error: Could not get historical market data for IE00BK5BQT80.SG (YAHOO) from 2023-11-30 to 2024-03-05: [HTTPError] Not Found`

`[Nest] 142  -  LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been completed for IE00BK5BQT80.SG (YAHOO) at 2024-03-05`
**Environment**

- Ghostfolio Version v2.61.0
- Self-hosted 
- Experimental Features disabled
- Firefox
- Debian Linux

**Comment by dtslvr** [comment]
Hi @cheesestickstomatojuice

Historical data is not available for `IE00BK5BQT80.SG` at the data provider. Please see [here](https://finance.yahoo.com/quote/IE00BK5BQT80.SG/history).
