### ISSUE TITLE
[BUG] Cannot remove account from activity

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3111]
**Bug Description**

Cannot remove account from _Valuable_ activity.

**To Reproduce**

1. Create an activity of type _Valuable_ and assign an account
2. Remove the account from the selector (via edit)
3. Save
4. Account is still assigned to the activity

**Expected behavior**

Account should not be assigned anymore.

**Environment**

- Ghostfolio Version 2.61.1
- Cloud and Self-hosted
- Experimental Features disabled

**Additional context**

See `PUT api/v1/order/{id}` where `accountId: null` is sent but not handled.

**Comment by GerardPolloRebozado** [comment]
You can assign it to me
