### ISSUE TITLE
[BUG] Manually imported market data not showing correctly

### ISSUE THREAD

**Issue by helgehatt** [ghostfolio/ghostfolio#3116]
**Bug Description**

Manually imported market data is not showing correctly in the overview and portfolio graphs:

![Screen Shot 2024-03-08 at 16 17 33](https://github.com/ghostfolio/ghostfolio/assets/12933913/71e4ba4d-4ee1-47c2-b266-ada777d03963)

After some debugging, I found that the source of the bug is related to *timezone* and *data decimation*. If I simply drop the `dateQuery` in the `marketDataService.getRange` function, I get the correct graph:

![Screen Shot 2024-03-08 at 16 29 05](https://github.com/ghostfolio/ghostfolio/assets/12933913/7051c8dc-f292-483f-a2d0-95236d122378)

The first date in `dateQuery.in` is `"2017-05-17T00:00:00.000Z"` while the corresponding market data date is `"2017-05-16T22:00:00.000Z"`. I imagine all instruments are priced per day, regardless of being located in Switzerland or Japan, so is there are reason for keeping the timezone component?

If so, then the problem is the data decimation, and that we're querying the database for specific timestamps. In my opinion, it would make more sense to let the database handle the decimation, e.g. group by week and select first in each group to get weekly decimation.

Please let me know your thoughts and if you want me to take a look at a fix.

**To Reproduce**

1. Add NOK currency and set NOK as base currency.

2. Import activities from [ghostfolio-export-202403081157.json](https://github.com/ghostfolio/ghostfolio/files/14540598/ghostfolio-export-202403081157.json).
3. Import market data from [ghostfolio-pareto-market-data.csv](https://github.com/ghostfolio/ghostfolio/files/14540606/ghostfolio-pareto-market-data.csv)

**Environment**

- Ghostfolio Version 2.61.1
- Self-hosted
- Experimental Features disabled
- Firefox
- Linux

**Comment by dtslvr** [comment]
Hi @helgehatt

Good catch! This could be related to https://github.com/ghostfolio/ghostfolio/issues/2965.

The initial idea was to store market data in the following format `2017-05-17T00:00:00.000Z` representing a date without time (`2017-05-17`).

I have found the query `dateQuery: { in: dates }` in combination with `resetHours` to be less than ideal for some time now. It could also be the reason for the `TZ` issue (https://github.com/ghostfolio/ghostfolio/issues/2669).

What is your idea for improving this in incremental steps?

**Comment by helgehatt** [comment]
I noticed that the client is sending ISO timestamps to the server, which are parsed with a timezone offset.

So when I tried to import market price for `"2017-01-01"`, the client was sending `{"marketData":[{"date":"2016-12-31T23:00:00.000Z","marketPrice":6500}]}`

The PR linked above fixes my issue with manually imported data not showing correctly.

**Comment by helgehatt** [comment]
I tried looking into the data decimation part, but it looks like prisma [doesn't support window functions out of the box](https://github.com/prisma/prisma/issues/7039), so that probably requires a bit more effort.

**Comment by helgehatt** [comment]
[Here](https://www.db-fiddle.com/f/sTjCrZVecHTZF4Bm4n7GTJ/0) is an example of how data decimation can be achieved on the DB side. This way you don't have to query for specific dates. I would imagine this has better time complexity than the `IN` lookup.
