### ISSUE TITLE
[BUG] latest release broke login

### ISSUE THREAD

**Issue by thefeli73** [ghostfolio/ghostfolio#3128]
I use the admin account as my only account. After running my weekly automatic update this morning I was logged out and can no longer log in and just get “incorrect security token”.

**Bug Description**
Login token is getting denied after update.

**To Reproduce**

1. update to 2.62.0
1. Try to log in
2. Can’t

**Expected behavior**

Can log in

**Environment**

- Ghostfolio Version 2.62.0
-  Self-hosted
- Experimental Features enabled
- Browser safari
- OS iOS

**Comment by Luminilion** [comment]
> The containers were all healthy. A recreate of the stack fixed the issue.

Hi @thefeli73, what do you mean with a recreate of the stack ? 
I'm taking over from someone who setup our ghostfolio and I'm having trouble logging in with the security token.
I've got access to the DB directly, but I need access to the ghostfolio app. 
The old security token worked before, but now seems to have stopped working.

I'm trying to figure out if it's an instance problem and I should regenerate another instance or if I need to reset the security token somehow by resetting some values in the DB.

**Comment by thefeli73** [comment]
@Luminilion 
stack = the stack of docker containers. i.e. `docker compose up -d --force-recreate`. Run that in the same folder where you have your [docker-compose-yml](https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.yml).
