### ISSUE TITLE
[BUG] Self hosted instance loses all data when restarted

### ISSUE THREAD

**Issue by chris-fj** [ghostfolio/ghostfolio#3136]
**Bug Description**

I'm using the self hosted version and set up the instance correctly (it seems so because it loads), I added my portfolio and started exploring. Then I noticed I was using the `latest` tag and I was not comfortable without pinning a version, so I shut down the instance, added a tagged version and I was surprised to find out my token was not working out. I created another token (to rule out the fact that I forgot or didn't copy the token correctly) and I was able to log in from several devices. Then restarted (`docker compose down -v; docker compose up -d`) and the same token that was working a minute ago, now it doesn't seem to work. I tried the same process with the same result: the token works on the same device and other devices as long as I don't shut down the container.

I have searched wide and deep this bug tracker and I didn't find anything related to this issue, so this may be something on my end, but I can't see it. 

**To Reproduce**

1. Clone the repo (you can checkout to 2.63.0 for the example) and start the container. This happens with no modification to the docker-compose file
2. Create a new user, copy the security code and save it 
3. Add a small modification like adding a currency (admin control > overview > add currency > "EUR")
4. Shut down the container and start it again
5. Try to log in with the security code in step 2
6. Error: "Oops! Incorrect Security Token."

**Expected behavior**

The security token should allow me to log in and keep the information

**Logs**

Nothing relevant that I have seen in the output of `docker compose logs` but I may be missing something 
**Environment**

- Ghostfolio Version 2.63.0
- Self-hosted
- Experimental Features disabled
- Browser: Brave/Firefox
- Ubuntu 22.04.3 for the server, Arch Linux, iOS for the clients

**Comment by christoph93** [comment]
Could you try running the postgres container with bind volume and check if the files are persisted?

    volumes:
      - ./postgres:/var/lib/postgresql/data

**Comment by chris-fj** [comment]
That was exactly it. It totally seemed like a persistence problem, but I couldn't suspect that a named volume was the problem. I'm not a big fan of them either. Thanks for helping

**Comment by christoph93** [comment]
Managed volumes should work... maybe it's a permission problem with the docker installation?

**Comment by chris-fj** [comment]
I can't see why, because other containers are working fine. However, none of them use managed volumes. Nothing on the logs as far as I can see
