### ISSUE TITLE
Extend holdings page by past holdings

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3137]
<img width="1112" alt="holdings-past" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/7afe46c5-1039-4091-b9e7-5d2fb7c97508">

### Tasks

- [ ] Backend: Support a query param `quantity=0`  in the `api/v1/portfolio/holdings` endpoint. If this filter is active, it returns holdings where `quantity` equals `0` (@GerardPolloRebozado)
- [ ] Frontend: Add a toggle component to switch between current and past holdings (@dtslvr)

**Comment by GerardPolloRebozado** [comment]
Just did a PR #3146 but I changed the param name to pastInvestments, in my opinion was more acurate because this filter was only for actual investments or past not to filter by X quantity
