### ISSUE TITLE
[BUG] activities.0.symbol ("bitcoin") is not valid for the specified data source ("COINGECKO")

### ISSUE THREAD

**Issue by bernardcosta** [ghostfolio/ghostfolio#3154]
**Bug Description**
I have a json export file with activities. This is an exmaple of an activity json:
```
 {
      "accountId": "<account_id>",
      "comment": null,
      "fee": xxxxx,
      "quantity": xxxxx,
      "type": "BUY",
      "unitPrice": xxxxx,
      "currency": "USD",
      "dataSource": "COINGECKO",
      "date": "YYY-MM-DDT00:00:00.000Z",
      "symbol": "bitcoin"
    }
```

As the title of the description goes, I am getting `activities.0.symbol ("bitcoin") is not valid for the specified data source ("COINGECKO")` when trying to import this file. 

I am using a CoinGecko DEMO API and I confirm I did not exceed my API limits.. This does not make sense since I exported this data from another ghostfolio instance which had the same API key for coinGecko

**Maybe Related:** I tried to manually add an activity via the UI and I noticed that the suggestions when I start typing the symbol field are showing less results than usual. Maybe calls to CoinGecko are not being made, and only seeing yahoo results.

**To Reproduce**

1.  Spin up a docker instance with `API_KEY_COINGECKO_DEMO`
2. Copy the above json instance into an properly formatted export file with `meta` and `accounts` objects too
3. import the file via UI

**Logs**

```
[Nest] 131  - 03/16/2024, 8:38:19 AM   ERROR [CoinGeckoService] HTTPError: Response code 403 (Forbidden)
[Nest] 131  - 03/16/2024, 8:38:19 AM   ERROR [class ImportController{constructor(e,t,a){this.configurationService=e,this.importService=t,this.request=a}async import(t,a="false"){const r="true"===a;if(!Qa(this.request.user.permissions,Oa))throw new e.HttpException((0,gt.getReasonPhrase)(gt.StatusCodes.FORBIDDEN),gt.StatusCodes.FORBIDDEN);let o=this.configurationService.get("MAX_ACTIVITIES_TO_IMPORT");this.configurationService.get("ENABLE_FEATURE_SUBSCRIPTION")&&"Premium"===this.request.user.subscription.type&&(o=Number.MAX_SAFE_INTEGER);try{return{activities:await this.importService.import({isDryRun:r,maxActivitiesToImport:o,accountsDto:t.accounts??[],activitiesDto:t.activities,user:this.request.user})}}catch(n){throw e.Logger.error(n,Kc),new e.HttpException({error:(0,gt.getReasonPhrase)(gt.StatusCodes.BAD_REQUEST),message:[n.message]},gt.StatusCodes.BAD_REQUEST)}}async gatherDividends(e,t){const a=this.request.user.Settings.settings.baseCurrency;return{activities:await this.importService.getDividends({dataSource:e,symbol:t,userCurrency:a})}}}] Error: activities.0.symbol ("bitcoin") is not valid for the specified data source ("COINGECKO")
```

**Environment**

- Ghostfolio Version v2.61.0
- Self-hosted
- Experimental Features disabled
- Safari
- SMP Debian 5.10.162-1 (2023-01-21) aarch64 GNU/Linux

**Comment by dtslvr** [comment]
Can you please provide a valid export file? You can remove `accountId` and set `quantity` to `1`. Thank you.

**Comment by bernardcosta** [comment]
[gf-export.json](https://github.com/ghostfolio/ghostfolio/files/14623051/gf-export.json)

This is a truncated version of my original. But I still reproduced the bug with this file.  I also removed the DEMO API key in case my account has issues or restrictions. But I am still getting the same error without any keys

**Comment by dtslvr** [comment]
> [gf-export.json](https://github.com/ghostfolio/ghostfolio/files/14623051/gf-export.json)

Thanks. When I remove the `accounts` block completely, I can import without any issues.

**Comment by bernardcosta** [comment]
@dtslvr I realised the coingecko API does not work behing a vpn tunnel. I stopped the vpn client and the import worked correctly. So this is not a ghostfolio bug and it can be closed. Its quite a deal breaker for me and maybe other users as well. Would be interested to explore some other APIs related to coin information like kraken and others.

**Comment by bcannell** [comment]
I ran into a similar error; it turns out I did not specify API_KEY_COINGECKO_DEMO.

Perhaps it could throw and render a better error message when there's connectivity or authentication issues?

**Comment by Calatravo1994** [comment]
I've had the same error messages and fixed it by setting API_KEY_COINGECKO_DEMO.

very confusing as pulling data from coingecko worked before.
