### ISSUE TITLE
[BUG] Interest is not updating the total value cash

### ISSUE THREAD

**Issue by zozito** [ghostfolio/ghostfolio#3162]
**Bug Description**

I really appreciate the support to update the cash balance of an account when adding an interest activity, thank you for that!

After i add a cash interest the cash balance doesn't update

**Environment**

- Ghostfolio Version 2.64.0
- Self-hosted
- Experimental Features enabled 
- All Browser

**Comment by dtslvr** [comment]
Can you confirm this issue @rodriguestiago0?

**Comment by rodriguestiago0** [comment]
Hey,

I think the order when you check the checkbox is affecting the behaviour.

if the checkbox is checked last it updates the cash balance, if it’s checked after selecting the account it doesn’t work.

I will have a look.

**Comment by davidojedalopez** [comment]
Hey there! I can confirm it's working for some cases, but not for all. 

For instance, I just created an account that generates me interests. If I create an _Interest_ activity in the past, with the update cash checkbox checked, it doesn't actually update the balance:

![image](https://github.com/ghostfolio/ghostfolio/assets/8418542/cfd0db13-0bf9-4c67-a2c0-41c7d9d93d58)

But it does update the balance when I add a new _Interest_ activity today.

**Comment by rodriguestiago0** [comment]
Are you able to reproduce every time?

**Comment by davidojedalopez** [comment]
Yes, @rodriguestiago0, I can consistently reproduce it.

Anything else I can help with to debug this issue?

**Comment by rodriguestiago0** [comment]
Can you describe step by step so I can reproduce locally?

**Comment by davidojedalopez** [comment]
Sure!

1. Create a new account with Cash Balance = 0
2. Add new _Interest_ activity for the newly created account. Make sure the _Update Cash Balance_ is checked and the date is before today.
3. Go to _Accounts_. Newly created account still has 0.0 in cash balance.
4. Click on this account, go to _Cash Balances_, and you will see the new activity, but no updated cash balance.

I just reproduced it again while writing this, just to be sure.

**Comment by rodriguestiago0** [comment]
I think think the solution is very good. The table account_balance could be one entry account.
