### ISSUE TITLE
[bug] Holdings screen does not work with a Frankfurt exchange transaction

### ISSUE THREAD

**Issue by I-Valchev** [ghostfolio/ghostfolio#320]
Hi @dtslvr, just trying out Ghostfolio and at first glance I must say it looks fantastic. Very well designed and great UX. Thank you for your work and making it open source.

I have an issue (hosted version) with the stock ticker options not always showing up. Sometimes I type part of it and it gets autocompleted, sometimes it does not The issue is that when I don't select one of the options, even if the text is the same (say, APC.F), it won't let me save the transaction.

**Comment by dtslvr** [comment]
Hello @I-Valchev 

Thank you very much for your kind words and reporting this issue. It will help to improve [https://Ghostfol.io](Ghostfol.io) further.

I think I could reproduce what you are describing: If you do not select the symbol from the suggestions, the currency is currently not set internally and thus you cannot save the transaction. If the currency would be set, you see the calculated total of the transaction (next to the _Save_ button).

I will fix this in the upcoming days. If you like to give it a try, you could check this component: https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/transactions/create-or-update-transaction-dialog/create-or-update-transaction-dialog.component.ts

**Comment by dtslvr** [comment]
Hi @I-Valchev

I have merged the fix (#322) and just deployed a new version to the cloud. Can you please verify if the experience of the symbol selection has been improved for you?

I look forward to your feedback.

**Comment by I-Valchev** [comment]
Hey there, @dtslvr ! Thanks for fixing it so soon, I can confirm it is much improved now! Good that you solved it, since it would have taken me a few more days until I can dig in. Maybe for some other PR in the future ;-)

**Comment by dtslvr** [comment]
That's great to read, @I-Valchev. Thanks a lot for verifying the improved symbol selection and posting your feedback here 🙂
