### ISSUE TITLE
Allow to edit of asset profile in Admin Control panel

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3207]
As a follow up to https://github.com/ghostfolio/ghostfolio/issues/3151 it should also be possible to edit the `assetClass`, `assetSubClass` and `url` of an asset profile regardless of the data source.

If data source is `MANUAL`, data can still be stored in the `SymbolProfile` database table. For all other data sources, an entry in `SymbolProfileOverrides` needs to be created or updated.

**Comment by dtslvr** [comment]
Something for you @Fedron?

**Comment by Fedron** [comment]
I'll happy to have a go!
