### ISSUE TITLE
[Bug] Upgrading from 2.68.0 to 2.69.0 breaks on ARM

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3217]
<div type='discussions-op-text'>

<sup>Originally posted by **dragosde** March 30, 2024</sup>
Hi guys, I wonder if you can help.
It may just be me, running the ghostfolio docker on an ARM but the new (latest) image breaks something. 
My container now throws 

```
exec /tini: exec format error 
```

Reverting to 2.68.0 restores functionality 

I wonder where I should look for a solution
</div>

### Discussed in https://github.com/ghostfolio/ghostfolio/discussions/3216

**Comment by MarcoColomb0** [comment]
Same problem here on ARM
![image](https://github.com/ghostfolio/ghostfolio/assets/127960315/da349086-5254-4fa5-b733-b473f447d862)

**Comment by Shub3am** [comment]
I suspect Non Matching Architecture Package for Tini Package

https://github.com/krallin/tini/releases -- we should be using arm, but as previous ver containers were working with this, I am thinking of specific arm versions which are throwing this issue
