### ISSUE TITLE
Add to close user account

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3244]
A user should be able to close their account.

<img width="1190" alt="close-account" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/2e2c2222-1a7c-4e97-b4f9-4c9891308c22">

### Tasks

- [ ] Add new endpoint `DELETE api/v1/user` (without `:id`) with `accessToken: string` and validate it
- [ ] Introduce new permission `deleteOwnUser` and assign it to the `USER` role
- [ ] Extend `UserAccountSettingsComponent` by a form if permission `deleteOwnUser` is present and let the user confirm this action
```confirm($localize`Do you really want to close your account?`);```

**Comment by SirZemar** [comment]
Hello @dtslvr! I would like to work on this one.

**Comment by SirZemar** [comment]
Thanks. I have one question @dtslvr. Do we push the locales messages files in the same branch?
