### ISSUE TITLE
Allow user to activate / deactivate X-ray rule

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3247]
An X-ray rule could be irrelevant for the user and they would prefer to deactivate it.

<img width="1181" alt="rules-with-menu" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/efcf98b1-7778-4eab-8086-bb8b764e137a">

### Tasks

- [ ] Add a menu to toggle (_Activate_ / _Deactivate_) a rule
- [ ] Make a request `PUT api/v1/user/setting` with the payload:
`{ rule.[key]: { isActive: true / false } }`
e.g. `{ "rule.EmergencyFundSetup": { "isActive": true } }`
- [ ] Set `isActive` dynamically in rules based on user settings (see [AccountClusterRiskCurrentInvestment](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/models/rules/account-cluster-risk/current-investment.ts#L81))

**Comment by Sonlis** [comment]
I'll have a look at it @dtslvr
