### ISSUE TITLE
[BUG] Saving Market Data is broken as of 2.69.0 (was working in 2.68.0)

### ISSUE THREAD

**Issue by karter16** [ghostfolio/ghostfolio#3265]
**Bug Description**
Saving changes to entries in Market Data ais broken as of 2.69.0. Previously this functionality worked (2.68.0), however in 2.69.0 and up if you attempt to save any changes to existing records it appears as though the save button does nothing.

**To Reproduce**

1. Open an existing record in Market Data
2. Make a change
3. Press Save
4. Exit the record
5. Re-open the record
6. Observe that change has not been saved

**Expected behavior**

Changes that are made should be saved

**Screenshots**

**Logs**

**Environment**

- Ghostfolio Version 2.69.0
- Self-hosted
- Experimental Features enabled
- Safari
- MacOS

**Additional context**

**Comment by karter16** [comment]
Today I downgraded to 2.68.0 and confirmed that this functionality was working then, I then upgraded to 2.69.0 and confirmed that the functionality is broken as of then. This was therefore introduced in 2.69.0

**Comment by karter16** [comment]
@dtslvr I believe that this issue should be tagged with [Bug] - not sure if that's something I'm allowed to do myself?

**Comment by karter16** [comment]
This is caused by #3218. It is possible to save change successfully ONLY if the URL field is populated with a url beginning with "https". Any other scenario (including saving an existing record that has url = null) results in the behaviour described.

**Comment by Dougal66** [comment]
It seems as though this bug has been re-introduced now.

I can confirm exactly the behavior described above using the newest version.

**Environment**

- Ghostfolio Version 2.138.0
- Self-hosted
- Experimental Features enabled
- Firefox / Opera / Chromium
- Linux / Kubuntu (Client)
- Debian (Server)

**Comment by dtslvr** [comment]
Thanks for the detailed report, @Dougal66! Since this original issue is closed, please create a new bug report following our template. That way, we can track it properly and investigate further.

**Comment by Dougal66** [comment]
> Thanks for the detailed report, [@Dougal66](https://github.com/Dougal66)! Since this original issue is closed, please create a new bug report following our template. That way, we can track it properly and investigate further.

Done
