### ISSUE TITLE
[BUG] currency of my country is wrong

### ISSUE THREAD

**Issue by 9acca9** [ghostfolio/ghostfolio#3273]
HI.

I open this as a discussion but maybe is more a bug, because the currency exchange for my country is not the currency exchange that the program have.
This is the discussion https://github.com/ghostfolio/ghostfolio/discussions/3264
(i dont receive any kind of responde there (anyway just two days passed), but... i dont know, maybe this is more a BUG)

Programs say USD ARS=865

but we use in Argentina USD CCL.

I have a file with all the info of this currency exchange.
It will be nice if it is problematic get the USD CCL, leave the user upload a file with the historical data of the currency.

It will be possible to fix, and change USD ARS for the USD CCL or at least, let the user upload a file with that data?
If not, all the values are wrong.

Thanks

**EDIT:**
mmm, i keep looking and maybe what im asking is already made. This:
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/61723b10-1d32-4a5a-aac4-a63ee2b3c5b0)

it is for upload my own file?
Here?
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/33644c32-75a1-414b-8532-77747ce32845)
how must be the format. I see .csv
and also 
date and marketPrice. but i already write that in my file, and is not uploaded:
an example of my cvs file:
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/4d419cb9-2c4a-4c3a-b5c8-1270335bdd9b)

https://filebin.net/yn7pb4e637kfeeno/HistorialDaa.csv

Well, maybe im understanding wrong.
Im getting just this error when try to import:
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/1a137006-415d-491c-99e0-ae99cc94324e)

Thanks!!!!!!!!!

**Comment by dtslvr** [comment]
I don't think this is currently possible. It will probably always fallback to _Yahoo_.
You can try to import the historical data in the asset profile dialog. But not via `url`, this is for the (asset) logo.

As Ghostfolio does not make any assumption regarding currencies (e.g. `ARS`), this is not considered a bug. Anything beyond this can be discussed here: #3264

**Comment by 9acca9** [comment]
Thanks.
"You can try to import the historical data in the asset profile dialog. But not via url,"
And how i could do that?

**Comment by dtslvr** [comment]
> And how i could do that?

Pasting your csv data into the historical market data textarea (same dialog where you have entered the url).

**Comment by 9acca9** [comment]
Oh! Thanks!!!
But this is fine? (while i was looking in the github issues i remember somebody saying that it is not good "have red dots in between"... but maybe i recall bad)
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/1a0fe885-a118-4030-98ef-fda7dc45fa5c)

Of course, those red dots are the days like saturday, monday or holidays. That will be a problem?
In the other hand, i cant change the USD currency of my account:
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/69330f03-a1a4-4586-aa1a-d7d8dae78029)

i try to change for CCL in the 3 dots, but nothing change:
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/c4c1d30c-5340-4aee-a787-897df85fee3a)

This is a mistake or im doing something wrong?
Thanks!!!!!!!!!
