### ISSUE TITLE
[BUG] know issue about timezone, possible fix

### ISSUE THREAD

**Issue by nodiaque** [ghostfolio/ghostfolio#3274]
Hello,

There is a know and we'll discuss issue here when using unraid, if you don't set container to timezone utc, it won't work. I just had a similar problem with another container where PostgreSQL database contained dates that were screwed because of timezone. Using tz=utc mitigate the problem but doesn't really solved it.

We've worked on the issue at the other container and the culprid was typeorm and other stuff.

See the saga here

https://github.com/Phalcode/gamevault-backend/issues/257#issuecomment-2053808077

I think you should contact falco or check the latest commit to see what change he did and how to solve this. Solving this would stopped the problem when people doesn't use utc as timezone (like everyone not in that timezone on unraid for instance)

**Comment by dtslvr** [comment]
Thanks for the reference, @nodiaque. Can you please post your findings in the other issue (https://github.com/ghostfolio/ghostfolio/issues/2669) so that it is together? Thank you.
