### ISSUE TITLE
[BUG] Pre-commit fails by default because the script is not executable by default

### ISSUE THREAD

**Issue by Sonlis** [ghostfolio/ghostfolio#3282]
**Bug Description**

By default, pre-commit has a permission of `744`, which means users can only read the file, not execute it. When committing, this warning is shown:
```
hint: The 'git-hooks//pre-commit' hook was ignored because it's not set as executable.
```

**To Reproduce**

1. Clone the repository
2. Run `git config core.hooksPath ./git-hooks/`
3. Commit an empty commit.

**Expected behavior**

By default, the script should be executable.

**Environment**

- Ghostfolio Version 2.72.0
- Self-hosted
- MacOs

**Comment by dtslvr** [comment]
Closed via https://github.com/ghostfolio/ghostfolio/pull/3283.
