### ISSUE TITLE
[BUG] Cant change Currency Account neither Base currency

### ISSUE THREAD

**Issue by 9acca9** [ghostfolio/ghostfolio#3289]
Hi.
I reinstall everything just in case something was wrong.
But i cant change the currency from a Account just created.
I mean, a new install, i went to add currency, add my currency... 
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/f3367178-7b33-463d-93b6-afc1b114a6ad)

![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/375a9eda-df4e-47f0-9f50-047dc981a66f)

**edit: something weird is that, as you see i create "CCL" but when i put "edit" the name is USDCCL. 
I try then instead of create "ccl" create "USDCCL"... but, dont leave me create that.... i dont get it.**
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/69761873-93f3-452d-a252-0a328ccf663f)

after that, i went to Base currency... change USD for my new created currency... but nothing is save.
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/2f9c91ca-74ad-4409-9be5-b6890e81524f)

Also i try to change the account currency... and also dont save anything:
![imagen](https://github.com/ghostfolio/ghostfolio/assets/25393371/ef30641f-3c67-4f96-831b-807368797cb3)

**Comment by gstr3745** [comment]
Hi @9acca9 , which version of Ghostfolio are you running?
Could you provide logs of your container? (I'm assuming it's self hosted)

I'm afraid I wouldn't be able to help you, but this kind of informations would be precious for someone who could :)
I'm not experiencing this behavior on 2.73.0

**Comment by dtslvr** [comment]
> Also i try to change the account currency... and also dont save anything:
> ![imagen](https://private-user-images.githubusercontent.com/25393371/323341941-ef30641f-3c67-4f96-831b-807368797cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTM1NzAsIm5iZiI6MTcxMzU1MzI3MCwicGF0aCI6Ii8yNTM5MzM3MS8zMjMzNDE5NDEtZWYzMDY0MWYtM2M2Ny00Zjk2LTgzMWItODA3MzY4Nzk3Y2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE5MDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOGMzYzFhMjJhODg1ZTg0MDA5ZmY5YjNhMDFmZTBjOThlN2YwOWQ3NWY2NWQyNTYxOTYxNmFiNGZkMDlhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cvb4j3_nEpiYRdDrl991tJ-P6HYwdEIu-OktWlL2lKg)

As `CCL` is not part of [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), the currency field is marked as invalid. As discussed in _Slack_ it does not seem to be possible at the moment. You can discuss all further details [here](https://github.com/ghostfolio/ghostfolio/discussions/3264).
