### ISSUE TITLE
[BUG] Strange data spike/drop

### ISSUE THREAD

**Issue by brhahlen** [ghostfolio/ghostfolio#3293]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

Addition of dividends adds a weird spike to the portfolio overview (not noticed in the example data) and a drop in the Account overview.

**To Reproduce**

1. Import the attached json
2. Look at the Account

**Expected behavior**

Don't see the drop

**Screenshots**

See the drop at 27-03:
![image](https://github.com/ghostfolio/ghostfolio/assets/1798663/7c001f58-34cd-471d-9cc5-68610adfb197)

**Logs**

**Environment**

- Ghostfolio Version 2.73.0
- Self-hosted
- Experimental Features disabled
- Firefox

**Additional context**

[ghostfolio-export-202404181124.json](https://github.com/ghostfolio/ghostfolio/files/15022860/ghostfolio-export-202404181124.json)

**Comment by brhahlen** [comment]
[ghostfolio-export-202404181356.json](https://github.com/ghostfolio/ghostfolio/files/15024450/ghostfolio-export-202404181356.json)

Hi @dtslvr 
Please see the attached

**Comment by PW999** [comment]
I just updated from 2.59.0 (self-hosted) to 2.73.0 and I have the same drops, though they are all today and not the date of the last dividend

E.g.
![image](https://github.com/ghostfolio/ghostfolio/assets/8831154/50a6cdb1-5f03-469f-a140-df9c9015c3a6)
Which is the same value as the last dividend
![image](https://github.com/ghostfolio/ghostfolio/assets/8831154/d7c0f6cb-1ae6-4fd0-853d-27de07dba23a)

**Comment by dtslvr** [comment]
> I have the same drops, though they are all today

I'm not sure if this is related.

>Which is the same value as the last dividend

It looks more like `0` than `1.45`, does it?

**Comment by PW999** [comment]
> > I have the same drops, though they are all today
> 
> I'm not sure if this is related.
> 
> >Which is the same value as the last dividend
> 
> It looks more like `0` than `1.45`, does it?

At the top of the screenshot it says €5,8 which also happens to be the total dividend value.

**Comment by dtslvr** [comment]
> At the top of the screenshot it says €5,8 which also happens to be the total dividend value.

Ok, I see. Would you please create a bug report that includes a minimal export file to reproduce this scenario? Thank you.

**Comment by PW999** [comment]
I've upgrade to 2.75.1 and that seems to have fixed the problem too 
![image](https://github.com/ghostfolio/ghostfolio/assets/8831154/be157b3c-b6b5-4f2d-9141-d97a9e1805b1)
