### ISSUE TITLE
Adopt validation with DTO for various forms

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3294]
Adopt concept of form validation with DTO for the access, asset profile, tag and platform management.

_Originally posted by @dtslvr in https://github.com/ghostfolio/ghostfolio/pull/3230#pullrequestreview-1999699948_

**Comment by Fedron** [comment]
@dtslvr I've created a PR for almost all the forms you mentioned with the exception of the account balance.

Looks like to me that the account balance form doesn't currently use a DTO, should this be refactored to use a DTO?

https://github.com/ghostfolio/ghostfolio/blob/b692b7432cd516f65cd15222a919f86f6a583e88/apps/client/src/app/components/account-detail-dialog/account-detail-dialog.component.ts

https://github.com/ghostfolio/ghostfolio/blob/b692b7432cd516f65cd15222a919f86f6a583e88/libs/ui/src/lib/account-balances/account-balances.component.ts

**Comment by dtslvr** [comment]
> Looks like to me that the account balance form doesn't currently use a DTO, should this be refactored to use a DTO?

Yes, that would make sense. Could you do it in a separate PR to keep it clear?
