### ISSUE TITLE
[BUG] Incorrect prices

### ISSUE THREAD

**Issue by ms32035** [ghostfolio/ghostfolio#3297]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

Don't know exactly the circumstances, but many APIs and screens return the price from the last transaction instead of the market price. Take an example below, the price is taken from dividend amount, which results in a completely incorrect value. This only started to happen recently, around 2.71 or 2.72. See the attached screenshot. Current price for PFE is around $25 no $0.42

**Expected behavior**

Correct latest price used for asset valuation

**Screenshots**

![gfolio](https://github.com/ghostfolio/ghostfolio/assets/5060473/46c8863e-c2ce-4798-86e7-5577d8d42b95)

**Environment**

- Ghostfolio Version 2.73
- Self-hosted
- Experimental Features enabled

**Comment by dtslvr** [comment]
Hi @ms32035

Thank you for the report. Can you please attach a minimal export file to reproduce this scenario?

**Comment by ms32035** [comment]
@dtslvr looks like in the latest version this is now ok. Don't know though what the issue was and which change fixed it.
