### ISSUE TITLE
[BUG] CLP Currency for Alphabet

### ISSUE THREAD

**Issue by ManfredWisniewski** [ghostfolio/ghostfolio#3334]
**Bug Description**
Whenever I try to add Alphabet stock (US02079K3059) ghostfolio always uses a strange "CLP" currency instead of the EUR that I selected. 
**To Reproduce**

1. Add Activity, type: Buy
2. Select Account
3. Select via ISIN: US02079K3059 (ghostfolio pre-selects CLP at this point)
4. Choose Date
5. Enter Quantity
6. Change Currency to EURO
7. Enter Unit Price
8. Enter Fee (0)
9. Save

**Expected behavior**
Instead of CLP the Currency should be what I selected - EUR

**Screenshots**

**Logs**

```
https://query2.finance.yahoo.com/v7/finance/download/GOOGLCL.SN?interval=1d&events=history&includeAdjustedClose=true&period1=1714089600&period2=1714176000
[Nest] 108  - 04/26/2024, 9:04:51 AM   ERROR [DataProviderService] Error: Could not get historical market data for GOOGLCL.SN (YAHOO) from 2024-04-26 to 2024-04-27: [HTTPError] Not Found
[Nest] 108  - 04/26/2024, 9:04:51 AM   ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Error: Could not get historical market data for GOOGLCL.SN (YAHOO) from 2024-04-26 to 2024-04-27: [HTTPError] Not Found
[Nest] 108  - 04/26/2024, 9:09:04 AM     LOG [DataGatheringProcessor (GATHER_ASSET_PROFILE)] Asset profile data gathering has been started for GOOGLCL.SN (YAHOO)
[Nest] 108  - 04/26/2024, 9:09:04 AM     LOG [DataGatheringProcessor (GATHER_ASSET_PROFILE)] Asset profile data gathering has been completed for GOOGLCL.SN (YAHOO)

```
**Environment**

- Ghostfolio Version 2.76.0
- Self-Hosted via Docker
- Experimental Features disabled
- Browser Chrome
- OS Windows 10

**Additional context**
Adding this google stock crashed the docker container once. I will give up on it for now.
I have not experienced the problem with any other stocks so far.

**Comment by dtslvr** [comment]
Hi @ManfredWisniewski

The scenario you are describing is related to https://github.com/ghostfolio/ghostfolio/issues/3320. Until this has been implemented, I recommend using a ticker that is already listed in `EUR` (e.g. [ABEA.DE](https://finance.yahoo.com/quote/ABEA.DE)).

**Comment by ManfredWisniewski** [comment]
Hi @dtslvr 
Thank you for the info! That is fine.
Can you give me a quick hint on how to do that?
Can I change the ticker that ghostfolio uses in general?
The only thing I could find is the "url" setting in Market Data - but that just seems to be a general URL not an API target.

Thanks!

**Comment by dtslvr** [comment]
Create a new activity and search for `ABEA.DE` (_Name, symbol or ISIN_).

**Comment by ManfredWisniewski** [comment]
Oh - I thought `ABEA.DE` was the domain of a tracker. :D
So if I go and find matching german trackers for my stock I won't have the currency problem anymore.
Sadly my bank(s) give me all kind of trackers - but I will see what I can find.

Thanks!

**Comment by ManfredWisniewski** [comment]
@dtslvr Is it possible to find EUR trackers for all stocks? I have some other stocks that I can't find trackers in EUR for them at yahoo or by just googling. Examples
iShares MSCI Poland ETF (EPOL)
Bank of America Corporation (BAC)

Even if I find the stock - BAC for instance - at Frankfurt it is listed in USD there:
https://www.boerse-frankfurt.de/equity/bank-of-america-corp

**Comment by dtslvr** [comment]
> Is it possible to find EUR trackers for all stocks?

Unfortunately not.

**Comment by ManfredWisniewski** [comment]
Thanks for your help! Just for reference in case someone else has this problem:
I have been able to find EUR trackers for most of the important stocks and for the other ones I have been able to manually calculate the exchange rate for the other ones here: https://www.xe.com/currencytables/?from=EUR

It's not the most comfortable way - but should only be necessary for activities that are quiet a while back. So once you start adding any new activities this is not a problem
