### ISSUE TITLE
Setup chartjs-plugin-datalabels

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#335]
Setup [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels) and use it in `PortfolioProportionChartComponent` with `alignment`: `end`.

Probably this only works on desktop, therefore pass the `deviceType` as an input to `PortfolioProportionChartComponent` (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/position/position.component.ts#L25) for an example).

![doughnut-with-labels](https://user-images.githubusercontent.com/4159106/132065626-bbd67752-dcfb-440a-a2d0-3480e02d1901.png)

Demo: https://chartjs-plugin-datalabels.netlify.app/samples/advanced/multiple-labels.html

**Comment by dtslvr** [comment]
@I-Valchev are you interested in implementing this improvement?

**Comment by I-Valchev** [comment]
@dtslvr yes, please assign it 👍

**Comment by I-Valchev** [comment]
Here's a great example too: https://peerberry.com/peerberry-statistics/

**Comment by dtslvr** [comment]
> Here's a great example too: https://peerberry.com/peerberry-statistics/

Interesting ideas and it looks like it is also based on [Chart.js](https://www.chartjs.org). Thanks for sharing!

**Comment by dtslvr** [comment]
Closed via #337 and #353.
