### ISSUE TITLE
Please revert the change in v. 2.79.0 "Moved the holdings table to the holdings tab of the home page"

### ISSUE THREAD

**Issue by myllo** [ghostfolio/ghostfolio#3375]
One could see how any individual stock or fund was performing both in monetary terms and in percentage at a glance in Oveview/Holding before version 2.79.0. Now this page/functionality has been removed. 

For me this was the most used page in Ghostfolio, actually the reason I use Ghostfolio. 
Please bring this page back.

**Comment by karter16** [comment]
Perhaps your need could be met by simply adding the "Change" value as a column in the holdings table.

**Comment by dtslvr** [comment]
Thank you for the feedback, @myllo!

> Perhaps your need could be met by simply adding the "Change" value as a column in the holdings table.

Yes, I have the same proposal, hope that works.

**Comment by myllo** [comment]
Depending on implementation, most likely this would do it.

How I have been using the page is to check for weak performers to get rid
of (using various data ranges by changing the settings).

su 5. toukok. 2024 klo 10.12 karter16 ***@***.***) kirjoitti:
