### ISSUE TITLE
Problem on exchange rate USD to GBP

### ISSUE THREAD

**Issue by zaromarco** [ghostfolio/ghostfolio#3379]
Hi , i'm using the latest version of ghostofolio hosted and i don't know why but after inserting all activity i have found this strange situation for the exchange rate:
![immagine](https://github.com/ghostfolio/ghostfolio/assets/13431840/8ac135f2-4f83-43cf-a8c5-4d401137aacd)
as you can see , marked in yellow there is a wrong exchange rate for USD to GBP , the correct one is the one above.
this problem cause in overview for top earning investment a wrong representation

**Comment by dtslvr** [comment]
Hi @zaromarco

I don't see any issue in the screenshot. Please note: `GBP` and `GBp` are not the same. `GBp` stands for "pence" and is used to represent smaller denominations of the British Pound. One pound is made up of 100 pence, so 1 `GBP` is equal to 100 `GBp`.

**Comment by zaromarco** [comment]
ok understood , i found where is the problem: when i reopen the activity on this etf i saw that there are no more selected GBP but Gbp , if i try to select again GBP it thrown an error that say it cannot get the exchange rate for april 8th 2024...i don't know why , so i adjusted the value in GBp.
another question: why some etf bought in EUR when added in activity automatically change the base currency to USD or GBP ?
and if i try to change it to EUR when i come back i get again USD or GBP...in this way i need to find the exchange rate for that particular date and made a conversion

**Comment by dtslvr** [comment]
> i found where is the problem

Great!

Your second questions seems to be related to this issue: https://github.com/ghostfolio/ghostfolio/issues/3320

I will close this ticket now for the sake of clarity.
