### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GerardPolloRebozado** [ghostfolio/ghostfolio#3387]
**Bug Description**
The page  overview -> holding page and portfolio -> analisys are very slow to load I suppose its because of the error of exchange rate. Other pages like overview or activities load pretty fast

**To Reproduce**

1.Add activities that use currencies that are not USD like EUR or GBp
2. Go to overview -> holdings page

**Expected behavior**

It should not take that long to load

**Logs**

I have a lot of logs that go from 2024 to 2022 trying to get exchange rate for diferent currencies

ghostfolio  | [Nest] 209  - 05/08/2024, 10:15:58 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for GBpEUR at 2024-01-02. Please complement market data for USDGBp and USDEUR.
ghostfolio  | [Nest] 209  - 05/08/2024, 10:15:58 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for GBpEUR at 2024-01-03. Please complement market data for USDGBp and USDEUR.
ghostfolio  | [Nest] 209  - 05/08/2024, 10:15:58 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for GBpEUR at 2024-01-04. Please complement market data for USDGBp and USDEUR.
ghostfolio  | [Nest] 209  - 05/08/2024, 10:15:58 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for GBpEUR at 2024-01-05. Please complement market data for USDGBp and USDEUR.
ghostfolio  | [Nest] 209  - 05/08/2024, 10:15:58 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for GBpEUR at 2024-01-06. Please complement market data for USDGBp and USDEUR.
ghostfolio  | [Nest] 209  - 05/08/2024, 10:15:58 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for GBpEUR at 2024-01-07. Please complement market data for USDGBp and USDEUR.
ghostfolio  | [Nest] 209  - 05/08/2024, 10:15:58 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for GBpEUR at 2024-01-08. Please complement market data for USDGBp and USDEUR.
**Environment**

- Ghostfolio Version: 2.80.0
- Self-hosted
- Experimental Features enabled
- Browser: Google Chrome | 124.0.6367.119 (Build oficial) (64 bits) (cohort: Control)

**Comment by dtslvr** [comment]
I wouldn't consider that a bug. Why not resolve the root cause? Please check _How do I resolve No exchange rate has been found errors?_ for further instructions in the [FAQ](https://ghostfol.io/en/faq/self-hosting) section.
