### ISSUE TITLE
Extend DELETE /api/v1/order by filters

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3390]
Add support for filters (`@Query`) to the `DELETE /api/v1/order` [endpoint](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/order.controller.ts#L56):

- `filterByAccounts`
- `filterByAssetClasses`
- `filterByTags`

Example: https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/order.controller.ts#L87

**Comment by GerardPolloRebozado** [comment]
I can work in that

**Comment by GerardPolloRebozado** [comment]
Just made a PR: #3394
