### ISSUE TITLE
[BUG] can u tell if we have video channel for all features?

### ISSUE THREAD

**Issue by johnfelipe** [ghostfolio/ghostfolio#3408]
Pls share link or community or forum for review all new features.

**Comment by dtslvr** [comment]
Hi @johnfelipe

Thank you for your input. We focus on bug reports here.

If you are interested in creating a video, feel free to share it in the Ghostfolio [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) channel or on [X](https://twitter.com/ghostfolio_). Thank you for your cooperation.
