### ISSUE TITLE
[BUG] [HomeAssistant] Problem to display perfomance  assets value / Timezone problems

### ISSUE THREAD

**Issue by evertonbtm** [ghostfolio/ghostfolio#3616]
**Bug Description**

I'm using homeassistant version add-on , but  all analysis,performance  calculated shows zero values.

**To Reproduce**

Debugging application i identify problem on data retrieve on marketSymbols hash map when end date +1 are used to retrieved prices and no data returned sample:

ghostfolio/apps/api/src/app/portfolio/calculator/twr/portfolio-calculator.ts

line 256

```
const unitPriceAtEndDate =
      marketSymbolMap[format(end, DATE_FORMAT)]?.[symbol];
```

at this point 'end' are  currentdate + 1, sample:  today is 27 Jul,   end = 28 Jul ,   nothing retrieved this date not exists on hashmap marketSymbolMap. 

line 259

```
    if (
      !unitPriceAtEndDate ||
      (!unitPriceAtStartDate && isBefore(dateOfFirstTransaction, start))
    )
```

when 'IF' tried to verify unitPriceAtEndDate this are 'undefined' and   all perfomance using this value are displayed 'zero'

i do a trick using:

```
   end = new Date(end);
   end.setDate(end.getDate() - 1); // 1 day back works , sample:   new Date() = 27 Jul    end = 28 Jul
```

 and performance showed normally on all screen,  but i don't know if a date problem or a  orders/market data problem.

**Expected behavior**

Are expected all calculated performance displayed correctly

**Screenshots**

![image](https://github.com/user-attachments/assets/b2cf1f39-757d-4366-b6a6-2780857d6a6f)
![image](https://github.com/user-attachments/assets/f0afd6d9-bd23-4f0c-b1dd-1e6214c99eab)

**Logs**

Nothing

**Environment**

- Ghostfolio Version 2.97.0
- Self-hosted
- Experimental Features disabled
- HomeAssistand Addon - https://github.com/lildude/ha-addon-ghostfolio/
- Raspberry Pi 4

     

Additional context

currency BRL
Brazil stocks market

**Comment by dtslvr** [comment]
Could it be related to a timezone setting in your environment? (https://github.com/ghostfolio/ghostfolio/issues/2669)

**Comment by evertonbtm** [comment]
I've tried other country locales but nothing changes, i'll be check this issue #2669

**Comment by dtslvr** [comment]
> Developer solved issue on this topic: https://github.com/lildude/ha-addon-ghostfolio/issues/66#issuecomment-2256222945

Great, @lildude! 👍🏻

Can we close this issue, @evertonbtm?

**Comment by evertonbtm** [comment]
Yes! Thank you!
