### ISSUE TITLE
[BUG] Set as a pre-release should not use "latest" tag for docker image

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3619]
**Bug Description**

When I _Draft a new release_ here on _GitHub_ and select _Set as a pre-release_ the image published on _Docker Hub_ gets the following tags:

* `latest`
* `2`
* `2.99.0`

**Expected behavior**

Pre-release should not set tags like `latest` or `2`.

**Comment by tdenny** [comment]
Looks like the easiest way would be to adopt prerelease tags, eg. `2.101.0-alpha`.

The `docker/metadata-action` has [some logic to detect such a prerelease tag](https://github.com/docker/metadata-action/blob/v4.6.0/src/meta.ts#L159) and will skip the `latest` tag as well ignoring supplied tag patterns. It just tags with the `{{version}}` pattern.

If you prefer not to change your release strategy, we could add a job step to check if the associated release is a prerelease and toggle the [flavor input](https://github.com/docker/metadata-action/tree/v4.6.0?tab=readme-ov-file#flavor-input) accordingly.

**Comment by dtslvr** [comment]
I currently trigger a build which is pushed to _Docker Hub_ via _GitHub_ GUI. It is quite convenient . Do you know what to change @tdenny?

**Comment by tdenny** [comment]
Option 1 just change the titles of your prereleases to comply with [the standard](https://semver.org/#spec-item-9). I don't think that will require any code changes. The current Actions workflow will handle the prerelease the way you described.

Option 2 we'll add a job in the workflow definition to check if the tag is attached to a prerelease with the GitHub CLI. I can submit a PR if you like.

**Comment by dtslvr** [comment]
Okay, I will try _Option 1_ next time.

**Comment by dtslvr** [comment]
I have successfully tested it @tdenny! 😎

<img width="1705" alt="docker-hub-alpha" src="https://github.com/user-attachments/assets/2cfe912e-64f2-4585-bb4b-6f89168bb8ea">

https://hub.docker.com/r/ghostfolio/ghostfolio/tags
