### ISSUE TITLE
Invalid value provided when importing market values manually

### ISSUE THREAD

**Issue by hamperfait** [ghostfolio/ghostfolio#3626]
**Bug Description**

I have been trying to import stock data manually for some markets. I have the right format, but in the end, when trying to import the data, the logs say ```"Argument `marketPrice`: Invalid value provided. Expected Float, provided String.```

**To Reproduce**

1. Prepare any historical data in the required format `date;marketPrice` 
2. Add market data in the historical data tab available
3. Click import

**Expected behavior**

The market data is imported into the application.

**Screenshots**

![image](https://github.com/user-attachments/assets/ffc5a7e1-1b65-4c30-a661-b92cb3345a3f)
I have also tried changing the value from `12,3` to `12.3` and that didn't work either, didn't want to bloat with all the screenshots

**Logs**

```
ghostfolio-1  | Argument `marketPrice`: Invalid value provided. Expected Float, provided String.
ghostfolio-1  | PrismaClientValidationError: 
ghostfolio-1  | Invalid `prisma.marketData.upsert()` invocation:
ghostfolio-1  | 
ghostfolio-1  | {
ghostfolio-1  |   create: {
ghostfolio-1  |     dataSource: "YAHOO",
ghostfolio-1  |     date: new Date("2019-01-01T23:00:00.000Z"),
ghostfolio-1  |     marketPrice: "27,81",
ghostfolio-1  |                  ~~~~~~~
ghostfolio-1  |     state: "CLOSE",
ghostfolio-1  |     symbol: "0P00000RNC"
ghostfolio-1  |   },
ghostfolio-1  |   update: {
ghostfolio-1  |     marketPrice: "27,81",
ghostfolio-1  |     state: "CLOSE"
ghostfolio-1  |   },
ghostfolio-1  |   where: {
ghostfolio-1  |     dataSource_date_symbol: {
ghostfolio-1  |       dataSource: "YAHOO",
ghostfolio-1  |       date: new Date("2019-01-01T23:00:00.000Z"),
ghostfolio-1  |       symbol: "0P00000RNC"
ghostfolio-1  |     }
ghostfolio-1  |   }
ghostfolio-1  | }
ghostfolio-1  | 
ghostfolio-1  | Argument `marketPrice`: Invalid value provided. Expected Float, provided String.
ghostfolio-1  |     at An (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:114:7526)
ghostfolio-1  |     at _n.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:121:7392)
ghostfolio-1  |     at _n.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:121:7057)
ghostfolio-1  |     at _n.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:121:6741)
ghostfolio-1  |     at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:130:9355)
```

**Environment**

- Ghostfolio Version 2.99.0
- Self hosted
- Experimental Features disabled
- Microsoft Edge
- Windows 11

**Additional context**

**Comment by dtslvr** [comment]
Hi @hamperfait

Thanks for sharing your issue.

> I have also tried changing the value from 12,3 to 12.3 and that didn't work either, didn't want to bloat with all the screenshots

Since you have tried changing the value from `12,3` to `12.3` and it still didn't work, would you mind providing the logs when you import `12.3`? This will help us understand what might be going wrong. Looking forward to your response!

**Comment by hamperfait** [comment]
Somehow I managed to make it work, probably some problem on my end or using a weirdly encoded character... Closing the issue, but thanks for the assistance
