### ISSUE TITLE
[Feature] Execute scraper configuration instantly

### ISSUE THREAD

**Issue by Krabtus** [ghostfolio/ghostfolio#3645]
**Bug description**

When manually adding an asset in Ghostfolio under Admin Control > Marketing Data, the current market price from the current day is not kept permanently updated, but only updated once a night, even though the scraper is configured.

1. Navigate to **Admin Control > Marketing Data**.
2. Manually add an asset, for example BTC-EUR.
3. Configure the scraper as follows:
`{"selector":"$.chart.result[0].meta.regularMarketPrice","url":"https://query1.finance.yahoo.com/v8/finance/chart/BTC-EUR"
}`
4. Observe that the market price is only updated once a night.

**Expected behavior**

The market price should be continuously updated to reflect the current price of the asset during the day, not just once a night.

 **Environment**

Ghostfolio Version: 2.101.0
Cloud or Self-hosted: Self-hosted

**Additional Context**

Is there a way to adjust the update frequency so that prices are updated more frequently? Do I need to make additional settings or adjust certain scripts to enable continuous updating?

**Comment by dtslvr** [comment]
Hi @Krabtus

Thank you for your suggestion! Introducing a `mode?: 'instant' | 'lazy';` on this [configuration](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/interfaces/scraper-configuration.interface.ts) would add flexibility to our scraper. If you are interested in working on this issue, we would greatly appreciate your contribution.

Feel free to submit a pull request. If you have any questions or need further guidance, don't hesitate to ask.

**Comment by Krabtus** [comment]
Hello @dtslvr 

Thank you for the offer. Unfortunately, I don't have the programming knowledge to be able to provide valuable support. But perhaps there is someone out there who can help.

**Comment by shaun-ak** [comment]
Hi @dtslvr , I was looking into this, can you please help me in identifying where in the code, the scrapper configuration is being executed once a night ?

I can see if we hit the 'Test' button , a scrape function is being called in manualservice.

**Comment by dtslvr** [comment]
> can you please help me in identifying where in the code, the scrapper configuration is being executed once a night ?

It is executed [every hour](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/cron.service.ts#L31) and skips once the historical data has been gathered.

However, the relevant part is in [getQuotes()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-provider/manual/manual.service.ts#L140) of the `ManualService`. Currently, `marketData` from the database is returned. Depending on the scraper configuration (`mode: instant`), it should scrape the current market price (cf. [getHistorical()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-provider/manual/manual.service.ts#L78C16-L78C29)).

**Comment by shaun-ak** [comment]
@dtslvr should there be a checkbox below scraper configuration input field to mark it as instant config?

**Comment by dtslvr** [comment]
@shaun-ak The configuration is currently a json with a single textarea. I would concentrate on the logic in this issue. We could create a dedicated form for all these parameters in a follow-up task. Okay?

**Comment by shaun-ak** [comment]
@dtslvr raised a PR [feature/execute scraper instantly 🚀 #3723](https://github.com/ghostfolio/ghostfolio/pull/3723).
