### ISSUE TITLE
[BUG] Can't use >= 2.102.0, due to permission issues with userns-remap

### ISSUE THREAD

**Issue by dittodhole** [ghostfolio/ghostfolio#3650]
**Bug Description**

I am hosting ghostfolio on docker [with user-namespaces enabled](https://docs.docker.com/engine/security/userns-remap/). Updating to 2.102.0 gives me the following error:

> ghostfolio-1  | npm notice
> ghostfolio-1  | npm notice New patch version of npm available! 10.8.1 -> 10.8.2
> ghostfolio-1  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
> ghostfolio-1  | npm notice To update run: npm install -g npm@10.8.2
> ghostfolio-1  | npm notice
> ghostfolio-1  | + echo Running database migrations
> ghostfolio-1  | + npx prisma migrate deploy
> ghostfolio-1  | Running database migrations
> ghostfolio-1  | Error: Can't write to /ghostfolio/apps/api/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.

When adding `userns_mode: host` to `compose.yml` I get another error:

> ghostfolio-1  | + echo Running database migrations
> ghostfolio-1  | + npx prisma migrate deploy
> ghostfolio-1  | Running database migrations
> ghostfolio-1  | Prisma schema loaded from prisma/schema.prisma
> ghostfolio-1  | Datasource "db": PostgreSQL database "ghostfolio", schema "public" at "postgres:5432"
> ghostfolio-1  | 
> ghostfolio-1  | Error: Schema engine exited. Error: Could not find schema-engine binary. Searched in:
> ghostfolio-1  | - /ghostfolio/apps/api/node_modules/@prisma/engines/schema-engine-linux-arm64-openssl-3.0.x
> ghostfolio-1  | - /ghostfolio/apps/api/node_modules/prisma/schema-engine-linux-arm64-openssl-3.0.x
> ghostfolio-1  | - /ghostfolio/apps/api/node_modules/schema-engine-linux-arm64-openssl-3.0.x
> ghostfolio-1  | - /ghostfolio/apps/api/node_modules/prisma/runtime/schema-engine-linux-arm64-openssl-3.0.x

Is that due to `read_only: true` (as suggested in https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.yml#L5)?

If there's any more information needed, please let me know (hopefully I've covered everything :thinking:)

**To Reproduce**

/etc/docker/daemon.json 

```
{
  "userns-remap": "default"
}
```

compose.yml

```
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    init: true
    read_only: true
    depends_on:
      <...>
    environment:
      <...>
```

**Expected behavior**

Running >= 2.102.0 with userns-remap should work

**Logs**

See above

**Environment**

- Ghostfolio Version 2.102.0
- Self-hosted
- Experimental Features enabled

```
$ hostnamectl
 Static hostname: <hostname>
       Icon name: computer
      Machine ID: <machineid>
         Boot ID: <bootid>
Operating System: Armbian 24.5.5 bookworm         
          Kernel: Linux 6.1.75-vendor-rk35xx
    Architecture: arm64
```

```
$ cat /proc/version
Linux version 6.1.75-vendor-rk35xx (armbian@next) (aarch64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #1 SMP Fri Jul 19 14:49:03 UTC 2024
```

**Comment by dtslvr** [comment]
Seems to be related to https://github.com/ghostfolio/ghostfolio/pull/3614. Any idea @rare-magma?

**Comment by rare-magma** [comment]
@dittodhole does the first problem still occur if you remove read_only from docker-compose? Prisma seems to error out because it can't write to the filesystem.

the second error is different, it seems that prisma can access the filesystem (due to the correct user namespace mapping) but can't find the engine for your architecture (Armbian)
