### ISSUE TITLE
Support for self-hosted instances in the Android app

### ISSUE THREAD

**Issue by Krabtus** [ghostfolio/ghostfolio#3659]
**Function request**

I would like to request a feature for the Android app that allows connecting a self-hosted Ghostfolio instance. Currently there doesn't seem to be an option to enter the address of a self-hosted server.

**Expected behavior**

A setting or option in the app that allows users to provide the URL and authentication details for a self-hosted Ghostfolio instance.

**Additional context**

Adding this feature would be useful for users who host Ghostfolio on their own servers.

Ghostfolio version: 2.102.0
Ghostfolio Android version: 2.0.1.0
Self-hosted
Experimental functions deactivated
Android

**Comment by dtslvr** [comment]
Thank you for your suggestion, @Krabtus!

At the moment, we don't have plans to add support for self-hosted instances in the Android app. However, you can still enjoy the very same experience by following the instructions in our [FAQ](https://ghostfol.io/en/faq/self-hosting) to set up and use your self-hosted Ghostfolio instance on your mobile device (see _Is there a mobile app for the self-hosting version of Ghostfolio available in the app store?_).
