### ISSUE TITLE
[BUG] GfCarouselComponent is broken

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3707]
**Bug Description**

The `GfCarouselComponent` does not slide to the next slide on click as expected.

**To Reproduce**

See testimonials on the [landing page](https://ghostfol.io/en/start).

**Expected behavior**

The carousel should smoothly slide to the next slide on click.

**Environment**

- Ghostfolio Version 2.105.0
- Cloud and Self-hosted
- Browser: Google Chrome (128.0.6613.85)

**Comment by dinirichard** [comment]
Hi @dtslvr, I would like to take this on.
