### ISSUE TITLE
Animate line chart

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#372]
Define an input property (`@Input() isAnimated: boolean`) in [GfLineChartModule](https://github.com/ghostfolio/ghostfolio/tree/main/libs/ui/src/lib/line-chart) which animates the line chart.

Resource: https://www.chartjs.org/docs/next/samples/animations/progressive-line.html

**Comment by AuthorShin** [comment]
Was about to open an issue about these lines (interactive chart to see price and values over the past days) then I found this.
Any progress?

**Comment by yksolanki9** [comment]
@dtslvr Can you assign this to me? I'd like to give it a try

**Comment by dtslvr** [comment]
> @dtslvr Can you assign this to me? I'd like to give it a try

This issue is ideal to work on in _Storybook_ (isolated component). Here are some hints @yksolanki9.

1. Run it via `yarn start:storybook`
2. Unfortunately, it currently throws some errors: `Cannot find name '$localize'`
3. Find and temporarily remove all occurrences of `$localize'` in `/libs/ui/src`
4. Run `yarn start:storybook` again
5. Open `http://localhost:4400/?path=/story/line-chart--simple` in your browser

**Comment by yksolanki9** [comment]
Thanks @dtslvr
