### ISSUE TITLE
[Feature] Setup skeleton loader for data tables

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3732]
[AdminMarketDataComponent](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/admin-market-data.html) shows a skeleton loader (`<ngx-skeleton-loader />`) while fetching data.

Adapt the same concept for the following components

* [AdminJobsComponent](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-jobs/admin-jobs.html)
* [AdminUsersComponent](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-jobs/admin-jobs.html)

**Comment by dtslvr** [comment]
@shaun-ak are you interested in working on this?

**Comment by shaun-ak** [comment]
@dtslvr , I am interested in this.

**Comment by shaun-ak** [comment]
Hey @dtslvr , raised the PR.
