### ISSUE TITLE
[Feature] Extend filters of order endpoint

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3734]
Extend the filters support of `GET api/v1/order` (see [getAllOrders()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/order.controller.ts#L98)) by

* `@Query('dataSource') filterByDataSource?: string`
* `@Query('symbol') filterBySymbol?: string`

Adapt `apiService.buildFiltersFromQueryParams()` and `orderService.getOrders()` accordingly.

**Comment by shaun-ak** [comment]
Hey @dtslvr , can I do this?
