### ISSUE TITLE
[BUG] Unable to get historical market data (YAHOO)

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3736]
**Bug Description**
There is the following error in `YahooFinanceService`:

```
ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)]
Error: Could not get historical market data for TSLA (YAHOO) from 2024-08-31 to 2024-09-07:
[HTTPError] Unauthorized
```

**To Reproduce**

Gather historical market data via _Admin Control_ panel > _Market Data_ for an asset with data source `YAHOO`.

**Expected behavior**

Gathering historical market data should succeed.

**Environment**

- Ghostfolio Version 2.106.0
- Self-hosted

**Additional context**

Switch (temporarily?) from `yahooFinance.historical()` to `yahooFinance.chart()` in [YahooFinanceService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-provider/yahoo-finance/yahoo-finance.service.ts#L111) as suggested here: https://github.com/gadicc/node-yahoo-finance2/issues/349#issuecomment-2335142620

**Comment by PrandoXMR** [comment]
Same error here, this is what the yahoo api returns: 

![afbeelding](https://github.com/user-attachments/assets/b1d0c5eb-0110-4cb8-a191-3b338a1d753d)

**Comment by shaun-ak** [comment]
Hey @dtslvr , can you give an example of an asset with data source `YAHOO`, so that I can test it in local ?

**Comment by dtslvr** [comment]
> can you give an example of an asset with data source `YAHOO`, so that I can test it in local ?

You can use `MSFT` for example. Here you can find a file to import: https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.json

**Comment by shaun-ak** [comment]
Hey @dtslvr , I made another account in my local, and now there is no admin control in the navbar.

Is there any specific condition where the 'accessAdminControl' permission is given on the creation of a new user?

**Comment by dtslvr** [comment]
> Is there any specific condition where the 'accessAdminControl' permission is given on the creation of a new user?

You could assign the role `ADMIN` to your users directly in the database.
