### ISSUE TITLE
[Feature] Extend market data endpoint by lastMarketPrice

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3739]
Extend the result of `GET api/v1/admin/market-data` by `lastMarketPrice` (e.g. filter `MarketData` table by `dataSource` / `symbol`, order by `date` and pick the first entry):

1. Extend [AdminMarketDataItem](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/interfaces/admin-market-data.interface.ts#L8) by `lastMarketPrice: number;`
2. Extend logic in two places of [AdminService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.service.ts):
   * `getMarketData()`
   * `getMarketDataForCurrencies()`

To call the endpoint, you can open _Admin Control_ panel → _Market Data_.

**Comment by verbindolai** [comment]
@dtslvr I could take a look at this? :)
