### ISSUE TITLE
[Feature] Introduce filters in account endpoint

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3747]
Introduce filters in `GET api/v1/account` (see [getAllAccounts()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/account/account.controller.ts#L87)) by adding

* `@Query('dataSource') filterByDataSource?: string`
* `@Query('symbol') filterBySymbol?: string`

Adapt the query in `portfolioService.getAccountsWithAggregations()`accordingly: filter the orders of account by `dataSource` and `symbol` ("I would like to get all accounts which include the desired orders").

For inspiration, please consult the related PR https://github.com/ghostfolio/ghostfolio/pull/3743.

**Comment by shaun-ak** [comment]
Hey @dtslvr , can I do this?
