### ISSUE TITLE
[Feature] Add "Copy to clipboard" action to access table component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3766]
Add a "Copy to clipboard" action to the `AccessTableComponent` using the `cdkCopyToClipboard` directive.
The action should be available if `type === 'PUBLIC'` and copy the value of `href`.

<img width="1231" alt="access-table-action" src="https://github.com/user-attachments/assets/fbcc8627-71da-422e-94c8-68feba768f0d">

**Comment by shaun-ak** [comment]
@dtslvr , can I take this up, please ?

**Comment by shaun-ak** [comment]
@dtslvr  How can I see this page in my local?

Are there any conditions that needs to be fulfilled for me to be able to view this page?
