### ISSUE TITLE
[Feature] Add business logic of rule settings

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3772]
Implement the missing business logic for rule settings (see _Portfolio_ > _FIRE / X-ray_)

1. Enable the customize rule action [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/rule/rule.component.html#L65) by removing `&& false`
2. Prefill provided data (`thresholdMax` and `thresholdMin`) in form of [rule settings dialog](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/rule/rule-settings-dialog/rule-settings-dialog.html). Display the form element only if needed (conditionally)
3. Persist rule settings on save (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/rule/rule.component.ts#L64) and compare with [onUpdateRule](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/rule/rule.component.ts#L70))

<img width="1009" alt="rule-settings-dialog" src="https://github.com/user-attachments/assets/4783fe70-abbe-4ffc-bae6-0bd0db18d212">

**Comment by shaun-ak** [comment]
@dtslvr can I take this?
