### ISSUE TITLE
[Feature] Integrate add currency into create asset profile dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3773]
Integrate the logic¹ of [onAddCurrency()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-overview/admin-overview.component.ts#L124) as a new option into the [create asset profile dialog](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts).

<img width="1237" alt="add-currency" src="https://github.com/user-attachments/assets/52f6cd53-4534-4577-b8c6-0d7ea0306159">

```
¹
const currencies = uniq([...this.customCurrencies, currency]);
this.putAdminSetting({ key: PROPERTY_CURRENCIES, value: currencies });
```

**Comment by madhab-chandra-sahoo** [comment]
Can you please assign me this task

**Comment by madhab-chandra-sahoo** [comment]
@dtslvr Please confirm if we need to show this current only in the Market Data section or only in the Overview section or in both sections.
