### ISSUE TITLE
[Feature] Show message if no results have been found in activity dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3779]
### Steps to reproduce

* Go to _Portfolio_ > _Activities_
* Click the + button
* Search for `asdlkfj` in the _Name, symbol or ISIN_ input field

Add a synthetic (disabled) option (`mat-option`) to the [symbol autocomplete component](https://github.com/ghostfolio/ghostfolio/tree/main/libs/ui/src/lib/symbol-autocomplete) if no results have been found with the following label:

> Oops! Could not find any assets.

**Comment by madhab-chandra-sahoo** [comment]
@dtslvr Please assign this to me

**Comment by dtslvr** [comment]
> @dtslvr Please assign this to me

Thanks for your interest, @madhab-chandra-sahoo! To give other developers a chance to participate in [Hacktoberfest 2024](https://ghostfol.io/en/blog/2024/09/hacktoberfest-2024), please focus on one issue at a time 🙂

**Comment by dw-0** [comment]
Hi @dtslvr , i would like to work on this.
Any further requirements or acceptance criteria apart from those in the initial post?

**Comment by dtslvr** [comment]
> Any further requirements or acceptance criteria apart from those in the initial post?

Maybe this: the synthetic (disabled) option (`mat-option`) should only be visible if the user has actually searched 🙂
