### ISSUE TITLE
[BUG] Despite different language setting: Ghostfolio only shows English after login

### ISSUE THREAD

**Issue by Krabtus** [ghostfolio/ghostfolio#3802]
Hi everyone,

I have hosted Ghostfolio myself and have encountered a problem with the language setting. If you have selected a different language in the settings under "My Ghostfolio" (e.g. German), the English language is still displayed as the default after logging in.

**Steps to reproduce:**
1. host Ghostfolio yourself.
2. set the language in the settings to a language other than English (e.g. German).
3. open Ghostfolio in the browser and log in.

**Expected behavior:**
The selected language (e.g. German) should be used after login.

**Actual behavior:**
After logging in, English is displayed by default, even if another language has been selected in the settings. To use the correct language, you have to manually change the "/en/" in the URL in the browser address bar (e.g. to ".../de/home").

It would be great if this problem could be fixed so that the selected language is taken into account directly after login without having to manually adjust the URL.

Many thanks for the great work to Ghostfolio!

**Comment by dtslvr** [comment]
@madhab-chandra-sahoo to test, you can start the frontend in a different language by changing the suffix e.g. from `-en` to `-de` in the `package.json` file [here](https://github.com/ghostfolio/ghostfolio/blob/main/package.json#L42).

**Comment by madhab-chandra-sahoo** [comment]
@dtslvr Thanks for the info. I will update asap.

**Comment by madhab-chandra-sahoo** [comment]
@Krabtus I'm unable to reproduce this bug locally, please find the attached video for reference

https://github.com/user-attachments/assets/c1b4eaba-724c-41c1-873c-f@dtslvr e5b84da3aa

@dtslvr

**Comment by Krabtus** [comment]
Hi @madhab-chandra-sahoo I can't open the reference video. Is your link correct?

**Comment by madhab-chandra-sahoo** [comment]
> Hi @madhab-chandra-sahoo I can't open the reference video. Is your link correct?

Please check now the updated link, sorry for the inconvenience.

**Comment by Krabtus** [comment]
In your reference video, you are going about it the wrong way by switching the page to German before logging in. Instead, click on the English 'Sign In' button on the start page. You will see that Ghostfolio continues to display everything in English. However, the user interface should appear in German if the user has previously selected the German language in their profile settings, even if they log in via the English login page.

**Comment by Krabtus** [comment]
@madhab-chandra-sahoo Were you able to reproduce the problem?

**Comment by madhab-chandra-sahoo** [comment]
@Krabtus Thanks for the information, was able to reproduce the problem. I'll work on it & will update asap.

**Comment by madhab-chandra-sahoo** [comment]
@Krabtus, can you please check the attached video for this bug? Fixed the issue, but for changing language it's loading the home page twice.

[Language change bug fix video](https://www.awesomescreenshot.com/video/31967152?key=199fa44e710bf3de4f24803427ebf3ef)

@dtslvr

**Comment by Krabtus** [comment]
Hello @madhab-chandra-sahoo , great that you were able to fix the error. Unfortunately, I can't say why the start page is loaded twice.

**Comment by dw-0** [comment]
> @madhab-chandra-sahoo to test, you can start the frontend in a different language by changing the suffix e.g. from `-en` to `-de` in the `package.json` file [here](https://github.com/ghostfolio/ghostfolio/blob/main/package.json?rgh-link-date=2024-09-24T18%3A20%3A54Z#L42).

Just out of curiosity, what is the reason to reflect the language in the URL/baseHref? Is this how working with @angular/translate works?

**Comment by dtslvr** [comment]
> Just out of curiosity, what is the reason to reflect the language in the URL/baseHref?

For SEO reasons.
