### ISSUE TITLE
[Feature] Set up tooltip in treemap chart component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3808]
The goal of this issue is to set up a tooltip in the [treemap chart component](https://github.com/ghostfolio/ghostfolio/tree/main/libs/ui/src/lib/treemap-chart) which is based on [chart.js](https://www.chartjs.org).

- Pass `[baseCurrency]="user?.settings?.baseCurrency"` to `<gf-treemap-chart />` in [home-holdings.html](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/home-holdings/home-holdings.html)
- The tooltip should display `valueInBaseCurrency` from `holdings` if available along with the user's currency (`baseCurrency`)
- Try to use [getTooltipOptions()](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/chart-helper.ts#L30) for the style

**Comment by uday-rana** [comment]
I'd like to try and work on this.

**Comment by dtslvr** [comment]
Hi @uday-rana! Any progress on the issue? Let me know if you need a hint.

**Comment by uday-rana** [comment]
Hi! Sorry for the delay. I'm working on the issue right now, I'll let you know if I need help. Thanks!

**Comment by uday-rana** [comment]
Where in the UI is this component actually rendered? I don't see a treemap chart on the Holdings page.

**Comment by uday-rana** [comment]
@dtslvr how should the tooltip be positioned? Do you want it to follow the mouse cursor?

**Comment by dtslvr** [comment]
> @dtslvr how should the tooltip be positioned? Do you want it to follow the mouse cursor?

No motion, the position should be static, somewhere in the middle (default?).
