### ISSUE TITLE
[BUG] Insert new activity just shows crytocurrency symbols

### ISSUE THREAD

**Issue by rubengr** [ghostfolio/ghostfolio#3820]
**Bug Description**

Try to insert new activity but systems just shows cryptocurrency Holdings. I have inserted before holdings like Apple, Meta Platforms, but now searching just show crypto.

**Screenshots**

![chrome_dXugmdGkEB](https://github.com/user-attachments/assets/0f9ca700-72d5-4f5b-b640-f23d3f0da74b)

**Environment**

- Ghostfolio Version 2.27.1
- Self-hosted
- Experimental Features enabled 
- Browser Chrome
- OS Windows 11 Home

**Comment by dtslvr** [comment]
> Ghostfolio Version 2.27.1

Please upgrade to the latest version and try again.

**Comment by rubengr** [comment]
How can i do that? I'm using docker containers

**Comment by rubengr** [comment]
OK, i have already updated, but know doesn't do loggin with same security token. Maybe because i don't add in .env file.

Now i can't remember the REDIS password and POSTGRES password to add to .env file, in docker is possible to get it?

Thanks
