### ISSUE TITLE
[FEATURE] Split resources page into multiple sub pages

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3830]
The goal of this issue is to split the overloaded [Resources](https://ghostfol.io/en/resources) page into [tabbed sub pages](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/about/about-page.component.ts#L20)

* `en/resources` - _Ghostfolio_
* `en/resources/guides` - _Guides_
* `en/resources/markets` - _Markets_
* `en/resources/glossary` - _Glossary_

The [About](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/pages/about) page can be used as a reference.

**Comment by madhab-chandra-sahoo** [comment]
@dtslvr I want to work on this feature, Can you please assign this to me?

**Comment by dtslvr** [comment]
> @dtslvr I want to work on this feature, Can you please assign this to me?

Thanks for your interest, @madhab-chandra-sahoo! To give other developers a chance to participate in [Hacktoberfest 2024](https://ghostfol.io/en/blog/2024/09/hacktoberfest-2024), please focus on one issue at a time 🙂

**Comment by STSonyThomas** [comment]
Hey can I work on this?

**Comment by STSonyThomas** [comment]
Hey I'm still working on this. I just need 2 more days.

**Comment by dtslvr** [comment]
Hi @STSonyThomas! Any progress on the issue? If you need any pointers, feel free to ask.

**Comment by STSonyThomas** [comment]
Hey I was stuck with Docker and was learning that. I have that right now. I am gonna get this done ASAP.

**Comment by STSonyThomas** [comment]
Hey @dtslvr I have a package-lock conflict. What should I do?

**Comment by STSonyThomas** [comment]
![image](https://github.com/user-attachments/assets/36c78c0a-8df9-4b48-b23d-950244556d2e)
This is how the page looks like

**Comment by dtslvr** [comment]
> This is how the page looks like

That looks good at first glance. Could you please create a PR and link it with this issue? Thank you.
