### ISSUE TITLE
[FEATURE] Set up @Output for click in holdings table component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3835]
Set up `@Output() holdingClicked = new EventEmitter<AssetProfileIdentifier>();` to eliminate the usage of _Router_ in [GfHoldingsTableComponent](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/holdings-table/holdings-table.component.ts).

Replace
```
this.router.navigate([], {
  queryParams: { dataSource, symbol, holdingDetailDialog: true }
});
```
with
```
this.holdingClicked.emit({ dataSource, symbol });
```

Then make use of the `holdingClicked` output in `HomeHoldingsComponent`.

**Comment by Prakhar29Sharma** [comment]
Hi @dtslvr
I'm new to open-source, and I'd love to work on this issue. Any guidance would be appreciated!
