### ISSUE TITLE
[FEATURE] Set up @Output for click in activities table component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3836]
Set up `@Output() activityClicked = new EventEmitter<AssetProfileIdentifier>();` to eliminate the usage of _Router_ in [GfActivitiesTableComponent](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/activities-table/activities-table.component.ts).

Replace
```
this.router.navigate([], {
  queryParams: { dataSource, symbol, holdingDetailDialog: true }
});
```
with
```
this.activityClicked.emit({ dataSource, symbol });
```

Then make use of the `activityClicked` output in `ActivitiesPageComponent`.

**Comment by Yordaniss** [comment]
Hello @dtslvr I could work on this. Can you please assign this issue to me?
