### ISSUE TITLE
[FEATURE] Improve handling of tags

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3839]
The handling of tags should be improved by the following changes

- [ ] Remove tags from info endpoint (`GET api/v1/info`)
- [ ] Change tags in user endpoint (`GET api/v1/user`)
  - [ ] Include all available tags (`WHERE userId is NULL or id of current user`)
  - [ ] Add a new flag `isUsed: boolean` to each tag
- [ ] Change `tagsAvailable` to tags of user endpoint in `GfHoldingDetailDialogComponent`
- [ ] Change `tagsAvailable` to tags of user endpoint in `CreateOrUpdateActivityDialog`
- [ ] Filter tags by `isUsed` in `GfAssistantComponent`

**Comment by matejgerek** [comment]
@dtslvr Hey Thomas, can I work on this one?
