### ISSUE TITLE
[FEATURE] Extract historical market data editor to @ghostfolio/ui

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3845]
The historical market data editor logic is currently present in `AssetProfileDialog`. The goal of this issue is to extract the code and create a reusable component in `@ghostfolio/ui`. The component should consist of `<gf-admin-market-data-detail />` (move to `@ghostfolio/ui`) and the historical data form.

<img width="1723" alt="historical-market-data-editor" src="https://github.com/user-attachments/assets/3450f91f-e0d1-4eab-ba4d-862be029ad0c">

### Settings

changeDetection: `ChangeDetectionStrategy.OnPush`
selector: `gf-historical-market-data-editor`
standalone: `true`

### Interface

* `@Input() currency: string`
* `@Input() dataSource: DataSource;`
* `@Input() dateOfFirstActivity: string;`
* `@Input() locale: string`
* `@Input() marketData: MarketData[];`
* `@Input() symbol: string;`

**Comment by sahil9001** [comment]
Hey @dtslvr , can I take this issue?

**Comment by dtslvr** [comment]
Hi @sahil9001! Any progress on the issue? If you need any pointers, feel free to ask.

**Comment by sahil9001** [comment]
Hey sorry, got really caught up with other issues in Hacktoberfest, I will address this one soon.

**Comment by amandee27** [comment]
Hi @dtslvr can I work on this?

**Comment by amandee27** [comment]
@dtslvr, <gf-admin-market-data-detail/> component includes the <gf-line-chart/> as well. Should we include <gf-line-chart/> in the new component as well? I'm asking because it was not highlighted in your screenshot.

**Comment by dtslvr** [comment]
> @dtslvr, component includes the as well. Should we include in the new component as well? I'm asking because it was not highlighted in your screenshot.

Hi @amandee27, it seems a word might be missing in your question. Dou you mean the chart? That should not be part of the new component.

Let me know so I can assist further 🙂

**Comment by amandee27** [comment]
> > @dtslvr, component includes the as well. Should we include in the new component as well? I'm asking because it was not highlighted in your screenshot.
> 
> Hi @amandee27, it seems a word might be missing in your question. Dou you mean the chart? That should not be part of the new component.
> 
> Let me know so I can assist further 🙂

Hi @dtslvr, For some reason, some formatted text was removed from my reply. Yes, I mean the chart. The AdminMarketDataDetailComponent also includes the chart (Line chart), but as you suggested, I'll keep the chart component out of the new component.

**Comment by dtslvr** [comment]
I have created a follow-up task: https://github.com/ghostfolio/ghostfolio/issues/4127
