### ISSUE TITLE
[FEATURE] Prepare users endpoint for pagination

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3861]
Add support for pagination (`skip`, `take`) to the [endpoint](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.controller.ts#L355): `GET api/v1/admin/user`

Reference: `GET api/v1/admin/market-data` (see [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.controller.ts#L193))

**Comment by sahilpatel342** [comment]
Hello can I work on this?

**Comment by sahilpatel342** [comment]
Just to confirm, is all I need to do is update the controller method, do I need to do any service layer implementation?

**Comment by qur786** [comment]
Hello @dtslvr I noticed this issue have been dormant. So I have created the the PR with the appropriate changes: https://github.com/ghostfolio/ghostfolio/pull/4050

I would be very happy if my contribution would be added to this project.

**Comment by dtslvr** [comment]
> Hello @dtslvr I noticed this issue have been dormant. So I have created the the PR with the appropriate changes: #4050
> 
> I would be very happy if my contribution would be added to this project.

Thank you for your contribution, @qur786! I have just assigned the ticket to you.
In the future, please share your intention first. This will help ensure the ticket is assigned and prevent others from working on the same. Thanks for your understanding.

**Comment by qur786** [comment]
> > Hello @dtslvr I noticed this issue have been dormant. So I have created the the PR with the appropriate changes: #4050
> > I would be very happy if my contribution would be added to this project.
> 
> Thank you for your contribution, @qur786! I have just assigned the ticket to you. In the future, please share your intention first. This will help ensure the ticket is assigned and prevent others from working on the same. Thanks for your understanding.

Thanks @dtslvr. I will keep in mind to share the intension first before working.
