### ISSUE TITLE
[FEATURE] Create a new rule: developedMarkets

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3870]
Set up a new rule `AllocationClusterRiskDevelopedMarkets` (`models/rules/allocation-cluster-risk/developed-markets.ts`) and register it in the [PortfolioService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.service.ts#L1169). Provide `markets` (available from [getDetails()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.service.ts#L1162)) to the constructor of the rule and evaluate that the `value` of `developedMarkets` is between `ruleSettings.thresholdMin` and `ruleSettings.thresholdMax`.

You can use the rule [FeeRatioInitialInvestment](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/models/rules/fees/fee-ratio-initial-investment.ts) as inspiration.

* Set the default value of `thresholdMax` to `0.68`
* Set the default value of `thresholdMax` to `0.72`
* Import the activities from [ok.json](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.json) for a sample portfolio
* Check the new rule via _Portfolio_ → _FIRE / X-ray_ → _X-ray_

### Inspiration

The same rule for `emergingMarkets` has been implemented here: https://github.com/ghostfolio/ghostfolio/pull/3949

**Comment by ishita-babar** [comment]
i want to work on this

**Comment by dtslvr** [comment]
Hi @ishita-babar

Any progress on the issue? Let me know if you need support.

**Comment by dtslvr** [comment]
The same rule for `emergingMarkets` has been implemented [here](https://github.com/ghostfolio/ghostfolio/pull/3949) and can be used as a reference.

**Comment by ivanskv2000** [comment]
@dtslvr hi! I used this issue as a starting point in learning the ghostfolio codebase, and implemented the changes in [this](https://github.com/ghostfolio/ghostfolio/pull/3975) PR

Sorry for hijacking the issue :) It seemed inactive though
