### ISSUE TITLE
[FEATURE] Set up recommendedTypeChecked rule in eslint configuration

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3874]
Setup `recommendedTypeChecked`.

> We could also think about adding the recommended sets of typescript-eslint (and overwrite every rule to "warn" until its fixed) before we start switching the previous rules back to error again. There might be some overlapping rules which may clean up the projects eslintrc.json once all rules are correctly in place again: 
> * https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended-type-checked.ts

_Originally posted by @dw-0 in https://github.com/ghostfolio/ghostfolio/issues/2782#issuecomment-2392182145_

**Comment by dw-0** [comment]
Feel free to assign this issue to me :)
