### ISSUE TITLE
[FEATURE] Set up stylisticTypeChecked rule in eslint configuration

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3877]
Set up `stylisticTypeChecked`.

> Add @typescript-eslint/stylistic-type-checked to the rules (https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/stylistic-type-checked.ts) via the same process: add rules -> lint -> overwrite broken rules from "error" to "warn".

_Originally posted by @dw-0 in https://github.com/ghostfolio/ghostfolio/pull/3876#issue-2568064758_

**Comment by dw-0** [comment]
@dtslvr Feel free to assign me.
I have a question to this rule: https://typescript-eslint.io/rules/naming-convention/
It is currently completely disabled. Is this intended? Should it stay disabled?

**Comment by dtslvr** [comment]
> I have a question to this rule: https://typescript-eslint.io/rules/naming-convention/
It is currently completely disabled. Is this intended? Should it stay disabled?

I guess it was not feasible or annoying, but I don't remember. You can try to reenable it.
