### ISSUE TITLE
[FEATURE] Add the TAX option to SELL activity action

### ISSUE THREAD

**Issue by fib1985** [ghostfolio/ghostfolio#3900]
Hi team,
thx for this awesome app!

I noticed that the SELL activity does not include an option to include the TAX tied to the security. For example the capital gain TAX. Now, as a workaround, you must sum the TAX with the FEE. (Actually the FEE is more like the broker commission for the trade). Doing this it calculate the perfomance correctly but won't categorize correctly the FEES and TAX. 
We should add this option, something like this:

![image](https://github.com/user-attachments/assets/ae69280b-47cf-4754-9279-da240fed483b)

![image](https://github.com/user-attachments/assets/c08f4ea3-ba73-4671-aed0-a677dac986c1)

**Comment by dtslvr** [comment]
Your idea seems to be a duplicate of https://github.com/ghostfolio/ghostfolio/discussions/2662. Please join the discussion there and use the upvote functionality, thank you.
