### ISSUE TITLE
[FEATURE] Extend tooltip in treemap chart component by name

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3904]
The goal of this issue is to extend the tooltip in the [treemap chart component](https://github.com/ghostfolio/ghostfolio/tree/main/libs/ui/src/lib/treemap-chart) by adding the `name` (or `symbol` as a fallback):
```
return [
  // `${name ?? symbol}`,
  // value or percentage as before
];
```

Get inspired by the [GfPortfolioProportionChartComponent](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts#L423).

**Comment by uday-rana** [comment]
Hi! Can I work on this?

**Comment by tushar-agarwal7** [comment]
@dtslvr  can i work on this??

**Comment by dtslvr** [comment]
> @dtslvr can i work on this??

@uday-rana was faster this time. But we still have other open issues, @tushar-agarwal7 🙂
