### ISSUE TITLE
[FEATURE] Improve background color assignment in treemap chart component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3906]
The goal of this issue is to improve the background assignment in the [treemap chart component](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/treemap-chart/treemap-chart.component.ts#L94):

* `annualizedNetPerformancePercentWithCurrencyEffect` of `0.00%` should always be in gray (round to 2 decimals) and not in a shade of green / red
* `annualizedNetPerformancePercentWithCurrencyEffect` of `-0.00%` should always be transformed to neutral (absolute value)

**Comment by madhab-chandra-sahoo** [comment]
I would like to work on this.

**Comment by nakul-py** [comment]
i want work on this issue pls assign me

**Comment by dtslvr** [comment]
> i want work on this issue pls assign me

Thanks for submitting a PR @nakul-py! Since @madhab-chandra-sahoo requested to work on this issue first, I'll keep it assigned to him. Feel free to check out other open issues for contributions!

**Comment by madhab-chandra-sahoo** [comment]
@dtslvr Please review the PR
