### ISSUE TITLE
[FEATURE] Simplify labels in treemap chart component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3911]
Instead of the current label consisting of name and symbol in the [treemap chart component](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/treemap-chart/treemap-chart.component.ts#L150), the label should only be the symbol (same size as the current name).

**Comment by tushar-agarwal7** [comment]
@dtslvr can i work on this?? plz assign me
