### ISSUE TITLE
[FEATURE] Change input to slider in rule settings dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3917]
Replace the `mat-input` components for _Threshold Min_ and _Threshold Max_ to `<mat-slider>` (see [Slider](https://material.angular.io/components/slider/overview)) in the [rule settings dialog component](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/rule/rule-settings-dialog).

<img width="1193" alt="x-ray-rule-settings-dialog" src="https://github.com/user-attachments/assets/69b07d91-17de-45e5-8f98-8144ec6d0f22">

Use the properties `min`, `max` and `step` from `data.rule.configuration` to customize the slider.

**Comment by vitalymatyushik** [comment]
good day @dtslvr!
can I work on the enhancement to be onboarded?

**Comment by nakul-py** [comment]
\assign
