### ISSUE TITLE
[FEATURE] Disable hover effect of labels in treemap chart component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3920]
The hover effect of the labels in the [treemap chart component](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/treemap-chart/treemap-chart.component.ts) should be disabled (currently it switches the font color from white to black).

**Comment by vitalymatyushik** [comment]
good day @dtslvr!
can I work on the fix?
