### ISSUE TITLE
[FEATURE] Create a new rule: emergingMarkets

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3930]
Set up a new rule `AllocationClusterRiskEmergingMarkets` (`models/rules/allocation-cluster-risk/emerging-markets.ts`) and register it in the [PortfolioService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.service.ts#L1171). Provide `markets` (available from [getDetails()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.service.ts#L1163)) to the constructor of the rule and evaluate that the `value` of `emergingMarkets` is between `ruleSettings.thresholdMin` and `ruleSettings.thresholdMax`.

You can use the rule [FeeRatioInitialInvestment](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/models/rules/fees/fee-ratio-initial-investment.ts) as inspiration.

* Set the default value of `thresholdMax` to `0.28`
* Set the default value of `thresholdMax` to `0.32`
* Create a buy activity for `TCS.NS` as a sample portfolio
* Check the new rule via _Portfolio_ → _FIRE / X-ray_ → _X-ray_

**Comment by vitalymatyushik** [comment]
good day @dtslvr!
can i take it?
