### ISSUE TITLE
[FEATURE] Improve background color assignment in treemap chart component

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3931]
Currently the background color assignment of the treemap chart component is quite static based on the `annualizedNetPerformancePercentWithCurrencyEffect` and predefined ranges: https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/treemap-chart/treemap-chart.component.ts#L114

From now on, the colors should be assigned dynamically by first determining the minimum or maximum of all `annualizedNetPerformancePercentWithCurrencyEffect` and then mapping these values to the color scale. The color scale ranges from `green[3]` to `green[9]` for positive values and `red[9]` to `red[3]` for negative values. For `0`, `gray[3]` should be used as before.

**Comment by vitalymatyushik** [comment]
hi @dtslvr !
can I take it?
