### ISSUE TITLE
[BUG] X-Axis of investment chart component does not adapt on date range change

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3932]
**Bug Description**

When you switch the date range, the chart data of _Portfolio Evolution_ and _Investment Timeline_ ([InvestmentChartComponent](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/investment-chart)) is squeezed in on the x-axis.

**To Reproduce**

1. Create a new user account via _Get started_
2. Go to _Portfolio_ → _Activities_ and import activities: [ok-vti-buy-long-history.json](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok-vti-buy-long-history.json)
3. Go to _Portfolio_ → _Analysis_ and switch the date range from _Max_ to _1 year_

**Expected behavior**

The x-axis adapts to _1 year_ (same as [Performance chart](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/benchmark-comparator))

**Screenshots**

<img width="1447" alt="portfolio-evolution-chart-bug" src="https://github.com/user-attachments/assets/806b0d22-1bb1-474b-b97d-cfa692957963">

**Environment**

- Ghostfolio Version `2.215.0`
- Cloud and Self-hosted
- Experimental Features enabled

**Comment by amandee27** [comment]
@dtslvr Can I work on this issue?
