### ISSUE TITLE
[BUG] Fix warning: export was not found

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3933]
**Bug Description**

Two warnings appear when starting the server.

**To Reproduce**

1. Set up the project locally (see [Ghostfolio Development Guide](https://github.com/ghostfolio/ghostfolio/blob/main/DEVELOPMENT.md))
2. Run `npm run watch:server`

**Expected behavior**

No warnings.

**Logs**

```
WARNING in ./src/app/portfolio/current-rate.service.ts 136:57-72
export 'GetValuesParams' (imported as 'GetValuesParams') was not found in './interfaces/get-values-params.interface' (module has no exports)

WARNING in ./src/app/portfolio/current-rate.service.ts 136:92-107
export 'GetValuesParams' (imported as 'GetValuesParams') was not found in './interfaces/get-values-params.interface' (module has no exports)
```

**Environment**

- Ghostfolio Version `2.115.0`

**Comment by 5AIPAVAN** [comment]
@dtslvr can you please assign this to me :-)

**Comment by OAtulA** [comment]
Could you please assign me this.

I can give it a shot.

**Comment by dtslvr** [comment]
Hi @OAtulA

> Could you please assign me this.

It looks like @dw-0 has already provided a potential fix for this. Please look around and find another issue to work on. Thanks.

**Comment by OAtulA** [comment]
@dtslvr Thanks for informing. Please close this issue.
