### ISSUE TITLE
[FEATURE] Extend assistant by selector for holdings

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3941]
Extend the [form](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/assistant/assistant.component.ts#L132) of the assistant component by a selector for holdings.

<img width="1192" alt="extend-assistant-by-holding" src="https://github.com/user-attachments/assets/25f760e4-6c88-4f41-808b-01e4c07f4b11">

### Implementation Details

* The selector should be similar to the one in [ImportActivitiesDialog](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/activities/import-activities-dialog/import-activities-dialog.html#L31-L60)
* Holdings can be fetched like this:
```
this.dataService
  .fetchPortfolioHoldings({
    range: 'max'
  })
  .pipe(takeUntil(this.unsubscribeSubject))
  .subscribe(({ holdings }) => {
    this.holdings = sortBy(holdings, ({ name }) => {
      return name.toLowerCase();
    });

    this.changeDetectorRef.markForCheck();
  });
```
* [onApplyFilters()](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/assistant/assistant.component.ts#L324) should emit `type: 'DATA_SOURCE'` and `type: 'SYMBOL'` for the selected holding

**Comment by tanmaytare** [comment]
i would like to work on it , assign me for this

**Comment by dtslvr** [comment]
@tanmaytare are you going to provide a PR for this issue?

**Comment by amandee27** [comment]
@dtslvr Can I work on this issue?

**Comment by dtslvr** [comment]
I have created a follow-up issue: https://github.com/ghostfolio/ghostfolio/issues/4065
