### ISSUE TITLE
[FEATURE] Extend notification service by prompt functionality

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3955]
The goal of this issue is to extend the existing [notification service](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/core/notification/notification.service.ts) by a prompt functionality similar to [prompt()](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt).

The new `GfPromptDialogComponent` (cf. [GfConfirmationDialogComponent](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/core/notification/confirmation-dialog/confirmation-dialog.component.ts)) should include a `mat-input` and support the following parameters:

* `confirmLabel?: string;` (default: `translate('OK')`)
* `defaultValue?: string;`
* `discardLabel?: string;` (default: `translate('CANCEL')`)
* `title: string;`
* `valueLabel?: string;`

Replace `prompt()` with
```
const value = await this.notificationService.prompt({
  confirmLabel: $localize`Save`,
  defaultValue: this.summary.emergencyFund?.total?.toString() ?? '0',
  title: $localize`Please enter the amount of your emergency fund.`,
  valueLabel: $localize`Emergency fund`
});
```
in [PortfolioSummaryComponent](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/portfolio-summary/portfolio-summary.component.ts#L52).

**Comment by patricksolka** [comment]
Hey @dtslvr would love to work on this issue, could you assign it to me?

**Comment by dtslvr** [comment]
Hi @patricksolka,
Any progress on the issue? Let me know if you need anything. Thanks!

**Comment by brandonw4** [comment]
Hi @dtslvr, could I be assigned? I'd be interested in implementing.

**Comment by Ayush2198-source** [comment]
Hello, is anyone currently addressing this issue? If not, I'd be happy to take a look and try to resolve it, with your permission.

**Comment by brandonw4** [comment]
@Ayush2198-source Hi I am currently working on finishing up another issue, although I do have a solution for this right now that hasn't been committed yet, I will share it if you would like to take a look.
