### ISSUE TITLE
[FEATURE] Clean up unused OnInit implementations

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3959]
1. Search the project for any occurrence of `public ngOnInit() {}`
1. Remove the `ngOnInit()` method from the file
1. Remove the `OnInit` interface from the class (usually found after `implements`)
1. Remove the `OnInit` import from the top of the file (typically something like `import { OnInit } from '@angular/core';`)

**Comment by wasif1** [comment]
Assign it to me
