### ISSUE TITLE
[BUG] ghostfolio docker compose does not start when REDIS_PASSWORD contains special characters

### ISSUE THREAD

**Issue by eeex** [ghostfolio/ghostfolio#3967]
**Bug Description**

When using the supplied docker-compose.yml, if REDIS_PASSWORD contains special characters like space or semicolon, the redis health check fails and ghostfolio never starts.

**To Reproduce**

1. set REDIS_PASSWORD to something with special characters "FOO;BAR"
2. docker compose up -d

**Console Output when wrong**

```
$ docker compose up -d
[+] Running 2/4                                                             
 ⠋ Network ghostfolio_default         Created                                                                                                      51.0s 
 ✔ Container ghostfolio-postgres-1    Healthy                                                                                                      10.9s 
 ✘ Container ghostfolio-redis-1       Error                                                                                                        50.9s 
 ⠏ Container ghostfolio-ghostfolio-1  Created                                                                                                      50.9s 
dependency failed to start: container ghostfolio-redis-1 is unhealthy

```

**Environment**

- Ghostfolio Version  2.117.0
- Self-hosted
- Experimental Features disabled
- Ubuntu 24.04

**Additional context**

Correctly quoting the health check commandline by changing the redis health check from 
`      test: ['CMD-SHELL', 'redis-cli --pass $REDIS_PASSWORD ping | grep PONG']`
to
`      test: ['CMD-SHELL', 'redis-cli --pass "$REDIS_PASSWORD" ping | grep PONG']`

fixed the issue for me.

**Comment by dtslvr** [comment]
Hi @eeex

Thanks for reporting this issue and providing a solution! Would you be open to submitting a PR?
