### ISSUE TITLE
[FEATURE] Change slider to range slider in rule settings dialog

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3972]
If _Threshold Min_ and _Threshold Max_ is defined in the [rule settings dialog component](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/rule/rule-settings-dialog) (see [AllocationClusterRiskEmergingMarkets](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/models/rules/allocation-cluster-risk/emerging-markets.ts)), show a [range slider](https://material.angular.io/components/slider/overview#selecting-a-range) instead of two (basic) sliders.

### Before

<img width="789" alt="rule-settings-before" src="https://github.com/user-attachments/assets/e9df15d3-730a-4f13-b36b-303ebd0f53ed">

### After

<img width="789" alt="rule-settings-after" src="https://github.com/user-attachments/assets/0d0663bf-da2d-4482-8f38-ddd1aa4e6a07">

**Comment by TechGeekRahul** [comment]
hey @dtslvr  I want to work on this issue. can you assign it to me?

**Comment by dtslvr** [comment]
Hi @TechGeekRahul

I noticed you’re interested in the other issue (#3995). Any updates on this one? Let me know if you need any help!

**Comment by amandee27** [comment]
Hi @dtslvr  I would like to work on this. Can please assign this to me?
