### ISSUE TITLE
[FEATURE] Move X-ray page to dedicated sub page

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3977]
The goal of this issue is to move the _X-ray_ section from the [FIRE page](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/fire/fire-page.html) to a separate [tabbed sub page](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/portfolio-page.component.ts#L31).

### Before

* `en/portfolio/fire` - _FIRE / X-ray_

### After

* `en/portfolio/x-ray` - _X-ray_
* `en/portfolio/fire` - _FIRE / X-ray_

**Comment by STSonyThomas** [comment]
Hey If my previous issue is alright could I work on this as well?

**Comment by mohanbyte** [comment]
Hi , could i work on this issue , if it's available now?

**Comment by mohanbyte** [comment]
Hi @dtslvr i could see in the required after title is FIRE/X-Ray , However i felt since we have moved from fire keeping X-ray in title would not be ideal. If we would like to keep it as required please let me know will modify accordingly.

**Comment by STSonyThomas** [comment]
Hey @dtslvr I will submit a PR in 2 days. Sorry about the delay.

**Comment by dtslvr** [comment]
> Hey @dtslvr I will submit a PR in 2 days. Sorry about the delay.

Hey @STSonyThomas
@mohanbyte has already submitted a PR for this issue. Would you be open to choosing [another one](https://github.com/ghostfolio/ghostfolio/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) to avoid overlapping efforts?

**Comment by Sony-MetaShot** [comment]
It's okayy. I'll find another issue to handle
