### ISSUE TITLE
[BUG] JSON scraper not working

### ISSUE THREAD

**Issue by calmandhandsome** [ghostfolio/ghostfolio#3997]
**Bug Description**

Before anything else, I want to thank you guys for the great project! Still learning about financial, investment, and stuff, and this project really helps me to track my portfolios!

When trying to set up scraper for manual source, I've got issues when testing the scraper using jsonpath. The error said:

```
Cannot read properties of undefined (reading 'query')
```

After some debugging, I think it's because of the jsonpath import wasn't correct on this line: https://github.com/ghostfolio/ghostfolio/blob/5de176a7ef829bc441bd7998638bb50981cd677e/apps/api/src/services/data-provider/manual/manual.service.ts#L32

Should be:

```ts
 import * as jsonpath from 'jsonpath'; 
```

Quick import fix and trying again using `docker-compose.dev.yml`  yields correct result, as seen on the screenshot.

This is my first time ever contributing to OSS project, and I'm also a beginner in terms of JS, but if the bug is confirmed and the fix is good for you guys, I can make the PR for this.

**To Reproduce**

1. Create manual market data (?).
2. Edit the scraper configuration that scrap from endpoint that returned `application/json` content-type.
3. Error happened when clicking `Test` button.

I used this scraper configuration:

```json
{
  "selector": "$.NetAssetValues[(@.length-1)].Value",
  "url": "https://pasardana.id/api/FundService/GetSnapshot?fundId=2214&snapshotTimestamp=undefined&username=anonymous"
}
```

Sample reduced response body from URL is as follows:

```json
{
  ...
  "NetAssetValues": [
    { "Date": "2023-10-27T00:00:00", "Value": 1709.2172, "DailyReturn": 0.00019000 },
    ...
    { "Date": "2024-10-28T00:00:00", "Value": 1836.5229, "DailyReturn": 0.00049000 }
  ],
  ...
}
```

**Expected behavior**

Scrapper working fine, in my example above should have got the latest NAV value from the URL response, which is `1836.5229`.

**Screenshots**

This is the not working sample on my self-hosted production env:
![Screenshot 2024-10-29 111805](https://github.com/user-attachments/assets/f8f9c321-7aa2-46c3-b21e-81ba886e9a64)

This is the working sample on my dev machine:
![image](https://github.com/user-attachments/assets/24c30647-2b31-418a-9591-85cda4ca647f)

**Logs**

```
[Nest] 121  - 10/29/2024, 11:17:32 AM   ERROR [AdminController] TypeError: Cannot read properties of undefined (reading 'query')
[Nest] 121  - 10/29/2024, 11:17:42 AM   ERROR [AdminController] TypeError: Cannot read properties of undefined (reading 'query')
[Nest] 121  - 10/29/2024, 11:17:45 AM   ERROR [AdminController] TypeError: Cannot read properties of undefined (reading 'query')
[Nest] 121  - 10/29/2024, 11:17:47 AM   ERROR [AdminController] TypeError: Cannot read properties of undefined (reading 'query')
[Nest] 121  - 10/29/2024, 11:17:50 AM   ERROR [AdminController] TypeError: Cannot read properties of undefined (reading 'query')
```

**Environment**

- Ghostfolio Version 2.118.0 - 2024-10-23
- Self-hosted
- Experimental Features disabled
- Browser Brave
- OS: Windows (browser), Linux (server using `linux/amd64` from [official prebuild container image](https://hub.docker.com/r/ghostfolio/ghostfolio))

**Comment by dtslvr** [comment]
Hi @uqsbtysdfjgh

Thanks for catching this issue! Your solution looks fine — feel free to open a PR, and we’ll review it.

**Comment by mtzanidakis** [comment]
Hello,
any updates on this?

**Comment by calmandhandsome** [comment]
Hi guys, so sorry for late response, got caught in something. I created the PR here #4115, please help to review it. Thanks!
cc: @dtslvr
