### ISSUE TITLE
[BUG] Unable to get historical conversion rates, even when not needed

### ISSUE THREAD

**Issue by pwaldhauer** [ghostfolio/ghostfolio#4025]
**Bug Description**

I started a fresh ghostfolio instance via the provided docker image, created an account and set everything to EUR (added EUR in the settings, created an account with EUR as currency). When adding an first activity from 8.6.2021 it says, that it cannot get historical currency conversion data and fails to add the activity.

Since everything is in euro I don't understand why he needs conversion data in the first place.

I'd really like to use this software but since I cannot even start by adding by first activity, I cannot continue.

**To Reproduce**

1. Install current version
2. Set currency to EUR
3. Add an activity from 2021

**Expected behavior**

It should work

**Screenshots**

<img width="995" alt="Screenshot 2024-11-05 at 13 43 22" src="https://github.com/user-attachments/assets/b8edd665-7efb-482b-b8e6-c5b80b8d634b">

**Logs**

**Environment**

- Ghostfolio Version: current
- Self-hosted (docker)
- Experimental Features disabled
- Browser: Chrome
- OS: MacOS

**Additional context**

**Comment by dtslvr** [comment]
Hi @pwaldhauer

As `V3AA.L` is listed in `USD` and you have manually switched the currency to `EUR`, the exchange rate is indeed needed. In Ghostfolio, you are responsible for providing the relevant historical exchange rates. Please follow the steps from the [Self-hosting FAQ](https://ghostfol.io/en/faq/self-hosting) (see _How do I resolve No exchange rate has been found errors?_).
