### ISSUE TITLE
[Feature] Extend users endpoint by count

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#4053]
Extend the response of the [endpoint](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.controller.ts#L355) `GET api/v1/admin/user` by `count` to support pagination.

Create a new function `countUsersWithAnalytics()` sharing the query logic of [getUsersWithAnalytics()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/admin/admin.service.ts#L649).

**Comment by qur786** [comment]
@dtslvr 

Can you please explain what does the endpoint `GET api/v1/admin/user` will return as response when `count` query params will be provided?

**Comment by dtslvr** [comment]
@qur786 `count` is not a query param, it should be part of the response (total number of users in the database).
