### ISSUE TITLE
[Feature] Set up pagination for user table

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#4059]
The goal of this issue is to set up pagination support for the [user table](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/admin-users) (see _Admin Control_ panel → _Users_).

Check out the [AdminMarketDataComponent](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/admin-market-data/admin-market-data.component.ts) as a reference.

Hint: you can create some users and set the default page size to 1 for testing.

**Comment by ahmedhalac** [comment]
@dtslvr please can you help me with project setup. I have issue with initializing the database schema.

I am getting this issue:
Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `user` are not valid.

I already populated .env file with the missing data. (REDIS_PASSWORD, POSTGRES_PASSWORD, ACCESS_TOKEN_SALT, JWT_SECRET_KEY)

**Comment by dtslvr** [comment]
> I am getting this issue:
> 
> > Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `user` are not valid.
> 
> I already populated .env file with the missing data. (REDIS_PASSWORD, POSTGRES_PASSWORD, ACCESS_TOKEN_SALT, JWT_SECRET_KEY)

Does an existing volume still holding the old credentials. You could try stopping the containers, removing the volume, and then starting them again after updating the `.env` file.

**Comment by ahmedhalac** [comment]
I already tried that, but again I am getting this issue

**Comment by Ayush2198-source** [comment]
Hello, is anyone currently addressing this issue? If not, I'd be happy to take a look and try to resolve it, with your permission.

**Comment by dtslvr** [comment]
> Hello, is anyone currently addressing this issue?

Hi @Ayush2198-source, thanks for reaching out! As far as I know, @ahmedhalac is already working on this issue. I noticed that you are assigned to https://github.com/ghostfolio/ghostfolio/issues/3834. It might be helpful to prioritize that one for now 😊

**Comment by ahmedhalac** [comment]
Hi @dtslvr. I still haven't managed to setup the project. If anyone can troubleshoot with me.
