### ISSUE TITLE
[BUG] Holdings are fetched in assistant for each change

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#4065]
**Bug Description**

`GET api/v1/portfolio/holdings` is triggered via`ngOnChanges` in the [assistant component](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/assistant/assistant.component.ts#L279) which is inefficient.

**To Reproduce**

Navigate in the app as a user and observe the many `GET api/v1/portfolio/holdings` request in the developer tools _Network_ tab.

**Expected behavior**

`GET api/v1/portfolio/holdings` (see `fetchPortfolioHoldings()` in [initializeFilterForm()](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/assistant/assistant.component.ts#L502)) should only be called, when the assistant gets opened (see `initialize()`).

**Environment**

- Ghostfolio Version 2.123.0

**Comment by amandee27** [comment]
hi @dtslvr , you can assign this to me

**Comment by Ayush2198-source** [comment]
I investigated the issue and found that it occurs because initializeFilterForm is called within ngOnChanges. This change was introduced in commit #4031.

**Comment by amandee27** [comment]
> ngOnChanges

@Ayush2198-source , Thanks for investigating it. I'll raise a PR tomorrow.
