### ISSUE TITLE
[Feature] More precise holdings quantity

### ISSUE THREAD

**Issue by DireMunchkin** [ghostfolio/ghostfolio#4085]
I own some Bitcoin that I track in value using Ghostfolio - As far as I can tell the holdings number is displayed to two decimal places. That is the "Quantity" number I see on `./en/home/holdings?dataSource=COINGECKO&symbol=bitcoin&holdingDetailDialog=true` on my server.

This is starting to get a bit too imprecise in my case though as 0.01 BTC is worth $963 at time of writing, so the rounding error could be almost $500 worst case.

I imagine this could also be a problem for other assets where one share is a large amount of money.

The easiest way to fix this would be to simply format the number with 1-2 decimals more, so I.E round to 0.001 or 0.0001.

**Comment by dtslvr** [comment]
Hi @DireMunchkin

The numbers are calculated with full precision, and the rounding is purely for display purposes, so accuracy is not affected.

There is an ongoing discussion about this topic, which you can join here: https://github.com/ghostfolio/ghostfolio/discussions/3689. I will close this ticket to avoid duplicates.
