### ISSUE TITLE
all in one docker compose configuration

### ISSUE THREAD

**Issue by psychowood** [ghostfolio/ghostfolio#409]
Hi,
I set up a quick'n' dirty set of scripts to allow using Ghostfolio in a headless docker environment, you can find it [here](https://github.com/psychowood/ghostfolio-docker).

Hopefully this can be useful, it's hackish but works :)

**Comment by dtslvr** [comment]
Thank you very much for your efforts @psychowood. As long as we do not provide an official [Ghostfol.io](https://ghostfol.io) docker image, this could be helpful.

I have added a link to your repository to the README.md file: #411
