### ISSUE TITLE
[BUG] Investment Timeline not correctly populated

### ISSUE THREAD

**Issue by cardom** [ghostfolio/ghostfolio#4094]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

I have some activities with date of 1st April 2022, but the Investment Timeline in Portfolio Analysis has the April bar empty.
If I edit the activities changing the date to something different such as April the 4th of April the 15th, the bar appear.

**To Reproduce**

1. Create an activity with date of 04/01/2022
2. Check the Investment Timeline bar graph under Portfolio Analysis to see if the bar for April 2022 is blank or not (should be blank)
3. Change the date of the activity to another date, like 04/04/2022
4. Check again the Investment Timeline bar graph under Portfolio Analysis to find that the bar is now visible

**Expected behavior**

The bar related to the investments for April 2022 should be populated from the 1st of April. Don't know if it is something related to the 1st day of the month and not only April 2022 is affected. I don't have other investments on the 1st day of the months to try with

**Screenshots**

BEFORE:

![Screenshot 2024-12-02 at 20 11 55](https://github.com/user-attachments/assets/82ddf69b-c68b-48a1-a431-22b7c2cbf012)
---
![Screenshot 2024-12-02 at 20 12 34](https://github.com/user-attachments/assets/26161ade-0c8d-4901-88ef-814db82efa67)

AFTER THE CHANGE OF ACTIVITY DATE:

![Screenshot 2024-12-02 at 20 12 53](https://github.com/user-attachments/assets/1c42f577-f36d-4d55-a34a-504f4f8802d8)
---
![Screenshot 2024-12-02 at 20 13 00](https://github.com/user-attachments/assets/c58a4395-c1f8-4b56-ba33-0880574cb48b)
---
![Screenshot 2024-12-02 at 20 11 18](https://github.com/user-attachments/assets/09d00e26-035c-439f-b5b1-edf04eab1e36)
---
![Screenshot 2024-12-02 at 20 13 14](https://github.com/user-attachments/assets/1eecd710-f69a-4171-8c38-6c2e2b7ae627)

**Logs**

I don't think are needed

**Environment**

- Ghostfolio Version 2.125.0 - 2024-11-30
- Self-hosted
- Experimental Features disabled
- Browser Google Chrome Version 131.0.6778.86 (Official Build) (arm64)
- OS macOS Sonoma Version 14.7 (23H124)

**Additional context**

No additiona context

**Comment by dtslvr** [comment]
Thanks for the report! This looks related to https://github.com/ghostfolio/ghostfolio/discussions/4024. Could you check there to see if it addresses the problem?

**Comment by cardom** [comment]
Yes! This definetively is the same issue, and adding the TZ in the compose file, solved the issue.

Thanks
