### ISSUE TITLE
How to use a new currency?

### ISSUE THREAD

**Issue by 2e3s** [ghostfolio/ghostfolio#444]
I see that it's supposed to have the functionality by #387 but I can't find how to do it.
I have tried the online version, it has a few currencies, but it doesn't have CAD. I've tried a local version, it has only EUR and USD and I can't find any place where I could add any. Is there any?
![image](https://user-images.githubusercontent.com/4003445/139561485-c2c51973-59c0-4844-9d94-72f5118aee4a.png)
I was able to specify CAD in API request manually, but it's hacky and I think something won't work. Also, it would be nice to use CAD by default for everything.
Thank you.

**Comment by dtslvr** [comment]
Hello @2e3s

The available currencies are derived from the transactions (database table `SymbolProfile`). As soon as you have added a transaction in `CAD`, the currency should show up in the account dialog.
If you don't own any asset in `CAD` you could create another user and add a fake transaction. This will have the same effect.

You can also set your base currency at _My Ghostfolio_. Is this working for you?

**Comment by 2e3s** [comment]
> As soon as you have added a transaction in CAD, the currency should show up in the account dialog.

I don't see how it's possible:
<details>
  <summary>Add transaction</summary>

  ![image](https://user-images.githubusercontent.com/4003445/139595197-da1f6ce9-2b03-400c-a64d-07c26087a4d4.png)
  
</details>

> You can also set your base currency at My Ghostfolio. Is this working for you?

I see CAD now after I did a manual API request with CAD to add an account with CAD (I see in the accounts now as well). How to add any other currency here in UI? If possible.
<details>
  <summary>My Ghostfolio</summary>

  ![image](https://user-images.githubusercontent.com/4003445/139595327-1ffb0a81-9716-46c1-adb0-c2d569bcf6f7.png)
  
</details>

I think there shouldn't be any pre-populated selector for a currency, or maybe there should be another option `Other...`.

**Comment by dtslvr** [comment]
> I don't see how it's possible

Yes, find a symbol there that is traded in `CAD`, for example `BB.TO` (_BlackBerry_). Add `Quantity`: `1` and for `Unit Price` click the refresh icon.

> I see CAD now after I did a manual API request with CAD to add an account with CAD

I would not recommend to do manual API requests because there could be side effects.

> I think there shouldn't be any pre-populated selector for a currency, or maybe there should be another option `Other...`

These currencies are wired with the exchange rate service therefore I don't think there can be an option `Other...`

**Comment by dtslvr** [comment]
Is it working @2e3s?

**Comment by 2e3s** [comment]
Hey, it seems to work. But this is very counterintuitive, the very fact you can't create an account with any existing currency and start working with it right away. I would propose to look at having a predefined list of currencies and at least to underive from transactions.

> `docker-compose -f docker/docker-compose-build-local.yml build`

By the way, I'm not sure what to do if I read [README](https://github.com/ghostfolio/ghostfolio#setup-docker-image).

**Comment by dtslvr** [comment]
Hey @2e3s

Good to hear it works now.

Thanks for your proposal to improve the usability. Are you interested in implementing it? I could provide hints where to manage the list of currencies.

Regarding the docker documentation, can you please create a separate issue and describe what is not clear for you? Thanks in advance.

**Comment by 2e3s** [comment]
> Thanks for your proposal to improve the usability. Are you interested in implementing it? I could provide hints where to manage the list of currencies.

Hi, yes, since I haven't found any other decent opensource investment tracker, if I settle with this one, I may implement the proposal and maybe some other improvements, although it would be in a few weeks when I get back. If it's not implemented by then and if I need help, I will ask in this issue I suppose.

Thanks for the help! I'm closing for now as I've got CAD.

**Comment by dtslvr** [comment]
I have created a follow-up issue #510.
