### ISSUE TITLE
Portfolio Allocation Currency 

### ISSUE THREAD

**Issue by nicktids** [ghostfolio/ghostfolio#507]
I'm a python guy looking to build a similar app to what you have built here.  Looks awesome by the way.

The currency on the portfolio, I created a base account in USD (would like to be able to create one in another currency but only EUR and USD came up) 

and then on the portfolio allocation currency chart it shows CHF in the hover text.  I'm not an expert in JS (a wee beginner) or TS or angular to understand how this is being created on the back end or even shown so will just raise an issue.

![image](https://user-images.githubusercontent.com/26164799/144346415-aa4eff66-7388-496e-a4c6-d15e74287aec.png)

**Comment by dtslvr** [comment]
Thanks a lot for your feedback @nicktids.

I have analyzed and found some issues with the allocations in combination with cash balances. Among other things `CHF` has been [hard-coded](https://github.com/ghostfolio/ghostfolio/pull/508/files#diff-b76b6c44c1bfd51ef638e858cc1226d3f730918ed2ffd4bf6890f3f97313cbdeL892) 😮 

I will merge the fix. Can you please check again and give a feedback?

Regarding the available currencies: These are derived from the transactions. As soon as you have added a transaction in your desired currency, it will show up as a base currency (see _My Ghostfolio_).

**Comment by nicktids** [comment]
> Regarding the available currencies: These are derived from the transactions. As soon as you have added a transaction in your desired currency, it will show up as a base currency (see _My Ghostfolio_).

Question? Do you not think that might need to be changed.

As I would think a person will log in as a fresh user.  create a starting balance of xxx amount in currency abc that I live in and if I can't find currency abc then I'm just going to not understand that I have to create a trade in said currency to then go and create another account in the correct currency.  And then go back and change the account of the trade back to the correct currency

**Comment by dtslvr** [comment]
Do you have feedback for the allocation by currency issue @nicktids?

I have created a separate ticket to manage the currencies #510.
