### ISSUE TITLE
Unable to add stock for a company that does not exist anymore

### ISSUE THREAD

**Issue by rb28z2** [ghostfolio/ghostfolio#509]
I'm trying to import all of my historical data and I have a stock from a company that no longer exists (it was bought by another company). When I try to add that stock to my portfolio, it does not show up in the list of securities and I can't import it.

Example: I used to have HSE.TO (Husky Energy) which was bought out by CVE.TO this year, but I can't add HSE to my portfolio since that stock no longer exists.

**Comment by dtslvr** [comment]
Thank you for reporting this issue @rb28z2.

Currently, Ghostfolio only supports symbols which are available by the data providers. Do you have an idea how to make this work?

As a workaround I would remove the old transactions (`HSE.TO`) from your import file and just import the new one `CVE.TO`.

**Comment by rb28z2** [comment]
Honestly I'm not sure how exactly to solve this outside of using a data provider that provides that data. I actually worked around it by combining some transactions together and changing the symbol to the new company - it's not a great solution but it's good enough I think.

It might be worth just closing this issue since it seems a little out of scope - I just wanted to make sure someone is aware.

Side question: is there an import file feature? I've just been importing my transactions by hand, one at a time, and it's a little tedious (I'm using the self-hosted option).

**Comment by dtslvr** [comment]
You can keep that issue open as a starting point for further discussion. Maybe there is an elegant approach to automate the problem you are describing.

Regarding imports, please open the transactions page and find the kebab menu close to _Account_ in the table header. There you can upload a _CSV_ file. You will get validation messages as a guidance to match the [format](https://raw.githubusercontent.com/ghostfolio/ghostfolio/main/test/import/ok.csv). If you have further questions, please create a new issue or join our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) channel 🙂

**Comment by FedericoComoglio** [comment]
Hi @dtslvr , I have a follow-up example that I believe could be of use for this issue. 

As you may be aware, Royal Dutch Shell (now officially just Shell) has recently simplified its share structure. This resulted in a delisting of RDSA.AS and RDSB.AS shares from AEX. The new ticker, which started to trade a few days ago, is SHELL.AS. How do you plan to handle such cases? A possible solution would be to introduce ad-hoc aliasing, which would make sure historical data are not affected.

Let me know.
Thanks a lot!

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, to follow up on the issue above - replacing all previous transactions with the new ticker fixes it.

**Comment by zeezhao** [comment]
Hi. How about ability to enter a custom stock that will be priced manually by the user?

**Comment by dtslvr** [comment]
> It would also be a useful placeholder for showing things like real-estate or property investments.

Have you tried to add an activity of type `ITEM`? You can track real estate or valuables with it.

**Comment by raider-com** [comment]
How would one show the values of those over time?
I've added an activity of ITEM type, but the value of that item is never shown in the overview, nor the account values.

**Comment by raider-com** [comment]
gotcha, thank you

**Comment by hvddrift** [comment]
> Hi. How about ability to enter a custom stock that will be priced manually by the user?
> 
> edit: It would also be a useful placeholder for showing things like real-estate or property investments.

Hi

I think this is a good solution. I have some investments that are Managed Funds that are not listed/tracked by any provider. The ability to make a custom equity that can track dividends, buy/sell and price updates would be great.

My 2 cents

Thank you

**Comment by raider-com** [comment]
> > Hi. How about ability to enter a custom stock that will be priced manually by the user?
> > edit: It would also be a useful placeholder for showing things like real-estate or property investments.
> 
> Hi
> 
> I think this is a good solution. I have some investments that are Managed Funds that are not listed/tracked by any provider. The ability to make a custom equity that can track dividends, buy/sell and price updates would be great.
> 
> My 2 cents
> 
> Thank you

I also have the same issue, and think that it would be a good feature.

**Comment by hvddrift** [comment]
@dtslvr Do you think this is a possibility? Its the only thing at the moment moving all my past transactions into Ghostfolio

**Comment by dtslvr** [comment]
> @dtslvr Do you think this is a possibility? Its the only thing at the moment moving all my past transactions into Ghostfolio

Yes, there is not much missing to make it usable with database access and some manual work.

**Comment by dtslvr** [comment]
Starting from Ghostfolio `1.213.0`, you will be able to track custom assets following these steps:

1. Create an entry in the table `SymbolProfile` with e.g. `symbol=MY_TEST` and `dataSource=MANUAL`
2. Create an activity for `MY_TEST`
3. Add entries in the table `MarketData` with `symbol=MY_TEST` and `dataSource=MANUAL`

**Comment by hvddrift** [comment]
Thank you @dtslvr 

excuse my ignorance but where is the SymbolProfile ?

**Comment by dtslvr** [comment]
Hi @hvddrift

> excuse my ignorance but where is the SymbolProfile ?

You can find the (database) table `SymbolProfile` when you connect directly to your database with a management tool. Here are some ideas how to do it: https://github.com/ghostfolio/ghostfolio/discussions/735#discussioncomment-2580028. For _Unraid_, there are maybe other ways. Please ask the [community](https://forums.unraid.net/topic/123829-support-community-applications-ghostfolio) there.
