### ISSUE TITLE
Please allow setting default currency for an account regardless of it being used in any transaction

### ISSUE THREAD

**Issue by lsrom** [ghostfolio/ghostfolio#523]
Currently if I want to set my default currency I need to choose from one that is used by some transaction (as far as I can tell). Could you make it possible to select any currency? I don't actually have any transactions in my native currency but I want to see the value of my portfolio in it.

**Comment by dtslvr** [comment]
You can now manage custom currencies in the _Admin Control_ which are then available in the list of base currencies (_My Account_).
