### ISSUE TITLE
Build new releases 1.87 and 1.88 fail

### ISSUE THREAD

**Issue by niceborn** [ghostfolio/ghostfolio#535]
I'm trying to build newest releases from 1.87.0 and 1.88.0 with docker-compose -f docker/docker-compose-build-local.yml build, but I get the following error message:

Step 25/30 : RUN yarn database:generate-typings
 ---> Running in 71b1bcd376f0
yarn run v1.22.15
$ prisma generate
/bin/sh: prisma: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn database:generate-typings' returned a non-zero code: 127
ERROR: Service 'ghostfolio' failed to build : Build failed

I'm now on 1.83.0.

**Comment by niceborn** [comment]
Tried also with 1.89.0, but same error.

**Comment by dtslvr** [comment]
Hi @niceborn

Thank you for reporting this issue. I have made a change in #465 which should solve the missing prisma binary (`/bin/sh: prisma: not found`). Can you please try again?

**Comment by niceborn** [comment]
Thank you for the quick solution. With the changes in package.json it worked and now I'm on release 1.89.0. Can be closed :-)

**Comment by dtslvr** [comment]
Great, thank you for confirming that it works now! 😃 

I had to move `prisma` from `devDependencies` back to `dependencies`. This is only needed for building the docker container. I don't know why `devDependencies` are missing, maybe @vzickner has an idea?
