### ISSUE TITLE
Cannot get symbol for Uniswap

### ISSUE THREAD

**Issue by OliRafa** [ghostfolio/ghostfolio#539]
Hey guys!

I was trying to insert some transactions on Uniswap but the API seems to not find the symbol.
Here's a screenshot for the console:
![Screenshot 2021-12-13 at 10 06 52](https://user-images.githubusercontent.com/33501164/145792501-8a3d103d-d34c-4360-bb8f-a73a25cf11ab.png)

And here are the requests:
![Screenshot 2021-12-13 at 10 07 20](https://user-images.githubusercontent.com/33501164/145792578-68af57b7-8b3c-4ccd-af0e-5de8d1ac96b8.png)

When trying to find directly on Yahoo Finance (https://finance.yahoo.com/quote/UNI3-USD/) there's a hyphen on the URL - maybe that's the problem.

**Comment by dtslvr** [comment]
Hello @OliRafa

Thank you for reporting this issue. In Ghostfolio, there is the convention that symbols are stored without hyphen. Therefore, there is some [conversion](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-provider/yahoo-finance/yahoo-finance.service.ts#L255) to handle the symbol of _Yahoo_ with the hyphen. It seems that it does not convert `UNI3USD` correctly.

Would you like to take a look?

By the way, thanks a lot for creating the other tickets. As they are quite broad I think it makes sense to discuss them in more detail in the [Slack channel](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) 🙂
