### ISSUE TITLE
Save button grayed-out in new transaction form

### ISSUE THREAD

**Issue by FedericoComoglio** [ghostfolio/ghostfolio#548]
Hi, 

while testing, I am unable to save a new (fake) transaction for ticker BRKB. I confirm the new transaction form is filled in entirely and with valid input. I did not experience this issue before for other tickers (I tested another 5 without changing anything else in the form and the save button became available). It appears to specifically affect BRKB. I can reproduce the issue both on Chrome as well as on Safari.

Hope this helps. Thank you!
<img width="773" alt="Screen Shot 2021-12-16 at 2 55 04 PM" src="https://user-images.githubusercontent.com/5443822/146384979-7dbb35af-3eaa-450c-958c-d191d1f7df64.png">
<img width="780" alt="Screen Shot 2021-12-16 at 2 54 58 PM" src="https://user-images.githubusercontent.com/5443822/146384998-35abbd5e-78e4-49ff-9b33-3d6d0334d200.png">

**Comment by dtslvr** [comment]
Thanks for reporting this issue @FedericoComoglio.

I have analyzed it and it seems that `BRKB` is not a valid symbol (anymore?): https://finance.yahoo.com/quote/BRKB
What you probably like to add is `BRK-B`, but there is currently a bug with the hyphen. I have fixed it here: #549

I will keep this issue open until I have deployed the new version.

**Comment by FedericoComoglio** [comment]
Thanks a lot for looking into it, @dtslvr. I overlooked the previously reported issue with hyphens, which explains it. I was tricked by the suggested ticker in the drop-down menu. Glad to hear you already had this on your radar. I will do more tests in the coming days. I noticed a few inconsistencies and will report them separately. Hope this helps.

**Comment by dtslvr** [comment]
No, you have not overlooked. I have just fixed it 🙂 
I have deployed the fix now, can you confirm that it is working as expected?

Feel free to report your findings in separate issues.

**Comment by FedericoComoglio** [comment]
Thank you. I tested it and it works as expected.

**Comment by dtslvr** [comment]
> Thank you. I tested it and it works as expected.

Great! 👍🏻
