### ISSUE TITLE
Inconsistent change/performance values in Holdings tab

### ISSUE THREAD

**Issue by FedericoComoglio** [ghostfolio/ghostfolio#554]
Hi,

I promised to report a few inconsistencies that I noticed while testing Ghostfolio functionalities. When thinking about the **performance** of a security, I generally think of three components: 

- capital gains
- dividend gains 
- currency gains.

Clearly, change/performance can be gross or net, depending on whether transaction fees are taken into account. Looking into previous issues, I noticed that recent releases of Ghostfolio indeed feature both net and gross performance (nice!). In addition, I am aware that some features -such as introducing a DIVIDEND transaction type - are in the making and cannot contribute to the issue I am reporting here. For simplicity, I also **picked an example of a stock in CHF**, to rule out currency effects. 

Based on the attached screenshot, I would like to understand **how the indicated "change" and "performance" are exactly computed** (of note, the total transaction fee for this position amounts to CHF 11.35). In particular:

- I get that `investment` simply refers to `average buy price * quantity` (141.8 * 14)
- I would expect `change` to be defined as `(market price - average buy price) * quantity`. This would amount to (143.9-141.8) * 14 = 29.4 gross or 18.05 net (i.e. 29.4 - transaction fees).
- I would expect `performance` to be defined as `change/investment * 100`, but this is not the case. I also don't get why it is negative in spite of a positive change. Even factoring in transaction fees, that would still result in a performance of -0.42%: (2.85 - 11.35) / 1985.2 * 100

Could you please clarify how are these quantities computed, and what am I missing here, in case?

Thanks a lot! 

<img width="595" alt="Screen Shot 2021-12-18 at 3 31 40 PM" src="https://user-images.githubusercontent.com/5443822/146644918-4faa3560-fee1-47c7-9ec2-bbb743b362c7.png">

**Comment by dtslvr** [comment]
Thank you for documenting your findings @FedericoComoglio!

Ghostfolio uses the [Time-Weighted Rate of Return](https://www.investopedia.com/terms/t/time-weightedror.asp) (TWR) to eliminate distorting effects created by inflows and outflows of money. This makes the calculation more complex compared to your example.

Nevertheless, I would expect that the change and the performance have the same algebraic sign. A starting point to analyze this issue would be to design a very simple [unit test](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio-calculator.spec.ts) to reproduce this behaviour.

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, thank you for looking into this issue. 

Using TWR makes sense. Metrics anyway converge to the simple performance measures I reported above for typical buy-and-hold (at regular intervals) investors who use dollar-cost averaging. 

To reproduce the issue above (coming from a stock simulator), I exported and formatted the relevant transactions:

date,type,ticker,currency,units,price,fee
30.11.2021,BUY,BALN.SW,CHF,2.00,136.60,1.55
26.11.2021,BUY,BALN.SW,CHF,3.00,139.90,2.40
22.11.2021,BUY,BALN.SW,CHF,7.00,142.90,5.75
12.11.2021,BUY,BALN.SW,CHF,2.00,146.00,1.65

Likely, it is possible to further simplify this set for a unit test but I hope this offers a starting point. Thank you!

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, not sure if this helps but I noticed another performance inconsistency, this time in the Summary tab. With a time in the market of 5 months for a simulated portfolio, I get:

- gross performance = -1.24%
- net performance = -1.93% (so far so good)
- annualized performance = +49.64%

I assume this once again stems from the use of TWR, with some positions in the simulated portfolio opened just a few days ago at the "dip" preceding the recent swift recovery.

**Comment by vzickner** [comment]
Hi @FedericoComoglio,

thank you for sharing the portfolio, that helped to create a test case.

First, I am not a financial expert and only contributed to the portfolio calculation because it was challenging and fun to write an efficient algorithm for the TWR. There might be a bug in there, but as far as my analysis is telling me, everything works as expected.

You can find the test case with some manual calculations here: https://github.com/ghostfolio/ghostfolio/commit/56c9b9c05f0f7b30221006ba6a686c610ddadaf7

My thoughts about your calculations vs TWR:

* Change: The change in your screenshot seems to be wrong and I am not sure why. The portfolio calculation returns the correct value for the specific date, for gross and net.
* Performance: I would agree with your formula if you would had one investment at the beginning. However, the investment was one after the other which makes it more complex. Assuming you hold an investment of $100 (quantity = 1) for a year and the market price is now $150. With that, your performance is 50%. Now you invest today another $15,000 (quantity = 100, price = $150). What would you expect as a new performance? With your formula, your change is still $50 and the investment is now $15,100, which gives a performance of 0.33 %. Not sure if it makes sense that your performance goes down because you invest more money.
* Annualized performance: This depends on which symbols you have and for how long. Each symbol is annualized by itself and then it's computed. In case you have one symbol for a really short time that is doing really well, you can see what you are experiencing.

I personally don't consider this a bug or inconsistency. Maybe we are using the wrong calculation methods, but in this case, the question is what we could switch to make the behavior better. Also, this example doesn't include the calculation of the performance since a given date, which makes everything even more complex (since you don't really have an average buy price anymore).

I wish you all happy holidays,

Valentin

**Comment by dtslvr** [comment]
Thanks for your detailed comments @FedericoComoglio and @vzickner.

Another thought on this: Is the time-weighted return (TWR) only suited for an investment portfolio and not for a single position?

**Comment by FedericoComoglio** [comment]
Thank you both for your feedback. I suggest that we focus on the change
computation before venturing into performance metrics. The first issue in
the example above remains the change value, which is not reflecting the
change value of the position (neither net nor gross). I imagine a typical
user would like to quickly gauge the total unrealised gain/loss here. I
also noticed in a few occasions  negative change values for a positive,
unrealized return. I see no logical/plausible explanation for it. I’m very
happy to discuss these issue with you further. Thank you!

**Comment by FedericoComoglio** [comment]
Re. Performance metrics, how about offering the user the possibility to
select one (or more) metric best suited for their strategy. I feel a
standard measure as straightforward as [ROI](
https://www.investopedia.com/articles/basics/10/guide-to-calculating-roi.asp)
could be a starting point.

**Comment by dtslvr** [comment]
> Thank you both for your feedback. I suggest that we focus on the change computation before venturing into performance metrics.

I have recalculated the change for your example and have found a mismatch. Can you confirm the result? (New: 67.20 vs. 53.15 currently in the app)
<img width="906" alt="BALN-change" src="https://user-images.githubusercontent.com/4159106/147411457-b46582e2-bd38-445a-ade2-4c7ff1d7367b.png">

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, thank you. I confirm the computed change is correct and precisely as I defined it initially. Thank you also for splitting up the original issue.

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, with reference to your request for help in #512, I would like to advocate for a simple and pragmatic approach once it comes to computing change and performance metrics. More details below.

- I do not think there is much room for interpretation in the definition of change. This can be computed exactly as you did above for the test case. When relevant, it would be great to display the contribution of price, currency and dividend to the total change for the position. Please note this is quite standard/accepted (see e.g. [sharesight](https://www.sharesight.com/portfolio-tracker/?utm_source=google&utm_medium=cpc&utm_content=Google_PerformanceMax_Switzerland&gclid=Cj0KCQiA2sqOBhCGARIsAPuPK0hDVASYtjHgAJMwfq24WR82EM0ZtUi6-txU7XIrKhqAiQPBcFAyBZgaAsB7EALw_wcB))
- Performance calculation can make use of different metrics, especially for annualization. I suggest implementing a standard ROI, to begin with. In the example proposed by @vzickner, it makes sense to me for the change to be diluted on the total investment in the position. Nothing counterintuitive there. It's just an ROI. Re. annualization, instead, I believe it would make sense to compute annualized performance metrics only after a minimum required time in the market, e.g. one month. 

Hope this helps. Happy to discuss further. Thank you so much once again for all the efforts you are putting into building Ghostfolio!

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, I hope you are well. Any update the on above?

**Comment by dtslvr** [comment]
Yes @FedericoComoglio, there is work in progress going on in #632.

The calculation will be based on this (first tab): https://docs.google.com/spreadsheets/d/1k7wwGIdvDmYM5yTs_0WM0cBZG7ZxiNXtrAX9Kezch9s/edit

If you have feedback, please post it here.

**Comment by FedericoComoglio** [comment]
Thank you, @dtslvr. I reviewed the calculation for BALN and it looks good. I assume you will account for transaction fees when computing the net return, as already implemented. Thanks!

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, a quick update on the new calculation engine. I tested it with a number of securities (in CHF) and I confirm it works as expected. At this stage, I think it would be very useful to:

1. Consider splitting the individual contributions to change as described in the [original issue](https://github.com/ghostfolio/ghostfolio/issues/554#issue-1083848312)
2. Introduce an ROI as a performance metric, so that users can benefit from a widely adopted and fairly standard metric to measure performance.

What do you think about it?

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, I hope you are well. Although I kept quiet for a few months, I kept using (and testing) Ghostfolio in the meantime :) Is there any update on the above? What is your view on the proposed three-component contribution to performance? Thank you!

**Comment by dtslvr** [comment]
Hi @FedericoComoglio

I have not prioritized that. However, I think it is a good idea and I would be supportive if there was a pull request from the community. So that it does not get lost, I have created a new [discussion topic](https://github.com/ghostfolio/ghostfolio/discussions/1166).
