### ISSUE TITLE
Selfhosting and custom Admin Access Token and Salt

### ISSUE THREAD

**Issue by veryhumble** [ghostfolio/ghostfolio#564]
Hello,

I tried running Ghostfolio with docker-compose. With defaults from .env and the Readme it works fine. But i would like to use my own Admin Access Token in the Seed as well as another Salt (ACCESS_TOKEN_SALT) . The App runs just fine and I am able to create a user with a Token. But unfortunately i have no idea what the Access Token for the Admin user is and therefore i am unable to login as Admin.

How do I find out the access token for the Admin user?

I was trying to replicate the `reateAccessToken` function from the project. But I'm not getting the Token mentioned in the Readme with Inputs from the Seed and Salt from this Repo.

**Comment by dtslvr** [comment]
Hey @veryhumble

Thank you for creating an issue. There is currently no graphical user interface to manage users. I would suggest that you assign the role `ADMIN` to your new user and then delete the original (seeded) administrator - directly in the database.

Does that work for you?

**Comment by veryhumble** [comment]
I suppose it will do. Thank you very much.

**Comment by dtslvr** [comment]
> I suppose it will do. Thank you very much.

You're welcome! 🙂 

I have added these instructions to the [documentation](https://github.com/ghostfolio/ghostfolio#finalization). I hope this helps.
