### ISSUE TITLE
Example for CSV import

### ISSUE THREAD

**Issue by fly-man-** [ghostfolio/ghostfolio#580]
Is it possible to include an example CSV file for when people want to import their full portfolio into Ghostfolio ?

I did see that there's a JSON reader but couldn't find the correct values that the CSV reader requires to load the whole portfolio in

**Comment by dtslvr** [comment]
Hi @fly-man-

For testing the import, I have created various scenarios with [example files](https://github.com/ghostfolio/ghostfolio/tree/main/test/import). You are probably looking for the file `ok.csv`.

**Comment by fly-man-** [comment]
Using this as the CSV file,using the import function on the transactions page

```
Date,Code,Currency,Price,Quantity,Action,Fee
21/11/2021,ACRE,USD,15.42,50,buy,0.0
21/11/2021,GAIN,USD,16.81,50,buy,0.0
21/11/2021,GOOD,USD,22.49,50,buy,0.0
21/11/2021,NLY,USD,8.39,100,buy,0.0
27/11/2021,ORC,USD,4.85,50,buy,0.0
21/11/2021,TRTX,USD,12.98,50,buy,0.0
21/11/2021,UWMC,USD,6.44,50,buy,0.0
21/11/2021,VALE,USD,11.45,50,buy,0.0
```

And the error I get then is: 
```
Import Transactions Error
Unexpected format
```

**Comment by dtslvr** [comment]
I cannot reproduce the error with the following file: [fly-man.csv](https://github.com/ghostfolio/ghostfolio/files/7776728/fly-man.csv)

The error "Unexpected format" means that the (general) file format is not valid. If it can be parsed at all as `csv`, you will get a more detailed validation error.

Can you try to validate your `csv` file [here](https://csvlint.io)?

**Comment by fly-man-** [comment]
I tried using the file you send, same error.

CSVLint tells me that the CSV file is correct, Ghostfolio still tells me

```
Import Transactions Error
Unexpected format
```

**Comment by dtslvr** [comment]
> I tried using the file you send, same error.

It seems to be an error on Windows, I'll analyze it.

**Comment by dtslvr** [comment]
I have found the issue. The file type was not detected correctly.

I assumed it to be `text/csv`, but it can also be `application/vnd.ms-excel` 🙄

**Comment by dtslvr** [comment]
Hi @fly-man-

This change has been released: https://github.com/ghostfolio/ghostfolio/releases/tag/v1.96.0
I hope it works as expected now.

**Comment by fly-man-** [comment]
Works like a charm now
