### ISSUE TITLE
Add Activity dialog not working 

### ISSUE THREAD

**Issue by anderick** [ghostfolio/ghostfolio#614]
**Steps to reproduce**
1. Create a new account
2. From the main screen, after signup
3. Click on "Time to add your first activity"

**Expected behaviour** 
- Dialog to add new activity shows up
- In the Activities page, clicking in "Time to add your first activity" shows the dialog

**Current behaviour**
- Dialog to add new activity don't shows up
- In the Activities page, clicking in "Time to add your first activity" does nothing

_Notes:_
- Navigating to http://localhost:3333/portfolio/activities?createDialog=true is another way to reproduce the issue
- Navigating to http://localhost:3333/portfolio/activities (without the query param) shows the dialog and let "Time to add your first activity" opens the dialog

**Comment by dtslvr** [comment]
Hey @anderick

Thank you very much for reporting this issue and adding a useful description. I have fixed the routing in #615.
