### ISSUE TITLE
Account Cluster Risk showing internal ID instead of Account Name

### ISSUE THREAD

**Issue by juic3pow3rs** [ghostfolio/ghostfolio#634]
While fiddling around with all the neat functions I stumbled upon a small UI error.

Installation: Self-hosted
Version: v1.104.0 (via Docker-Hub)

As seen in below screenshot the Account Cluster Risk under Xray shows the internal ID of the Account instead of the Account-name:
![image](https://user-images.githubusercontent.com/9073421/150011491-1a4083ae-682c-484d-870c-2fcd27f1ab52.png)

Cheers!

**Comment by dtslvr** [comment]
Thanks for reporting this issue @juic3pow3rs! I will take a look later this day.
