### ISSUE TITLE
Line chart (overview) missing data points for 2022

### ISSUE THREAD

**Issue by FedericoComoglio** [ghostfolio/ghostfolio#643]
Hi,

I noticed the line chart in the overview stopped updating at the end of last year. There seem to be missing data points for 2022. As a consequence, the trend for the new year is simply a segment. A message ("Sorry! Our data providing partner is experiencing the hiccup") keeps appearing since the beginning of the year, too.

Thank you!

**Comment by dtslvr** [comment]
Hi @FedericoComoglio

That could happen when historical data is missing. I will analyze it this weekend to find out which symbols are affected.
As it is related to the SaaS offering of Ghostfolio, I will close this ticket and come back to you directly.

Have a nice weekend!

**Comment by FedericoComoglio** [comment]
Sure, thank you! Happy to provide more information for debugging. Have a nice weekend!
