### ISSUE TITLE
Duplicated time in market text entry in Summary

### ISSUE THREAD

**Issue by FedericoComoglio** [ghostfolio/ghostfolio#699]
Hi @dtslvr,

I noticed the time in market text entry is now displayed twice in the Summary. 

<img width="712" alt="Screen Shot 2022-02-14 at 7 27 40 PM" src="https://user-images.githubusercontent.com/5443822/153924437-efdf599f-13cf-4bbd-973a-af14f218b7df.png">

Hope this helps,
Federico

**Comment by dtslvr** [comment]
Thanks for reporting @FedericoComoglio 🙂
