### ISSUE TITLE
Failed to gather data for symbol HJUF.BE/HJUF.F

### ISSUE THREAD

**Issue by niceborn** [ghostfolio/ghostfolio#725]
Hi,

I don't know if it could be a general issue, but since last time I have an issue with my Portfolio (selfhosted docker). I already had some HJUF.BE or HJUF.F in my list and everything was fine. Since about two weeks the chart in Overview only shows a line (not a curve) from the value two weeks before to actual value.

![image](https://user-images.githubusercontent.com/19347993/155727554-acd9cdb0-2134-4127-893f-6d0ca4e99ea9.png)

As I wanted to migrate my docker images to kubernetes I set Ghostfolio up in k3s again, and now I get only a line from start to end
![image](https://user-images.githubusercontent.com/19347993/155727486-d8cd9127-d3b9-4e5e-ac8f-45279161f9b4.png)

If I delete HJUF.xx from the list it works again:
![image](https://user-images.githubusercontent.com/19347993/155727842-17b926e8-4d74-4e69-acf1-ae8e0dcef727.png)

In the logs are a lot of entries: [33m[Nest] 1  - [39m02/25/2022, 2:42:15 PM [33m   WARN[39m [33mFailed to gather data for symbol HJUF.BE at 2021-11-20.[39m

Any hints? I'm on Ghostfolio v1.120.0.

**Comment by dtslvr** [comment]
Hello @niceborn

The problem is, that you don't get historical data from the data provider anymore (see [HJUF.BE](https://finance.yahoo.com/quote/HJUF.BE/history?p=HJUF.BE) and [HJUF.F](https://finance.yahoo.com/quote/HJUF.F/history?p=HJUF.F)).

The date (x-axis) in the chart is currently skipped if one historical data point is missing. As you now only have data for the current date, a straight line is rendered. This algorithm could be improved that it still renders a chart even if historical data is missing.

**Comment by niceborn** [comment]
Thanks for quick reply. 

Instead HJUF I could also change the entry to [this](https://finance.yahoo.com/quote/0P0001BFUD.F?p=0P0001BFUD.F) ISIN DE000DWS2NM1 with historical data, but this is not shown in the list to select.

**Comment by dtslvr** [comment]
I have quickly analyzed ISIN `DE000DWS2NM1`. It is of type `MUTUALFUND`, which is currently not supported and thus excluded from the search results. I think there is nothing wrong to support it, too.

I will check this weekend.

**Comment by dtslvr** [comment]
@niceborn, with [1.121.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.121.0) you should be able to add `DE000DWS2NM1`.

**Comment by niceborn** [comment]
I have updated and it's working :-) Nice and thank you for the very quick solution.

**Comment by niceborn** [comment]
Can be closed now.

**Comment by dtslvr** [comment]
> I have updated and it's working :-) Nice and thank you for the very quick solution.

Thank you for the feedback 🙂 

I have created a follow-up issue for the chart rendering: #728
