### ISSUE TITLE
Add more options for base currency

### ISSUE THREAD

**Issue by pakaka** [ghostfolio/ghostfolio#765]
I would love to see PLN available as base currency

+ one other small thing: it would be great to have an option to add notes or short comments to your activities in portfolio

Thank you guys <3

**Comment by dtslvr** [comment]
Hi @pakaka

Thanks for your feedback. In the self-hosted variant it is possible to manage your custom currencies in the admin control panel. If you are using the [Ghostfol.io](https://ghostfol.io) cloud offering, I have just added support for PLN.

I have created a new ticket for your suggestion regarding notes: #766

**Comment by pakaka** [comment]
Thank you <3 

I will leave one more suggestion here, unfeortunately my programming skills are insufficient to implement it...
I think it would be nice to have an easy ability to track gold prices- I took me a while to find an instrument like that on ghostfolio.

I think you should add support for:
XAUUSD
XAUEURXC0009655157

22 mar 2022, 21:29 od ***@***.***:

**Comment by dtslvr** [comment]
Hello @pakaka

Have you already tried to track gold via [GC=F](https://finance.yahoo.com/quote/GC=F)?

I cannot find `XAUUSD` on _Yahoo Finance_. Can you please provide a link?
