### ISSUE TITLE
Add guide for activity importing

### ISSUE THREAD

**Issue by crunchtoinfo** [ghostfolio/ghostfolio#769]
Hi. I was looking for help on how to import activities and could not find any. Am I missing something? This could make it easier for people to onboard and would be a good

**Comment by dtslvr** [comment]
Thanks for creating this ticket @crunchtoinfo.

As already discussed in [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg), it would be great to have a little guide directly in the app. You could modify [import-transaction-dialog](https://github.com/ghostfolio/ghostfolio/tree/b57301ef5000a20f7810f86ce1cd6601f181146d/apps/client/src/app/pages/portfolio/transactions/import-transaction-dialog) to a [stepper](https://material.angular.io/components/stepper/overview). 

The first step could be the instructions:

> You can import Ghostfolio `*.json` files as well as `*.csv` files. You can find an example `*.csv` file [here](https://github.com/ghostfolio/ghostfolio/blob/main/test/import/ok.csv).
>
> "Import activities" or "Drop your file here" (nice to have)

The second step could be the validation information as before.

What do you think?

**Comment by WayneBusby** [comment]
More than documentation is needed.  Even when you POST the ok.json you get an error:
{
    "statusCode": 400,
    "message": [
        "activities must be an array"
    ],
    "error": "Bad Request"
}

**Comment by dtslvr** [comment]
> Even when you POST the ok.json you get an error

I have just imported the file `ok.json` successfully. Can you please provide more information @WayneBusby?

**Comment by developerbuzz** [comment]
Hi @dtslvr 

I'm using the latest docker image and using POSTMAN to send the request.  I've add the ok.json content to the raw body of the POST object and added the authorization header using a token generated via a browser request.  When I send I get back at 400 error saying bad request and that activities must be an array.

The url I'm POST'ing to is:
http://<server ip>:3333/api/v1/import

There are no entries in the log files.

**Comment by developerbuzz** [comment]
It would be good to get detailed instructions on importing data.  I have managed to export ok, but when I try and use the raw data provided from the GET request into the import POST endpoint I just get a bad request - activities must be an array!

**Comment by dtslvr** [comment]
Hi @developerbuzz

Can you try to import this _Raw Text_ in _Postman_ and compare with what you are currently sending? It has been exported from the browser when I import `ok.json`.

```
curl 'http://localhost:4200/api/v1/import' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7' \
  -H 'Authorization: Bearer ey*******' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:4200' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:4200/en/portfolio/activities' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  --data-raw '{"activities":[{"fee":0,"quantity":0,"type":"BUY","unitPrice":0,"currency":"USD","dataSource":"YAHOO","date":"2050-06-05T22:00:00.000Z","symbol":"MSFT"},{"fee":0,"quantity":1,"type":"ITEM","unitPrice":500000,"currency":"USD","dataSource":"MANUAL","date":"2021-12-31T22:00:00.000Z","symbol":"Penthouse Apartment"},{"fee":0,"quantity":5,"type":"DIVIDEND","unitPrice":0.62,"currency":"USD","dataSource":"YAHOO","date":"2021-11-16T22:00:00.000Z","symbol":"MSFT"},{"fee":19,"quantity":5,"type":"BUY","unitPrice":298.58,"currency":"USD","dataSource":"YAHOO","date":"2021-09-15T22:00:00.000Z","symbol":"MSFT"}]}' \
  --compressed
```

P.S. Don't forget to replace the _Bearer_.

**Comment by developerbuzz** [comment]
Thanks @dtslvr, you are a star.

It seems that even though you set the content in Postman it doesn't seem to set the Content-Type header in the request.  Once I added that the import worked. 

![image](https://user-images.githubusercontent.com/23062252/195281868-6e7d2e77-d103-4ef3-9e3d-b020326ea2c2.png)

Your help was most appreciated.  Thank you.

**Comment by dtslvr** [comment]
> Your help was most appreciated. Thank you.

You're welcome. I'm glad it is working now 🙂

**Comment by dtslvr** [comment]
Integrated documentation for the activities import:

<img width="1097" alt="import-activities-dialog" src="https://user-images.githubusercontent.com/4159106/200117339-f6bbe7d8-85ea-4e71-95b2-73cadc1ff9d0.png">
