### ISSUE TITLE
Add a new Currency: Bitcoin

### ISSUE THREAD

**Issue by simonMoisselin** [ghostfolio/ghostfolio#775]
Hey here great project!

It will be cool if we could denominate the return of investment in Bitcoin terms, instead of USD.

**Comment by SH4LT1S** [comment]
Yeah, I wish we could track crypto. Just enter buy dates and price like stocks to track return and avg price. https://docs.coincap.io/

**Comment by dtslvr** [comment]
This feature is currently not planned.
