### ISSUE TITLE
Allow different currency for fees

### ISSUE THREAD

**Issue by ruudk** [ghostfolio/ghostfolio#789]
I'm using DEGIRO with a EUR account. That means that all costs are done in EUR. But the transactions I do can be done in USD.

When trying to add a buy activity in USD, I want to specify the cost (fee) in EUR.

**Comment by casitu** [comment]
This issue needs to be adressed, not only in the fee amount but also in unit price (as stated in issue #705). Most of EU brokers directly convert USD operations into EUR in their reports.

**Comment by bootsofglory** [comment]
Agreed with @casitu the currency should be selectable for both fees and unit pricing.

**Comment by dtslvr** [comment]
![select-currency-for-fee](https://user-images.githubusercontent.com/4159106/191795994-b0ae5da0-d633-4c15-9f24-d8c87831ed85.png)

**Comment by casitu** [comment]
> The currency of the fee could be converted before it is stored. For the unit price I don't think it makes sense, because that currency is derived from the symbol.
> 
> ![select-currency-for-fee](https://user-images.githubusercontent.com/4159106/191795994-b0ae5da0-d633-4c15-9f24-d8c87831ed85.png)

Thing is, I may be purchasing an american stock but I'm in Europe (or elsewhere). And most european brokers give your purchase's info in euros, not in dollars. And sometimes the exchange rate it is not the rate of the purchase date, but the clearing date in backoffice. So, in essence, unit price should be not derived exclusevely from the symbol, but your account's base currency instead if you desired, too. This reasoning, exposed in #705, is actually preventing me (and I imagine other users too) to migrate my entire portfolio to Ghostfolio.

**Comment by cbirkenbeul** [comment]
That's the exact problem I have too. Maybe its possible to add a second field to put the value in euro instat of the original currency and store the original currency in the database. Workaround but much easier for the user. 

Alternatively, but that's much more work is to import the pdfs we get from our broker.

**Comment by ChristianHuff-DEV** [comment]
Same for me. Since all my transactions are invoiced in € (with an for me intransparent exchange rate) I would want to use these values even for stocks issued in $.
To determine the current value in Ghostfolio I would expect the current exchange rate to be used. I would expect (and not mind) to see a difference here between the values shown in Ghostfolio and my broker.
