### ISSUE TITLE
Activities overview only shows amount without currency

### ISSUE THREAD

**Issue by ruudk** [ghostfolio/ghostfolio#791]
My base currency is EUR and my account is set to USD. When I go to Activities it shows me numbers that I have to guess which currency they are:

![Screenshot 2022-04-02 at 13 34 44@2x](https://user-images.githubusercontent.com/104180/161381251-29c27a45-53a4-46a8-a5c0-22960aadf2bb.png)

**Comment by dtslvr** [comment]
Thanks for the feedback @ruudk. I will change the values to your base currency in the mobile view of activities (and accounts).
