### ISSUE TITLE
Dividends and fees

### ISSUE THREAD

**Issue by casitu** [ghostfolio/ghostfolio#799]
When you introduce a dividend, the fee (i.e: simulating taxes) is adding itself to the dividend (it should be substracting from it).

I noticed you can type a negative fee and this do the math, but in case of dividend operations fee should be substracting, not adding.

**Comment by casitu** [comment]
This also occurs when selling.

**Comment by FedericoComoglio** [comment]
Hi @casitu, this is reproducible and I communicated it to @dtslvr. When entering a dividend, you may want to indicate the net dividend. This would avoid withholding taxes on dividends to skew your average fee estimates.

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, I noticed this only in the "Add activity" dialog. Hope this helps.

**Comment by dtslvr** [comment]
> Hi @dtslvr, I noticed this only in the "Add activity" dialog. Hope this helps.

Thanks for your feedback @FedericoComoglio! There is a fix in the latest release.

I will close this issue now. If you find a related issue, please create a new ticket.
