### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by casitu** [ghostfolio/ghostfolio#801]
I discover ghostfolio couple weeks ago and I think is a fabulous idea and needs to be translated to other languages. I offer my self for spanish translation if needed.

Keep up the good work!

**Comment by alfredonodo** [comment]
I agree, I could help with Italian.

**Comment by dtslvr** [comment]
Ghostfolio is now ready for multi-language support. German has already been implemented, this is how the file looks like: https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/locales/messages.de.xlf

Who would like to translate Ghostfolio into a new language? Please post here and I will create the foundation for the translation.

**Comment by dtslvr** [comment]
Great @alfredonodo! 😎 

I have set up [messages.it.xlf](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/locales/messages.it.xlf) now.

Please add `<target state="translated">...</target>` below each `<source>...</source>`.

E.g.
```
<source>Create Account</source>
<target state="translated">Creare un account</target>
```

Just start and commit if you have something to show.

**Comment by alfredonodo** [comment]
Hello,
I extracted all the terms between <source> and </source> and translated them into a csv file. I think a spreadsheet with each language in a column and with a script would be much faster for both the volunteer translator and you to have a valid messages.language.xlf file.
What do you think?

For instance: https://cryptpad.fr/sheet/#/2/sheet/edit/OwORnGwI8Obls8PIIxW1x9ND/

**Comment by dtslvr** [comment]
Hi @alfredonodo

Have you already managed to translate the locales? 😃

I don't mind how you want to work on the translations, it just needs a pull request that can be merged. By the way, there are even dedicated tools to manage `XLIFF` files, but I think that's an overhead and I prefer to keep it simple at the moment.

Can you prepare a pull request? It does not have to be perfect, improvements are easy to implement. I can extend the language selector in the meantime.

**Comment by dtslvr** [comment]
> I can extend the language selector in the meantime.

#1276

**Comment by alfredonodo** [comment]
Hi @dtslvr,
I completed the translation and will soon make a pull request ([here](https://cryptpad.fr/code/#/2/code/view/jgDkDwTsSJpxcR3UdU1K94qYU6NncgbkxegWReQlcO0/) there is the translation file). I am not a professional developer, however I created [this](https://gist.github.com/alfredonodo/beabe5d945758899c60f50434a6ed489) script which speeds up the translation process. If you would like to feel free to use it and modify it.

**Comment by dtslvr** [comment]
The Italian translation has just been deployed in the cloud. If you find something to improve, please create a PR or post an issue with a screenshot.

Thanks again for your contribution, @alfredonodo 🎉  Which language is next?

**Comment by casitu** [comment]
Please, setup set up spanish file and I'll do my best to translate.

**Comment by alfredonodo** [comment]
> Please, setup set up spanish file and I'll do my best to translate.

If you want you can compile [this table](https://cryptpad.fr/sheet/#/2/sheet/edit/OwORnGwI8Obls8PIIxW1x9ND/) (3° column) and then I will use my script to generate the corresponding messages.es.xlf file.

**Comment by casitu** [comment]
> > Please, setup set up spanish file and I'll do my best to translate.
> 
> If you want you can compile [this table](https://cryptpad.fr/sheet/#/2/sheet/edit/OwORnGwI8Obls8PIIxW1x9ND/) (3° column) and then I will use my script to generate the corresponding messages.es.xlf file.

Thanks, I'll begin translating to spanish ;)

**Comment by casitu** [comment]
Hi @alfredonodo, I just finished translating the table to spanish. Use your script to generate the file in order to publish it when @dtslvr thinks it is possible to do so.

**Comment by alfredonodo** [comment]
@casitu I generated `messages.es.xlf` and created a pull request.

**Comment by dtslvr** [comment]
> If you want you can compile [this table](https://cryptpad.fr/sheet/#/2/sheet/edit/OwORnGwI8Obls8PIIxW1x9ND/) (3° column) and then I will use my script to generate the corresponding messages.es.xlf file.

Please do not use this table from now on, it is causing a lot of overhead.

**Comment by dtslvr** [comment]
> I just finished translating the table to spanish.

Español has just been deployed in the cloud. Great work @casitu! 👍🏻

**Comment by alfredonodo** [comment]
> > If you want you can compile [this table](https://cryptpad.fr/sheet/#/2/sheet/edit/OwORnGwI8Obls8PIIxW1x9ND/) (3° column) and then I will use my script to generate the corresponding messages.es.xlf file.
> 
> Please do not use this table from now on, it is causing a lot of overhead.

What kind of overhead? Spacing problems? From a translator's point of view, it is easier, faster and less prone to errors to translate from a table than from an xml file.
If you want, I can adapt the trust to your needs.

**Comment by dtslvr** [comment]
> What kind of overhead?

Resolving conflicts.

**Comment by alfredonodo** [comment]
> > What kind of overhead?
> 
> Resolving conflicts.

I took the Italian and Spanish translations [here](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/locales). I fine tuned the script and for the Spanish version there is no difference between github and the version generated by the script (I used diff). In the case of Italian, there is still ' (apostrophe) instead of &apos;, but I can replace it with an operation.
Also, I found that there are two new untranslated strings at the end of the [English locale](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/locales/messages.xlf), so I updated the Italian and Spanish versions.

**Comment by dtslvr** [comment]
When I extract the locales after a change, the new locales will be marked with `state="new"`. I think the benefit of the table applies mainly for a new language. When you just translate some (additional) locales, it's easier to change it directly.

Strange, I don't know why the order is not consistent for all files.

**Comment by alfredonodo** [comment]
Hi,
I agree about the translation. However, I noticed that sequence numbers `<context context-type="linenumber">` change during the various translation [commits](https://github.com/ghostfolio/ghostfolio/commit/3715edd9ba70cb702b250ff057644254146fe3d0#diff-cbdd4c6579a096858bd41cb6172bffa57c6224b585f0fbcef055932c1a5bcf61).
I therefore modified the script and it is now able to handle the `<new>` tag.
Finally, I noticed that in the new commit for Spanish some variables have been translated:
```
<target state="translated">Comisiones por <x id="INTERPOLATION" equiv-text="{{ summary?.ordersCount }}"/> <x id="ICU" equiv-text="{summary?.ordersCount, plural, =1 {t**ransacción**} otras {**transacciones**}}"/> </target>
<target state="translated">{VAR_PLURAL, plural, =1 {**transacción**} otras {**transacciones**}}</target>
<context-group purpose="location">
```

**Comment by casitu** [comment]
X-Ray and FIRE sections are not translated. Any chance to translate it?

![Captura de pantalla 2022-10-03 194806](https://user-images.githubusercontent.com/25199636/193644549-b5454d2b-0362-47e6-8181-0e8cd119ea92.jpg)
![Captura de pantalla 2022-10-03 194830](https://user-images.githubusercontent.com/25199636/193644554-4fb6ba23-6456-4895-bb70-92bd9c8bbb32.jpg)

**Comment by dtslvr** [comment]
The translations have a few gaps gaps and should be refreshed. Are you fluent in Spanish, French, Italian, Portuguese or Dutch?

**Comment by alfredonodo** [comment]
Hi, I can do it for Italian if you are not in a hurry.

**Comment by jstrvr** [comment]
Hi I managed to do my first contribution on GitHub. So I should be able to work on the Dutch translation and commit changes.

**Comment by alfredonodo** [comment]
> Hi, I can do it for Italian if you are not in a hurry.

Hi, I completed the task. See my comments.

**Comment by dtslvr** [comment]
Thank you for your great contributions! Will close this issue now, we can create new ones if needed.

**Comment by traceur** [comment]
Add Chinese support : https://github.com/ghostfolio/ghostfolio/pull/3215

**Comment by dtslvr** [comment]
> Add Chinese support : https://github.com/ghostfolio/ghostfolio/pull/3215

I have just created a PR with the setup for `zh`: https://github.com/ghostfolio/ghostfolio/pull/3220
