### ISSUE TITLE
Average Cost per share

### ISSUE THREAD

**Issue by casitu** [ghostfolio/ghostfolio#802]
One useful indicator that is missing when you go into symbol detail is Average Cost per share. In my view, is most useful than buy price because you have each transaction detail at bottom, but you need to know if current price is above or below you average cost per share.

**Comment by dtslvr** [comment]
Hi @casitu

Do you mean the average cost per share here?
<img width="774" alt="average-cost" src="https://user-images.githubusercontent.com/4159106/161619605-96468bf9-82f1-4db5-ac10-2658c8b34ebe.png">

**Comment by casitu** [comment]
Hi @dtslvr! If that is the average price, I’d label it as such, rather than “buy price”. It got me confused! ;)
