### ISSUE TITLE
Issue when import csv with unit price at 0

### ISSUE THREAD

**Issue by paranoiasystem** [ghostfolio/ghostfolio#872]
When I try to import a csv like this:

```csv
Date,Code,Currency,Price,Quantity,Action,Fee
11/04/2022,MATICUSD,USD,0,0.0361482,buy,0.00
```

I receive the following error: activities.0.unitPrice is not valid

![image](https://user-images.githubusercontent.com/9149503/165469430-c37d364b-4e6f-4559-8e1f-54cdf29f7449.png)

but from add activity form is possible to set the unitPrice to 0, I think this is a bug, someone can help me? Thanks.

**Comment by dtslvr** [comment]
Thank you for providing this bug report @paranoiasystem. I have created a pull request with a fix.

**Comment by leecosta466** [comment]
Sorry to reopen but I am seeing the same error:

`activities.0.currency is not valid

{
  "Plan name:": "Date Range",
  "REDACTED": "05/05/2010 - 06/02/2023",
  " INC": null,
  "__parsed_extra": [
    null,
    null,
    null
  ]
}`

**Comment by dtslvr** [comment]
Hi @leecosta466

This error message looks weird. Can you please create a new ticket with a concrete, reproducible use case including the `csv` file you are trying to import? Thank you.
