### ISSUE TITLE
Pressing Enter doesn't save changes

### ISSUE THREAD

**Issue by Marilok** [ghostfolio/ghostfolio#902]
In 

[/portfolio/activities/ 
](https://www.ghostfol.io/portfolio/activities)

if you add or edit an activity and press Enter, then the changes don't save.

**Comment by dtslvr** [comment]
Thank you for the suggestion @Marilok.

I have implemented it for the [activity dialog](https://github.com/ghostfolio/ghostfolio/pull/913/files#diff-58017bda755c7596ec203fcfb626689295efccb88fba9dce7d382fb60e7193bd). Are you interested to implement it also for the [account dialog](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/accounts/create-or-update-account-dialog/create-or-update-account-dialog.html)?

**Comment by Marilok** [comment]
Yes, from the UX perspective, it would be great to implement it also for the account dialog.
