### ISSUE TITLE
Unable to delete account with at least one transaction

### ISSUE THREAD

**Issue by FedericoComoglio** [ghostfolio/ghostfolio#909]
Hi @dtslvr, when trying to delete an account that contains at least one transaction I get a prompt to "Upgrade plan" ("This feature requires a subscription"). I do 😄 

Thank you!

**Comment by dtslvr** [comment]
Thanks for reporting this issue @FedericoComoglio. It used to disable the delete button if there are more than one activities. I will just fix this for the moment to avoid delete cascade.

**Comment by FedericoComoglio** [comment]
Thank you, @dtslvr. I am still unable to delete the accounts (same message).

**Comment by dtslvr** [comment]
> Thank you, @dtslvr. I am still unable to delete the accounts (same message).

This change has [not been released](https://github.com/ghostfolio/ghostfolio/blob/main/CHANGELOG.md#unreleased) yet. I will probably deploy a new version at the weekend.
