### ISSUE TITLE
Currency conversion in 'Accounts' reversed

### ISSUE THREAD

**Issue by BackedUpBooty** [ghostfolio/ghostfolio#917]
When inputting an account balance in a currency other than USD (i.e. the account holds funds in EUR, say 100Eur) if I input Currency as EUR and Balance as 100, the platform decides that the cash balance is 100USD and the Value then gets converted from USD to EUR. 

This should be the other way around - we input the cash balance in the currency we select, and the platform converts it to it's comparable USD value.

**Comment by onstring** [comment]
yeah, I meet with the same issue. The default account in 'Accounts' tab shows my balance as USD(which is not when I add activities).  So it gets converted to my currency with a wrong number.

**Comment by dtslvr** [comment]
**After**
<img width="1177" alt="account-calculation" src="https://user-images.githubusercontent.com/4159106/169663863-d2ce13f3-3196-4f05-b65c-a1f5af73ec8e.png">

**Comment by dtslvr** [comment]
@BackedUpBooty and @onstring, I have [released](https://github.com/ghostfolio/ghostfolio/releases/tag/1.150.0) and deployed a fix. Can you please verify that it is working as expected now?

**Comment by BackedUpBooty** [comment]
@dtslvr that's great thank you, yes can confirm it's now functioning as expected. 

Cheers!

**Comment by dtslvr** [comment]
> @dtslvr that's great thank you, yes can confirm it's now functioning as expected.

Thank you @BackedUpBooty 😃
