### ISSUE TITLE
DataGatheringService failure loop on install (Docker)

### ISSUE THREAD

**Issue by pbonnell** [ghostfolio/ghostfolio#924]
I'm happy to debug this fursther with sdome guidance. 
It looks like I'm not getting yahoo data at install. I'm assuming this call is initiated after seed data is installed with `database:setup`. What's the best way to get more info on this failure?
[I'm looped here](https://github.com/ghostfolio/ghostfolio/blob/40380346e678e7c8d0c38d8ca38db6c027d20df3/apps/api/src/services/data-gathering.service.ts#L398).

Maybe something in [yahoo-finance2](https://github.com/ghostfolio/ghostfolio/blob/40380346e678e7c8d0c38d8ca38db6c027d20df3/apps/api/src/services/data-provider/yahoo-finance/yahoo-finance.service.ts#L22) ?

### TO REPRODUCE

Docker: **ghostfolio/ghostfolio:latest**
Version : **v1.148.0**

Follow [Run with Docker Instructions](https://github.com/ghostfolio/ghostfolio#run-with-docker-self-hosting) through `yarn database:setup` (successful)

Am I missing something with the instrcutions? 
Tried adding a **ALPHA_VANTAGE_API_KEY** ENV as well, but unsure of how to make this default (if it's possible now).

Docker log: 

```
LOG    ________               __  ____      ___
LOG   / ____/ /_  ____  _____/ /_/ __/___  / (_)___
LOG  / / __/ __ \/ __ \/ ___/ __/ /_/ __ \/ / / __ \
LOG / /_/ / / / / /_/ (__  ) /_/ __/ /_/ / / / /_/ /
LOG \____/_/ /_/\____/____/\__/_/  \____/_/_/\____/ v1.148.0
LOG 
LOG Listening at http://localhost:3333
LOG 
LOG [DataGatheringService] 7d data gathering has been started.
WARN [DataGatheringService] Failed to gather data for symbol USDEUR from YAHOO at 2022-05-07.
WARN [DataGatheringService] Failed to gather data for symbol USDEUR from YAHOO at 2022-05-07.
WARN [DataGatheringService] Failed to gather data for symbol USDEUR from YAHOO at 2022-05-07.
WARN [DataGatheringService] Failed to gather data for symbol USDEUR from YAHOO at 2022-05-07.
... <loop>
```

**Comment by dtslvr** [comment]
Thanks for creating an issue @pbonnell. It looks like there is no `lastMarketPrice`. Does it work after restarting the server?

Setting `ALPHA_VANTAGE_API_KEY` won't have any effect.

**Comment by pbonnell** [comment]
I've rebuilt the DB a few times for a clean run and yes, this seems to have gone away.

However, after adding an Activity for a BUY (successful), then clicking on it from the list, the popup errors on  : 
```
 [Nest] 1  -    WARN [PortfolioCalculator] Missing initial value for symbol AMZN at 2022-05-16
 [Nest] 1  -    ERROR [ExceptionsHandler] [big.js] Invalid number
 Error: [big.js] Invalid number
    at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
    at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
    at Big.P.times.P.mul (/ghostfolio/apps/api/node_modules/big.js/big.js:832:17)
   at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:197842)
    at Generator.next (<anonymous>)
    at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:114:62)
```

[Error throws here ](https://github.com/ghostfolio/ghostfolio/blob/0e4c39d14548401c72aa3759cda5212f38901386/apps/api/src/app/portfolio/portfolio-calculator.ts#L471). Are you sure `!currentPosition.quantity.eq(0)` is what you want here ? Isn't this  `TRUE` for any non-zero value (not  = 0) ?

**Comment by dtslvr** [comment]
@pbonnell the source code is far from perfect 🙂 If you see a way to improve it, feel free to make a suggestion.

**Comment by ikoyhn** [comment]
I am also having this issue, its nearly crashing my small server. I've tried rebuilding the database using the yarn command but the error doesn't seem to go away.

**Comment by dtslvr** [comment]
The implementation of the data gathering has changed fundamentally recently. Please create a new ticket if the problem persists.
