### ISSUE TITLE
Add easy docker-compose/docker cli installation methods

### ISSUE THREAD

**Issue by AuthorShin** [ghostfolio/ghostfolio#928]
Hello
Can you please add/make docker-compose/docker cli installation methods so that we can install ghostfolio via docker management services like casaOS and Portainer?

**Comment by Diondk** [comment]
Would be great if someone could also add to the unraid  app store!

**Comment by LeonStoldt** [comment]
Hi @AuthorShin ,
I think I can help with this issue.
Could you describe what do you mean by "make docker-compose installation methods". You should be able to run the [docker-compose file](https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.yml) in e.g. portainer right now.

Open Portainer, navigate to `Stacks`, click `Add Stack` from `git repository` and fill in the parameters:
**Name**: ghostfolio
**Repository URL**: https://github.com/ghostfolio/ghostfolio
**Repository reference**: refs/heads/main
**Compose path**: docker/docker-compose.yml
Add environment variables according to [.env](https://github.com/ghostfolio/ghostfolio/blob/main/.env) file or upload .env file.

This should run all your containers and is the easy-to-use UI method of deploying ghostfolio.

---

@Diondk, I created my own Unraid ghostfolio template by filling in the environment variables in the UI, but I like the idea of publishing an image to the Community Store.
I think the Template should only include the ghostfolio image, as Postgres and Redis are easy to find and setup from the Community Store. So these could be referenced as Placeholders and the description explains how to add the reference variables. @dtslvr, I would work on the Unraid Template to spread this application to the Unraid Community.

**Comment by LeonStoldt** [comment]
@Diondk, I created a template which is pending in review right now. If it is published, I'll let you know.
https://github.com/LeonStoldt/Unraid-Community-Applications/tree/main/ghostfolio

**Comment by AuthorShin** [comment]
@LeonStoldt Thank you very very much man but I was looking for a way to install it on casaOS as well since on casaOS you can only install containers if they are hosted on hub.docker.com and also they have their services and dependencies inside so it's just a single container not Stack.

**Comment by dtslvr** [comment]
> @dtslvr, I would work on the Unraid Template to spread this application to the Unraid Community.

As I'm not familiar with [Unraid](https://unraid.net), it's great you can help out here @LeonStoldt. Tell us when it's ready that we can also mention it in the [README.md](https://github.com/ghostfolio/ghostfolio/blob/main/README.md).

**Comment by LeonStoldt** [comment]
@Diondk the Ghostfolio Unraid Template has been published to the Community Appstore and already received first reactions.

More detailed information about the setup process can be found at the [Support Thread](https://forums.unraid.net/topic/123829-support-community-applications-ghostfolio/). Please check it out and set up your instance. It would be great if you could provide a short feedback.

@dtslvr FYI: The Unraid Template is a predefined "Run Configuration" for running the docker container in Unraid. I provided some helpful default values and a detailed description on how to setup and change parameters of the template. All links of the template and the Support Thread reference your official ghostfol.io page and this this github repo.

**Comment by LeonStoldt** [comment]
@AuthorShin , I am not familiar with CasaOS but i tried the live demo for a few minutes. Basically, you can start the containers (postgres, redis and ghostfolio) individually and reference them as usual (as you would do in docker compose) by providing the environment variables (see .env file). So it should work in CasaOS. As it is pretty similar to Unraid, the Unraid setup explanation might help you aswell: [Support Thread](https://forums.unraid.net/topic/123829-support-community-applications-ghostfolio/)

If you still have issues setting up the containers, I can take a deeper look.

The alternative would be to build a fat container including redis and postgres, but this would be bad practise and not the lightweight container approach.

**Comment by zenkraker** [comment]
I added a new little section for Portainer/Unraid users to perform the db creation (which wasn't that obvious)
[https://github.com/ghostfolio/ghostfolio/pull/943/commits/17737a92adccc39cd07745709391e91b5ef3e2f8](url)

**Comment by Diondk** [comment]
> @Diondk the Ghostfolio Unraid Template has been published to the Community Appstore and already received first reactions.
> 
> More detailed information about the setup process can be found at the [Support Thread](https://forums.unraid.net/topic/123829-support-community-applications-ghostfolio/). Please check it out and set up your instance. It would be great if you could provide a short feedback.
> 
> Update: Someone noticed strong CPU usage which caused problems. This is related to [issue 924](https://github.com/ghostfolio/ghostfolio/issues/924).
> 
> @dtslvr FYI: The Unraid Template is a predefined "Run Configuration" for running the docker container in Unraid. I provided some helpful default values and a detailed description on how to setup and change parameters of the template. All links of the template and the Support Thread reference your official ghostfol.io page and this this github repo.
> 
> @dtslvr if you want, I can provide a pull request for the Readme.

Thanks it works for me, i will starting playing around with it today and let you know if there are any issues!

**Comment by LeonStoldt** [comment]
@AuthorShin did it work out for you at Casa OS?
If so, this issue could be closed I think ;)

**Comment by AuthorShin** [comment]
@LeonStoldt @zenkraker Thank you very much for all the effort and help.
@LeonStoldt Well, I originally was looking for exactly the alternative way that you mentioned (one fat container) but since it seems not available at the current moment I just use the given instruction at repository and install it with Docker-compose and then import it to casaOS (as since v3.1 now they support adding already existing containers).

**Comment by luk6173** [comment]
> Hi @AuthorShin , I think I can help with this issue. Could you describe what do you mean by "make docker-compose installation methods". You should be able to run the [docker-compose file](https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.yml) in e.g. portainer right now.
> 
> Open Portainer, navigate to `Stacks`, click `Add Stack` from `git repository` and fill in the parameters: **Name**: ghostfolio **Repository URL**: https://github.com/ghostfolio/ghostfolio **Repository reference**: refs/heads/main **Compose path**: docker/docker-compose.yml Add environment variables according to [.env](https://github.com/ghostfolio/ghostfolio/blob/main/.env) file or upload .env file.
> 
> This should run all your containers and is the easy-to-use UI method of deploying ghostfolio.
> 
> @Diondk, I created my own Unraid ghostfolio template by filling in the environment variables in the UI, but I like the idea of publishing an image to the Community Store. I think the Template should only include the ghostfolio image, as Postgres and Redis are easy to find and setup from the Community Store. So these could be referenced as Placeholders and the description explains how to add the reference variables. @dtslvr, I would work on the Unraid Template to spread this application to the Unraid Community.

Hi,

I tried this method but it doesn't work for me. I deploy the stack and I get this error in Portainer:
![grafik](https://user-images.githubusercontent.com/24668586/201461776-6263379d-e6f4-4ee3-bc42-53edfe585a45.png)

What's wrong?

Thank you,
Lukas
