### ISSUE TITLE
Add a note box inside "Add activity" window

### ISSUE THREAD

**Issue by AuthorShin** [ghostfolio/ghostfolio#932]
Hello
Can you please add a note box inside "Add activity" window so when we add a new activity we can also add notes related to that activity/transaction?
<img src="https://i.ibb.co/pWF7WpL/note-box.png" alt="note-box">

**Comment by dtslvr** [comment]
Duplicate of #766.

**Comment by dtslvr** [comment]
Duplicate of #766
