### ISSUE TITLE
Adding the same asset (Bitcoin) as transaction in EUR and USD?

### ISSUE THREAD

**Issue by iMartien** [ghostfolio/ghostfolio#951]
Hi,

In addition to #945 I have bought Bitcoin in the past with USD and in EUR on the same exchange.

I do run in a couple issues:
- When adding an Account (Exchange) with the currency set as USD, you only can add USD/BTC transactoins (#945)
- When you've already added USD transactions and change your base currency in to EUR via the .env. and than goto "Accounts" in the top menu, you'll get an error: "Something went wrong, please try again later" and your accounts will not show anymore. (Accounts screen stays empty). This will resolve when you delete all previous USDBTC transactions.
- When you dont have any previous BTC transactions in USD and you change your base currency to EUR, you cannot add transactions in BTCUSD anymore (not selectable). 

I have also tried to add my Exchange twice, one Account with USD as currency and one with EUR as currency. But still when you add an account that has USD as currency and your base currency in .env is set to EUR, you cannot at BTCUSD transactions, only BTCEUR.

Would be great to have it possible to add transactions of the same asset in different currencies.

**Comment by dtslvr** [comment]
This feature is currently not planned. You could manually convert the purchases to your main currency.
