### ISSUE TITLE
Intermittent issue with application

### ISSUE THREAD

**Issue by x80486** [ghostfolio/ghostfolio#996]
I just opened an account to try `Ghosfolio`. I really like the interface, the features, and pretty much everything else — great stuff :blush:

I've noticed, though, that after working with the application for a few minutes, the application stops responding and there is always a call to `/api/v1/account` that respond with an `HTTP 500 (Internal Server Error)`.

Not sure if this is sporadic, or because I'm in the middle of a maintenance/update.

![image](https://user-images.githubusercontent.com/34633617/172971195-487e104f-31cd-41f9-bbc9-a9709d11fcc0.png)

**Comment by x80486** [comment]
I've been using the application from time to time today, and I haven't had any more problems. I didn't close it because I thought it might happen again...but all working fine so far :+1:

**Comment by dtslvr** [comment]
I'm closing this ticket now. Don't hesitate to create a new one if you are affected by an error.
